package com.lam.coder.topCoder;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(Suite.class)
@SuiteClasses({
        // A
        AlephNullTest.class,
        AmebaDiv2Test.class,
        AppleWordTest.class,
        ArchimedesTest.class,
        AverageTest.class,
        // B
        BasesTest.class,
        BearCheatsTest.class,
        BettingMoneyTest.class,
        BenfordsLawTest.class,
        BigBurgerTest.class,
        BillboardTest.class,
        BinaryCodeTest.class,
        BinPackingEasyTest.class,
        BirthdayOddsTest.class,
        BirthdayTest.class,
        BirthNumbersValidatorTest.class,
        BishopMoveTest.class,
        BitsTest.class,
        BlackAndRedTest.class,
        BlackAndWhiteSolitaireTest.class,
        BloggoShortcutsTest.class,
        BonusesTest.class,
        BritishCoinsTest.class,
        // C
        CalcTestTest.class,
        CandidatesSelectionEasyTest.class,
        CarBuyerTest.class,
        CCipherTest.class,
        CeyKapsTest.class,
//	CheatCodeTest.class,
        ChessboardPatternTest.class,
        ChivalryTest.class,
        CircleGameTest.class,
        ClockWalkTest.class,
        CodeRedTest.class,
        ColorfulBricksTest.class,
        CombinerTest.class,
        CommonCharTest.class,
        ContestCoordinatorTest.class,
        CostOfDancingTest.class,
        // D
        DayAgeTest.class,
        DiceCheckerTest.class,
        DiceTest.class,
        DinkyFishTest.class,
        DitherCounterTest.class,
        DivisorDigitsTest.class,
        DNATest.class,
        DoubleLetterTest.class,
        DrivingDirectionsTest.class,
        // E
        EllysDirectoryListingTest.class,
        EllysSortingTrimmerTest.class,
        EllysTimeMachineTest.class,
        EndOfContestTest.class,
        ErasingCharactersTest.class,
        ExerciseMachineTest.class,
        // F
        FinancesTest.class,
        FixedDiceGameDiv2Test.class,
        FormatAmtTest.class,
        FoxAndClassroomTest.class,
        FoxAndGomokuTest.class,
        FoxAndSightseeingTest.class,
        FoxAndWordTest.class,
        FractionTCTest.class,
        // G
        GolfScoreTest.class,
        GooseTattarrattatDiv2Test.class,
        GrafixClickTest.class,
        GrafixCorruptTest.class,
        GrafixGlobsTest.class,
        GoodWordTest.class,
//	GravityBombTest.class,
        // H
        HappyLetterDiv2Test.class,
        HowEasyTest.class,
        HuffmanDecodingTest.class,
        // I
        IDNumberVerificationTest.class,
        InchwormTest.class,
        InsertZTest.class,
        InstantRunoffTest.class,
        // J
        JingleRingleTest.class,
        JumpFurtherTest.class,
        // K
        KeyDungeonDiv2Test.class,
        // L
        LeaguePicksTest.class,
        LetterRangeTest.class,
        LetterSortTest.class,
        LevelUpTest.class,
        LexerTest.class,
        LinearTravellingSalesmanTest.class,
        LittleElephantAndBallsAgainTest.class,
        LittleElephantAndBooksTest.class,
        LittleElephantAndDoubleTest.class,
        LotteryTicketTest.class,
//	LittleElephantAndStringTest.class,
        // M
        MagicSeriesTest.class,
        MagicalStringDiv2Test.class,
        ManySquaresTest.class,
//	MatArithTest.class, 
        MatchMakerTest.class,
        MatchMakingTest.class,
        MedianOfNumbersTest.class,
        MergeSortIntegerTest.class,
        MergeSortStringTest.class,
        MetricClockTest.class,
//	MessageMessTest.class,
        MicroStringsTest.class,
        MiniatureDachshundTest.class,
        ModEncoderTest.class,
        MovingAveragesTest.class,
        MostProfitableTest.class,
        MovingAveragesTest.class,
        MusicalChairsTest.class,
//	MultifactorialTest.class,
        // N
        NoOrderOfOperationsTest.class,
        NumerologyTest.class,
        NumberMagicEasyTest.class,
        // O
//	OmahaLowTest.class,
        // P,
        PairGameEasyTest.class,
        PalindromePrimeTest.class,
        PalindromizeTest.class,
//	PaperFoldTest.class,
//	PascalCountTest.class,
        PassingGradeTest.class,
        PaternityTestTest.class,
        PeacefulLineTest.class,
        PairGameEasyTest.class,
        PersistentNumberTest.class,
        PiCalculatorTest.class,
//	PeopleCircleTest.class,
//	PipeCutsTest.class,
//	PoetryTest.class,
        PrefixCodeTest.class,
        PrimalUnlicensedCreaturesTest.class,
        PrimeNumbersTest.class,
        ProfitTest.class,
        PunnetTest.class,
//	ProblemWritingTest.class,
        // Q
        //   QuizShowTest.class,
        QuipuTest.class,
        // R
        RaceTest.class,
        RaiseThisBarnTest.class,
        RectangleCoveringEasyTest.class,
        RegularSeasonTest.class,
        RochamboTest.class,
        RecurrenceRelationTest.class,
        RPNTest.class,
        // S
        SemiPerfectSquareTest.class,
        SeriesTest.class,
        ShoelaceLengthTest.class,
        ShorterSuperSumTest.class,
        ShoutterDiv2Test.class,
        SkipRopeTest.class,
        SnakyTest.class,
        SoccerLeaguesTest.class,
        SpamCheckerTest.class,
        SpamDetectorTest.class,
        StickTest.class,
        StockCalcTest.class,
        StringCompressorTest.class,
        StringDupTest.class,
        StringParserTest.class,
        SupermarketDiscountTest.class,
        SwappingDigitsTest.class,
        SyntaxTest.class,
        // T
//	TallPeopleTest.class,
        TeamsSelectionTest.class,
        TheAirTripDivTwoTest.class,
        TheKingsArmyDiv2Test.class,
        TimeTest.class,
        TitleStringTest.class,
//    TopFiveTest.class,
        TopFoxTest.class,
        TransportCountingTest.class,
        TravellingSalesmanEasyTest.class,
        TriTravelTest.class,
        TwoWaysSortingTest.class,
        TypoCoderDiv2Test.class,
        // U
        UnLinkerTest.class,
        UniqueTest.class,
        UserNameTest.class,
        // V
        VigenereTest.class,
        VLNStringTest.class,
        VolumeGuessTest.class,
        VowelLatinTest.class,
        // W
        WakingUpEasyTest.class,
        WeekDayTest.class,
//    WindowManagerTest.class,
        WinterAndCandiesTest.class,
        WinterAndMandarinsTest.class,
        WordFilterTest.class,
        WordFormTest.class,
        WordWrapTest.class,
        // Y
        YahtzeeTest.class
        // Z
})

public class AllTests {
}