package com.lam.coder.topCoder;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import junit.framework.TestCase;

import com.lam.coder.topCoder.EllysDirectoryListing;

public class EllysDirectoryListingTest extends TestCase {
	EllysDirectoryListing dir;

	@Before
	protected void setUp() throws Exception {
		super.setUp();
		dir = new EllysDirectoryListing();
	}

	@After
	protected void tearDown() throws Exception {
		super.tearDown();
		dir = null;
	}

	@Test
	public void testGetFiles() {
		Assert.assertArrayEquals(
				new String[] { "ContestApplet.jnlp", "Movie.avi", "Image.jpg",
						"Book.pdf", "..", "." },
				dir.getFiles(new String[] { "ContestApplet.jnlp", ".",
						"Image.jpg", "..", "Book.pdf", "Movie.avi" }));
		Assert.assertArrayEquals(new String[] { "Image.jpg", "..", "." },
				dir.getFiles(new String[] { "Image.jpg", "..", "." }));
		Assert.assertArrayEquals(new String[] { "Image.jpg", ".", ".." },
				dir.getFiles(new String[] { "..", ".", "Image.jpg" }));
		Assert.assertArrayEquals(
				new String[] { "No", "Improbable", "Zaphod", "very...", "Just",
						"very", ".", ".." },
				dir.getFiles(new String[] { "No", "..", "Zaphod", ".", "Just",
						"very", "very...", "Improbable" }));
		Assert.assertArrayEquals(
				new String[] { "www.topcoder.com", "Ever.tried", "Fail.Better",
						"Ever.failed", "Again..", "No", "Matter.", "Try",
						"Again.", "Fail", "..", "." },
				dir.getFiles(new String[] { "www.topcoder.com", "Ever.tried",
						".", "Ever.failed", "..", "No", "Matter.", "Try",
						"Again.", "Fail", "Again..", "Fail.Better" }));
		 Assert.assertArrayEquals(new String[] {"This", "test", "is", "tricky", "..", "." }, 
				 dir.getFiles( new String[] {"This", ".", "is", "tricky", "test", ".."}
		 ));
		 
		 Assert.assertArrayEquals(new String[] {"This", "test", "is", "tricky, too", "..", "." }, 
				 dir.getFiles( new String[] {"This", ".", "is", "tricky, too", "..", "test" }
		 ));
	}
	
	@Test
	public void testGetFilesSystemTest() {
		Assert.assertArrayEquals(new String[] {"ContestApplet.jnlp", "Movie.avi", "Image.jpg", "Book.pdf", "..", "."} 	, dir.getFiles(new String[] {"ContestApplet.jnlp", ".", "Image.jpg", "..", "Book.pdf", "Movie.avi"}));
		Assert.assertArrayEquals(new String[] {"Image.jpg", "..", "."} 	, dir.getFiles(new String[] {"Image.jpg", "..", "."}));
		Assert.assertArrayEquals(new String[] {"Image.jpg", ".", ".."} 	, dir.getFiles(new String[] {"..", ".", "Image.jpg"}));
		Assert.assertArrayEquals(new String[] {"No", "Improbable", "Zaphod", "very...", "Just", "very", ".", ".."} 	, dir.getFiles(new String[] {"No", "..", "Zaphod", ".", "Just", "very", "very...", "Improbable"}));
		Assert.assertArrayEquals(new String[] {"www.topcoder.com", "Ever.tried", "Fail.Better", "Ever.failed", "Again..", "No", "Matter.", "Try", "Again.", "Fail", "..", "."} 	, dir.getFiles(new String[] {"www.topcoder.com", "Ever.tried", ".", "Ever.failed", "..", "No", "Matter.", "Try", "Again.", "Fail", "Again..", "Fail.Better"}));
		Assert.assertArrayEquals(new String[] {".", ".."} 	, dir.getFiles(new String[] {".", ".."}));
		Assert.assertArrayEquals(new String[] {"..", "."} 	, dir.getFiles(new String[] {"..", "."}));
		Assert.assertArrayEquals(new String[] {"This", "test", "is", "tricky", "..", "."} 	, dir.getFiles(new String[] {"This", ".", "is", "tricky", "test", ".."}));
		Assert.assertArrayEquals(new String[] {"This", "samples.", "is", "covered", "in", "the", "..", "."} 	, dir.getFiles(new String[] {"This", ".", "is", "covered", "in", "the", "..", "samples."}));
		Assert.assertArrayEquals(new String[] {".htaccess", "..evenWorse", "tricky", "also", "..", "."} 	, dir.getFiles(new String[] {".htaccess", "..evenWorse", ".", "..", "also", "tricky"}));
		Assert.assertArrayEquals(new String[] {"...", "Elly.cpp", "empty", ".", ".."} 	, dir.getFiles(new String[] {"...", "..", ".", "empty", "Elly.cpp"}));
		Assert.assertArrayEquals(new String[] {"dhgSPDW", "YANMPUaFJyELpmpND", "GIVsdxAFZuD", "JkqPFz", "fwssmvagCN", "gIcW", "pkNNK.", "nBNexlrLkXhw", "gfrCmNFpSB", "H", "zOdKpJOeaZJJSR", "Q", "HX.tFKzsoEtLbNpvgKZg", "fLG", "BaRtmT", "WtyOZ", "JIGbDEmT", "eyqPbEAxBXKt", "EyFacvLo", "ejDTNO.mn", "dIrrbDRPkLQvTqn", "nsD", "ZBOkXkvlvd", "hiFchtsNqNrmJqKJoK", "MBfhCEwxOYpwtLVC", "Ouubr", ".MfYCktLXrgNJOLKOhEq", "vazvCvRsIoPRqSbbA", "oa", "cvaLMsbIQKPs", "SULbweWxSc", "..", "."} 	, dir.getFiles(new String[] {".", "YANMPUaFJyELpmpND", "GIVsdxAFZuD", "JkqPFz", "fwssmvagCN", "gIcW", "pkNNK.", "nBNexlrLkXhw", "gfrCmNFpSB", "H", "zOdKpJOeaZJJSR", "Q", "HX.tFKzsoEtLbNpvgKZg", "fLG", "BaRtmT", "WtyOZ", "JIGbDEmT", "eyqPbEAxBXKt", "EyFacvLo", "ejDTNO.mn", "dIrrbDRPkLQvTqn", "nsD", "ZBOkXkvlvd", "hiFchtsNqNrmJqKJoK", "MBfhCEwxOYpwtLVC", "Ouubr", ".MfYCktLXrgNJOLKOhEq", "vazvCvRsIoPRqSbbA", "oa", "cvaLMsbIQKPs", "..", "SULbweWxSc", "dhgSPDW"}));
		Assert.assertArrayEquals(new String[] {"qJV", "hCkSUzAzbYcdL", "Sf", "hqNtCDDoQmHOfk", "lENYhZHGDV", "AajQBWtFLVJTnSZXIX", "Q", "uqyJVhUGy", "BBKjDHBO", "lk.YnSVE", "TRcFbcjmVKQggtAGARhB", "mslXg", "ipCO", "bDYwyJ", "IllnQLZhKPZILL", "ynYH", "q", "KWZl", "FDLMnsGQolUcfbR", "AKtGzsmFkEWmZLtdHQP", "TOKi", "oySGaZDJApHHQL", "xgEfKTZ", "JJkZkwLbuAn", "liUzHJzH", "GFgINdqf", "AKLKsAKCGYgKpRHWit", ".", ".."} 	, dir.getFiles(new String[] {"qJV", "hCkSUzAzbYcdL", "..", "hqNtCDDoQmHOfk", "lENYhZHGDV", "AajQBWtFLVJTnSZXIX", "Q", "uqyJVhUGy", "BBKjDHBO", "lk.YnSVE", "TRcFbcjmVKQggtAGARhB", "mslXg", "ipCO", "bDYwyJ", "IllnQLZhKPZILL", "ynYH", "q", "KWZl", "FDLMnsGQolUcfbR", "AKtGzsmFkEWmZLtdHQP", "TOKi", "oySGaZDJApHHQL", "xgEfKTZ", "JJkZkwLbuAn", "liUzHJzH", "GFgINdqf", "AKLKsAKCGYgKpRHWit", ".", "Sf"}));
		Assert.assertArrayEquals(new String[] {"svnJZvF", "Xx", "NXR", "KIQGWcFVDEovPYhoNsKd", "XitCJw", "fb", "rEhVAenGvhaNKRJk", "P.bdhJbZFxXGhpnno", "aWILEaRPr", "vrfeO.QuLRbMltFlf", "vdamGPUfvJekbH", "ULTs.Xe", "UBNCdzapQN", "eGrQBWWzA", "IXZOsLqOulWTf", "KaSE", "cuLhLvvI.", "PlgtUlRTLzebAaPFV.hS", "reaZDHVw", "QQWkLkPungCQMsN", "P", "QIMQmscnb", "PXMJColxCZgPnLcA", "OHv", "qO", "CfPjmRifRcK", "RfHFkH", "DPNCXNZWg", "JYDMRKLE", "RxMPRREpNd", "ANgmuRHvmKwfNFcTSTjP", "Fu", "RZFdZ", "GsqNSIwwcnfNZYHwgtEP", "oQBRVQmeP", "UdNXhwoxfMeTlC", "kA", "MkzFAqyvMrXputJ.OC", "SAqyV", "HdvL", "IDXFJwWRx", "YQvXE", "sywXT", ".", ".."} 	, dir.getFiles(new String[] {"svnJZvF", "Xx", "NXR", "KIQGWcFVDEovPYhoNsKd", "XitCJw", "fb", "rEhVAenGvhaNKRJk", "P.bdhJbZFxXGhpnno", "aWILEaRPr", "vrfeO.QuLRbMltFlf", "vdamGPUfvJekbH", "ULTs.Xe", "UBNCdzapQN", "eGrQBWWzA", "IXZOsLqOulWTf", "KaSE", "cuLhLvvI.", "PlgtUlRTLzebAaPFV.hS", "reaZDHVw", "QQWkLkPungCQMsN", "P", "QIMQmscnb", "PXMJColxCZgPnLcA", "OHv", "qO", "CfPjmRifRcK", "RfHFkH", "DPNCXNZWg", "JYDMRKLE", "RxMPRREpNd", "ANgmuRHvmKwfNFcTSTjP", "Fu", "RZFdZ", "..", "oQBRVQmeP", "UdNXhwoxfMeTlC", "kA", "MkzFAqyvMrXputJ.OC", "SAqyV", "HdvL", "IDXFJwWRx", "YQvXE", "sywXT", "GsqNSIwwcnfNZYHwgtEP", "."}));
		Assert.assertArrayEquals(new String[] {"hPWfyqo", "MaMXpnN", "WEyViH.zfcpS", "VtBuzuNkNQc", "ZbS.tJRUlre", ".lHgvFVz", "HSCbrGvogN", "QSKNyfZjLtRUcRjP", "yWiEJRPhADCcsggBhr", "uD.dtXcr.XO.xLfqfmXo", "Eti", ".cIfElUQDVdS", "DccFZagWnyvyqSuwmW", "dkc", "ksJqyqxkPSSlst", "Y", "oWDqdqmOMBceE", "..", "."} 	, dir.getFiles(new String[] {"hPWfyqo", "MaMXpnN", "WEyViH.zfcpS", "VtBuzuNkNQc", ".", ".lHgvFVz", "HSCbrGvogN", "QSKNyfZjLtRUcRjP", "..", "uD.dtXcr.XO.xLfqfmXo", "Eti", ".cIfElUQDVdS", "DccFZagWnyvyqSuwmW", "dkc", "ksJqyqxkPSSlst", "Y", "oWDqdqmOMBceE", "yWiEJRPhADCcsggBhr", "ZbS.tJRUlre"}));
		Assert.assertArrayEquals(new String[] {"OAJBDS", "m", "gDPy", "GThg", "sN", "hSeRrXnj", "ZrunWlZQ", "V", "geDlYdamhfQoEo", "ctAbhaXjagtGcU", "sdzfuyJTyLB", "aNNdNqdYacldGxFMDecP", "zhXBRwYHI.xTmOe", "diOOWfIob.tee", "rrFsUZfCgjcLIKNjWB", "mRolTlxoqSfozDkjC", "AldYVDAQNTyGfnE", "cuURGey", "TOkGv", "MfcSSOKPKwEfALAEeJWF", "UrLpAruAYfnHgynJlY", "cLbg", "AwJ.BoqJxvbEzy.IiEP", "yAnTgHZzhyR", "JVM.EdAEKcqFTSgCuvt", "SPDSVaobE", "Cp", "OAU.uiGE", "saGUDuLBERxDtElX", "DRyVlyXOXOOOWKbImdP", "NofgN", "mQVgfvPYv", "KIMdj", "HQps", "eIAOuTaIGUO", "rYUKuRSt", "WZjTCKGTNZMJkXgFovL", "fqZjfOhyQ", "NDOlyoByl", "ERQMJRskCRGvjbBzugb", "..", "."} 	, dir.getFiles(new String[] {"OAJBDS", "m", "gDPy", "GThg", "sN", "hSeRrXnj", "ZrunWlZQ", "V", "geDlYdamhfQoEo", "ctAbhaXjagtGcU", "sdzfuyJTyLB", "aNNdNqdYacldGxFMDecP", ".", "..", "rrFsUZfCgjcLIKNjWB", "mRolTlxoqSfozDkjC", "AldYVDAQNTyGfnE", "cuURGey", "TOkGv", "MfcSSOKPKwEfALAEeJWF", "UrLpAruAYfnHgynJlY", "cLbg", "AwJ.BoqJxvbEzy.IiEP", "yAnTgHZzhyR", "JVM.EdAEKcqFTSgCuvt", "SPDSVaobE", "Cp", "OAU.uiGE", "saGUDuLBERxDtElX", "DRyVlyXOXOOOWKbImdP", "NofgN", "mQVgfvPYv", "KIMdj", "HQps", "eIAOuTaIGUO", "rYUKuRSt", "WZjTCKGTNZMJkXgFovL", "fqZjfOhyQ", "NDOlyoByl", "ERQMJRskCRGvjbBzugb", "diOOWfIob.tee", "zhXBRwYHI.xTmOe"}));
		Assert.assertArrayEquals(new String[] {"xkcIQ", "xLitehhPHPUYlvSRm", "twYcKY", "gPAQgNaRLEQj", "IyIOHWdaXzBAqKtjzBg", "XqZQMU", "VcPDsTxNG", "HJFuHGQF", "fceZmQYkze", "WReDYw", "VAcEPh", "RLPxYyNBBiZZnoPmGvQ", "FdNYpGWVU", "loxsOkvVxr", "DRoaPrXlkEJzKIDvQE", "KrJNalUsnEjqkp", "LorACqcaIZnknkooexl", "bAqQUKUBWVtKlXxfPSNz", "tpujOinvOLEUa.JPCqro", "UiH", "rhdoEpzRzSFSFsEPf", "QHVmDWWxQROgIrMMkx", "jPeqzz", "ZIOteDkWEkltUliXQLX", "XbCYOdMqpVP.PWW", "CF", "latzGGipobNhfU", "UgeDlBYthRdkrx", "cMHUjGdYSqioWZRNEX", "tlF", "BCIqjRIIGU", "hiHxVaakzmv", "PKIV.YYuqKaZZdE", "n", "XFtTPL", "LpsMPXGPOel", "VnMaY", "nfswAP", "bnZAbFgHXBoE", "EFLGbXHkCc", "GktgKpbm", "tYpzTViYjQPCoiI", "YbwBTTGZjlTjNPwoU", "FzN", "wbEYE", "CWdARjeFIRKmM", ".", ".."} 	, dir.getFiles(new String[] {"xkcIQ", "xLitehhPHPUYlvSRm", "twYcKY", "gPAQgNaRLEQj", "IyIOHWdaXzBAqKtjzBg", "XqZQMU", "VcPDsTxNG", "HJFuHGQF", "fceZmQYkze", "WReDYw", "VAcEPh", "RLPxYyNBBiZZnoPmGvQ", "FdNYpGWVU", "loxsOkvVxr", "DRoaPrXlkEJzKIDvQE", "KrJNalUsnEjqkp", "LorACqcaIZnknkooexl", "bAqQUKUBWVtKlXxfPSNz", "tpujOinvOLEUa.JPCqro", "UiH", "rhdoEpzRzSFSFsEPf", "QHVmDWWxQROgIrMMkx", "jPeqzz", "ZIOteDkWEkltUliXQLX", "XbCYOdMqpVP.PWW", "CF", "latzGGipobNhfU", "..", "cMHUjGdYSqioWZRNEX", "tlF", "BCIqjRIIGU", "hiHxVaakzmv", "PKIV.YYuqKaZZdE", "n", "XFtTPL", "LpsMPXGPOel", "VnMaY", "nfswAP", "bnZAbFgHXBoE", "EFLGbXHkCc", "GktgKpbm", "tYpzTViYjQPCoiI", "YbwBTTGZjlTjNPwoU", "FzN", "wbEYE", "CWdARjeFIRKmM", "UgeDlBYthRdkrx", "."}));
		Assert.assertArrayEquals(new String[] {"spPbFWYYWYVbXfYZY", "qRe", "uOJQn", "MBktWNbnCrWTPCzQTnkw", "fOxMmxV", ".Fjg", "Gbzrudbi", "oXvXIJtRDqGkwTrmPcO", "l", "GqCyxoLAYhUJ", "mGZFXFZxopBBudUt", "QlduN", "Op", "moXms", "kcFPfNl.Bj", ".", ".."} 	, dir.getFiles(new String[] {"..", "qRe", "uOJQn", "MBktWNbnCrWTPCzQTnkw", ".", ".Fjg", "Gbzrudbi", "oXvXIJtRDqGkwTrmPcO", "l", "GqCyxoLAYhUJ", "mGZFXFZxopBBudUt", "QlduN", "Op", "moXms", "kcFPfNl.Bj", "fOxMmxV", "spPbFWYYWYVbXfYZY"}));
		Assert.assertArrayEquals(new String[] {"LPvjmshH", "WucLKHlBnYujkw", "XbPETLcMsMYdpi.qu", "tbRoKfOLsmCcXDvhd.yp", "zJR", "iYkJMwXkScKsBIOIJ", "uvGjqBk.cVRiBRNz", "mjlz", "XiWJFuVGGMQCbwIpbjs", "rLSy", "EkdvDZGefA.P", "VhqUVnGprH.rADBoRR", "zNNiKckKrNJKnFJQSVd", "GIyBkKbl", "DzwRColvdnRBsASAB", ".", ".."} 	, dir.getFiles(new String[] {"LPvjmshH", "WucLKHlBnYujkw", "XbPETLcMsMYdpi.qu", "tbRoKfOLsmCcXDvhd.yp", "zJR", "iYkJMwXkScKsBIOIJ", "uvGjqBk.cVRiBRNz", "mjlz", "XiWJFuVGGMQCbwIpbjs", "rLSy", "EkdvDZGefA.P", "VhqUVnGprH.rADBoRR", "zNNiKckKrNJKnFJQSVd", "..", "DzwRColvdnRBsASAB", ".", "GIyBkKbl"}));
		Assert.assertArrayEquals(new String[] {"ykaerT.pXbD.Lns", "sc", "VGmkMEOUr", "COMhqlxOUJmgZQQ", "PeH", "NLa", "Xjn", ".", ".."} 	, dir.getFiles(new String[] {"ykaerT.pXbD.Lns", "sc", "VGmkMEOUr", "COMhqlxOUJmgZQQ", "PeH", "..", "Xjn", "NLa", "."}));
		Assert.assertArrayEquals(new String[] {"aYYhhg", "cRlBEbJKPAeXtzWGY", "KeMJLZTNqlnxOwnXvV", "BnpqaYaKiTaHIsygktXv", "..", "."} 	, dir.getFiles(new String[] {".", "cRlBEbJKPAeXtzWGY", "KeMJLZTNqlnxOwnXvV", "..", "BnpqaYaKiTaHIsygktXv", "aYYhhg"}));
		Assert.assertArrayEquals(new String[] {".HmKDDI", "aD", "bSedVQuDiXNue", "IRsuk", "VLlfnl.zaTyihOlm", "crhsu", "PEOkSAiEuRlq.pGxQmc", "hcFtlGYdHAvUnnxdyQhW", "FV", "kjSn.EMLQWtvoICg", "LbcouMbu", "sHkXPdUCTZFZpCc", "YhZfihGqKzR", ".", ".."} 	, dir.getFiles(new String[] {".HmKDDI", "aD", "bSedVQuDiXNue", "IRsuk", "VLlfnl.zaTyihOlm", "crhsu", "..", "hcFtlGYdHAvUnnxdyQhW", "FV", "kjSn.EMLQWtvoICg", "LbcouMbu", "sHkXPdUCTZFZpCc", "YhZfihGqKzR", ".", "PEOkSAiEuRlq.pGxQmc"}));
		Assert.assertArrayEquals(new String[] {"IjCeQzpgUxnaD", "ILLXqsUk", "QDHipSS", ".MgQ", "mrIr.UZB", "LvgpfVu.mKM", "..", "."} 	, dir.getFiles(new String[] {".", "ILLXqsUk", "..", ".MgQ", "mrIr.UZB", "LvgpfVu.mKM", "QDHipSS", "IjCeQzpgUxnaD"}));
		Assert.assertArrayEquals(new String[] {"bHMAlvvwVO", "iAty.qOcJZSgHezBiGTE", "B.KHWAwvuMD", "rX", "GfSPUKxuPLhyptVzykg", "KlYmDCyDtMRVUODe", "ZNxsqK.", "gOMKpIAtiUaj.UGolIf", "bBbpZNvOKFFpzKPyUqzQ", "x.wwMXhoa", "pjMBWgWLBLDYvTBVIQ.e", "lcukIMvOwoVxmanbEZLz", "rJWabz", "AWoEaRvFbgVGpYcz", "wzdWXqjz", "HbD.JNtBqmQDt", "WrdvNRr", "sD", "JIn.USFZLuYuihOgZm", "LKN", "KIytUFZp", ".uljRFv.sZPznPhR", "QUcPbquaudXpIiQBy", "bVRImqycZOxEGyaiKfUD", "UoL", "NzOycOBVKpz", "SLdrJTegP", "GlyZxCCuDlCgAPKR", "mbxBozKtxeAHhyhLhF", "XrfqyutaMN", "DEnRRwP", "rIIbKb.rqllOAGVIh", "YuWEBJPYThoiAS", "LyP.jBAB", "mFnOAzDFj", "IJpgqw", "YvnUaXyduC", "pJpDIQVk", "c", "ny", "wPIufzLHYQCs", "dlVhy.rPxbQvutyRIqO", "jlmGXlqhNsXmRUYwAxEP", "wYVoxrushHu", "ju", "ijr", "VXi", "..", "."} 	, dir.getFiles(new String[] {"bHMAlvvwVO", "iAty.qOcJZSgHezBiGTE", "B.KHWAwvuMD", "rX", "GfSPUKxuPLhyptVzykg", "KlYmDCyDtMRVUODe", "ZNxsqK.", "gOMKpIAtiUaj.UGolIf", "bBbpZNvOKFFpzKPyUqzQ", "x.wwMXhoa", "pjMBWgWLBLDYvTBVIQ.e", "lcukIMvOwoVxmanbEZLz", "rJWabz", "AWoEaRvFbgVGpYcz", "wzdWXqjz", "HbD.JNtBqmQDt", "WrdvNRr", "sD", "JIn.USFZLuYuihOgZm", "LKN", "KIytUFZp", ".uljRFv.sZPznPhR", "QUcPbquaudXpIiQBy", "bVRImqycZOxEGyaiKfUD", "UoL", "NzOycOBVKpz", "SLdrJTegP", "GlyZxCCuDlCgAPKR", "mbxBozKtxeAHhyhLhF", "XrfqyutaMN", "DEnRRwP", "rIIbKb.rqllOAGVIh", "YuWEBJPYThoiAS", "LyP.jBAB", "mFnOAzDFj", "IJpgqw", "YvnUaXyduC", ".", "c", "ny", "wPIufzLHYQCs", "dlVhy.rPxbQvutyRIqO", "jlmGXlqhNsXmRUYwAxEP", "wYVoxrushHu", "ju", "ijr", "VXi", "..", "pJpDIQVk"}));
		Assert.assertArrayEquals(new String[] {".", ".."} 	, dir.getFiles(new String[] {".", ".."}));
		Assert.assertArrayEquals(new String[] {"UgAzS", "uHTtJY", "crgQJvZoNLuIj", "tqiRElXZVrHY.BtDm", "NztUUW.PUwZdEcTg", "Ui", "qvyVXoATDsQ", "ihAaoSvAmnzULlhm", "e", "tJOb", "NdsuTQIqLcJ", "tBJzQ", "x.Y", "LcoycXLFwBjdbMLYs", "cRXQFSlIuaivGwTJJOe", "RurJOuKiIYoDMeyyW.N", "qvAyitnMhWAVMmrad", "GAPSAdDoEYTyyLLItus", "FqULzI", "pGlMMox", "T", "pBblBbzBbjXOJ", "BsMuHS", "UWDolYKfuXsA", "JSY", "MadCURQCcCsiunWZ", "..", "."} 	, dir.getFiles(new String[] {"UgAzS", "uHTtJY", "crgQJvZoNLuIj", "tqiRElXZVrHY.BtDm", "NztUUW.PUwZdEcTg", "Ui", "qvyVXoATDsQ", "ihAaoSvAmnzULlhm", "e", "tJOb", "NdsuTQIqLcJ", "tBJzQ", "x.Y", "LcoycXLFwBjdbMLYs", "cRXQFSlIuaivGwTJJOe", "RurJOuKiIYoDMeyyW.N", "qvAyitnMhWAVMmrad", "GAPSAdDoEYTyyLLItus", "FqULzI", "pGlMMox", "T", "pBblBbzBbjXOJ", "BsMuHS", ".", "JSY", "..", "MadCURQCcCsiunWZ", "UWDolYKfuXsA"}));
		Assert.assertArrayEquals(new String[] {"EcYES.NEEnuCF.KZZiEw", "HmWlr.VGt.vVOBAI", "Ie", "se", "NMsrpJnz", "hrjAymxagF", "mjgNAEFMFwAylvbHnJl", "VdWIcdKjtj", "rkoyCeIFS", "HjK", "LOm", "SVMGmsKbqQ.xRdvIbLkX", "cFZ", "uNMPmpKioyLH", "OVJm.ryxbyPfSZQjn", "SvDYLGNCe.gfi", "xAMfyvTGGFvppUdUwSo", "ddSHqE.QUbTiUXbu", "wREZJagGh", "IaLExxIMjUjgWDa.NfO", "wzax", "sJhMIFdB", "..", "."} 	, dir.getFiles(new String[] {"EcYES.NEEnuCF.KZZiEw", "HmWlr.VGt.vVOBAI", "Ie", "se", "NMsrpJnz", "hrjAymxagF", "mjgNAEFMFwAylvbHnJl", "VdWIcdKjtj", "rkoyCeIFS", "HjK", "LOm", "SVMGmsKbqQ.xRdvIbLkX", "cFZ", "uNMPmpKioyLH", "OVJm.ryxbyPfSZQjn", "SvDYLGNCe.gfi", "xAMfyvTGGFvppUdUwSo", "ddSHqE.QUbTiUXbu", ".", "..", "wzax", "sJhMIFdB", "IaLExxIMjUjgWDa.NfO", "wREZJagGh"}));
		Assert.assertArrayEquals(new String[] {"IWN", "xVvYNPiJfdvtEHfomB", "SMzpVu", "yciQORaxCETBDLcxPok.", "aKXWPVbG", "ZYERuHzLNBrNZOgY.", "avvbknWbrqO", "wwxjy", "BRhjDxZZGgw", "SzLoYOde", "oKNXxHdOjzHNDfTV", "d", "dIPcoL.zLkJpvsCS", "vVXcmGAlszwMEyhFloyl", "nNXlZKeSUU", "f", "SsyUSboZ", "CBMcrQCgWSExKQoW", "Rhf", "sdnnrjuZzrleipio.s", "vVYPqbCUJlGvLuS", "yXwVsF", "bxPCgQO", "SIxUbUeUBl", "VgQTgjmryXriO.C", "nsyzA", "YoBRBPMhOybgdokZp", "m", "ILCrdIRQTTEnldiHT", "RtK", "wTSVCPvRz", "xWAVqLDWrHffyGz.I", "qSCFmHVdwi", "kUMyBvLSXHnUgpekHj", "YwvtgB", "..", "."} 	, dir.getFiles(new String[] {"IWN", "xVvYNPiJfdvtEHfomB", "SMzpVu", "yciQORaxCETBDLcxPok.", "aKXWPVbG", "ZYERuHzLNBrNZOgY.", ".", "wwxjy", "BRhjDxZZGgw", "SzLoYOde", "oKNXxHdOjzHNDfTV", "d", "dIPcoL.zLkJpvsCS", "vVXcmGAlszwMEyhFloyl", "nNXlZKeSUU", "f", "SsyUSboZ", "CBMcrQCgWSExKQoW", "Rhf", "sdnnrjuZzrleipio.s", "vVYPqbCUJlGvLuS", "yXwVsF", "bxPCgQO", "SIxUbUeUBl", "..", "nsyzA", "YoBRBPMhOybgdokZp", "m", "ILCrdIRQTTEnldiHT", "RtK", "wTSVCPvRz", "xWAVqLDWrHffyGz.I", "qSCFmHVdwi", "kUMyBvLSXHnUgpekHj", "YwvtgB", "VgQTgjmryXriO.C", "avvbknWbrqO"}));
		Assert.assertArrayEquals(new String[] {"NlnKDFqDdsCqathg", "gxMaxseRm.SXc.jTb", "qXMiGQr", "LeQcTPjtK", "H", "ixAfL", "UhZRPcsOBjKPHlQlPwq", "UNmXx.XhwJnrgwRPq", "rxzUXDCHbVwqSskNgtKi", "vgt", "wVgZjdS", "FEoSAtoAxy", "zHEYbkgqvTjmkoLf", ".xeVozFaSu", "JU", "nBhtpUkJTZwRejUrhrZ", "WumnuVODXkLjslMvr", "XhTMrLEiEBGuFYCZu", "JQlaLGwY", "RWLnCHBwltxdteXrQCA", "SjUxUN.G", "chLApEkFcmfhLLi", "OxWxDHZRhWcwyjGryqeb", "TqRISPR", "VNKB", "KIAGrAGZy.AKNkvweLjR", "QrSPSVmL", "HJ", "ECrBEwqfQQidoJVyqcK", "dDzFtLe", "YKvDjKjXjdhUFkmJYNB", "pQpXBgUkMOCdHLLNsfxq", "MY", "lCeIRi.", "wWD.iJa", "GFAaiBZbLRyNHUTfiv", "blroClHpEhAXxV", "OqxKqM", "TXdwMsJsg", "VSIGiPekrVOLdZuLfv", "wdoxuwdXtmOiukFRzwMX", "Ny", "TGnaCx.IFkblHmD", "PRveVeaJaQxqoFnPqrVb", "OilZFfWgzHgBPADbNhEN", "ni", "flRLIBvbDQ", ".", ".."} 	, dir.getFiles(new String[] {"NlnKDFqDdsCqathg", "gxMaxseRm.SXc.jTb", "qXMiGQr", "LeQcTPjtK", "H", "ixAfL", "UhZRPcsOBjKPHlQlPwq", "UNmXx.XhwJnrgwRPq", "rxzUXDCHbVwqSskNgtKi", "vgt", "wVgZjdS", "FEoSAtoAxy", "zHEYbkgqvTjmkoLf", ".xeVozFaSu", "JU", "nBhtpUkJTZwRejUrhrZ", "WumnuVODXkLjslMvr", "XhTMrLEiEBGuFYCZu", "JQlaLGwY", "RWLnCHBwltxdteXrQCA", "SjUxUN.G", "chLApEkFcmfhLLi", "OxWxDHZRhWcwyjGryqeb", "TqRISPR", "VNKB", "KIAGrAGZy.AKNkvweLjR", "..", "HJ", "ECrBEwqfQQidoJVyqcK", "dDzFtLe", "YKvDjKjXjdhUFkmJYNB", "pQpXBgUkMOCdHLLNsfxq", "MY", "lCeIRi.", "wWD.iJa", "GFAaiBZbLRyNHUTfiv", "blroClHpEhAXxV", "OqxKqM", "TXdwMsJsg", "VSIGiPekrVOLdZuLfv", "wdoxuwdXtmOiukFRzwMX", "Ny", "TGnaCx.IFkblHmD", "PRveVeaJaQxqoFnPqrVb", "OilZFfWgzHgBPADbNhEN", ".", "flRLIBvbDQ", "ni", "QrSPSVmL"}));
		Assert.assertArrayEquals(new String[] {"QCvytlZRjdTxqKUkT.Y", "mIcPeKmIHJv", "oTCOelQZFoLEIZYDhtb", "qquAEEmNxHOT", "lFH", "iLKZXbqreX", "inVbqmallLBjzTAzAl", "t", "UhF", "vqxvkcKNZXKQ", "YWA", "VRrU", "SwsYaLVd", "SFddFvPELLPLJiMw", "JLpoby", "scMWFMmrK", "xIkyGl", "KYUxCpyc.bHwPaH", "grdQu", ".Y", "JEupqFoJ", "KQqvKcB", "UY", "CkMVgbnIVUF", "ZFEuFmCHFvTUWmyvJ", "..", "."} 	, dir.getFiles(new String[] {"QCvytlZRjdTxqKUkT.Y", "mIcPeKmIHJv", ".", "qquAEEmNxHOT", "lFH", "iLKZXbqreX", "inVbqmallLBjzTAzAl", "..", "UhF", "vqxvkcKNZXKQ", "YWA", "VRrU", "SwsYaLVd", "SFddFvPELLPLJiMw", "JLpoby", "scMWFMmrK", "xIkyGl", "KYUxCpyc.bHwPaH", "grdQu", ".Y", "JEupqFoJ", "KQqvKcB", "UY", "CkMVgbnIVUF", "ZFEuFmCHFvTUWmyvJ", "t", "oTCOelQZFoLEIZYDhtb"}));
		Assert.assertArrayEquals(new String[] {"Fnmpgy", "ykucy", "nAsQhNyimSxANK", "lpSaG", "nuLeTI", "iMBDdfxLWEUUSLs", "hDLbKwAtXZLUDqsqVEuS", "U", "plWGZsWBsMjnPYNpg", "LXnafBHbWksudlctCnf.", "QZcM.tnTWcsLaqvPL", "qfO", "nqF", "bYBUwFiX", "qpyNVJa", "oSTrEgK", "VchStpAedNgJ", "rEOoLIrJHkb", "DwdGh", "E.fBEdrBQjuKdjLze", ".XcTeq.bsGHg.wF", "DSAxZTCDnal", "IzOZfqMfjrE", "cBmKDyNgsjsK", "HEe", "..", "."} 	, dir.getFiles(new String[] {"Fnmpgy", "ykucy", "nAsQhNyimSxANK", "lpSaG", "nuLeTI", "iMBDdfxLWEUUSLs", "hDLbKwAtXZLUDqsqVEuS", "U", "plWGZsWBsMjnPYNpg", ".", "QZcM.tnTWcsLaqvPL", "qfO", "nqF", "bYBUwFiX", "qpyNVJa", "oSTrEgK", "VchStpAedNgJ", "rEOoLIrJHkb", "DwdGh", "E.fBEdrBQjuKdjLze", ".XcTeq.bsGHg.wF", "DSAxZTCDnal", "IzOZfqMfjrE", "cBmKDyNgsjsK", "..", "HEe", "LXnafBHbWksudlctCnf."}));
		Assert.assertArrayEquals(new String[] {".", ".."} 	, dir.getFiles(new String[] {".", ".."}));
		Assert.assertArrayEquals(new String[] {"Wx", "wu.G", "FdfzM.Nkcp", "CkTOVBJOVO", "ZWNNbIFeipWAsbj", "GWmABAfbKnz", "XpHNZklRyNYJyp.sQZkX", "qckyUcS", "vryHjqqDcToE", "FjvHyNSB", "wYfiE", "IMiNdUPQmHGfWzczTLSo", "qfkz", "znkHCMgwiydUJDB", "AyEMVIoaTN.UthKD", "ldUBTVfmoRfSLgI", "FlEPlcXwjhjXe", "aEPtEbAfNZOTApRI", "kSkglNJSXuGV", "JIFgLn", "evdNFNIUCpzNyv", "MMj", "ZBigOFfZdguZaY", "SkqKhrmBGG", ".", ".."} 	, dir.getFiles(new String[] {"Wx", "wu.G", "FdfzM.Nkcp", "CkTOVBJOVO", "ZWNNbIFeipWAsbj", "GWmABAfbKnz", "..", "qckyUcS", "vryHjqqDcToE", "FjvHyNSB", "wYfiE", "IMiNdUPQmHGfWzczTLSo", "qfkz", "znkHCMgwiydUJDB", "AyEMVIoaTN.UthKD", "ldUBTVfmoRfSLgI", "FlEPlcXwjhjXe", ".", "kSkglNJSXuGV", "JIFgLn", "evdNFNIUCpzNyv", "MMj", "ZBigOFfZdguZaY", "SkqKhrmBGG", "aEPtEbAfNZOTApRI", "XpHNZklRyNYJyp.sQZkX"}));
		Assert.assertArrayEquals(new String[] {"EnbhjUawcwBAEvhtOMqk", "WUXYQJJumxGhpnvkX", "DVZG", "FVmEYEzAOQJUwNPwrHB", "Zt", "gxbzDcL", "SIGoAUnkh", "qA", "adCBYEn.zFkgrVvho.Yg", "wHo", "huvWYHBIRoYiu", "ZoBv.ukVQSepDCW", "rXp", "iHeX", "E", "oeaeDMXadyIC", "TKzGROPSXVlhbcGj", "l", "ZVqXwUDqK", "JtnwLdHFJDmh..S", "xTuYRRaaPANqmgX", "SzJvVrV.a", "XJIEcSkQyCmg", ".", ".."} 	, dir.getFiles(new String[] {"EnbhjUawcwBAEvhtOMqk", "WUXYQJJumxGhpnvkX", "DVZG", "..", "Zt", "gxbzDcL", "SIGoAUnkh", ".", "adCBYEn.zFkgrVvho.Yg", "wHo", "huvWYHBIRoYiu", "ZoBv.ukVQSepDCW", "rXp", "iHeX", "E", "oeaeDMXadyIC", "TKzGROPSXVlhbcGj", "l", "ZVqXwUDqK", "JtnwLdHFJDmh..S", "xTuYRRaaPANqmgX", "SzJvVrV.a", "XJIEcSkQyCmg", "qA", "FVmEYEzAOQJUwNPwrHB"}));
		Assert.assertArrayEquals(new String[] {"udGXgRUK.FXm", "CyMNJhexIrCKNvdED", "EbynnwqNKUw", "cfLDLQcxbON", "DRaSfUzZxVAzY", "Uafag", "NfrcPqy", "TiS", "PDfjiyri", "pdjWT.TfVsLk", "dGMfxHGaqWQtBySgosEE", "pmMgJWbLTnb", "nGSIgVtZV", "PRRk.tLUjzvwLvR", ".", ".."} 	, dir.getFiles(new String[] {"udGXgRUK.FXm", "CyMNJhexIrCKNvdED", "EbynnwqNKUw", "cfLDLQcxbON", "DRaSfUzZxVAzY", "..", "NfrcPqy", "TiS", "PDfjiyri", ".", "dGMfxHGaqWQtBySgosEE", "pmMgJWbLTnb", "nGSIgVtZV", "PRRk.tLUjzvwLvR", "pdjWT.TfVsLk", "Uafag"}));
		Assert.assertArrayEquals(new String[] {"LTPugNQEHDZHSWCy", "t", "kZxvgZREzrQKWNMlxn", "WaqnSPl", "XdHIwALtDJ", "TmFqCthReSvjYELdg", "..", "."} 	, dir.getFiles(new String[] {"LTPugNQEHDZHSWCy", "t", ".", "..", "XdHIwALtDJ", "TmFqCthReSvjYELdg", "WaqnSPl", "kZxvgZREzrQKWNMlxn"}));
		Assert.assertArrayEquals(new String[] {"PQbAqocUlnwneKwzyCDJ", "FFkexGe", "DzvGWAEIxrMQ", "t", "I.F", "njWVxiKaZzHcbbs", "XVmkRZGddOiacMSOQ", "bgKIRwxVEqdbrmx", "blArMpIU", "ytuFxWgNXYVLvrVbDb", "vGJBHIJ", "QyxAef", "FUGytMq", "xgZiZmgsPVDsMCZQmL", "RDYe", "r", "HwyAiHlswdbExUWXLq", "TPvBz", "kuzziVPpLzEcqLrgSnp", "VnY", ".ByPF", "G", "xTIbwjlICPIGySsI", "vLUaEVLoBEkA", "QpgvLbUOEgUnqcMQ", "ZCIMnQgnTXLFrn.H", "RYgpXN.", "SdBJnk", "OWjFE", ".MNXGGUFfgBmdHqKcBl", "lE", "gplowqcJk", "RZ", "XwDw", "yvhCpPuE", "LhOfWrFfqHHDrxLH", "QueYrxa", "d", "a", ".", ".."} 	, dir.getFiles(new String[] {"PQbAqocUlnwneKwzyCDJ", "FFkexGe", "DzvGWAEIxrMQ", "t", "I.F", "njWVxiKaZzHcbbs", "XVmkRZGddOiacMSOQ", "bgKIRwxVEqdbrmx", "blArMpIU", "ytuFxWgNXYVLvrVbDb", "vGJBHIJ", "QyxAef", "FUGytMq", "xgZiZmgsPVDsMCZQmL", "RDYe", "r", "HwyAiHlswdbExUWXLq", "TPvBz", "kuzziVPpLzEcqLrgSnp", "..", ".ByPF", "G", "xTIbwjlICPIGySsI", "vLUaEVLoBEkA", ".", "ZCIMnQgnTXLFrn.H", "RYgpXN.", "SdBJnk", "OWjFE", ".MNXGGUFfgBmdHqKcBl", "lE", "gplowqcJk", "RZ", "XwDw", "yvhCpPuE", "LhOfWrFfqHHDrxLH", "QueYrxa", "d", "a", "QpgvLbUOEgUnqcMQ", "VnY"}));
		Assert.assertArrayEquals(new String[] {"brhaSQu", "ZdInMgTvXLUkOrBZ", "UX", "GGdyyRHWIJg", "knRVebqtelsrOFw", "XHrnKey", "cHiIPLVuEJZzlU", "QCIzOOtWeUBZodCMg", "uN", "OaWUVaKRELpUdAXAb.", "SkFIoYE", "AFFFbORzd", "bbqg", "jfLBmEJV", "T", "E", "DO.XgdHBGYqF", "gljFOutYRsMyWLnmoWW", "qSjCbcbn", "VDfBRAHRU", "yEfDyEXQeDOahUIO", "vkccBR", "XiIpaNPlitqTlCjBJT.", "OyMhSjunbstdy", "y", "uMddDG.wwqZNN", "SWqDhXhF", "zLbjLCYRSpPenumeV", "EsuvIvrybVEQWr", "BYNxmiWkY", "tyyLWhNCaKCuPdjY", "BdcbAVKuvTioDEIUKyV", "EcRbHPttwWUeGRs", "spDHNYELmuWYJw", "HZYKA.ozIx", "rDTXEmZbMFYFAIn", "IvkntdjEyPXYaQyKGg", "uRjda", "kwJlEVa", ".", ".."} 	, dir.getFiles(new String[] {"brhaSQu", "ZdInMgTvXLUkOrBZ", "UX", "GGdyyRHWIJg", "knRVebqtelsrOFw", "XHrnKey", "cHiIPLVuEJZzlU", "QCIzOOtWeUBZodCMg", "uN", "OaWUVaKRELpUdAXAb.", "SkFIoYE", "AFFFbORzd", "..", "jfLBmEJV", "T", "E", "DO.XgdHBGYqF", ".", "qSjCbcbn", "VDfBRAHRU", "yEfDyEXQeDOahUIO", "vkccBR", "XiIpaNPlitqTlCjBJT.", "OyMhSjunbstdy", "y", "uMddDG.wwqZNN", "SWqDhXhF", "zLbjLCYRSpPenumeV", "EsuvIvrybVEQWr", "BYNxmiWkY", "tyyLWhNCaKCuPdjY", "BdcbAVKuvTioDEIUKyV", "EcRbHPttwWUeGRs", "spDHNYELmuWYJw", "HZYKA.ozIx", "rDTXEmZbMFYFAIn", "IvkntdjEyPXYaQyKGg", "uRjda", "kwJlEVa", "gljFOutYRsMyWLnmoWW", "bbqg"}));
		Assert.assertArrayEquals(new String[] {"WqhxZNNC.Inxd", "ROmtGvcHkX", "MM..NmzZ.wlM", "MWCqJ", "YPbehIxJc", "iDdxtLkpcrA", "jZDzTWYFp.DKz", "AaYaVRYHomxOMIQy", "FKhqyCiFUMCM", "nTkvMAcRnRIGpdOzlA", "GGglAXwzhpKp", "ymTTl", "oHQMYPRRYiYbKWv", "wClhRrwiqEpx", "..", "."} 	, dir.getFiles(new String[] {"WqhxZNNC.Inxd", "ROmtGvcHkX", "MM..NmzZ.wlM", "MWCqJ", "YPbehIxJc", "iDdxtLkpcrA", "jZDzTWYFp.DKz", "AaYaVRYHomxOMIQy", "FKhqyCiFUMCM", ".", "GGglAXwzhpKp", "..", "oHQMYPRRYiYbKWv", "wClhRrwiqEpx", "ymTTl", "nTkvMAcRnRIGpdOzlA"}));
		Assert.assertArrayEquals(new String[] {"tbWxmPe", ".tGd", "WrvxAmwAhn", "eWajeNxo.lwNp", "yPVShhGP", "bLjKwptFlF", "G", "paLhTmnnvyCPjeOCLNeb", "Ynke", "MVxSPNSFFUDYsSPRtLSq", "l", "sAc", "opRYt", "FaJL", "pCmYnZoKEenIBT", "hWzOQFmBCtxag", "EyvKbjlPV", "mk", "GNRuraZquCnxFUm", "BpnFjnfvWXg.mEvZPO", "OhNgHdGtyVkxcB", "jAWQRHXGICtaUrDbDvv", ".", ".."} 	, dir.getFiles(new String[] {"tbWxmPe", "..", "WrvxAmwAhn", "eWajeNxo.lwNp", "yPVShhGP", "bLjKwptFlF", ".", "paLhTmnnvyCPjeOCLNeb", "Ynke", "MVxSPNSFFUDYsSPRtLSq", "l", "sAc", "opRYt", "FaJL", "pCmYnZoKEenIBT", "hWzOQFmBCtxag", "EyvKbjlPV", "mk", "GNRuraZquCnxFUm", "BpnFjnfvWXg.mEvZPO", "OhNgHdGtyVkxcB", "jAWQRHXGICtaUrDbDvv", "G", ".tGd"}));
		Assert.assertArrayEquals(new String[] {"SrOaPvxOu", "gFaX.f", "PQtgm", "HQkzmkBnHDXRezca", "PZvhn.IP", "yBNfQNHO.", "ytI.", "ZOF", "wRqdAILENxmmsJhiNOhA", "C", "XhTVzA.WXY", "BCzbOkoVHQwUPBeBnB", "nZBehLSlTFQjArhznBk", "YDRVRP.ajyHEpfsC", "EJawCieZyDdc", "bogtIliRhFf", "p", ".", ".."} 	, dir.getFiles(new String[] {"SrOaPvxOu", "gFaX.f", "PQtgm", "HQkzmkBnHDXRezca", "PZvhn.IP", "yBNfQNHO.", "ytI.", "ZOF", "wRqdAILENxmmsJhiNOhA", "C", "XhTVzA.WXY", "BCzbOkoVHQwUPBeBnB", "..", "YDRVRP.ajyHEpfsC", ".", "bogtIliRhFf", "p", "EJawCieZyDdc", "nZBehLSlTFQjArhznBk"}));
		Assert.assertArrayEquals(new String[] {"PAsSiKkvuFyBjIiYl", "uBCd", "zmu.p", "GACPUiRilzhHhF", "..", "."} 	, dir.getFiles(new String[] {"PAsSiKkvuFyBjIiYl", "uBCd", "zmu.p", ".", "..", "GACPUiRilzhHhF"}));
		Assert.assertArrayEquals(new String[] {"OkpVxCtQHFbLMItYiQ", "tZbFbC", "GtBkoxq", "nRoZXkRhcvxNOodEAmn", "tMKCvbBBpyPFaJ", "flquOJ", "bdGVCwLcTYqGa", "FCLtmvyAoCT", "SuieHXchRAmEJE", "NfgfiRRAxfiXUClEACvE", "eovE", "MHdkj", "DJTG", "QFEsOnIv", ".", ".."} 	, dir.getFiles(new String[] {"OkpVxCtQHFbLMItYiQ", "tZbFbC", "GtBkoxq", "..", "tMKCvbBBpyPFaJ", "flquOJ", "bdGVCwLcTYqGa", ".", "SuieHXchRAmEJE", "NfgfiRRAxfiXUClEACvE", "eovE", "MHdkj", "DJTG", "QFEsOnIv", "FCLtmvyAoCT", "nRoZXkRhcvxNOodEAmn"}));
		Assert.assertArrayEquals(new String[] {"BNqp", "Y", "uGzLOrVfrENI", "gh.", "sjNeNVkThRfKLWS", "ZfirLizmCPSDMpM", "NCQOpLw", "gWC", "bQKzHJ", "XwN.hIiBQdkbbG", "UnHcxHMQfmZSBeYCFjs", "raRnL", "BrcSxhj", "PbnwtNN", "cdXGxHQWbZ", "UnDM", "OlFcLyKF", "hlfWEi", "n", "xjBpHrObbAlisJW", "cLB.pacuYteLmjJZb", "KinkJL.kjl", "nZLn.KoSEGCbKem", "ed", "..", "."} 	, dir.getFiles(new String[] {"BNqp", "Y", "uGzLOrVfrENI", "gh.", "sjNeNVkThRfKLWS", "ZfirLizmCPSDMpM", "NCQOpLw", "gWC", "bQKzHJ", "XwN.hIiBQdkbbG", "UnHcxHMQfmZSBeYCFjs", "raRnL", ".", "PbnwtNN", "cdXGxHQWbZ", "UnDM", "OlFcLyKF", "hlfWEi", "n", "xjBpHrObbAlisJW", "cLB.pacuYteLmjJZb", "KinkJL.kjl", "nZLn.KoSEGCbKem", "ed", "BrcSxhj", ".."}));
		Assert.assertArrayEquals(new String[] {"cDEURSSRyfmcrtcYEUed", "OrkrTeufKablDYOMmTK", "oyQnShbbJbAjSIcg", "yHaWMlXoRHvkCeYWAlZi", "D", "RPFMZInTsqqip", "fsjbDrKlxPbZgu.Ju", "tiSfoyLHkieAnVeErL", "mHBVgFJCcpQlRqoFlHWQ", "jcaMwqzj", "BaPtTFgk", "gwsubdbGGXBZ", "XlKZIrLvi", "wl", "PwJbiKNkTK.ohWk", "LpKiC", "SpsZwLRxZgnoG", "kRKDyOUvZvGXSaZmUAxc", "FSBKxFZsFojmHpcu", "qansbazGCS", "A", "NAgisdmTZpNXkKE", "PNvvcpOcPqWwXC", "HZExiUpel", "TQnoOAiTc", "ManMofveo", ".", ".."} 	, dir.getFiles(new String[] {"cDEURSSRyfmcrtcYEUed", "OrkrTeufKablDYOMmTK", "oyQnShbbJbAjSIcg", "yHaWMlXoRHvkCeYWAlZi", "D", "RPFMZInTsqqip", "fsjbDrKlxPbZgu.Ju", "tiSfoyLHkieAnVeErL", "mHBVgFJCcpQlRqoFlHWQ", "jcaMwqzj", "BaPtTFgk", "gwsubdbGGXBZ", "XlKZIrLvi", "wl", "PwJbiKNkTK.ohWk", "LpKiC", "..", "kRKDyOUvZvGXSaZmUAxc", "FSBKxFZsFojmHpcu", "qansbazGCS", "A", "NAgisdmTZpNXkKE", "PNvvcpOcPqWwXC", "HZExiUpel", "TQnoOAiTc", ".", "ManMofveo", "SpsZwLRxZgnoG"}));
		Assert.assertArrayEquals(new String[] {"otrIJksLDnE", "oBIlrppNaqHsdiAIlYsc", "GBKlzAGGPjJmZmsvefv", "ZwjjBiJBwX.EC", "Kjc", "xZ", "dkT", "yOqbg", "zNAfWXPdmXuhn", "iMagHZeAhzJr.", "IsELlNPZCiOh", "joerBofoMBAjVNILHLE", "tyGwCtxgFJacnVpvloJ", "RGnSf", "yjZCfsMUMEm", "hYHxx", "onrEqjkUoZMJOICXBCHp", "eRmfcNNaIrSKZf", "b", "..", "."} 	, dir.getFiles(new String[] {"otrIJksLDnE", "oBIlrppNaqHsdiAIlYsc", "GBKlzAGGPjJmZmsvefv", "ZwjjBiJBwX.EC", ".", "xZ", "dkT", "..", "zNAfWXPdmXuhn", "iMagHZeAhzJr.", "IsELlNPZCiOh", "joerBofoMBAjVNILHLE", "tyGwCtxgFJacnVpvloJ", "RGnSf", "yjZCfsMUMEm", "hYHxx", "onrEqjkUoZMJOICXBCHp", "eRmfcNNaIrSKZf", "b", "yOqbg", "Kjc"}));
		Assert.assertArrayEquals(new String[] {"tEgee", "zDDoy.", "hKLIzH.Baynub", "MnKwMRlfewo", "tGtFj", "mMisrtA", "sfdgJQPmq", "ISXCtbSdVcdCAAZPv", "DaEBQ", "AHCss.ppKyoi", "ivkVAMyDl", "IZySmLfVzUnp", "VrVh", "R.ftGfjIiiZEIfu", "MIytIAJzS", "jiYZbRbbLIlvBkKgUJ", "chzdDlQcDk", "a", "gIJZOF", "EPk", "wtxqQYwSKTg.Zq", "BXkHIssLbGchXqtcncuJ", "RGpjYiFrZjik", "toUKxobvpjLURWewPk", "nA", "RS", "H", "VMbtVoiVFvgKL", "iEHrNpcYUs", "MAPirAwNGyTuOQ", "TvbU.", "llBLiGrpZoHy", "SHthcbBb.GDWvsCyuWLA", "J", "aTYc", "bXWkPYJEMsdGIva", "oGdkvQfEuYWRBnntyFzZ", "prr", "twfN", "fjJuPcFmhOuxLsxt", "..", "."} 	, dir.getFiles(new String[] {"tEgee", "zDDoy.", "hKLIzH.Baynub", "MnKwMRlfewo", "tGtFj", "mMisrtA", "sfdgJQPmq", "ISXCtbSdVcdCAAZPv", "DaEBQ", "AHCss.ppKyoi", "ivkVAMyDl", "IZySmLfVzUnp", "VrVh", "R.ftGfjIiiZEIfu", "MIytIAJzS", "jiYZbRbbLIlvBkKgUJ", "chzdDlQcDk", "a", "gIJZOF", "EPk", "wtxqQYwSKTg.Zq", "BXkHIssLbGchXqtcncuJ", "RGpjYiFrZjik", "toUKxobvpjLURWewPk", "nA", "RS", "H", "VMbtVoiVFvgKL", "iEHrNpcYUs", "MAPirAwNGyTuOQ", "TvbU.", ".", "SHthcbBb.GDWvsCyuWLA", "J", "aTYc", "bXWkPYJEMsdGIva", "oGdkvQfEuYWRBnntyFzZ", "prr", "..", "fjJuPcFmhOuxLsxt", "twfN", "llBLiGrpZoHy"}));
		Assert.assertArrayEquals(new String[] {"kdLldIlsJfMGV", "CjVKBhnIhBArinG", "sBSMjjmfU.KZZdXBSX", "vFTp", "VFQ", "bOfyM.w", "JHfE.QGfeSsZVAsIWNa", "rhAdLhPIILiBKRf", "KXDizBdTdsU", "cPlug", ".nxdUrabLVkpOMBojWu", "ylONrmLvyrwCN", "XWtnquMWwG", "XrjqoxbkSswpj", "FsVInJkMqzLGgjXvM", "aPJxxewqqTvIFGry", "mdekOaYvFpX", "zEK.MesRl.L", "snGMrSEqcGV", ".", ".."} 	, dir.getFiles(new String[] {"kdLldIlsJfMGV", "CjVKBhnIhBArinG", "..", "vFTp", "VFQ", "bOfyM.w", "JHfE.QGfeSsZVAsIWNa", ".", "KXDizBdTdsU", "cPlug", ".nxdUrabLVkpOMBojWu", "ylONrmLvyrwCN", "XWtnquMWwG", "XrjqoxbkSswpj", "FsVInJkMqzLGgjXvM", "aPJxxewqqTvIFGry", "mdekOaYvFpX", "zEK.MesRl.L", "snGMrSEqcGV", "rhAdLhPIILiBKRf", "sBSMjjmfU.KZZdXBSX"}));
		Assert.assertArrayEquals(new String[] {"bEFPK.I", "vRtMoupmCJcoLO", "ia.", "aWtMybbcgShXc", "DnrpjUT.fSkBfkzy", "hThP", "uoQF", "rGvXwgal.rXCzVG", "DDbbYaAbeUWXYzOx", "mzlzk", "jrCGzSugLjRMc", "zcsphxDcMuZpZomdHp", "LDRrLjOW", "UjO.ubOfsSFVFQtVxqo", "AD", "fhqtqkF", "rbBGZEuIVkhBHOUnonf", "jGiHgCFEnEMdEAFTqxS", "yviHof.wUnzHXFRpNT", "Q.NqGK", "HXuxwwLIFujnzxvgOI", "imruWff", "CBx", "..", "."} 	, dir.getFiles(new String[] {"bEFPK.I", "vRtMoupmCJcoLO", "ia.", "aWtMybbcgShXc", "DnrpjUT.fSkBfkzy", ".", "uoQF", "rGvXwgal.rXCzVG", "DDbbYaAbeUWXYzOx", "mzlzk", "jrCGzSugLjRMc", "zcsphxDcMuZpZomdHp", "LDRrLjOW", "UjO.ubOfsSFVFQtVxqo", "AD", "..", "rbBGZEuIVkhBHOUnonf", "jGiHgCFEnEMdEAFTqxS", "yviHof.wUnzHXFRpNT", "Q.NqGK", "HXuxwwLIFujnzxvgOI", "imruWff", "CBx", "fhqtqkF", "hThP"}));
		Assert.assertArrayEquals(new String[] {"hdJphQQvqFbtjllJSN", "yRlIfC", "bVjeYa", "oYvEBcNVuSU.XIIi", "umFMkuqQPjNuZyKW.JIi", "u", "BBZJ", "wro.xvKjhgbeSUtOcT", "SaHqBCzBiDFTn", "MVNFMlIaLcGLFu", "lNAdiuNgBkRtWix.NZ", "SoTPbOqpgilhuhtu", "surSKPjMwferxyMNv", "olokUuGA", ".", ".."} 	, dir.getFiles(new String[] {"hdJphQQvqFbtjllJSN", "..", "bVjeYa", "oYvEBcNVuSU.XIIi", "umFMkuqQPjNuZyKW.JIi", "u", "BBZJ", ".", "SaHqBCzBiDFTn", "MVNFMlIaLcGLFu", "lNAdiuNgBkRtWix.NZ", "SoTPbOqpgilhuhtu", "surSKPjMwferxyMNv", "olokUuGA", "wro.xvKjhgbeSUtOcT", "yRlIfC"}));
		Assert.assertArrayEquals(new String[] {"This", "test", "is", "tricky", "..", "."} 	, dir.getFiles(new String[] {"This", ".", "is", "tricky", "test", ".."}));
		Assert.assertArrayEquals(new String[] {".", ".."} 	, dir.getFiles(new String[] {".", ".."}));
		Assert.assertArrayEquals(new String[] {"Image.jpg", "..", "."} 	, dir.getFiles(new String[] {".", "..", "Image.jpg"}));
		Assert.assertArrayEquals(new String[] {"ContestApplet.jnlp", "Movie.avi", "Image.jpg", "Book.pdf", "..", "."} 	, dir.getFiles(new String[] {"ContestApplet.jnlp", ".", "Image.jpg", "..", "Book.pdf", "Movie.avi"}));
		Assert.assertArrayEquals(new String[] {"www.topcoder.com", "Ever.tried", "Fail.Better", "Ever.failed", "Again..", "No", "Matter.", "Try", "Again.", "Fail", "..", "."} 	, dir.getFiles(new String[] {"www.topcoder.com", "Ever.tried", ".", "Ever.failed", "..", "No", "Matter.", "Try", "Again.", "Fail", "Again..", "Fail.Better"}));
		Assert.assertArrayEquals(new String[] {"abc", ".", ".."} 	, dir.getFiles(new String[] {"..", "abc", "."}));
		Assert.assertArrayEquals(new String[] {"..", "."} 	, dir.getFiles(new String[] {"..", "."}));
		Assert.assertArrayEquals(new String[] {"image", ".", ".."} 	, dir.getFiles(new String[] {"..", "image", "."}));
		Assert.assertArrayEquals(new String[] {"a", "..", "."} 	, dir.getFiles(new String[] {".", "a", ".."}));
		Assert.assertArrayEquals(new String[] {"No", "Improbable", "Zaphod", "very...", "Just", "very", ".", ".."} 	, dir.getFiles(new String[] {"No", "..", "Zaphod", ".", "Just", "very", "very...", "Improbable"}));
		Assert.assertArrayEquals(new String[] {"a.a", "a.b", ".", ".."} 	, dir.getFiles(new String[] {"a.a", "..", "a.b", "."}));
		Assert.assertArrayEquals(new String[] {".Image.jpg", ".", ".."} 	, dir.getFiles(new String[] {"..", ".", ".Image.jpg"}));
		Assert.assertArrayEquals(new String[] {"a", ".", ".."} 	, dir.getFiles(new String[] {"a", ".", ".."}));
		Assert.assertArrayEquals(new String[] {"a", "b", ".", ".."} 	, dir.getFiles(new String[] {"a", "..", "b", "."}));
		Assert.assertArrayEquals(new String[] {"A", ".", ".."} 	, dir.getFiles(new String[] {"..", "A", "."}));
		Assert.assertArrayEquals(new String[] {"kk", "..", "."} 	, dir.getFiles(new String[] {"kk", "..", "."}));
		Assert.assertArrayEquals(new String[] {"Image.jpg", ".", ".."} 	, dir.getFiles(new String[] {"..", ".", "Image.jpg"}));
		Assert.assertArrayEquals(new String[] {".b", "..a", "..", "."} 	, dir.getFiles(new String[] {".", "..", "..a", ".b"}));
		Assert.assertArrayEquals(new String[] {"dsa", "..", "."} 	, dir.getFiles(new String[] {".", "dsa", ".."}));
		Assert.assertArrayEquals(new String[] {"b", "a", "..", "."} 	, dir.getFiles(new String[] {".", "a", "b", ".."}));
		Assert.assertArrayEquals(new String[] {"A", "B", ".", ".."} 	, dir.getFiles(new String[] {"A", "..", ".", "B"}));
		Assert.assertArrayEquals(new String[] {".vinay", "..dssdsd", ".", ".."} 	, dir.getFiles(new String[] {".vinay", "..dssdsd", ".", ".."}));
		Assert.assertArrayEquals(new String[] {"a", "b", "c", "..", "."} 	, dir.getFiles(new String[] {"a", "b", ".", "c", ".."}));
		Assert.assertArrayEquals(new String[] {"a", ".", ".."} 	, dir.getFiles(new String[] {"..", "a", "."}));
		Assert.assertArrayEquals(new String[] {"abc", ".a", "test", "tricky", "..", "."} 	, dir.getFiles(new String[] {".", ".a", "..", "tricky", "test", "abc"}));
		Assert.assertArrayEquals(new String[] {"This", "test", "is", "tricky", ".", ".."} 	, dir.getFiles(new String[] {"This", "..", "is", "tricky", "test", "."}));
		Assert.assertArrayEquals(new String[] {"tc", ".", ".."} 	, dir.getFiles(new String[] {"..", "tc", "."}));
		Assert.assertArrayEquals(new String[] {"a", "b", "..", "."} 	, dir.getFiles(new String[] {"a", ".", "b", ".."}));
		Assert.assertArrayEquals(new String[] {"a.a", "aa.b", ".", ".."} 	, dir.getFiles(new String[] {"a.a", "..", "aa.b", "."}));
		Assert.assertArrayEquals(new String[] {"abc", "pqr", ".", ".."} 	, dir.getFiles(new String[] {"..", "pqr", "abc", "."}));
	}

}
