package com.lam.coder.topCoder;

import junit.framework.Assert;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import com.lam.coder.topCoder.FoxAndWord;

public class FoxAndWordTest {
	FoxAndWord fox; 
	
	@Before
	public void setUp() throws Exception {
		fox = new FoxAndWord();
	}

	@After
	public void tearDown() throws Exception {
		fox = null;
	}

	@Test
	public void testHowManyPairs() {
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"tokyo", "kyoto"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"aaaaa", "bbbbb"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"ababab","bababa","aaabbb"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"eel", "ele", "lee"}));
		Assert.assertEquals(6, fox.howManyPairs(new String[] {"aaa", "aab", "aba", "abb", "baa", "bab", "bba", "bbb"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"top","coder"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"a", "b"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"a", "ab"}));
	}

	@Test
	public void testHowManyPairsSystemTest() {
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"tokyo", "kyoto"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"aaaaa", "bbbbb"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"ababab", "bababa", "aaabbb"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"eel", "ele", "lee"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"top", "coder"}));
		Assert.assertEquals(6, fox.howManyPairs(new String[] {"aaa", "aab", "aba", "abb", "baa", "bab", "bba", "bbb"}));
		Assert.assertEquals(11, fox.howManyPairs(new String[] {"acaaacaabaabbbcbbbbabcabaac", "abaaababaababaaaacbbabbbacabcbc", "babbbbcbccbbbabcaacabccaaccaacccc", "ababaaaacbbabbbacabcbcabaaababa", "aaacbbabbbacabcbcabaaababaababa", "bbccabaacacaaaabbcccabbcaac", "accabbbccccbaacbacbabbccbcabacaaababccabcb", "cbccabcabaaabcbabacbacbacbbcacc", "cbabbbbcbccbbbabcaacabccaaccaaccc", "ababaaccbbaaccbcbcaaabbcbbbbbabcaccbabac", "bababacabccacbccababaabaaaabacaacbcca", "aaaacbbcbcbcacabacabbababccaabbba", "aaccaaccccbabbbbcbccbbbabcaacabcc", "bcababcccbabacaccaacccacababbcaabca", "bacccaabccbcaaccccbcbbccbbbbccccbabbbbb", "bcaaacaaccbbacbccaccbcbcaaaacaabcbabcb", "acacabbacbacccbaccabbabaacac", "aaaababbacabaccaabacbbabcbbacabbcbb", "ababbacbbaabccbacbbaaacacacbbb", "acabccbccbaaaabbbaacbccbbacc", "ccacabccbaabcbccbbbcbabbcababccba", "bbabbbacbbacaccccabbbabbcbabbbacaaacbccbbb", "bcaaabbbbbaabbaabccbbaccbaaabac", "baaacbaabbaacaccacbbbccbbcccbc", "bcbbaabcacaaacacbcccbcbbcbbcbaabaacaccacac", "abbcccbabaccabcacbbbbaabbccbabcccab", "ababbacaaaacbcabcaccccacabcac", "cbcbcacabacabbababccaabbbaaaaacbb", "ccbabbbbcbccbbbabcaacabccaaccaacc", "abacabbacababcacbcbabccbababacabaabb", "ccaacbccaacccacccbbbccaccccbbbaacacacbcacb", "bacccbcbabbbccccbcbbccaacaacaacaabc", "bcbabcabcbbacacaaabaaacccacbcacbbba", "bccaccbccccccacbcccccbabbabab", "bbcbbcbbabaabbbcbabacbacbbcbbbcccbcb", "bbbacaaccbcbbccabaaaacabbacabac", "aabbccccccbbccaaaabbcbbabbcbcbaaccabcaab", "aabaccbabccaccaaabbcaacbabcacabaabcbbcaa", "acbabcbbcbccaabacbacbacbbbbccbbbbcccc", "bbacabcacbacbacccaabbaaabaacbbcaabacacc", "accccbbbaacacacbcacbccaacbccaacccacccbbbcc", "ccbbbccaaccbbcccaaaacaaccbaabcbbbabbaaaa", "bcabbbbbaaaacacaabcacccabbcaccaaaacbc"}));
		Assert.assertEquals(5, fox.howManyPairs(new String[] {"fbkifigf", "ifjagkj", "jcacecc", "ghgcgak", "dhfhijddb", "iejaaeb", "jifjagk", "eeahfbiag", "kjifjag", "ghbdehe", "eghbdeh", "baikfgc", "kbcjikaj", "hdeabcaai", "eagecjjfi", "jcikdigig", "debbidbi", "gfbkiig", "begcdddk", "cibakjhck", "cdgbkhejh", "cbieajcfa", "fkaijja", "fjbccad", "dfddfgd", "edahhde", "fdabeied", "ecggbbcdb", "ebgaagg", "iiejiabf", "kegfhifdk", "bebceck", "ieddkcjfg", "kjfhhke", "fbdhjjji", "hkbbecdi", "afeccid", "dihkiccb", "gejijhiih", "hkefdfgdi", "ckacfjd", "iageeahfb", "kcgjdfe", "jhicikb"}));
		Assert.assertEquals(7, fox.howManyPairs(new String[] {"tpleiolbdjtfrlrtkilb", "cekepdkmqjbnoqoci", "fadbbiblcledebkejbdigaqlphler", "elgnekaceplgdqjksjogifdmlo", "pdkmqjbnoqociceke", "qjksjogifdmloelgnekaceplgd", "frlrtkilbtpleiolbdjt", "ijkqpdmrgnlgbhnqkhrqnbpjed", "jbnoqocicekepdkmq", "rtkilbtpleiolbdjtfrl"}));
		Assert.assertEquals(36, fox.howManyPairs(new String[] {"fsismkrmifgkljcqmidqjeea", "eeafsismkrmifgkljcqmidqj", "ismkrmifgkljcqmidqjeeafs", "sismkrmifgkljcqmidqjeeaf", "afsismkrmifgkljcqmidqjee", "jcqmidqjeeafsismkrmifgkl", "ljcqmidqjeeafsismkrmifgk", "qmidqjeeafsismkrmifgkljc", "kljcqmidqjeeafsismkrmifg"}));
		Assert.assertEquals(73, fox.howManyPairs(new String[] {"bcbdddcccaddaccbabacdaccbbdbcacacdcdbccd", "caddaccbabacdaccbbdbcacacdcdbccdbcbdddcc", "cacdcdbccdbcbdddcccaddaccbabacdaccbbdbca", "bbadaaaadbbddbbcbcdbabccbcaccaaacbddbcdac", "dbbddaacdbdddadbabbdcababcdddddbddda", "ddbddbcaabddaadcacaacbad", "aabbcaabadadcaba", "dddadbbddaacdbdddadbabbdcababcdddddb", "dacddbcddabbddcdacbaddabbadaaabacabd", "cccaddaccbabacdaccbbdbcacacdcdbccdbcbddd", "bdddcccaddaccbabacdaccbbdbcacacdcdbccdbc", "aacdcddcababdccdbbba", "ddabbddcdacbaddabbadaaabacabddacddbc", "bddbcaabddaadcacaacbaddd", "dacbaddabbadaaabacabddacddbcddabbddc", "acdcddcababdccdbbbaa", "dadcdcacdcadcbddbdaaaaddc", "badadcabaaabbcaa", "abddddaadbadabbabcbaaa", "bdbdcadbdbdccdaadac", "aaccddbbdbdcccbabbacbcdacdccacaddbbb", "bddcdacbaddabbadaaabacabddacddbcddab", "aabbbdabdcbcddbbabcdcdddadccdbbbaaacadbdccaa", "dbbacddaaabbaccdb", "aadaaddbaadcddccbdcadbcabaaabaadd", "cdacbaddabbadaaabacabddacddbcddabbdd", "aaaddadcabcddadbacbaabcadbccadaddabbcddadcccdca", "bcaabadadcabaaab", "ddacddbcddabbddcdacbaddabbadaaabacab", "dbccdbcbdddcccaddaccbabacdaccbbdbcacacdc", "cdaccbbdbcacacdcdbccdbcbdddcccaddaccbaba", "bdbcacacdcdbccdbcbdddcccaddaccbabacdaccb", "bdaaadcbddbdacbdbdddaaadcbcdabcabcadcdbdbccb", "dbaccaadbaddabccaabacdbdddbdddd", "bcbbbbbcbdcadbdaabcddcbabaddadaaaaaccccbacbadb", "baddbbadcacdbdabacddacdabbabcaddbcaccadcbaa", "dbbdcbabadaddacbddaacccacdcbccadacdcbc", "aaabacabddacddbcddabbddcdacbaddabbad", "daabaaddabadbdbdddbaccccbddcacbabb", "acdaccbbdbcacacdcdbccdbcbdddcccaddaccbab", "dcabaaabbcaabada", "badddbddbcaabddaadcacaac", "bdaabdaabccdcdadcbdbbbbbaadbbdacdda", "adaaddbaadcddccbdcadbcabaaabaadda", "dcaccdaabacdbbddcbcccdbcdbbcdda", "abcdbaddddccbdcda", "acbdababcaadbdadadbabcdbacadcbbacdab", "adadcabaaabbcaab", "dbbdbabbddabbccaaaaba", "aaaabdaaaabbddcaadaaa"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"kmcegahkceneelhaabei", "cemeofbojbiibdagkbdnakl", "knfhfhcenlcjoaojednid", "jbafomffejjjbgoehcikkla", "hmmgamcleeaaohghocmnien", "lcjoaojednidknfhfhcen", "kgbjdjoemkbgjcbjoehcgo", "efhdnjchojfcdmbfebdk", "bceklbgcobdodoogljelli", "ochiabbfnkbgaiceghngh", "ebjnbmdkboicnbocimiimml", "jododeideighgdegbahcfldi"}));
		Assert.assertEquals(29, fox.howManyPairs(new String[] {"oomdminclfldcghmdbmljimbnlajbgnonljjjmoeofncgkogk", "minclfldcghmdbmljimbnlajbgnonljjjmoeofncgkogkoomd", "onhbfcokagdomcgginmjmgceookokflbnbnkbfjciikimded", "bfcokagdomcgginmjmgceookokflbnbnkbfjciikimdedonh", "clfldcghmdbmljimbnlajbgnonljjjmoeofncgkogkoomdmin", "mcgginmjmgceookokflbnbnkbfjciikimdedonhbfcokagdo", "gginmjmgceookokflbnbnkbfjciikimdedonhbfcokagdomc", "eechcdfbmbbbkekgkifnoeacjifimfijjhmhd", "fbmbbbkekgkifnoeacjifimfijjhmhdeechcd", "fenddjofbdgkdcbeaeflcokbaaociaf", "cgkogkoomdminclfldcghmdbmljimbnlajbgnonljjjmoeofn", "jmlonhhlabbncmbc", "onhhlabbncmbcjml", "nkbfjciikimdedonhbfcokagdomcgginmjmgceookokflbnb", "ghmdbmljimbnlajbgnonljjjmoeofncgkogkoomdminclfldc", "nhbfcokagdomcgginmjmgceookokflbnbnkbfjciikimdedo", "imnnbaoejfhldkigahhdhlldanenlomenblonhnlabnclhng", "jmmaodakaeghaonojifhcjoodhknjnohmkgal", "oolancghciimegjlekonmbe", "bmbbbkekgkifnoeacjifimfijjhmhdeechcdf"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"eadfbccbffefcffaeadbb", "acbcbbadfb", "edcaafaabddeaededeccfbff", "aededeccfbffedcaafaabdde"}));
		Assert.assertEquals(153, fox.howManyPairs(new String[] {"ecceeaadddebaccbeeacadebdaecaccacadbccedcb", "dbccedcbecceeaadddebaccbeeacadebdaecaccaca", "aecaccacadbccedcbecceeaadddebaccbeeacadebd", "ecaccacadbccedcbecceeaadddebaccbeeacadebda", "dcbecceeaadddebaccbeeacadebdaecaccacadbcce", "ceeaadddebaccbeeacadebdaecaccacadbccedcbec", "bdaecaccacadbccedcbecceeaadddebaccbeeacade", "cbeeacadebdaecaccacadbccedcbecceeaadddebac", "adebdaecaccacadbccedcbecceeaadddebaccbeeac", "caccacadbccedcbecceeaadddebaccbeeacadebdae", "baccbeeacadebdaecaccacadbccedcbecceeaaddde", "ccacadbccedcbecceeaadddebaccbeeacadebdaeca", "cceeaadddebaccbeeacadebdaecaccacadbccedcbe", "acadbccedcbecceeaadddebaccbeeacadebdaecacc", "eaadddebaccbeeacadebdaecaccacadbccedcbecce", "accacadbccedcbecceeaadddebaccbeeacadebdaec", "eacadebdaecaccacadbccedcbecceeaadddebaccbe", "daecaccacadbccedcbecceeaadddebaccbeeacadeb"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"jhgjfdekdbgijfeeiich", "bcdkhbgcabifbdkfckgkhbkii", "idjcccjgjhghgajgkiaaebhhkjed", "ggebiccdedihbbdidfiiihbha", "iahhfcgckhdcbejg", "gkhbkiibcdkhbgcabifbdkfck", "bhehjgcgbjfacjacacbi", "habgdikcgcbbjdjadkgicacaijjik", "fgbeicfhcjbhgbbeadekafagjfdjbgihgh", "cdifkkccjjddcckkjjfkgikji", "ceddahbiiddgahekebfghchjdi"}));
		Assert.assertEquals(95, fox.howManyPairs(new String[] {"agocsomaqwtjnjm", "jnjmagocsomaqwt", "magocsomaqwtjnj", "suqnkwohsrjjkki", "ojdgqkmfmwpgpag", "wtjnjmagocsomaq", "somaqwtjnjmagoc", "qwtjnjmagocsoma", "hafafwbenltordagn", "pagojdgqkmfmwpg", "pgpagojdgqkmfmw", "aqwtjnjmagocsom", "gojdgqkmfmwpgpa", "jqnfnildiijna", "ocsomaqwtjnjmag", "nsobjbreidrjlff", "wlhttprcrtatg", "nkwohsrjjkkisuq", "wpgpagojdgqkmfm", "gqkmfmwpgpagojd", "ettnajqpkbqmp", "eqbchbholcadumkdf", "olcadumkdfeqbchbh", "vvtpvlajjmdkvfb", "geiseupvfwiilecm", "glpwriqdijfrtc", "dagnhafafwbenltor", "qnkwohsrjjkkisu", "ueqqavumkdfqc", "gbqwbtkusqnetjo", "omaqwtjnjmagocs", "maqwtjnjmagocso", "tjnjmagocsomaqw", "vopgdhbcakenktt", "ijnajqnfnildi", "benltordagnhafafw", "atgwlhttprcrt", "iogakihmdgmpvtbl", "wbenltordagnhafaf", "ecmgeiseupvfwiil", "nltordagnhafafwbe", "mhkrkkfkeoiaakls", "qkmfmwpgpagojdg", "chbholcadumkdfeqb"}));
		Assert.assertEquals(38, fox.howManyPairs(new String[] {"knlcfkohccpbkegfohihliaflnejgeif", "nmaoealnjelejibgma", "aoealnjelejibgmanm", "klkmgjleaahlcpdmjcmihhohjpai", "hlcpdmjcmihhohjpaiklkmgjleaa", "dlacdlpoabnmfbbcbebdmepicghkcimmepjmeejgpgkkminl", "aniapanhlmmiemfcalcljafalhefbbhnngopfpmcabbeno", "gdmnkogdmjpkcibihpcmlklidgnpbmegjeihfaonddjglolhi", "pcdebmoglmadpbhjjiigpgoienppnaambplbhj", "jpaiklkmgjleaahlcpdmjcmihhoh", "mgjenogeelgogakpmamlmalkgoknajp", "adpbhjjiigpgoienppnaambplbhjpcdebmoglm", "bbenoaniapanhlmmiemfcalcljafalhefbbhnngopfpmca", "jiccjdgflmonlbdaaiddjfjbochnjddfmkhakjofgbfogbdof", "chmmmbaofjaofaclammklnokfmdhgdmeckbbnkgim", "dhgdmeckbbnkgimchmmmbaofjaofaclammklnokfm", "fiejlmipoiijcpeljmkcgpimkojhjfbfdmfllgghakho", "gllbmgcdbdhgifoppaiaehckddfhpccadabbkkalbbcni", "ihhefmkphoohlpinmpkdbejfaemncjehjlijpgblbpoji", "ofeahjldindieccobfnc", "ljafalhefbbhnngopfpmcabbenoaniapanhlmmiemfcalc", "ojmgdlbaeiangibkcgmkemlakkmhinkhhkbenj", "enoaniapanhlmmiemfcalcljafalhefbbhnngopfpmcabb", "olokcdpgmihkbmfjkeghalhce", "ophiekmkimcjhkfakfbaebanmpfpekdpnn", "bdkjcnhbebkgcknojchjnaiedghehfajlfcinndgfgfdmdo", "opfpmcabbenoaniapanhlmmiemfcalcljafalhefbbhnng", "jcdpgafdbmlnphamfpjlkgagdengndlifcalhdekhb", "lfpacmefmcplinnacpccpkb", "acchjemaifkfnkdjpgmffppbnkgilchleogacfpbffjdnlbk", "ajkckalmlddogbifmmpealjdlia", "bohomalohomniblecjnajnkaoehalhfmkf", "hjpaiklkmgjleaahlcpdmjcmihho", "falhefbbhnngopfpmcabbenoaniapanhlmmiemfcalclja", "fbbhnngopfpmcabbenoaniapanhlmmiemfcalcljafalhe", "kdmhbohekonieabecefghaalfgpb", "bkogeikfkebhcbhgablcgajdackahjmfkieikfjgemcdifn", "anhlmmiemfcalcljafalhefbbhnngopfpmcabbenoaniap", "ffakjaheappnjpjhlnmkcgljajlkpeepaolodek", "gcjebnpedlfdpojelbafhniillonijhop", "cjhkfakfbaebanmpfpekdpnnophiekmkim", "jfgcofobfmcnpgckbkgedjbc", "adneidnoejgaliacahnmgoigcblmmanmfhh"}));
		Assert.assertEquals(129, fox.howManyPairs(new String[] {"idlcoeqlar", "oeqlaridlc", "coeqlaridl", "lcoeqlarid", "ldbkmiqgaipj", "kmiqgaipjldb", "qlaridlcoe", "kqpcifijihn", "saesrabdcg", "dlcoeqlari", "pjldbkmiqgai", "qgaipjldbkmi", "laridlcoeq", "cgsaesrabd", "abdcgsaesr", "jldbkmiqgaip", "aipjldbkmiqg", "mohehinhgqhs", "pcifijihnkq", "ibbahbe", "miqgaipjldbk", "dcgsaesrab", "febodksk", "qhsmohehinhg", "gsaesrabdc", "cqofcnpam", "dbkmiqgaipjl", "ihnkqpcifij", "ridlcoeqla", "qpcifijihnk", "nkqpcifijih", "iqgaipjldbkm", "jihnkqpcifi", "bkmiqgaipjld", "ipjldbkmiqga", "bdcgsaesra", "mcqofcnpa", "fijihnkqpci", "psgsacp", "ijihnkqpcif", "kfebodks"}));
		Assert.assertEquals(23, fox.howManyPairs(new String[] {"dkdhhhhalhklkdkhfaljaagedel", "hhhhalhklkdkhfaljaagedeldkd", "ldkdhhhhalhklkdkhfaljaagede", "kdkhfaljaagedeldkdhhhhalhkl", "lkdkhfaljaagedeldkdhhhhalhk", "dbjakdklbdjedggllflkcjebe", "eldkdhhhhalhklkdkhfaljaaged", "ebedbjakdklbdjedggllflkcj", "gkaahbdjclfgeecibhcegkkfb", "khfaljaagedeldkdhhhhalhklkd", "hbdjclfgeecibhcegkkfbgkaa"}));
		Assert.assertEquals(295, fox.howManyPairs(new String[] {"abbababababbaababbabaaaab", "baababbabaaaababbabababab", "bbaababbabaaaababbabababa", "abaaaababbababababbaababb", "abbbbbbabaabbabbabbbaa", "bbabaaaababbababababbaaba", "ababbabaaaababbababababba", "bababbaababbabaaaababbaba", "babaaaababbababababbaabab", "aaaababbababababbaababbab", "aaababbababababbaababbaba", "babaabbabbabbbaaabbbbb", "babababbaababbabaaaababba", "bababababbaababbabaaaabab", "abbabaaaababbababababbaab", "baaaababbababababbaababba", "babbbabaabbabababbbbbbaa", "bbabaabbabbabbbaaabbbb", "abbaababbabaaaababbababab", "ababbababababbaababbabaaa", "bbbbabaabbabbabbbaaabb", "ababababbaababbabaaaababb", "babbababababbaababbabaaaa", "baabbabbabbbaaabbbbbba", "ababbbabaabbabababbbbbba", "baababbbabaabbabababbbbb", "ababbaababbabaaaababbabab", "aababbbabaabbabababbbbbb", "baaabbbbbbabaabbabbabb", "bbbbbabaabbabbabbbaaab", "aababbababababbaababbabaa", "bbababababbaababbabaaaaba", "babbabaaaababbababababbaa", "aabbabababbbbbbaababbbab", "bababbbbbbaababbbabaabba", "abbbbbbaababbbabaabbabab", "babbaababbabaaaababbababa"}));
		Assert.assertEquals(9, fox.howManyPairs(new String[] {"ccnkiofeakpkplmkdkg", "ncdibdljpdkicnhlombcl", "nhhekbkdhnacjcnldig", "npdpmhocejhddiaaijk", "goghfagljdelfmifaojdlcd", "dibdljpdkicnhlombclnc", "lmjgjmhicpfjghddlml", "gmobcppibbcdhcclfego", "monlbdnkdhlgmlfbioc", "ccieanopgjgchglgoidegof", "ejfkdikjknmkfpnifkbhdpab", "mmmaammhoicneaabfpi", "idfpaajgpjgembbpalnkjlcafm", "kpmafhpmnhfkjdfeglbnein", "lipkcbdgfpdhnlcceigpc", "keabipoihbiobbmobapgkfge", "kbkjdpaedbaldgcelcgalfffcm", "kplmkdkgccnkiofeakp", "dlmllmjgjmhicpfjghd", "ccgplfniigpcapehcjm", "pehbkpknnblmodkkkdhc", "inleojgnbnhbogoekkgmkhiagp", "dlgfcaljgcbioffblogp", "pdpmhocejhddiaaijkn", "lombclncdibdljpdkicnh", "gjcplhdfabdbpdffenenhmmdl", "illdnhcijmoahbmkmifoni", "glgoidegofccieanopgjgch", "khhjhcdjhhbchkbnomfmpokegl", "gkcllcdbljcdjeoiefellnn", "enbbabjdpficnbgphnbll", "cpdidhiddaglfapmalecpf", "opopehpiiegjdafelmifpndan", "hcpehbkpknnblmodkkkd", "kcllcdbljcdjeoiefellnng", "bjbaifphmhpmbdahfbbkokfme", "emplhkenhlfibbaglca"}));
		Assert.assertEquals(10, fox.howManyPairs(new String[] {"baegadfecdgbebgcadgbagccebdf", "ebgcadgbagccebdfbaegadfecdgb", "bgcadgbagccebdfbaegadfecdgbe", "aabcdfgbfddegagdefbcedegabg", "gbagccebdfbaegadfecdgbebgcad", "dgbebgcadgbagccebdfbaegadfec"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"imgcl", "cckkffe", "iiem", "ejil", "geaj", "elkablk", "gkkam", "gdij", "gije", "bliigf", "ceehkjm", "hcaaiha", "makehl", "ldclldf", "kiile", "eadg", "ehlmak", "gead", "mhjea", "dejh", "figmeg", "lkadl", "mafgdmd", "mclgdj", "ibcf", "mdmafgd", "hmieae", "bkibck", "flhed", "ahgada", "hllmekc", "bekg", "mbmlfah"}));
		Assert.assertEquals(87, fox.howManyPairs(new String[] {"wdttregsrtfvtduoimohoghoomcbipbotikru", "wsaeakfkqnwemwttlfgcge", "ivaguinwdwsctg", "ttregsrtfvtduoimohoghoomcbipbotikruwd", "givaguinwdwsct", "duoimohoghoomcbipbotikruwdttregsrtfvt", "nwdwsctgivagui", "tgivaguinwdwsc", "guinwdwsctgiva", "gsrtfvtduoimohoghoomcbipbotikruwdttre", "wdwsctgivaguin", "apnutisiojnskcwivggwojqosnwufjcredeaamfabo", "kqnwemwttlfgcgewsaeakf", "urnuqjiubrcsrfisdlpomvcfqnuaqlbvijtjatbw", "fmlofsppwvvqjjukurnrecehtcjh", "inwdwsctgivagu", "brcsrfisdlpomvcfqnuaqlbvijtjatbwurnuqjiu", "ghoomcbipbotikruwdttregsrtfvtduoimoho", "mlofsppwvvqjjukurnrecehtcjhf", "csrfisdlpomvcfqnuaqlbvijtjatbwurnuqjiubr", "vagqlufja", "jiubrcsrfisdlpomvcfqnuaqlbvijtjatbwurnuq", "gqlufjava", "mcbipbotikruwdttregsrtfvtduoimohoghoo", "fjcredeaamfaboapnutisiojnskcwivggwojqosnwu", "fjavagqlu", "eedccfjntoijwbkkknqckfljtdwi", "ruwdttregsrtfvtduoimohoghoomcbipbotik", "flwsckrconvjjsn", "wfajuogjcm", "fmaoui", "eownemosvrhmwjbcqgaifjtcv", "snwufjcredeaamfaboapnutisiojnskcwivggwojqo", "isnhtqsmlethpuffuciuoddkhddawrplqvfng", "uwdttregsrtfvtduoimohoghoomcbipbotikr", "qvajjmijvfrkplndowhbk", "vvqjjukurnrecehtcjhfmlofsppw", "wsctgivaguinwd", "aqlbvijtjatbwurnuqjiubrcsrfisdlpomvcfqnu", "nuqjiubrcsrfisdlpomvcfqnuaqlbvijtjatbwur", "njrgeecawhhlivfefromurbhcamjc", "jniibtrekpwh", "oodwhgdmmksprhcdmknlkueqahoeglvlkjkrbtufwfi", "qnwemwttlfgcgewsaeakfk", "ojnskcwivggwojqosnwufjcredeaamfaboapnutisi", "ogjcmwfaju"}));
		Assert.assertEquals(25, fox.howManyPairs(new String[] {"trn", "inratl", "rnt", "jnor", "ntr", "mmkrupe", "tlinra", "linrat", "mkrupem", "gmjpuuj", "uio", "egah", "nratli", "uujgmjp", "ratlin", "puujgmj", "ostpb", "jpuujgm", "atlinr", "qrgkipl"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"ilqpfafkqrldiermqmorffqieobdajlenebbgofeekcr", "apqinfdmiiiodadaoofqcirgreopqdnbcgnpkkcacg", "pkrgecceemcfrpheicdggfejhlmjlicogjdociihhjjbp", "idgedirknkaodpbbdokmrakidiocnpbiblrjhrhlmcjg", "mgdrldpfipjo", "bajrhcniihjfgrlprlbcnmmkaaefdmecdkhpmhqnhagcq"}));
		Assert.assertEquals(39, fox.howManyPairs(new String[] {"ddadabecbddccaeadacabbbcdbdaebdbaddaaeb", "edcdeaecebeabbaabaeeadccacdcccbbeaaadc", "ccaeadacabbbcdbdaebdbaddaaebddadabecbdd", "bddadabecbddccaeadacabbbcdbdaebdbaddaae", "bbbeeaeadeaebbcdbeebbdedcdbcaaddcba", "debbacbaaccdabadcaadcaeababcbecdceacadbde", "ebdbaddaaebddadabecbddccaeadacabbbcdbda", "dcbabbbeeaeadeaebbcdbeebbdedcdbcaad", "baddaaebddadabecbddccaeadacabbbcdbdaebd", "bcdbeebbdedcdbcaaddcbabbbeeaeadeaeb", "adbdedebbacbaaccdabadcaadcaeababcbecdceac", "bdedcdbcaaddcbabbbeeaeadeaebbcdbeeb", "eeaeadeaebbcdbeebbdedcdbcaaddcbabbb", "aebbcdbeebbdedcdbcaaddcbabbbeeaeade", "eaeadeaebbcdbeebbdedcdbcaaddcbabbbe", "eebbdedcdbcaaddcbabbbeeaeadeaebbcdb"}));
		Assert.assertEquals(352, fox.howManyPairs(new String[] {"cfadffbahdabhchgbch", "hchgbchcfadffbahdab", "dffbahdabhchgbchcfa", "gbchcfadffbahdabhch", "deadfhfdhbgfhaecbhd", "fadffbahdabhchgbchc", "hdabhchgbchcfadffba", "bgfhaecbhddeadfhfdh", "dhbgfhaecbhddeadfhf", "ahdabhchgbchcfadffb", "bahdabhchgbchcfadff", "dabhchgbchcfadffbah", "chcfadffbahdabhchgb", "hcfadffbahdabhchgbc", "bchcfadffbahdabhchg", "fbahdabhchgbchcfadf", "abhchgbchcfadffbahd", "adffbahdabhchgbchcf", "hgbchcfadffbahdabhc", "ffbahdabhchgbchcfad", "hbgfhaecbhddeadfhfd", "chgbchcfadffbahdabh", "fhfdhbgfhaecbhddead", "eadfhfdhbgfhaecbhdd", "gfhaecbhddeadfhfdhb", "ddeadfhfdhbgfhaecbh", "bhchgbchcfadffbahda", "bdffgdfgehdbhbagacaadb", "bhddeadfhfdhbgfhaec", "haecbhddeadfhfdhbgf", "hddeadfhfdhbgfhaecb", "adfhfdhbgfhaecbhdde", "fhaecbhddeadfhfdhbg", "cbhddeadfhfdhbgfhae", "hfdhbgfhaecbhddeadf", "dfhfdhbgfhaecbhddea", "aecbhddeadfhfdhbgfh", "fdhbgfhaecbhddeadfh", "ecbhddeadfhfdhbgfha", "bhbagacaadbbdffgdfgehd", "fgehdbhbagacaadbbdffgd", "aadbbdffgdfgehdbhbagac", "ffgdfgehdbhbagacaadbbd"}));
		Assert.assertEquals(13, fox.howManyPairs(new String[] {"bibdebiefhiacjbdbdijijahccbjfeadjdgjdiggdehch", "bichbbjbjhjijchbebjhifcaajeab", "ahaadfghdhjihdfjfhacbgdefahigbdefdffhcbhaejcgif", "hacbgdefahigbdefdffhcbhaejcgifahaadfghdhjihdfjf", "hbebjhifcaajeabbichbbjbjhjijc", "daaiefjghhfhaddciiihhgfibdcchheaacaehb", "ddcchc", "dbbahabifdgddj", "heaacaehbdaaiefjghhfhaddciiihhgfibdcch", "ggahbjiffchjdjdfdibbgdhcbgadfbfaheaijfihjcjjh", "jcebbagfbacbfdhgcaddejcadfdadfdaidicgeafibj", "jjaiiaebhafgcgjadadbgbjefcgaabggehf", "defahigbdefdffhcbhaejcgifahaadfghdhjihdfjfhacbg", "bhgdbbifbhcjigeif", "jafeidbaja", "cijgeeaicagaajjeaiegehjiaehdfhdgfeiidbi", "fbacbfdhgcaddejcadfdadfdaidicgeafibjjcebbag", "cdhibcidhigidiiebecijbhcgbi", "jeabbichbbjbjhjijchbebjhifcaa", "abcjjbgeegibhaeg", "hcjbiiiaf", "dehchfejaccbfhahebaiiaajifadgihcfdb", "hfagjhjahebefaij", "jhjijchbebjhifcaajeabbichbbjb", "gagdchjibfcdbaahcajjcagdfgbiihdhfcecagiidfebhgj", "hdh", "eaadihjedjiejifbj", "igjhabdegejdjcbiciiihddifhbeaeaj", "hhadjiiidedhceeijcdjbj", "ieeahbdeigijgabafdidegijchcfggjaahhihc", "bhcjigeifbhgdbbif", "ecijbhcgbicdhibcidhigidiieb"}));
		Assert.assertEquals(6, fox.howManyPairs(new String[] {"gdecfecajgjchlafmed", "hlafmedgdecfecajgjc", "ghhfkdeiglkdlhdgmdeldk", "idcahdhcgkmfkeemaii", "eaehebeemfcimchdhiifj", "lhdgmdeldkghhfkdeiglkd", "kkhlglmbmacldbcdbkifl", "emhcjkdiiadmmhfcgmfihcgkca", "jgdmkeagfdhaijdidfhijjhhilabge", "baldljammjaflcleii", "ghacbagedmhlaafacc", "jchlafmedgdecfecajg", "accghacbagedmhlaaf", "lfkilefljkikcllcbglekj", "ihcgkcaemhcjkdiiadmmhfcgmf", "hlmfggkffljllbggdcccmdmb", "kcckcajilklehfeeckhk"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"kndbinekhflmfe", "bdbiahcmfqlgjnmeiidqbjdeonffkpmhkqakg", "mmjccbjkoappqcgdh", "lpqhgaifnkajadecnblelkqljgp", "fjkmjbfmbjqaglb", "eafeeddqhm", "lhggibedpkpgibimfideeb", "onoaqgdmqdlaammegacaledb", "gbpodckogjjnfjjflnnfipeqkndqodhmmkk", "phkkaiijblqqmginboehmgopaofhgmk", "hcgqpkifnfohbjipahml", "hahddqlaeogmcadei", "pgqjidohpgpfmmjabinddkjnbmohgeaqb", "moljcngpgocpimmadcqlfdiqndaqmqlibhcqk", "nnqahecpgfk", "ehlgophnhoejfmpoegmaaaaclhfihpfkkmi", "qkklgjnlqmmdgk", "ghbaombnqaihakhnqppnij", "pjjipibalqaihnfnnhobn", "ednfoocephi", "hdnimjmepdh", "kmiapjappfaioncdiqgconcmjoppdnhgg", "aoolkceakpbqjogmhqjdflbohgojidd", "qdhbokdmmdm", "glbnhjhmdpbdnodpia", "phgqqokka", "phmbkphedjbfqfnpmehgehho", "llhnfedeqmlplc", "geaioihbggidkhnjml", "jpcnapagkeedqiehidjeficcg", "pkcbppmlnjcgbomql", "eeellphjndifmagofqnbnbadhbqgcpedhbb", "hchjqmdegn", "gokdkcmqalnb", "dlndafnjjmqgcldeebckb", "pjlemloccfkpocaclalagj", "iocbnlcbjmnp"}));
		Assert.assertEquals(8, fox.howManyPairs(new String[] {"beea", "eabe", "cceceeebdce", "abee", "aacadbcbdbceebed", "ccedd", "acadbcbdbceebeda", "dae", "eeab", "eceeebdcecc"}));
		Assert.assertEquals(21, fox.howManyPairs(new String[] {"hliiejpofodmjpemlnqlrqgrcehf", "cehfhliiejpofodmjpemlnqlrqgr", "hlbfbjbpmc", "ocoicbngqldrgnekdehell", "mlnqlrqgrcehfhliiejpofodmjpe", "qalpbjjpgicniclrobdhabblc", "aaojrqeopegjqppqdarqpgiirlki", "alpbjjpgicniclrobdhabblcq", "cijmodcghrlrbknhirlijlkf", "bkonffjlddgpoelcbci", "cbcibkonffjlddgpoel", "agkl", "bgkkgkiacaa", "lijlkfcijmodcghrlrbknhir", "moagkmlcrmmmpfqrkalp", "agkmlcrmmmpfqrkalpmo", "rlijlkfcijmodcghrlrbknhi", "emlnqlrqgrcehfhliiejpofodmjp", "ofnk", "nqg", "ikpcn", "roegcgp", "nenljeohpharqndrnirkdhbriecq", "bddmldhknjdehglnjgicpkgio", "epqkriljfdjdgqm", "cfggdgclerlpdpirrca", "mhgeq", "r", "oqnogbedgddkmjhabiepgdhfo", "qpng", "gbedgddkmjhabiepgdhfooqno", "abiepgdhfooqnogbedgddkmjh", "efikmiokpfalqo", "jjii", "cnikp", "nqjjfak", "alolfnpmebkdfkmkgoinrgrnah", "innjncmcjcceionmqkehhe", "be", "pbpfeegmjrijhmlce", "rqgrcehfhliiejpofodmjpemlnql", "glonhkqlampadc", "lqnkfqrm", "cc", "ncbcmjcokbceaanij", "gnekdehellocoicbngqldr"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"aeyflhakyh", "yflhakyhae", "cvmrmicmoemndqarhrpfsh", "qwixibmpso", "udqmjcrbftldgappsqymv", "gdcitrcuxsnussjpa", "xxjmaicuoolebuefnj", "deucuxucqmitgcricdb", "buljwyrmkw", "aulyrnkua"}));
		Assert.assertEquals(31, fox.howManyPairs(new String[] {"nthmwhrnnrtmcsneiqoovojgpagpgwlmanppriltk", "fjdalgwqtu", "mwhrnnrtmcsneiqoovojgpagpgwlmanppriltknth", "hrnnrtmcsneiqoovojgpagpgwlmanppriltknthmw", "manppriltknthmwhrnnrtmcsneiqoovojgpagpgwl", "dorikmjppooedubaffcfwkiu", "gwggjiaiqufithftwkjodvaafmhbv", "ojgpagpgwlmanppriltknthmwhrnnrtmcsneiqoov", "cwbauhjidcwbabknbjfq", "agpgwlmanppriltknthmwhrnnrtmcsneiqoovojgp", "ivgnlnuwtmdqhl", "vhhqcmivmoo", "lsetidcgpwcouidh", "krlcjjfgheoomqjruuovbmvgdivvbiimaldbbna", "lqtdwscpwpg", "afrnbuquplhotqwwejuvihmnrdfpwpqjvomvfuslt", "tvjfhvljn", "wvlutssnegkfgjedqtlehpocwjaamjd", "tmdqhlivgnlnuw", "whrmgalbrraswoploq", "rghfabjgwpgcluiakpnbdk", "pvhgdhjdttvlfcjhoodolawcakgnr", "qtlgnvtspuiqenmflenkifjfjwolugauhtikoiitg", "ivmoovhhqcm", "hsglwddktnolowwpkrobsapvt", "gpgwlmanppriltknthmwhrnnrtmcsneiqoovojgpa", "cjhoodolawcakgnrpvhgdhjdttvlf", "jwolugauhtikoiitgqtlgnvtspuiqenmflenkifjf", "nrhohbpsfwi", "orikmjppooedubaffcfwkiud", "hqcmivmoovh", "ucpdavkptpprebpggertpakenowgptnolilpwck", "dgccnnb", "ermhdbrtmlabfcebfevmrbiwdqjwjbfct", "hgdhjdttvlfcjhoodolawcakgnrpv", "lehpocwjaamjdwvlutssnegkfgjedqt", "oppjqebadkrgpsd"}));
		Assert.assertEquals(2, fox.howManyPairs(new String[] {"edafdfhbafdceffc", "fhaefehcafcghedecfffdafg", "fcghedecfffdafgfhaefehca", "ggadebbgcbhagcghbcddgdhbe", "hbgcbacghbfdgaeagggbbfhfdd", "ddgdhbeggadebbgcbhagcghbc", "gabbbbbbhebfbchdhfba", "efbgfhbchafefhghedbdeced", "cfdbgecfebcbedgbdhahfc", "ebbfecfbccddceebb", "cbdchefbcgfgeehgdcbgbhd", "ghgcfadcafhcfhdgceae", "dccefaebccagedhbaf", "abfhaacdbcaeeefheegaabfed", "hfbfdadbhhhfahfeggdcgcdf", "bbhebdffdfhfaeea", "ehhbdhgghcehdhgeddcadhee", "dehbagecgfedahgecghcfaeccaf", "fahhcaeaaebahfeg", "ebdecadgahbecdgfbagecc", "hceheccfdbcaecaede", "dheedcafghcaafd", "dbhdfaahdfecaaccbdcbeaegbhh", "bbbdbdbahadadf", "gfdddhfhdgdbddebccfbacaaah", "ghbhfaffgabghhfgeaehcgcgf", "bddgabhcegggbfgedfcdgbhfgce", "adahffghedehdadgbge", "dghffacbbeffcha", "fbgdcgagbcffgfefhbdhdc"}));
		Assert.assertEquals(97, fox.howManyPairs(new String[] {"blshkfikbtqlakhs", "tqlakhsblshkfikb", "ikbtqlakhsblshkf", "lakhsblshkfikbtq", "hkfikbtqlakhsbls", "sblshkfikbtqlakh", "hsblshkfikbtqlak", "oglskal", "shkfikbtqlakhsbl", "lskalog", "dtrkggrkhreetcjmfllssuogfbjr", "smpppob", "kbtqlakhsblshkfi", "lshkfikbtqlakhsb", "kfikbtqlakhsblsh", "uibauistjjrthadjbirtesmsbnnhcirp", "bthncuqpkeqjqrnjrplecjnaucjoislkla", "uogfbjrdtrkggrkhreetcjmfllss", "rbhidlbebtmeb", "ueqiohbsejfkbudhjutsgdl", "jaoq", "jjrthadjbirtesmsbnnhcirpuibauist", "btqlakhsblshkfik", "fikbtqlakhsblshk", "gucciedhjbsrrmrrneujsenppfcjp", "pobsmpp", "aflahmo", "glskalo", "aoqj", "rplecjnaucjoislklabthncuqpkeqjqrnj", "flahmoa", "tkbmoe", "naucjoislklabthncuqpkeqjqrnjrplecj", "moaflah", "psebqojmteigmllrhgfbcgnpptujuparuu", "oqja", "rrneujsenppfcjpgucciedhjbsrrm", "ebabejuiritlbeh", "rptllobqtlgdaqojjkcpgjh", "btmebrbhidlbe", "bqojmteigmllrhgfbcgnpptujuparuupse", "oetkbm"}));
		Assert.assertEquals(156, fox.howManyPairs(new String[] {"ibjchaccagdhgdjefdfj", "haccagdhgdjefdfjibjc", "efdfjibjchaccagdhgdj", "chaccagdhgdjefdfjibj", "gbgaddjg", "jejcbefaaahiggdheaefcghfegccfcgff", "ccagdhgdjefdfjibjcha", "jhadgdbaege", "fdfjibjchaccagdhgdje", "jfajicbhjgbhdghgggigiiicbhejjafea", "aahiggdheaefcghfegccfcgffjejcbefa", "ejcbefaaahiggdheaefcghfegccfcgffj", "fjibjchaccagdhgdjefd", "jefdfjibjchaccagdhgd", "gdjefdfjibjchaccagdh", "jgciiacchf", "hgdjefdfjibjchaccagd", "bjchaccagdhgdjefdfji", "ahiaaaddafagaj", "hfegccfcgffjejcbefaaahiggdheaefcg", "agajahiaaaddaf", "ia", "adhffdiihhghgbffdfggaa", "efcghfegccfcgffjejcbefaaahiggdhea", "accagdhgdjefdfjibjch", "gcfddedbhiadcjdaf", "jibjchaccagdhgdjefdf", "fjejcbefaaahiggdheaefcghfegccfcgf", "cagdhgdjefdfjibjchac", "gaddjggb", "ejjafeajfajicbhjgbhdghgggigiiicbh", "iggdheaefcghfegccfcgffjejcbefaaah", "dfjibjchaccagdhgdjef", "dhgdjefdfjibjchaccag", "cbhjgbhdghgggigiiicbhejjafeajfaji", "hjgbhdghgggigiiicbhejjafeajfajicb", "ggdheaefcghfegccfcgffjejcbefaaahi"}));
		Assert.assertEquals(34, fox.howManyPairs(new String[] {"eidhgkhbkgbmbgggbgkjigdihjheikjldk", "echcjmgkfcdhakhbaaajbie", "bgggbgkjigdihjheikjldkeidhgkhbkgbm", "mejbhbmakechfabkdldmllgmjelbj", "ieldjjgfjcbacbllhmebffmckillldgabebla", "jhilbajchbmkleibmbmbjflbjfijkeddbhjiehgfeg", "ieechcjmgkfcdhakhbaaajb", "jmgkfcdhakhbaaajbieechc", "eikjldkeidhgkhbkgbmbgggbgkjigdihjh", "hbgickhcgabkjligjbdbelh", "acgfbgdlkjcmgkdfgmhchcadhgkflhmhh", "kkdjhmcmjeakklkmmhegjbdhfjgjlkfgameibjgkmd", "fbikdejbfbddggejhkddibjbfjdj", "jmcikhileajfleegfhbeiibhlehlafm", "cjmgkfcdhakhbaaajbieech", "cahkjdaaeibmjflamccmkcdbhbkaahgfblheejbic", "lhhbgickhcgabkjligjbdbe", "hjcjlidlbedjafleigmaekkgamcacheejbmbjlcdg", "hcijgkbelbfjmklkkfimlgad", "hcaeakbfgjaaimkgkhijikfhielhidkeedblj", "jbmhdfkcchgcmeifeglccdaiggaiihiaae", "gelgcjjjdmmejleiblbejdeimeljaahajmdleeba", "dmlkaggabbiiggihcfeikfgacmheml", "cjlljdikhdemhaledhcdligeihdflmjceahbeckcd", "fabkdldmllgmjelbjmejbhbmakech", "kimflllidehimhgddaghhdikahfc", "kgbmbgggbgkjigdihjheikjldkeidhgkhb", "djmmdeiamhjdjjdhaaembhk", "fdcmkifaaclcjegljmedflbcdfl", "khbkgbmbgggbgkjigdihjheikjldkeidhg", "dljddhmckamkbmgliejhdlm", "imkgkhijikfhielhidkeedbljhcaeakbfgjaa", "baaajbieechcjmgkfcdhakh", "lkjcmgkdfgmhchcadhgkflhmhhacgfbgd", "kjldkeidhgkhbkgbmbgggbgkjigdihjhei", "mbabhldmghigaljiadlbllhidcbclkfa", "cbacbllhmebffmckillldgabeblaieldjjgfj", "abegdhgjbdfaijeagdkfaefffdk", "imbcbceeldklhdeblfiaadkbijmamjmdmkchabmemmjl", "bfgjaaimkgkhijikfhielhidkeedbljhcaeak", "mhjdjjdhaaembhkdjmmdeia", "dcbbbjjbfijlkbekmhjhmjaika", "hgddaghhdikahfckimflllidehim", "fedmcjbelebmkcalcmfihhfcih", "blffgkkdfjgehmacfccidbfcagjmjhldmheglkfkabdc"}));
		Assert.assertEquals(10, fox.howManyPairs(new String[] {"lnbifmg", "ljjmebb", "abibhniiehad", "dabibhniieha", "cmekfljceenicn", "djdicdale", "bhniiehadabi", "adabibhniieh", "bibhniiehada", "dlmmlcafhj", "cnmmbdff", "bgfmgkkej", "jjegadm"}));
		Assert.assertEquals(443, fox.howManyPairs(new String[] {"akwkceseglgglknpdtiwlfjnuwnpdpw", "knpdtiwlfjnuwnpdpwakwkceseglggl", "lfjnuwnpdpwakwkceseglgglknpdtiw", "pwakwkceseglgglknpdtiwlfjnuwnpd", "pdpwakwkceseglgglknpdtiwlfjnuwn", "lgglknpdtiwlfjnuwnpdpwakwkceseg", "jnuwnpdpwakwkceseglgglknpdtiwlf", "glknpdtiwlfjnuwnpdpwakwkceseglg", "eseglgglknpdtiwlfjnuwnpdpwakwkc", "wlfjnuwnpdpwakwkceseglgglknpdti", "eglgglknpdtiwlfjnuwnpdpwakwkces", "gglknpdtiwlfjnuwnpdpwakwkcesegl", "lknpdtiwlfjnuwnpdpwakwkceseglgg", "dpwakwkceseglgglknpdtiwlfjnuwnp", "pdtiwlfjnuwnpdpwakwkceseglgglkn", "seglgglknpdtiwlfjnuwnpdpwakwkce", "pfgtilpkuesf", "npdtiwlfjnuwnpdpwakwkceseglgglk", "fjnuwnpdpwakwkceseglgglknpdtiwl", "kceseglgglknpdtiwlfjnuwnpdpwakw", "tiwlfjnuwnpdpwakwkceseglgglknpd", "dtiwlfjnuwnpdpwakwkceseglgglknp", "ceseglgglknpdtiwlfjnuwnpdpwakwk", "nuwnpdpwakwkceseglgglknpdtiwlfj", "wnpdpwakwkceseglgglknpdtiwlfjnu", "glgglknpdtiwlfjnuwnpdpwakwkcese", "wkceseglgglknpdtiwlfjnuwnpdpwak", "uwnpdpwakwkceseglgglknpdtiwlfjn", "kwkceseglgglknpdtiwlfjnuwnpdpwa", "npdpwakwkceseglgglknpdtiwlfjnuw", "wakwkceseglgglknpdtiwlfjnuwnpdp", "fpfgtilpkues", "pkuesfpfgtil", "vhaolk", "uqbjlitpnjocofajwwafslgrkupiaqoajb", "kvhaol", "kuesfpfgtilp", "ajwwafslgrkupiaqoajbuqbjlitpnjocof"}));
		Assert.assertEquals(191, fox.howManyPairs(new String[] {"necekhmkhibbbedhcijbeimgniaefhnelk", "imgniaefhnelknecekhmkhibbbedhcijbe", "hmkhibbbedhcijbeimgniaefhnelknecek", "hcijbeimgniaefhnelknecekhmkhibbbed", "hhakcjijbeganghbaahengcahgmfgbkejgkdifbfdndbl", "mgniaefhnelknecekhmkhibbbedhcijbei", "hnelknecekhmkhibbbedhcijbeimgniaef", "ghbaahengcahgmfgbkejgkdifbfdndblhhakcjijbegan", "hifbkeelgldmaaedfgbfeiffeiddllahbcenmndg", "bbedhcijbeimgniaefhnelknecekhmkhib", "beimgniaefhnelknecekhmkhibbbedhcij", "lknecekhmkhibbbedhcijbeimgniaefhne", "eiffeiddllahbcenmndghifbkeelgldmaaedfgbf", "ejgkdifbfdndblhhakcjijbeganghbaahengcahgmfgbk", "ddllahbcenmndghifbkeelgldmaaedfgbfeiffei", "lkelggmlkcjcginefidbemjeigiemcaed", "ganghbaahengcahgmfgbkejgkdifbfdndblhhakcjijbe", "ifbfdndblhhakcjijbeganghbaahengcahgmfgbkejgkd", "mndghifbkeelgldmaaedfgbfeiffeiddllahbcen", "cijbeimgniaefhnelknecekhmkhibbbedh", "cjcginefidbemjeigiemcaedlkelggmlk", "gdgihjacggifbedhcldkbhdnebfci", "hibbbedhcijbeimgniaefhnelknecekhmk", "bkejgkdifbfdndblhhakcjijbeganghbaahengcahgmfg", "edfgbfeiffeiddllahbcenmndghifbkeelgldmaa", "iaefhnelknecekhmkhibbbedhcijbeimgn", "cldkbhdnebfcigdgihjacggifbedh", "ijbeimgniaefhnelknecekhmkhibbbedhc", "engcahgmfgbkejgkdifbfdndblhhakcjijbeganghbaah", "ecekhmkhibbbedhcijbeimgniaefhnelkn", "jbeimgniaefhnelknecekhmkhibbbedhci", "gmfgbkejgkdifbfdndblhhakcjijbeganghbaahengcah", "bfeiffeiddllahbcenmndghifbkeelgldmaaedfg", "bbbedhcijbeimgniaefhnelknecekhmkhi", "lhhakcjijbeganghbaahengcahgmfgbkejgkdifbfdndb", "fhnelknecekhmkhibbbedhcijbeimgniae", "bhdnebfcigdgihjacggifbedhcldk"}));
		Assert.assertEquals(15, fox.howManyPairs(new String[] {"ncsjdqrdqitstfencdqaafkpejqrsqt", "tnhinmodpcfmuqgaqapaculfmdap", "mqkinnpncafjqjmjadkufddeh", "grkfdgetditbstfgqejaburtkqducmsm", "oknlelrimtmisgrnofdjirgmko", "npncafjqjmjadkufddehmqkin", "qducmsmgrkfdgetditbstfgqejaburtk", "rimtmisgrnofdjirgmkooknlel", "rjlakrpdeqtacjocrafbqqa", "edikqeqmpdsdufftfjtkfksobngnr", "lruqonresgcqkigoeeuomuopnphmkiip", "isgrnofdjirgmkooknlelrimtm", "rgmkooknlelrimtmisgrnofdji", "mkincrchefoadosbabnnjeimeodnbne", "jqkgospitfsofskamjslluktoqcdnse", "ptceugjjlrcphhndbsnkqgkptkp", "jndkkccanrunplgoibbkqkjjuhml", "smgrkfdgetditbstfgqejaburtkqducm", "shldklsjucdnmihjemhgomhdd", "lfelenblqoufqaglrulauhhkjkgltt", "grnofdjirgmkooknlelrimtmis", "stfencdqaafkpejqrsqtncsjdqrdqit", "iiqlfadkjgmrkpraelmkprnuchrqtn"}));
		Assert.assertEquals(10, fox.howManyPairs(new String[] {"oocqfjenrhhomordgfcplopqjpndbghkgkpmfkdqqdnbqqqb", "qdnbqqqboocqfjenrhhomordgfcplopqjpndbghkgkpmfkdq", "homordgfcplopqjpndbghkgkpmfkdqqdnbqqqboocqfjenrh", "fcgpqndkodmaaimchkpnnhahcimrpppjkilhhbfaem", "dbghkgkpmfkdqqdnbqqqboocqfjenrhhomordgfcplopqjpn", "maqqrkdkgfmbeqlihboqqenaagremiha", "ordgfcplopqjpndbghkgkpmfkdqqdnbqqqboocqfjenrhhom"}));
		Assert.assertEquals(351, fox.howManyPairs(new String[] {"bbbabaabbbaaabbaaaababababababbab", "aaaababababababbabbbbabaabbbaaabb", "bababbabbbbabaabbbaaabbaaaabababa", "babababbabbbbabaabbbaaabbaaaababa", "abababababbabbbbabaabbbaaabbaaaab", "aaabbaaaababababababbabbbbabaabbb", "bbaaaababababababbabbbbabaabbbaaa", "bbbbabaabbbaaabbaaaababababababba", "aabbaaaababababababbabbbbabaabbba", "bbbaaabbaaaababababababbabbbbabaa", "babaabbbaaabbaaaababababababbabbb", "baabbbaaabbaaaababababababbabbbba", "babababababbabbbbabaabbbaaabbaaaa", "babbabbbbabaabbbaaabbaaaababababa", "abaabbbaaabbaaaababababababbabbbb", "ababababababbabbbbabaabbbaaabbaaa", "baaabbaaaababababababbabbbbabaabb", "bbabaabbbaaabbaaaababababababbabb", "aababababababbabbbbabaabbbaaabbaa", "abbabbbbabaabbbaaabbaaaababababab", "ababababbabbbbabaabbbaaabbaaaabab", "aabbbaaabbaaaababababababbabbbbab", "abbbaaabbaaaababababababbabbbbaba", "aaababababababbabbbbabaabbbaaabba", "bababababbabbbbabaabbbaaabbaaaaba", "bbabbbbabaabbbaaabbaaaabababababa", "abbaaaababababababbabbbbabaabbbaa"}));
		Assert.assertEquals(6, fox.howManyPairs(new String[] {"ljiagfkehlegmccaiikj", "ehlegmccaiikjljiagfk", "iagfkehlegmccaiikjlj", "kjljiagfkehlegmccaii"}));
		Assert.assertEquals(23, fox.howManyPairs(new String[] {"jhghiaegageigibifgaaeahifgciaebfhdd", "eigibifgaaeahifgciaebfhddjhghiaegag", "ecghfeadabhjbjehbigdjcgaaijbadbecbhihbjd", "ifgciaebfhddjhghiaegageigibifgaaeah", "fdhcdjbacejjabefggdfgchehjjaidjbdggedcic", "jfbbjfccabchdciaghheabcbciafhbdajjjfgcci", "bjgidbcafhfddaajdebfcjahcdaihjebahdjbedbab", "cabchdciaghheabcbciafhbdajjjfgccijfbbjfc", "efbacaigbijgjfaefhfghacggjbibgdddciefeee", "hjbjehbigdjcgaaijbadbecbhihbjdecghfeadab", "cfhchdghfcgcjhicbdfaageighbiadegehecj", "gedaaajiifijbiabhfajeaidgahdfafgbfab", "jjaidjbdggedcicfdhcdjbacejjabefggdfgcheh", "jehbbfcjfibegddchijhehdjgbfcbjcebjedgejdhb", "baahjiefabbaehfgageihifjbdgdffefahf", "gbfabgedaaajiifijbiabhfajeaidgahdfaf", "jaiajfgaaabjacfddejiifijiedaejijfcdi", "fbhgigffehdcjihedhaebjfbcaibdcdgbfhgeagd", "cijbiggcfehdaacadfbjebajcffdajdbcid", "cccficdigeafibaadghjcfjajdcbcjabeg", "cdadjchbijfhjheagbhghcjfbchbaiedic", "jfbcaibdcdgbfhgeagdfbhgigffehdcjihedhaeb", "bficicgghgfgiddeggbbjacafchbdifajdbg", "chdciaghheabcbciafhbdajjjfgccijfbbjfccab", "fjddecjjahhijjeddaadifhdecjbbfabgdiiefd", "hagcbehijeafbabeihiiighehchegbgigd", "chegbgigdhagcbehijeafbabeihiiigheh", "fijhahfhjdficgbdhjfhccbaedafbadgibci", "dcifjffhbjfgdiiiadbicdgbcbbeiajdifijdgdc", "gcccficdigeafibaadghjcfjajdcbcjabe", "ghiaegageigibifgaaeahifgciaebfhddjh", "djefchdgechdgajhfhabcfabagdibbgbbhiibjiida", "ebajcffdajdbcidcijbiggcfehdaacadfbj", "ihaghdihibbeecdgdeedcdjgbigifjaebgeeijf", "eabcbciafhbdajjjfgccijfbbjfccabchdciaghh", "iaegageigibifgaaeahifgciaebfhddjhgh", "iejfcdgieggjgidbiiigfhcbidgiddagciehgdb", "fdbjhbghgddihhbejafdbcecifebgjjcdd", "jgaijggffdbaihffdjcbacjhfadeaffhhjcbcad", "hbfjbehiiicbgceffhbejcjfdegjaicjghbcggjc"}));
		Assert.assertEquals(77, fox.howManyPairs(new String[] {"ghdpmicbbmdhdjjbal", "bbmdhdjjbalghdpmic", "dhdjjbalghdpmicbbm", "jjbalghdpmicbbmdhd", "jbalghdpmicbbmdhdj", "djaqhdnqoiopjgo", "cbbmdhdjjbalghdpmi", "micbbmdhdjjbalghdp", "ffgojgncahnbdmnhdkdb", "godjaqhdnqoiopj", "ncahnbdmnhdkdbffgojg", "hdpmicbbmdhdjjbalg", "jlohhkjpfancmjgflkdfl", "pmicbbmdhdjjbalghd", "lghdpmicbbmdhdjjba", "bmdhdjjbalghdpmicb", "odjaqhdnqoiopjg", "aqhdnqoiopjgodj", "qoiopjgodjaqhdn", "djjbalghdpmicbbmdh"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"ibefhaigddbabdc", "bdcibefhaigddba", "ebidebccgfdbfafdchabiddighheahiigbfhd", "eibgdebbfcagdcidcbeibhdgad", "abaaieifgcifbdabebf", "gdahcggfieidaagabafhcgcbdefcbdgbhaecccfdegcdehdf", "biiagceigageh", "fhaigddbabdcibe", "behgghffeddgicc"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"bdppreldlmdgodqhprr", "cfgddngqbcfdllgpgesdamilpp"}));
		Assert.assertEquals(485, fox.howManyPairs(new String[] {"egjebjaaihjgcadibjhdabjjheciacaadca", "jgcadibjhdabjjheciacaadcaegjebjaaih", "cadibjhdabjjheciacaadcaegjebjaaihjg", "hdabjjheciacaadcaegjebjaaihjgcadibj", "ciacaadcaegjebjaaihjgcadibjhdabjjhe", "ibjhdabjjheciacaadcaegjebjaaihjgcad", "jheciacaadcaegjebjaaihjgcadibjhdabj", "dcaegjebjaaihjgcadibjhdabjjheciacaa", "ihjgcadibjhdabjjheciacaadcaegjebjaa", "adibjhdabjjheciacaadcaegjebjaaihjgc", "dibjhdabjjheciacaadcaegjebjaaihjgca", "jaaihjgcadibjhdabjjheciacaadcaegjeb", "caadcaegjebjaaihjgcadibjhdabjjhecia", "iacaadcaegjebjaaihjgcadibjhdabjjhec", "bjhdabjjheciacaadcaegjebjaaihjgcadi", "gcadibjhdabjjheciacaadcaegjebjaaihj", "bccdfideibfjfihfejgffjjbdgdjhaahfbdeid", "jhdabjjheciacaadcaegjebjaaihjgcadib", "hjgcadibjhdabjjheciacaadcaegjebjaai", "dggegfffbhdahabchggfhcchdajeigebfgfh", "aadcaegjebjaaihjgcadibjhdabjjheciac", "aegjebjaaihjgcadibjhdabjjheciacaadc", "heciacaadcaegjebjaaihjgcadibjhdabjj", "adcaegjebjaaihjgcadibjhdabjjheciaca", "hdiiahgbgjcbhecigfaficbhjebfhhdjjee", "caegjebjaaihjgcadibjhdabjjheciacaad", "aaihjgcadibjhdabjjheciacaadcaegjebj", "hgbgjcbhecigfaficbhjebfhhdjjeehdiia", "eigebfgfhdggegfffbhdahabchggfhcchdaj", "ebjaaihjgcadibjhdabjjheciacaadcaegj", "hdjjeehdiiahgbgjcbhecigfaficbhjebfh", "eiighggbgfcehhiccijciafhhbegeaejdfj", "aahfbdeidbccdfideibfjfihfejgffjjbdgdjh", "jjheciacaadcaegjebjaaihjgcadibjhdab", "bjjheciacaadcaegjebjaaihjgcadibjhda", "eciacaadcaegjebjaaihjgcadibjhdabjjh", "bfjfihfejgffjjbdgdjhaahfbdeidbccdfidei", "jbdgdjhaahfbdeidbccdfideibfjfihfejgffj", "acaadcaegjebjaaihjgcadibjhdabjjheci", "geaejdfjeiighggbgfcehhiccijciafhhbe", "egfffbhdahabchggfhcchdajeigebfgfhdgg", "aihjgcadibjhdabjjheciacaadcaegjebja", "hfbdeidbccdfideibfjfihfejgffjjbdgdjhaa", "ggfhcchdajeigebfgfhdggegfffbhdahabch", "abjjheciacaadcaegjebjaaihjgcadibjhd"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"hgehfhd", "hdhgehf", "ehfhdhg"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"aefmccddqldwfpvlcsu", "qldwfpvlcsuaefmccdd", "gvmbolrsvvtaohicnok", "wfpvlcsuaefmccddqld", "pwngvfdmsbcmjwtkklo", "bfcsieummlpllnweojd"}));
		Assert.assertEquals(32, fox.howManyPairs(new String[] {"fdjcaiiiajaciijbbdgfcgheefehjchga", "jdhjchachjeiaahifciajgeibfihdbjdjgidcdie", "eibfihdbjdjgidcdiejdhjchachjeiaahifciajg", "aai", "jcaiiiajaciijbbdgfcgheefehjchgafd", "djcaiiiajaciijbbdgfcgheefehjchgaf", "dgfcgheefehjchgafdjcaiiiajaciijbb", "baeabeechdgfcefbiebcbaaije", "bhcjaabgehdaggjcbjeegfbfjdbbgbcabaidggjdi", "gfcgheefehjchgafdjcaiiiajaciijbbd", "caiiiajaciijbbdgfcgheefehjchgafdj", "iajgeibfihdbjdjgidcdiejdhjchachjeiaahifc", "ejjdifdeigdiaahi", "hcjhbieaedejcciadjehbcjcddhjeaefeafi", "cbaaijebaeabeechdgfcefbieb", "dbjhgaejabafhiieaicjgedc", "hdaggjcbjeegfbfjdbbgbcabaidggjdibhcjaabge", "gaejabafhiieaicjgedcdbjh", "ieffeeageaacjiaibgdhbdbcf", "jjecdcjehg", "aahifciajgeibfihdbjdjgidcdiejdhjchachjei", "ejdhjchachjeiaahifciajgeibfihdbjdjgidcdi", "cjiaibgdhbdbcfieffeeageaa", "idgddgijjbabdabcgdeebefgdga", "hjeaefeafihcjhbieaedejcciadjehbcjcdd", "jcciadjehbcjcddhjeaefeafihcjhbieaede"}));
		Assert.assertEquals(56, fox.howManyPairs(new String[] {"qvmvfmorovlblsjrtwdtctwqcaapjwjcglcsbs", "mvfmorovlblsjrtwdtctwqcaapjwjcglcsbsqv", "morovlblsjrtwdtctwqcaapjwjcglcsbsqvmvf", "fwmdmprvrpdikiglixgbjfucjvdguq", "caapjwjcglcsbsqvmvfmorovlblsjrtwdtctwq", "nrxikrmhtwhleehnihpnsijritjtrkqgjjeloojdiu", "ojdiunrxikrmhtwhleehnihpnsijritjtrkqgjjelo", "uclavlnlpembifonftnrqbjrflqmqxt", "gbjfucjvdguqfwmdmprvrpdikiglix", "vsqvviewrowcpnrsjokfssouxxeuldsmpfjo", "jcteevouiooqknxddxlfmisf", "vrpdikiglixgbjfucjvdguqfwmdmpr", "ihpnsijritjtrkqgjjeloojdiunrxikrmhtwhleehn", "etbxdmkuwqdbugcoftkfssiomkbvjooaiksegpinthjk", "dmprvrpdikiglixgbjfucjvdguqfwm", "kmsbpohmefidikpptelthlvakommufwvaqofomcfaxr", "kqgjjeloojdiunrxikrmhtwhleehnihpnsijritjtr", "pdikiglixgbjfucjvdguqfwmdmprvr", "bktgeopexwfdketpsjohdqggedsa", "uvktajawnwfahkmmnbawmnjxbdkaui", "pohmxikbsqotofdltuvvebwdoao", "jwjcglcsbsqvmvfmorovlblsjrtwdtctwqcaap", "dkauiuvktajawnwfahkmmnbawmnjxb", "jaffgmewoxtwrscwrvujwidfsf", "qgjjeloojdiunrxikrmhtwhleehnihpnsijritjtrk", "obduwghtobkkgujrgstl", "jcglcsbsqvmvfmorovlblsjrtwdtctwqcaapjw", "uhlcbpwftelhniagxcwalowesrwksmwah", "fmisfjcteevouiooqknxddxl", "mmnbawmnjxbdkauiuvktajawnwfahk", "leehnihpnsijritjtrkqgjjeloojdiunrxikrmhtwh", "awmnjxbdkauiuvktajawnwfahkmmnb", "hpnsijritjtrkqgjjeloojdiunrxikrmhtwhleehni", "dlfoobcsbvntdalmfnxbjuqxbpegejohueflsudtrvioex", "wfvmxhcqbbqqhdmqcjoegerannsluuunsevjeunlo", "pcggtmjgcegflgmkcdeqbtnrlkwdiumdjfwomidjaqutviwwx", "oodpbawihhniepkrxpqtieiojcsrxopupfgrpldalvdequmh", "gldgqutamsxogobhofelvxrtdntavucgnleotw", "pxmuuaxippjcewfkmexdouql", "ogobhofelvxrtdntavucgnleotwgldgqutamsx", "pooohpiwjvbpltnqklcchmlrie", "hhkbpgufnipxeaoaunjnnpmansvbqaobsvsju", "nghwqmxvrbudslgcboudfv", "felvxrtdntavucgnleotwgldgqutamsxogobho"}));
		Assert.assertEquals(22, fox.howManyPairs(new String[] {"bbcebcba", "cbabbceb", "cddabcdacebbcbbd", "caeaadbe", "ceaebebcaaeee", "eaadbeca", "aeaadbec", "cedabbedabb", "caddddecceecdcbc", "eccbcadac", "bbbcbedbcabdeeabb", "decbcadecae", "decaedecbca", "acbcddebecbe", "cddebecbeacb", "caedbaace", "ebdddaeaecd", "daeecbbd", "dbdaeadcee", "cbbbdaecace", "ceaeaca", "baddacbdcaeaaeac", "ccaddeeaecaebb", "adbecaea", "aececaba", "abaceeccdbbda", "abbcebcb", "bdceddecbadbebc", "cebedaaeecdd", "baaececa", "ccadbcecbeeace", "beadacadeeceaade", "bcecebdbaca", "dbaabedddb", "dbecaeaa", "ebcbabbc", "edecbcadeca", "bdecbabadeaeaaca", "ccbbceccbae", "baceeccdbbdaa", "adcabeccaecde", "bacdacbdeddaadda", "edeeacd", "abeaadaabacccebbe", "eedbabbebdaae"}));
		Assert.assertEquals(104, fox.howManyPairs(new String[] {"abbcbaabccaaacccababb", "abbaaaaaacaaabaaaabbb", "cbaabccaaacccababbabb", "aacccababbabbcbaabcca", "bccaaacccababbabbcbaa", "cababbabbcbaabccaaacc", "baaaaaacaaabaaaabbbab", "caaacccababbabbcbaabc", "abbabbcbaabccaaacccab", "bbcacbaabbbcccccccbcaabbb", "bcccaabbccbcacbbbbabcbacc", "aabccaaacccababbabbcb", "acccababbabbcbaabccaa", "acaaabaaaabbbabbaaaaa", "babccabcbabbbbbbabccabac", "aaaabbbabbaaaaaacaaab", "aaacaaabaaaabbbabbaaa", "babbcbaabccaaacccabab", "bbcbaabccaaacccababba", "abccaaacccababbabbcba", "bbabbcbaabccaaacccaba", "acaccaccbaacccccaabcaaa", "aacaccaccbaacccccaabcaa", "bcbbbcaaabbccaaabbcccab", "aabcaaaacaccaccbaaccccc", "babbabbcbaabccaaaccca", "accacaaacaaaabcab", "ccbabaaccaacacbccab", "bbccbacaacbbbccacbbbc", "cacabaabcccccaabacbaccbb"}));
		Assert.assertEquals(72, fox.howManyPairs(new String[] {"dgjhuuvc", "jkasokqapdnrshdoftorj", "uuvcdgjh", "tknqipmjctasmhbctcbgfrs", "eghcogslrlbglecslrnrluh", "ftorjjkasokqapdnrshdo", "qipmjctasmhbctcbgfrstkn", "asokqapdnrshdoftorjjk", "jjkasokqapdnrshdoftor", "fifhnmfelbcrugneqou", "ipmjctasmhbctcbgfrstknq", "jctasmhbctcbgfrstknqipm", "hcogslrlbglecslrnrluheg", "knqipmjctasmhbctcbgfrst", "lmmtqsvmqjet", "rjjkasokqapdnrshdofto", "nmminjpvsknfkgcccjsafp", "escjkcgjk", "uvcdgjhu", "pmjctasmhbctcbgfrstknqi", "cjkcgjkes", "jsafpnmminjpvsknfkgccc", "mligsunmkrprhsmqee", "minjpvsknfkgcccjsafpnm", "cdgjhuuv", "kescjkcgj", "hmqjdfpvrrfopmb", "tcbgfrstknqipmjctasmhbc", "asmhbctcbgfrstknqipmjct", "shfaakdmqadmitfeh", "dnrshdoftorjjkasokqap", "doftorjjkasokqapdnrsh", "cccjsafpnmminjpvsknfkg", "vsknfkgcccjsafpnmminjp", "scjkcgjke"}));
		Assert.assertEquals(34, fox.howManyPairs(new String[] {"achejhoglklcmhkfeknafifdko", "lbbfjlookionjfcgblcgomklchnfnmol", "bdleokmfkdnonckblgabgjjclinl", "gnamjbdimbihajilohgnellffhe", "kfeknafifdkoachejhoglklcmh", "ejhoglklcmhkfeknafifdkoach", "ionjfcgblcgomklchnfnmollbbfjlook", "knafifdkoachejhoglklcmhkfe", "dkoachejhoglklcmhkfeknafif", "jhoglklcmhkfeknafifdkoache", "eklffbjejifnfnejbnamfaenjffbdlfi", "imhmhochgbbajlldgjamkoodaeef", "ckioaohnnhdokdmahoo", "ojfffkihonoddonkkdoidmngaioaali", "nboedjnbomeck", "dmngaioaaliojfffkihonoddonkkdoi", "okinlgalijakdejblkemlglbneoomdobfknfoke", "miokmfgkbadcklfhelbgo", "oachejhoglklcmhkfeknafifdk", "mlilanmgnbmfebelfmaajlki", "nafifdkoachejhoglklcmhkfek", "jnbomecknboed", "eelabgaolibbcmdjjnonj", "jjofomnhcacegldieabjjolcbhleceiog", "fffkihonoddonkkdoidmngaioaalioj", "fgkbadcklfhelbgomiokm"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"ccjlgz", "fpkwtyzlcccrq", "oezqnzqhez", "wqcvetlqawcv", "pepyslleg", "zuslh", "mmpsblmmiorgg", "pziymnheh", "lmkjb", "mmiorggmmpsbl", "boqjklt", "ggmmpsblmmior", "vxyijxqifloc", "nebczwb", "mimqgdlkedhwv", "uygkxtlvpp", "gaswti", "rnepvfzfaqvyr", "cckjl", "uevwnbpl", "nqqstm", "jbvqnu", "hscjemrb", "qiifayjn", "snddkx", "msshgkuz", "yjoghlgf", "nnxmly"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"diiiddccdghdbggegejffciccb", "cjeddagjhahgcihfhahgfeigd", "gagihghbjhcgggdaabgacgeggb", "iccbdiiiddccdghdbggegejffc", "ejffciccbdiiiddccdghdbggeg"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"fgghbhkdcfhdabhfeaeeadhj", "bggeflkbblkgdbcgdgekdfjhdeklagfbdhhlckdgg", "igkecchekekillkjcfgildiglcjbk", "fichjhfjliabhfdgedjhliijbeegjajf", "ghkdcikhkdjegkjikkfdakbejec", "gjidhddagaealeialjhgaiadgahliifbhkbg"}));
		Assert.assertEquals(6, fox.howManyPairs(new String[] {"adccbbcedbecbaa", "edbecbaaadccbbc", "dbecbaaadccbbce", "aaadccbbcedbecb", "accaddaacedbdebbbbaccdabaaedbeebadadbadded", "beddbbacadebcebdeecbcaecdbcdebebdbaacdbedc", "baececdabacbdbacbcbadbcaecbbdabcdbbccde"}));
		Assert.assertEquals(109, fox.howManyPairs(new String[] {"khhchfbmmckeadcmgkdbh", "mckeadcmgkdbhkhhchfbm", "cmgkdbhkhhchfbmmckead", "bhealigcgeffickigbhi", "keadcmgkdbhkhhchfbmmc", "ckeadcmgkdbhkhhchfbmm", "dlhhmgjljgdfhelegjmimjlhjhm", "hchfbmmckeadcmgkdbhkh", "hkhhchfbmmckeadcmgkdb", "dcmgkdbhkhhchfbmmckea", "fkdkcddcc", "fbmmckeadcmgkdbhkhhch", "jbdhfialaiihglkighdegfgeee", "gdaadlagakbjeegdhbdcihemgiedbj", "bfmibjibkcadllif", "dbhkhhchfbmmckeadcmgk", "mdeijkdjmlejckehccch", "jgdfhelegjmimjlhjhmdlhhmgjl", "hfbmmckeadcmgkdbhkhhc", "kcddccfkd", "mgkdbhkhhchfbmmckeadc", "cfkdkcddc", "hhchfbmmckeadcmgkdbhk", "ccfkdkcdd", "dccfkdkcd", "gikdejhdaajmdmieiickgbic", "hmdlhhmgjljgdfhelegjmimjlhj", "ddccfkdkc", "glbkeicdedbkgja", "eadcmgkdbhkhhchfbmmck"}));
		Assert.assertEquals(363, fox.howManyPairs(new String[] {"neakembomknhlhnckmnjkocgjijln", "mknhlhnckmnjkocgjijlnneakembo", "jlnneakembomknhlhnckmnjkocgji", "omknhlhnckmnjkocgjijlnneakemb", "njkocgjijlnneakembomknhlhnckm", "knhlhnckmnjkocgjijlnneakembom", "kocgjijlnneakembomknhlhnckmnj", "jkocgjijlnneakembomknhlhnckmn", "mbomknhlhnckmnjkocgjijlnneake", "nckmnjkocgjijlnneakembomknhlh", "lhnckmnjkocgjijlnneakembomknh", "nhlhnckmnjkocgjijlnneakembomk", "kembomknhlhnckmnjkocgjijlnnea", "bomknhlhnckmnjkocgjijlnneakem", "lnneakembomknhlhnckmnjkocgjij", "kmnjkocgjijlnneakembomknhlhnc", "cgjijlnneakembomknhlhnckmnjko", "hlhnckmnjkocgjijlnneakembomkn", "embomknhlhnckmnjkocgjijlnneak", "mghbjcofkenccmkkfejhkcdailkhmgbbn", "mnjkocgjijlnneakembomknhlhnck", "ocgjijlnneakembomknhlhnckmnjk", "ijlnneakembomknhlhnckmnjkocgj", "eakembomknhlhnckmnjkocgjijlnn", "kfejhkcdailkhmgbbnmghbjcofkenccmk", "ckmnjkocgjijlnneakembomknhlhn", "hbjcofkenccmkkfejhkcdailkhmgbbnmg", "akembomknhlhnckmnjkocgjijlnne", "cmkkfejhkcdailkhmgbbnmghbjcofkenc", "nolfgomfhncmhchkhaldddiinh", "lbjijanekekfbkllkbncodiodh", "bnmghbjcofkenccmkkfejhkcdailkhmgb", "gjijlnneakembomknhlhnckmnjkoc", "ibgkfddkelbohkfhfjkakkgdfc", "khaldddiinhnolfgomfhncmhch", "anekekfbkllkbncodiodhlbjij", "hnckmnjkocgjijlnneakembomknhl"}));
		Assert.assertEquals(39, fox.howManyPairs(new String[] {"bfedddggkai", "fedddggkaib", "ggkaibfeddd", "gkaibfedddg", "aibfedddggk", "cekdlebafai", "ajjkmkdeekf", "dggkaibfedd", "ddggkaibfed", "edddggkaibf", "kfajjkmkdee", "kaibfedddgg", "jaicgjfklik", "jkmkdeekfaj", "fchfgmiibba"}));
		Assert.assertEquals(100, fox.howManyPairs(new String[] {"mgggijnahjlighbnjianfidoemlinnnd", "mlinnndmgggijnahjlighbnjianfidoe", "anfidoemlinnndmgggijnahjlighbnji", "njianfidoemlinnndmgggijnahjlighb", "ghieholkleojgohnejajabkgaffgaogbikgdkejdjmm", "cfiimaiabfbmdgmmmmbiehm", "mghieholkleojgohnejajabkgaffgaogbikgdkejdjm", "ighbnjianfidoemlinnndmgggijnahjl", "maiabfbmdgmmmmbiehmcfii", "ibaggifeacolccnnned", "oemlinnndmgggijnahjlighbnjianfid", "iccdkb", "emlinnndmgggijnahjlighbnjianfido", "kinnhgefaikheekbjgafaicn", "iimaiabfbmdgmmmmbiehmcf", "gohnejajabkgaffgaogbikgdkejdjmmghieholkleoj", "nahjlighbnjianfidoemlinnndmgggij", "efaikheekbjgafaicnkinnhg", "bkddkodhoinagdnjddicfienoi", "hbijecfjclmmlnmbomam", "ekkiilamkhnoffojhmkcnollefdlfbgdimcmiloodj", "jlighbnjianfidoemlinnndmgggijnah", "foemcobnnfbiiemoalf", "dmgggijnahjlighbnjianfidoemlinnn", "gijnahjlighbnjianfidoemlinnndmgg", "fmcfdnjekeigjehgkljdil", "ikgdkejdjmmghieholkleojgohnejajabkgaffgaogb", "dimcmiloodjekkiilamkhnoffojhmkcnollefdlfbg", "eholkleojgohnejajabkgaffgaogbikgdkejdjmmghi", "mcmiloodjekkiilamkhnoffojhmkcnollefdlfbgdi", "efdlfbgdimcmiloodjekkiilamkhnoffojhmkcnoll", "cnkinnhgefaikheekbjgafai", "linnndmgggijnahjlighbnjianfidoem", "idoemlinnndmgggijnahjlighbnjianf"}));
		Assert.assertEquals(21, fox.howManyPairs(new String[] {"giivcknrmjpsntdpctlttoks", "jnmroursmldldm", "smldldmjnmrour", "dldmjnmroursml", "tlrmevotkjfi", "rhhojfgnht", "nmroursmldldmj", "rmjpsntdpctlttoksgiivckn", "snrfcefqdqenjduudgpctsefk", "dmjnmroursmldl", "nferqemqmmocomctkovfoc", "oursmldldmjnmr", "otkjfitlrmev", "kmtsoeopasfocohmtjiuvb", "upvfprspdqdusvjdeum", "fertelbiduvs", "jlgscjocsgljnusvilcnvq", "opsljmuolrlkjhnsbprfbi", "rthbjemjtuotbthlbi", "lrmevotkjfit", "olhegegmnelhcmn", "lbiduvsferte", "erqemqmmocomctkovfocnf", "sjmskpjuihvuoj", "illvkmevfu", "avmkciaaalkcblrlphedmkvu", "qiqiqdgekjkgqhjiisedhfmje", "dekshpiithqaulogkglmrpopm", "mlkqdfatlinvovdlfta"}));
		Assert.assertEquals(830, fox.howManyPairs(new String[] {"gkamklgbgejnlbhmmkkpakdhodeololkkfipikoiajen", "amklgbgejnlbhmmkkpakdhodeololkkfipikoiajengk", "pikoiajengkamklgbgejnlbhmmkkpakdhodeololkkfi", "ajengkamklgbgejnlbhmmkkpakdhodeololkkfipikoi", "oiajengkamklgbgejnlbhmmkkpakdhodeololkkfipik", "lgbgejnlbhmmkkpakdhodeololkkfipikoiajengkamk", "koiajengkamklgbgejnlbhmmkkpakdhodeololkkfipi", "iajengkamklgbgejnlbhmmkkpakdhodeololkkfipiko", "ikoiajengkamklgbgejnlbhmmkkpakdhodeololkkfip", "ipikoiajengkamklgbgejnlbhmmkkpakdhodeololkkf", "odeololkkfipikoiajengkamklgbgejnlbhmmkkpakdh", "engkamklgbgejnlbhmmkkpakdhodeololkkfipikoiaj", "kdhodeololkkfipikoiajengkamklgbgejnlbhmmkkpa", "gbgejnlbhmmkkpakdhodeololkkfipikoiajengkamkl", "bgejnlbhmmkkpakdhodeololkkfipikoiajengkamklg", "nlbhmmkkpakdhodeololkkfipikoiajengkamklgbgej", "hodeololkkfipikoiajengkamklgbgejnlbhmmkkpakd", "mkkpakdhodeololkkfipikoiajengkamklgbgejnlbhm", "mklgbgejnlbhmmkkpakdhodeololkkfipikoiajengka", "kamklgbgejnlbhmmkkpakdhodeololkkfipikoiajeng", "bhmmkkpakdhodeololkkfipikoiajengkamklgbgejnl", "ololkkfipikoiajengkamklgbgejnlbhmmkkpakdhode", "klgbgejnlbhmmkkpakdhodeololkkfipikoiajengkam", "ngkamklgbgejnlbhmmkkpakdhodeololkkfipikoiaje", "lkkfipikoiajengkamklgbgejnlbhmmkkpakdhodeolo", "dhodeololkkfipikoiajengkamklgbgejnlbhmmkkpak", "hmmkkpakdhodeololkkfipikoiajengkamklgbgejnlb", "ejnlbhmmkkpakdhodeololkkfipikoiajengkamklgbg", "deololkkfipikoiajengkamklgbgejnlbhmmkkpakdho", "ojeejmifddikpnlcfgkfjekfafghhbklfhpnpccg", "kkfipikoiajengkamklgbgejnlbhmmkkpakdhodeolol", "mgigmhafmlkbplnhgidbbgkcpmjmeijeeoeakonpa", "jnlbhmmkkpakdhodeololkkfipikoiajengkamklgbge", "lolkkfipikoiajengkamklgbgejnlbhmmkkpakdhodeo", "jengkamklgbgejnlbhmmkkpakdhodeololkkfipikoia", "kkpakdhodeololkkfipikoiajengkamklgbgejnlbhmm", "akdhodeololkkfipikoiajengkamklgbgejnlbhmmkkp", "eololkkfipikoiajengkamklgbgejnlbhmmkkpakdhod", "lkbplnhgidbbgkcpmjmeijeeoeakonpamgigmhafm", "kpakdhodeololkkfipikoiajengkamklgbgejnlbhmmk", "pakdhodeololkkfipikoiajengkamklgbgejnlbhmmkk", "eeoeakonpamgigmhafmlkbplnhgidbbgkcpmjmeij", "mhafmlkbplnhgidbbgkcpmjmeijeeoeakonpamgig", "lbhmmkkpakdhodeololkkfipikoiajengkamklgbgejn", "gejnlbhmmkkpakdhodeololkkfipikoiajengkamklgb", "olkkfipikoiajengkamklgbgejnlbhmmkkpakdhodeol", "akonpamgigmhafmlkbplnhgidbbgkcpmjmeijeeoe"}));
		Assert.assertEquals(19, fox.howManyPairs(new String[] {"bbbaabb", "aaaabaa", "ab", "baaaab", "abab", "bbbbaab", "aabaabb", "bbbbbbb", "ababbbab", "aaab", "abbaa", "abbbbba", "bbbbbb", "bbaaabb", "bbbbbaa", "abbbab", "abaabb", "bbbbaaa", "abaaaa", "abaaaaab", "aabbb", "aaaaaabb", "aaa", "aa", "bbbbabbbb", "bbababbba", "abb", "aaaaaba", "bbabaa", "ababaa", "bb", "bbaaabbb", "aaaa", "abaaab", "ba", "bbaab", "bbba", "aabbabbb", "baabb", "bba", "bbbbabba", "abaa", "baabaab", "bbbbbabb", "babb", "bbaa", "bababaa", "babbbba", "baabbb", "aaaaab"}));
		Assert.assertEquals(4, fox.howManyPairs(new String[] {"dqfsenbtxxzxl", "rlwnbljxybctijgfejg", "wnbljxybctijgfejgrl", "btxxzxldqfsen", "ctijgfejgrlwnbljxyb", "wynyxtghwmwx"}));
		Assert.assertEquals(6, fox.howManyPairs(new String[] {"lfuzbcw", "uzbcwlf", "wlfuzbc", "bcwlfuz", "s", "jgjrlcoyhajllzaonnj", "ghn", "dbffkynqvxccvhbr", "jpyqeyjkjzjplmtmfkd"}));
		Assert.assertEquals(91, fox.howManyPairs(new String[] {"ffhfdbdddaadafcahh", "hffhfdbdddaadafcah", "adafcahhffhfdbddda", "bdddaadafcahhffhfd", "dbdddaadafcahhffhf", "aadafcahhffhfdbddd", "hhffhfdbdddaadafca", "ddaadafcahhffhfdbd", "afcahhffhfdbdddaad", "dddaadafcahhffhfdb", "fcahhffhfdbdddaada", "ahhffhfdbdddaadafc", "hfdbdddaadafcahhff", "cahhffhfdbdddaadaf"}));
		Assert.assertEquals(6, fox.howManyPairs(new String[] {"bdacaacaccaceedbaaebbaccbeddddcc", "ecbeaabacceedcbbdbeacbceaaaeded", "ddaeeacebcbabbeaeddaeabcabbde", "edceacdadaeebebccddcbeadbdabcbebcacaeddeedbeb", "dcadebebaacbcdddacbceccadcaacaebbcddd", "eccadcaacaebbcddddcadebebaacbcdddacbc", "caabcbabbebdeadcedaabebabdedacbecdebddbceebae", "ecabccaadacbaecbaeddcdadbbcedcedd", "eeacbcdeabedeaabadeeccbbaedddcccbb", "caebdeebceebeebebadebabbceecadabaeeeabececeeae", "dacbeaaaeeddddcecabcbecccdd", "dacddaadaacdebebcadedbecbcedccaebdeee", "dddcddebeecbcedccbdaddbccdddcdd", "cbbdbeacbceaaaededecbeaabacceed", "eeadebedceadbeedbceaecbedacbaeccbce", "ecdbeaebaaaebbdceaddacdeedadbdcbcbcdc", "cbcaaccaccbadcacbbaaceddbdaaebeeebddcbdeeeeda", "cdececddcbbeedcdbcabbbaadbcbbdcebacecbbdb", "cccabdbcdcdacddddcdecbdebbdaeddcadddb", "dcdccdcecebcededdbddaddcaeddbccacbccbbaaaccb", "ecbcbcaccadeaeaaaaedabbabadecaabaecbbec", "dcecabdabcdecaeabdbaccecbbadcecbecdcadbacaebd", "cbabcedcedaccacacceacbdaceacddedadaeb", "eceddcdedbbeccabaeececcaeaaeccdecdce", "bbcddacadbaecbccbcdbdbaaeacdcbebdebdececcabda", "eddcadddbcccabdbcdcdacddddcdecbdebbda", "eadebbacdccedcdcddcadbaeecabcdbbbddbac", "abeceeddaaabbcdcacbdddcbadbdc", "ebeadabecaaecabdeaebbcaedacbcdbaacddcaacbec", "ecddaeabdbdcebdbbdaedaecbebeeabc", "aeeaababedacaadbcddbebbcbbdbdecaeecabcebdccc", "aeabaaddaccdbaaeccebdbeebdbbaaa", "caeebaeaaabedbbcbcdbbceccdaccdcccedb", "eeacbcbccbddbeedaaedeadaaabdbcbccbd", "dceddeccddaebabcadaedceccebdcaceeea", "edaedecbbacabbddceddacaaddbedeeadceceaabadc", "bdcdddbedebebbceddccecddbbdecedda", "dedcbcadaaeabeaeccedebbcecaacb", "adbedebbebbbacabcdbdadbddecbadbcacbd", "cabaeececcaeaaeccdecdceeceddcdedbbec", "edecbdbabadeeabdbabcbecaeecdcadc", "ecaacbeabbcdbcbbbeaccddebbeddcbce", "caacaebbcddddcadebebaacbcdddacbceccad"}));
		Assert.assertEquals(181, fox.howManyPairs(new String[] {"adceefhfcgaaaedhaabbhdiehee", "dceefhfcgaaaedhaabbhdieheea", "haabbhdieheeadceefhfcgaaaed", "ihehdefhaeifichhefiid", "bbhdieheeadceefhfcgaaaedhaa", "cgaaaedhaabbhdieheeadceefhf", "aaedhaabbhdieheeadceefhfcga", "dieheeadceefhfcgaaaedhaabbh", "hfcgaaaedhaabbhdieheeadceef", "aaaedhaabbhdieheeadceefhfcg", "bhdieheeadceefhfcgaaaedhaab", "fhfcgaaaedhaabbhdieheeadcee", "defhaeifichhefiidiheh", "hdefhaeifichhefiidihe", "dhaabbhdieheeadceefhfcgaaae", "ieheeadceefhfcgaaaedhaabbhd", "eadceefhfcgaaaedhaabbhdiehe", "aedhaabbhdieheeadceefhfcgaa", "eheeadceefhfcgaaaedhaabbhdi", "bdfdghbhebidfhahaifchedigf", "abbhdieheeadceefhfcgaaaedha", "efhaeifichhefiidihehd", "aabbhdieheeadceefhfcgaaaedh", "hehdefhaeifichhefiidi", "heeadceefhfcgaaaedhaabbhdie"}));
		Assert.assertEquals(48, fox.howManyPairs(new String[] {"ceccbcbcddacbaebae", "addacacdbaeeeedceaeae", "ebbcceddcceadbbaea", "dbbaeaebbcceddccea", "dacacdbaeeeedceaeaead", "cbabebdaededbaaaaccce", "dbcdccabeecdbacbd", "abaeeeebabdaabceee", "bddbcdccabeecdbac", "acbaebaececcbcbcdd", "aeaddacacdbaeeeedceae", "decbbcbaedebabbeebac", "cbeedcabacbdadcdc", "bedaacebbceccedacdaedcbcdcd", "cabacbdadcdccbeed", "badcebabeaeabccbdadcacbcdadcba", "ddbeabbbdbceddaacceabbda", "cebabeaeabccbdadcacbcdadcbabad", "acabaaebbcbbccedbbdbada", "cbedbbeaccdaebaaaaeecddccbbbc", "eeeedceaeaeaddacacdba", "cacecbdaebceeabbebceb", "cacdbaeeeedceaeaeadda", "eedceaeaeaddacacdbaee", "acacaeacbaddbdabbbcdcecd", "ccecbdddaadebcebdcbaea", "aedccbbecdaecdbdadeeedcbeecead", "bedbeadabaedecaeeadbceae", "cbdadcacbcdadcbabadcebabeaeabc", "cdbaeeeedceaeaeaddaca", "deeedcbeeceadaedccbbecdaecdbda", "bbeebacdecbbcbaedeba", "adedcdcdeadbbccabdaae", "ebabdaabceeeabaeee", "ddacbaebaececcbcbc", "cbbdddccbbddaedbbace", "baedebabbeebacdecbbc", "bcddacbaebaececcbc", "edceaeaeaddacacdbaeee", "cdddabddcecdddcaa", "adcacbcdadcbabadcebabeaeabccbd", "cdcbbeebcdaabdecedcdc", "ebbccccbecccddaedaecd", "cebaabaecbeaeecbb"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"maka", "lncekdcjacabjkapfmioacoeljjln", "hclklgokpgef", "mpiddh", "jggcabcnjcahiibakmce", "ogangpa", "fdbcmhdeckmcdbikmfijcagcene", "ebbmlkicmapcb", "ogigelckdhfacjmjlpkockopahchp", "pcbebbmlkicma", "n", "ooahohpddcknkgopfopdpibejleghf", "kmlhhllfpmapiiancgbfbeajiepa", "g", "agdjgcmlnlg"}));
		Assert.assertEquals(11, fox.howManyPairs(new String[] {"aaaccbccababaaaacacaaaccabaacacaaaa", "baccaacccbcccaabbcacbacbcbabaabb", "acccbbaaacbcaccabacccbbbbaabbbacccccbabcbb", "aaacacaaaccabaacacaaaaaaaccbccababa", "caccbaaccaaaaabbaabbaaabbaaaaacabcabccabcb", "bcbabcaacabbaabbbababcccca", "ccbbcbbbbabccbcaa", "ababaaaacacaaaccabaacacaaaaaaaccbcc", "ccbaaccbcbabbcbbbcacbbcacacbcbcb", "babbaaaccccabcacbcabacb", "acbbbababbbacabaccacaaabaabcbcbc", "bbbacbbcaabbbaccbabcabacbaa", "bacbacabcbacabacabbaaaaacbabbaa", "bbcbaccbcacccbabacabbbcbaaabcbcabcababccaabaa", "abbaabbaaabbaaaaacabcabccabcbcaccbaaccaaaa", "cccbaacbabbbccbcbccbbabc", "abcbbbabcccacbcaaacbaabbbcabaaacbabb", "aaaaccbccababaaaacacaaaccabaacacaaa", "baaabbaaaaacabcabccabcbcaccbaaccaaaaabbaab", "bcacbbcacacbcbcbccbaaccbcbabbcbb", "bbabaaabaaaccaaccaacccb", "cbbcbacbcbaaabbabcbbaabcccbbbcaacccabccbabb", "aabbacbabbbccbcb", "bccacbbacbbbacacbabca", "bbbacacbabcabccacbbac", "bbacaabaccaccabacaabaabcacacba", "aaccacbababcbacbbcabacabbcaabbcaabba", "baabbcaaaacbbabaaccbabbcccbcaaacccabacaaa", "aaccbbbaaaccbacaaacccacacbcacbacbbacabccb", "caabbabccbccacbacbaaccaacbc"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"gkznzfmxdxtanzzujjhvwpsdyxwnowdrn", "dxtanzzujjhvwpsdyxwnowdrngkznzfmx"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"hfabddhfggiafehjh", "cdjdhdhhdcaaieaj", "feebibgidjehjabi", "iacggigacjhfdjjdj", "eahdifjbbgahhjgij", "fgcijijhbahaagid", "ijajdajfdgfhabeci", "fcibchibebigfcfdf", "gbgfbibdeiggfafh", "edaeicaeaahdibhbd", "eeafffgfgcedgagh", "ggaaacjahedhbeifb", "hcidbaifigbbgbfa", "dbfeecdejjgbjcda", "hdhddgffcbgbbhfb", "ghiiigcgheefdhhgf", "fifdihjfhcjihehcc"}));
		Assert.assertEquals(150, fox.howManyPairs(new String[] {"dacurgonhfpgmdoegdjubqtbfoi", "gonhfpgmdoegdjubqtbfoidacur", "ubqtbfoidacurgonhfpgmdoegdj", "gdjubqtbfoidacurgonhfpgmdoe", "egdjubqtbfoidacurgonhfpgmdo", "djubqtbfoidacurgonhfpgmdoeg", "mtbjtbkfjedhaargabcitogslqp", "nhfpgmdoegdjubqtbfoidacurgo", "oidacurgonhfpgmdoegdjubqtbf", "bcitogslqpmtbjtbkfjedhaarga", "curgonhfpgmdoegdjubqtbfoida", "tbkfjedhaargabcitogslqpmtbj", "bkfjedhaargabcitogslqpmtbjt", "jtbkfjedhaargabcitogslqpmtb", "onhfpgmdoegdjubqtbfoidacurg", "bqtbfoidacurgonhfpgmdoegdju", "citogslqpmtbjtbkfjedhaargab", "togslqpmtbjtbkfjedhaargabci", "gslqpmtbjtbkfjedhaargabcito", "dhaargabcitogslqpmtbjtbkfje", "urnfgjbcuiiellopdihmdrliefc", "argabcitogslqpmtbjtbkfjedha", "ngskbhrsoocbcehtlpiscsrbkgj", "oegdjubqtbfoidacurgonhfpgmd", "bfoidacurgonhfpgmdoegdjubqt", "idacurgonhfpgmdoegdjubqtbfo", "urgonhfpgmdoegdjubqtbfoidac"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"ggdgedbhcbgldbbmio", "ibbklngcgijfoijkeljclcodbnc", "nlbinaldechomjkeafhl", "ocfcbomekmhaaafedfikgjcnenb", "ecamhecbikmflmcddmlocmjhobnjalcncnjkjeagm", "fhaedddjgdfoicaeohgb", "dnemglnagjbeimflke", "ajoahacgioiidjjafhokekki", "bofabeblgelccedoeioi", "odbncibbklngcgijfoijkeljclc", "klocokmiolkbnoegjiiaamjahla", "mmdgbkaggekcohnbelhikhfegofmocmdnlej", "khencojkjhnloibkmcgcbimfmfejfebdiancaehb", "hkbfhaimoneinjab", "mflflhglfnldlegmcagkkdhlagdhgbia", "gkhmenngclinofiadkfnoon", "mefcgcakojblelccgkk", "lbcgkldnejeniedibohgbdejklcjigilgjhfiehabkbja", "ajbiefcomhmjfjammeamccdjmhlalnnbflaebfbigncf", "chemnoajfcenlfklhaamnjckglfbihbo", "eocikgblmolgo", "fbobgadlcbcifflljnedllknbmkbockeloanhnakbacnckmd", "kcoahmikcgoad", "kcgoadkcoahmi", "afgbdfkmmmheacionkkmibojedieckdfnfjkhkoiiobi", "eflbbdjfkbgbajibklabbcefdcbfknjldinockoojknnfbag", "oakimijbileeihkcljgmjc", "ieakcdngimgfaneehbdjdljmhmkhhibnnebf", "ieaighmaigkahkknfiabbcdcihbbgbjeb", "mifbalahnknmidefkengkjfmminhlolenh", "fanoocdamkjenadajbckbmodmkjlfoilagonc", "ocmhilikicfbjclfmbaafekjchbblkaokfadh", "hajnegogkekkaofhkdihljadnmdkjgmgjkjjohbmjoiaoai", "oeiehhhllnjdaebmhkgoojigbogainjlochcfhlkcegfig", "fnnodaihakomeegfddmdoacfg", "iflebfngfcaajmhdoembnhojlcael", "obdkkceclbeegcacejeafadocnhblfigaljmimaefkcbag", "gdmmbikgfafgnongbekbh", "blamigcbmoklehafhjnbamimeoffgkdbmihdlhkdcio", "cdalhnegjccnaocmciobkohcmdeeclf", "milfmbbjhiohdndoabibhlbebfjdb", "bbmioggdgedbhcbgld", "igogldjcicndhkkcdbdaoloojlihociidcdgnjbk", "mhgaalagkifhcgfejeghhfklmoanobi", "bjfeeakoojaoi", "mcengfenaeboaicijehmiljmlndoglai", "nknkccbccnlmmecjihifdkhicmhfh", "klfmgblcncibadhjdlbccbfglebcedofkeefflccbaakinl"}));
		Assert.assertEquals(172, fox.howManyPairs(new String[] {"daeecfacbcfebbaceddcedcfadf", "dcfadfdaeecfacbcfebbaceddce", "bcdcdccaefbcbfdeeccfaddeecbcbcecdfc", "dcdccaefbcbfdeeccfaddeecbcbcecdfcbc", "cedcfadfdaeecfacbcfebbacedd", "caaedcfebfdfaeebaaaddfdabdfe", "acbcfebbaceddcedcfadfdaeecf", "bffccafeeccbddcaacbcfffcadddacedceaedbacb", "ecbcbcecdfcbcdcdccaefbcbfdeeccfadde", "fdeeccfaddeecbcbcecdfcbcdcdccaefbcb", "aefbcbfdeeccfaddeecbcbcecdfcbcdcdcc", "ebdfaefefeafcceaebbdabdceeeefbacb", "efbcbfdeeccfaddeecbcbcecdfcbcdcdcca", "ccfaddeecbcbcecdfcbcdcdccaefbcbfdee", "cbebdfaefefeafcceaebbdabdceeeefba", "acedffbcacbcfdbdbecceecddadfbbdbdeeefeccffd", "fefeafcceaebbdabdceeeefbacbebdfae", "bdfaefefeafcceaebbdabdceeeefbacbe", "faddeecbcbcecdfcbcdcdccaefbcbfdeecc", "aefeebbeadcbdcdbafdfeecaaacedcfbbe", "eccfaddeecbcbcecdfcbcdcdccaefbcbfde", "dcdbafdfeecaaacedcfbbeaefeebbeadcb", "bdbdeeefeccffdacedffbcacbcfdbdbecceecddadfb", "efefeafcceaebbdabdceeeefbacbebdfa", "cdcdccaefbcbfdeeccfaddeecbcbcecdfcb", "ccaefbcbfdeeccfaddeecbcbcecdfcbcdcd", "dccaefbcbfdeeccfaddeecbcbcecdfcbcdc", "aeecfacbcfebbaceddcedcfadfd", "eebcfdbeabbcaefcbbbfbabbceaefcadfdddadd", "eaedbacbbffccafeeccbddcaacbcfffcadddacedc", "cafeeccbddcaacbcfffcadddacedceaedbacbbffc", "dcfebfdfaeebaaaddfdabdfecaae", "eecbcbcecdfcbcdcdccaefbcbfdeeccfadd", "cadddacedceaedbacbbffccafeeccbddcaacbcfff", "abcdfbacfbeccddadafcbaccc", "bcfebbaceddcedcfadfdaeecfac", "caefcbbbfbabbceaefcadfdddaddeebcfdbeabb", "bcecdfcbcdcdccaefbcbfdeeccfaddeecbc", "aefefeafcceaebbdabdceeeefbacbebdf", "cfaddeecbcbcecdfcbcdcdccaefbcbfdeec", "adfdaeecfacbcfebbaceddcedcf", "bebdfaefefeafcceaebbdabdceeeefbac", "deeccfaddeecbcbcecdfcbcdcdccaefbcbf", "dfeacbecfdbbdbadadcadddfe"}));
		Assert.assertEquals(232, fox.howManyPairs(new String[] {"aoihndcheddmhiifbnmnlkngkoakhn", "oakhnaoihndcheddmhiifbnmnlkngk", "akhnaoihndcheddmhiifbnmnlkngko", "ddmhiifbnmnlkngkoakhnaoihndche", "fjgdidmjgohmkanljfjdaedhnjggblfaihnfdeh", "kngkoakhnaoihndcheddmhiifbnmnl", "oihndcheddmhiifbnmnlkngkoakhna", "iifbnmnlkngkoakhnaoihndcheddmh", "ihndcheddmhiifbnmnlkngkoakhnao", "hndcheddmhiifbnmnlkngkoakhnaoi", "dcheddmhiifbnmnlkngkoakhnaoihn", "eddmhiifbnmnlkngkoakhnaoihndch", "bnmnlkngkoakhnaoihndcheddmhiif", "nmnlkngkoakhnaoihndcheddmhiifb", "fbnmnlkngkoakhnaoihndcheddmhii", "afcdgniogbkaimejodcclnmcacfknfkkmj", "aimejodcclnmcacfknfkkmjafcdgniogbk", "lhehndlbcfaafmgbhhiafegffkhdnlagl", "dnlagllhehndlbcfaafmgbhhiafegffkh", "ffkhdnlagllhehndlbcfaafmgbhhiafeg", "ieibbmnflddchlehofjecijncmbcnjjiago", "afegffkhdnlagllhehndlbcfaafmgbhhi", "heddmhiifbnmnlkngkoakhnaoihndc", "gbhhiafegffkhdnlagllhehndlbcfaafm", "hdnlagllhehndlbcfaafmgbhhiafegffk", "hiifbnmnlkngkoakhnaoihndcheddm", "blcbllahbcibcnhjhccfkamggmaogi", "cheddmhiifbnmnlkngkoakhnaoihnd", "mnlkngkoakhnaoihndcheddmhiifbn", "fnjjnmjlccaolgecjdkjnegjdmmj", "ifbnmnlkngkoakhnaoihndcheddmhi", "ognhgkeajkfhobknofabffemeefbcfikihcelgm", "bhhiafegffkhdnlagllhehndlbcfaafmg", "geidfagknmganhlmfdifjncgnhilh", "mhiifbnmnlkngkoakhnaoihndchedd", "ganhlmfdifjncgnhilhgeidfagknm", "kkmjafcdgniogbkaimejodcclnmcacfknf", "afmgbhhiafegffkhdnlagllhehndlbcfa", "lmfdifjncgnhilhgeidfagknmganh", "agllhehndlbcfaafmgbhhiafegffkhdnl"}));
		Assert.assertEquals(6, fox.howManyPairs(new String[] {"aecjdhmi", "jdhmiaec", "medgfflhfhbkjbgf", "hmiaecjd", "ghgadhee", "ajccdh", "iajgegallehah", "gjmkdblccbkjggam", "hlifil", "eiehb", "fljjbcgmgh", "kgmdghbjcffdfeh", "klkcfbffkkajdfdj", "ijfali", "jggamgjmkdblccbk", "jfdhjckjihgf", "lbiijgaeljd", "gbfchligbhhkhhhb", "iijfal", "hmlmk", "jjdcmkjjfigdim", "dalmicecgbi", "gildemibhacjh", "jjacaihlh", "hajccd"}));
		Assert.assertEquals(127, fox.howManyPairs(new String[] {"gcggcibcaiaaecccbhf", "cibcaiaaecccbhfgcgg", "bcaiaaecccbhfgcggci", "hfgcggcibcaiaaecccb", "bhfgcggcibcaiaaeccc", "aecccbhfgcggcibcaia", "ibcaiaaecccbhfgcggc", "eibhfeeghfibeahbcicia", "cbhfgcggcibcaiaaecc", "ecccbhfgcggcibcaiaa", "ccbhfgcggcibcaiaaec", "aiaaecccbhfgcggcibc", "cggcibcaiaaecccbhfg", "caiaaecccbhfgcggcib", "ggcibcaiaaecccbhfgc", "gcibcaiaaecccbhfgcg", "eeghfibeahbciciaeibhf", "fgcggcibcaiaaecccbh", "eghfibeahbciciaeibhfe", "fcaddfadegibcd", "ffbah", "iciaeibhfeeghfibeahbc", "adegibcdfcaddf"}));
		Assert.assertEquals(146, fox.howManyPairs(new String[] {"opobokagkqobgehgq", "hgqopobokagkqobge", "onhqkppjhckqkiqlpnkgfgkidanajgclc", "kqobgehgqopobokag", "clconhqkppjhckqkiqlpnkgfgkidanajg", "gfgkidanajgclconhqkppjhckqkiqlpnk", "qlpnkgfgkidanajgclconhqkppjhckqki", "hqkppjhckqkiqlpnkgfgkidanajgclcon", "lmancqiafaefnknjqne", "bocicfnejbjaqknf", "fgkidanajgclconhqkppjhckqkiqlpnkg", "bjaqknfbocicfnej", "lconhqkppjhckqkiqlpnkgfgkidanajgc", "cfqplfdpaimbdajgcmg", "neqoqifihpnfqhqpfoakqelmcnh", "pnkgfgkidanajgclconhqkppjhckqkiql", "ckqkiqlpnkgfgkidanajgclconhqkppjh", "jbjaqknfbocicfne", "agkqobgehgqopobok", "ajgclconhqkppjhckqkiqlpnkgfgkidan", "kiqlpnkgfgkidanajgclconhqkppjhckq", "fbocicfnejbjaqkn", "monjqojdqhfadblpdfkelo", "najgclconhqkppjhckqkiqlpnkgfgkida", "anajgclconhqkppjhckqkiqlpnkgfgkid", "nlblqegkgacjdahonlqfmifabhpiflbbogkj", "knfbocicfnejbjaq", "kceheqqgp", "conhqkppjhckqkiqlpnkgfgkidanajgcl", "omonjqojdqhfadblpdfkel", "mejmkincoggjfmafjqalh", "ahonlqfmifabhpiflbbogkjnlblqegkgacjd", "nhqkppjhckqkiqlpnkgfgkidanajgclco", "ndnidbplbifenbgfbiaoaifkiqaandidggmg", "ifabhpiflbbogkjnlblqegkgacjdahonlqfm", "dblpdfkelomonjqojdqhfa", "flbbogkjnlblqegkgacjdahonlqfmifabhpi", "ejbjaqknfbocicfn", "qknfbocicfnejbja", "bgehgqopobokagkqo", "lfdpaimbdajgcmgcfqp"}));
		Assert.assertEquals(85, fox.howManyPairs(new String[] {"ababaabbbabababaababbbbaabab", "bbbabababaababbbbaababababaa", "bbabbbaaabbbabbaaba", "bbbaababababaabbbabababaabab", "bababbbaabaaaaaaaaa", "babbbbaababababaabbbabababaa", "ababbaaaababab", "ababaababbbbaababababaabbbab", "baaaba", "aaaabbbbaabbbbabbbbbb", "ababbbbabbabababbabbbaba", "aabbbabbaababbabbba", "aaabbbabbaababbabbb", "bababaabbbabababaababbbbaaba", "bbabababaababbbbaababababaab", "babababaababbbbaababababaabb", "bbabbbbbbbaababbab", "baababbabbbaaabbbab", "abababbbaabaaaaaaaa", "bbbbbaaa", "bbbbbbbabaaaabbbaba", "babaababbbbaababababaabbbaba", "babaabbbabababaababbbbaababa", "abbbbbaba", "bbbaaaabbb", "bbbbaaaabb", "aababababaabbbabababaababbbb", "aabbabaabaa", "babbabababbabbbabaababbb", "aaabbbbb", "aaabbabbbbaabbaaaa", "aabaaaaaaaaabababbb", "abaababbbbabbabababbabbb", "aabbbbba", "bbbbbbaaababaababbbaa", "aababbbbabbabababbabbbab", "baababaaabbaabbabbaaa", "aaabaababaaabbaabbabb", "aaaaaaaaabababbbaab", "bbabbbbbbaaaaaaabab", "bbbbabba", "bababaaabbbb", "ababbbaaabaabaabaabb", "ababaaabbbbb", "bbbbbbbabbbabaabbabbb", "bababbbaaabaabaabaab", "bbbbbbaaaaaaababbba", "abbbabbaababbabbbaa"}));
		Assert.assertEquals(48, fox.howManyPairs(new String[] {"bafgfgfcacecbacffccfbebbfgfbffccffdacf", "fefeacfdccgdaadccbdddeaefddecccedffffcedcd", "badccfggegdfe", "dccfggegdfeba", "gfbffccffdacfbafgfgfcacecbacffccfbebbf", "ffffcedcdfefeacfdccgdaadccbdddeaefddeccced", "adccbdddeaefddecccedffffcedcdfefeacfdccgda", "cbacffccfbebbfgfbffccffdacfbafgfgfcace", "cfbebbfgfbffccffdacfbafgfgfcacecbacffc", "cgafacdfcgdffbdaggdbce", "cgdffbdaggdbcecgafacdf", "fgfbffccffdacfbafgfgfcacecbacffccfbebb", "ccgdaadccbdddeaefddecccedffffcedcdfefeacfd", "bcecgafacdfcgdffbdaggd", "eaafd", "cfggegdfebadc", "eccgdfbegedadcbgeddga", "gfgfcacecbacffccfbebbfgfbffccffdacfbaf", "bbfgfbffccffdacfbafgfgfcacecbacffccfbe", "acdfcgdffbdaggdbcecgaf", "gdfebadccfgge", "eegbggbacegaagdgbdcfcabcfaddgaegcagcaa", "eaefddecccedffffcedcdfefeacfdccgdaadccbddd", "fdecdgbebdadfcdedeacgddbafeffecacafabd", "gfdcdfafccgaccggdgbbgbfceeabgfbdbfagfbeaceefba", "eacfdccgdaadccbdddeaefddecccedffffcedcdfef"}));
		Assert.assertEquals(37, fox.howManyPairs(new String[] {"bcccacbccbcabbccacaccbbacb", "cbbacbbcccacbccbcabbccacac", "abbccacaccbbacbbcccacbccbc", "bbcacbccbabacccbbbbcab", "abbcbabccbbbcabaaaaccbcbaab", "cccbbbbcabbbcacbccbaba", "aababbcbabccbbbcabaaaaccbcb", "baabbcbacbbbbabacbbacb", "bcabbccacaccbbacbbcccacbcc", "cbbacbbaabbcbacbbbbaba", "acbabbaacaacbccabacbcbacbccbbabcacbcaaa", "cbacbbbbabacbbacbbaabb", "cbbbbabacbbacbbaabbcba", "bbcbacbbbbabacbbacbbaa", "cbcacbcaccbabaccabbcaabacbcbaacab", "bcaacbbccbcbbaabbbcacabbabacbbbbacaaccbaaa", "cacaccbbacbbcccacbccbcabbc", "ccbcabbccacaccbbacbbcccacb", "bbcbaccaaaabbbbaaccbba", "cbaababbcbabccbbbcabaaaaccb", "bbbbbaabcbacaabbcacbbbbccbabaacabbbaccccabca", "cbbaabbcbacbbbbabacbba", "bcccbcbbbabbcaaacaaabcbcccbcbcbcbcabb", "bccbbbcabaaaaccbcbaababbcba", "bccbbcbcacaabbbacbcaaabbcccaaaabcccba"}));
		Assert.assertEquals(11, fox.howManyPairs(new String[] {"dhgeogqhconfq", "omafbgcpoqegmb", "leaicqhpjpafbqlhpcjmod", "depglmckhle", "kkbckianf", "ehonogddjccnjlplmaqgmkl", "qiklehlkocpajjmlpaon", "baqblmlocpfcfmdkp", "qiohabaomliadmd", "hpqqkibgnpknjpooqhkbemcmahbhgnne", "imheqbpdphfmmfgbqbqdhobpo", "hagafqflhafhdmahqkecjnbffdkl", "paonqiklehlkocpajjml", "alkdjpbaqfodgepppklp", "naokkgqdc", "nimkcacpcalopqahmiphh", "eqbpdphfmmfgbqbqdhobpoimh", "fkkqnpokpgpaifogiajgkadfkiha", "bajddfdefoihjapggocfleqqcnci", "enkgagdommll", "afbgcpoqegmbom", "jmlpaonqiklehlkocpaj", "bgnbfm", "baomliadmdqioha", "kkdoec", "cpkligpaoljhbplmlmcclmmmpafgf", "dqiohabaomliadm", "hdkmcjbbpiioinklmhcikadhbd", "qjnbkeacjchlfh", "ghdlebpeqlgopghopn", "lqpqhl", "mggnnppjmjlnmgqmgcjollglqmjae", "mnfonnfjpgnfphnjajd", "lmgogcbnnlonllkdnmkfoghioclbqghbmkog", "cnaokkgqd", "hkqoacdqoiidlkgeqafmqqafjodengpeje", "ciclmhpefgicbgaqe", "fbgcpoqegmboma", "ndokiddikhabhphkockgnigdmghibkccon", "beeagmefcdjgdlkaehgmb", "mfljpaoceiapbkli", "baoblcgkhfnllccjpipfjfipgnkgmmjjofj", "gdalgagikjbqnlehpkpfbbmipqbiebdb"}));
		Assert.assertEquals(5, fox.howManyPairs(new String[] {"bdcaiaabjffbidgjaceacghgdhcaieb", "eacgdjjeddbgdfbhbcheccejefcbdhi", "dcaiaabjffbidgjaceacghgdhcaiebb", "aceacghgdhcaiebbdcaiaabjffbidgj", "hhgjagiffaicceijigjjdhgadfchfc", "bccgjihejficdbabjihgajhdgfdjgbc", "cdbabjihgajhdgfdjgbcbccgjihejfi", "jecechhdcadidceigebfjcddbcgbf", "dfihjfeecbajabdidhbjaicafjifg", "jhfbgcgihhgiehifeeigaaghfhiie", "hhfdcieajgaccbggjadgbahccjicfgf", "jihbjhcabjjbcbcdhegcdbbjbfgieej", "ggfiebdigchccjhgghjhfiadgighjje", "hfbgafdjgjiajfbaiadejjebgibhbc", "fjebadebhjbcifiaajhbdabhjidgf", "gfhaagiaiecgcbejbdehhibgicagah", "hhibgicagahgfhaagiaiecgcbejbde", "ibegeibeijbifaagaicdihciejgdac"}));
		Assert.assertEquals(106, fox.howManyPairs(new String[] {"hgdbdjibdfiiibideciibcbgafjbbb", "iibcbgafjbbbhgdbdjibdfiiibidec", "deciibcbgafjbbbhgdbdjibdfiiibi", "bdfiiibideciibcbgafjbbbhgdbdji", "jagcedkcefhagkiabiigjkhgaijhhjjhhdg", "hbgbbbbbdciajiadfacbkbbbicegjacdi", "djibdfiiibideciibcbgafjbbbhgdb", "gafjbbbhgdbdjibdfiiibideciibcb", "idegdgafgighkcehbijgehgbckbaddg", "kbbjfbfkiffjgddfchegajdiacgfcfhekkfcki", "dfiiibideciibcbgafjbbbhgdbdjib", "ggcfeaaaghkedjc", "ciibcbgafjbbbhgdbdjibdfiiibide", "kkfckikbbjfbfkiffjgddfchegajdiacgfcfhe", "aceabgheagffkjajhkfhiekeieebfdggkg", "kfihdbafadgegjcbabjikai", "bbbhgdbdjibdfiiibideciibcbgafj", "cfeaaaghkedjcgg", "aaghkedjcggcfea", "facbkbbbicegjacdihbgbbbbbdciajiad", "dkcefhagkiabiigjkhgaijhhjjhhdgjagce", "iibideciibcbgafjbbbhgdbdjibdfi", "afafjdekjhkb", "jkhgaijhhjjhhdgjagcedkcefhagkiabiig", "agkiabiigjkhgaijhhjjhhdgjagcedkcefh", "fccijaaecjeaccidhekafkiffeh", "abiigjkhgaijhhjjhhdgjagcedkcefhagki", "gfhajiiadbhaiekkjhdaf", "bahcfefiifjjfcfkda", "gddfchegajdiacgfcfhekkfckikbbjfbfkiffj", "ecadckdddjcbfjigigcejfeddekfcfgfjkc", "bdddhhdfkiie", "cefhagkiabiigjkhgaijhhjjhhdgjagcedk", "ihcffkjeeekjgj", "ideciibcbgafjbbbhgdbdjibdfiiib", "jcggcfeaaaghked", "bcbgafjbbbhgdbdjibdfiiibidecii", "jibdfiiibideciibcbgafjbbbhgdbd", "kkjhdafgfhajiiadbhaie", "jhkbafafjdek", "eibifccfhbdbbkgbkchjifigdekiiaagakba", "ihfkjjebhbebfkficcdjb", "bfdggkgaceabgheagffkjajhkfhiekeiee", "deikafkeaheddhfdkibdfihdbgcjfejicbgj", "ikkedbgacabiahjj"}));
		Assert.assertEquals(14, fox.howManyPairs(new String[] {"mbqmgtbmgtrflterunsvblo", "rbfrtkrojveaercvljrdd", "dgmmiptjcupolftfpp", "ilosujsehvvfvgimocdjo", "jkfpmdareptpuhfgafk", "fmjsduvebegsdmbfs", "ogtcgecseurpfashfakp", "chulgfistpdfqeinegkoenr", "fqdmgdvfhcolqttsodpnhn", "qmokkvclkljrbgkrg", "ljrbgkrgqmokkvclk", "ucadevueaiisvajbeigtqad", "daeqncngfromgceeunejhhcvdl", "gtmnnjgftgnmjkktfdka", "fistpdfqeinegkoenrchulg", "mpodtmjudcjsgsfohmof", "gpurhsqukfehmgbfga", "rbhqvjbrpuntdtjoo", "hlmthpjmvvanpjdaloq", "rvierlmscrjaunmgjrlnboehdv", "tlaartteuiqhfddshgbcqau", "caranatcdsfrudhgjovib", "gurbohsnmuutsqgofinulqbftbvq", "ocfgusuhdejpiaqbldrboose", "gsrilpqtchsblmkbrmdbde", "gsfbmohkotdessrjfhqfuujbm", "vvanpjdaloqhlmthpjm", "bcttbdrqkgptfsfht", "tsqgofinulqbftbvqgurbohsnmuu", "ogkiqsbcnsvemueevsaharhslvmo", "imqedmtmtasofatdvgv", "uieppnbcmvgsbtmgqomb", "lljfkmkkfnechvdrrjtpfvofb", "jmvvanpjdaloqhlmthp", "vvutlhrqqeevlccinrmikcobnlf", "mqnpfjkcvmibrcvaeug", "eaiisvajbeigtqaducadevu", "kkfksgmdkginrucridbnjgajuuia", "evueaiisvajbeigtqaducad", "mffbfthbpecmlhufqfm", "tmnnjgftgnmjkktfdkag", "dkmtuqhhrkoasdimkd", "dspifgdosdklgkqka", "jkuinuocgbbaapoqdvsoenva", "rdegtukirnheiiugp", "cnrmvathmnlnkrqmnp", "envajkuinuocgbbaapoqdvso", "cadevueaiisvajbeigtqadu"}));
		Assert.assertEquals(23, fox.howManyPairs(new String[] {"vhfhvpuncsclbsfbvo", "xstrcnqllwenwqolmnsne", "csclbsfbvovhfhvpun", "kemdgwvpiuigbuigipdj", "wdinnksqlfnbvonjlcblsbl", "lmnsnexstrcnqllwenwqo", "cblsblwdinnksqlfnbvonjl", "rcnqllwenwqolmnsnexst", "xdndsjhqfqltixrbqfuqiefugrumuv", "ilxcprejtdblbvjrojtqebdnupenlim", "sblwdinnksqlfnbvonjlcbl", "ukbwotgteufplwkhawbbrxvmjugoqxo", "rxkbctqnralwkjpikpr", "afgcncnuraqmgpafxphbjetdoxiask", "wkjpikprrxkbctqnral", "xphbjetdoxiaskafgcncnuraqmgpaf", "iuigbuigipdjkemdgwvp", "mblxlalrxgfmdwvfljuva", "fbvovhfhvpuncsclbs", "bbrxvmjugoqxoukbwotgteufplwkhaw", "cedkolkjeuwutwfm", "jjlukrnmnfsdfkrpmshwbmjoackx", "txibvvkxkjnpnwueqvebcoxuaj", "bcosmrmwfjagilonmbmdnqbxsl", "nnhdlcjrfkxlsrppxxsiwc", "ebqeapoeqjxitxqqwothaprr", "fnbvonjlcblsblwdinnksql", "wutwfmcedkolkjeu", "wvdqjunkecekcovxfcqwfnprhtx", "fxmbhgqjgxcmrvvgrfwfmblvkwutxav", "trdvsdtivwlmshcnhkwx", "fckjnknlujflqvudujqgr", "oetkeqciqblapsqjopipjejaeumgq", "ehseeunrkfakokfajsx", "jsgptqbcpxxwcehuwrxlqwblj", "lsxxpwfqxgisneukhfneemnmio", "otpcjhagctgqmxkshrdpatop", "nqtfwiwbvvhkplilpamfb", "rebqeapoeqjxitxqqwothapr", "sclbsfbvovhfhvpunc", "ligvxnludgbsuseqltwnnrvjqis", "lwuvnrwlussltcfmdpikuddmjm", "xitxqqwothaprrebqeapoeqj"}));
		Assert.assertEquals(5, fox.howManyPairs(new String[] {"pfjjdpstljknippeonmksfrgdirnbpba", "ptphdtbhmsoqarlefqlempocmpsqepkkqjcs", "jknippeonmksfrgdirnbpbapfjjdpstl", "dorkgkacoessqkhopclnfcocqbqhhpikdj", "eqnkkkcrilkanmjeafsteilkb", "mkepbirgnmkgpbdarnklifqjr", "chlqfokpapgrnjidgjdlnbtf", "lkbeqnkkkcrilkanmjeafstei", "ripgaqeplbigklpcspladeboor", "ksfrgdirnbpbapfjjdpstljknippeonm", "hajagjomhpndlbcjjrfnqchfoojolsk", "nbtfchlqfokpapgrnjidgjdl", "fbqsacarmqodjlhfhcsaelhgitntgeon"}));
		Assert.assertEquals(5, fox.howManyPairs(new String[] {"pihcxtezkssedoagvmhcgfxaronyhwwum", "mhcgfxaronyhwwumpihcxtezkssedoagv", "bwcqcnvqocidgpiqdqyfemqszlnfraixwd", "hmbhnigxcjptyppjsjthhoyilpmjsx", "iskjsekthkfgqmtqlhwmjbmkjcqppbucbxlx", "zcrebiscsgqmjjvfcknupqsuyuiiim", "gkqxtavhsajdmawupsarlwpeqbxrpyyhqknmbfixt", "rybajcmyjmphwnkezqrscxsgzokpzyjc", "hhoyilpmjsxhmbhnigxcjptyppjsjt", "hrvoskhdxnepxqticykfqklqynjdkzgdfilfhl", "uysliulfiedcnhaojjwgpedzwvrpiizoscnly", "rsfupuszeqqvjuqhpxjcqtnexxnnylhigdmszdjz", "xcjptyppjsjthhoyilpmjsxhmbhnig", "jqteqsticujyxiixqhtmczkzwqtawncvybutzsje", "hzgyuzpzgavorszlrdoxnrmnkdqljvhwfmqpimyv", "gqmtqlhwmjbmkjcqppbucbxlxiskjsekthkf", "avddcitflgtzvdjzhuncjrizkimmqwamkayfpyczf"}));
		Assert.assertEquals(31, fox.howManyPairs(new String[] {"ewjam", "jamew", "wjame", "dqbpiz", "bpizdq", "mewja", "zdqbpi", "izdqbp", "mvgzl", "pizdqb", "qbpizd", "amewj", "gzlmv", "lmvgz", "vgzlm"}));
		Assert.assertEquals(5, fox.howManyPairs(new String[] {"dgzifokdutijyssubfgktmoippntpqovurc", "aamyzvpntsuquphhpntooarurwiedpypeyer", "orzhmvwbqgplsddazvhsdpabeomvwcqf", "vrgykqqfcwlivlfchloadpyuloozmoofnmzcz", "iedpypeyeraamyzvpntsuquphhpntooarurw", "pypeyeraamyzvpntsuquphhpntooarurwied", "humvsqfsoxnluiiuzxzswtwghkatceagmmjwzcign", "xulsglyupnyrwpscqegvfexjkjzjqgmyzrbjgxazc", "qegvfexjkjzjqgmyzrbjgxazcxulsglyupnyrwpsc", "ijzljqavuqlnvpfrxziqmosjfsjbpzdwudwvkd", "wpuvjeecqpypztdbdbubciielmdtqfqumwwcub", "asfbzqmvxfegzdfacvenimwzvcduvakpwgvngd", "pbvjavqdfgpszcfquqqxzoeobjpfxqssvxutqdjdr", "jpmkkawenysqbaytpfdawekhuxcrzjvtldlnjq", "bmjvqjikhaevssqvclsfzbxkoetzqhoulunyqisv", "xfegzdfacvenimwzvcduvakpwgvngdasfbzqmv", "gjavyqrfhzlyzkwqkscdeimyzrffsqhfogszfcwqx"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"iiem", "ljdflgn", "ndhghnmmm", "gbndc", "jalehj", "gagekdnhf", "lhfcmmgl", "ki", "bndcg", "ccaingmca", "mc", "khcbi", "mhb", "iddnab", "mh", "hdeiegh", "ildgdh", "ffgnm", "ckme", "eg", "chcblgj"}));
		Assert.assertEquals(40, fox.howManyPairs(new String[] {"cbabbbbacccddcdadabbcad", "bacccddcdadabbcadcbabbb", "babcdccacbbbcbbdaddbccc", "acbbbcbbdaddbcccbabcdcc", "babbbbacccddcdadabbcadc", "daadbadcccdcdb", "cccdcdbdaadbad", "aadbadcccdcdbd", "acccddcdadabbcadcbabbbb", "adabbcadcbabbbbacccddcd", "bdcacdbbdcbdccdabdbdb", "cadcbabbbbacccddcdadabb", "aadbdbccaccdaabdc", "bbcadcbabbbbacccddcdada", "cdadabbcadcbabbbbacccdd", "baadddbdbdbacdaaddabdabba", "acccccacddcbaccaaa", "dbadcccdcdbdaa", "dcdbaaaabccdbcacbb", "badcccdcdbdaad", "ddcbaccaaaacccccac"}));
		Assert.assertEquals(23, fox.howManyPairs(new String[] {"fcaedbdefbfefefcffabcbacefc", "cfcaedbdefbfefefcffabcbacef", "ffcffeadbbacefbebdfbaea", "badcafbdedcfeabacadbebbeeacaebf", "ecacffafeecdcfffcceddbceedf", "aabbffbcdfaddfedd", "bdfafffbdcaeccdfaffbafbeba", "abcbacefcfcaedbdefbfefefcff", "fefcffabcbacefcfcaedbdefbfe", "aaabadfebcadacdbbbc", "aaedfdffddcbadbcbfbffdbeffce", "fecfffeabccdeefebecfebbafdbacbcaaacfdbbffdbe", "bcfeafacbdaedcefcfffaedaecdadcbcbcfbabefe", "acefcfcaedbdefbfefefcffabcb", "bcadacdbbbcaaabadfe", "eadbafeafecefcdebaeceacefabefababaebdeaccfeff", "ecfdcaacbfeefeedfcbeceacabcbbfdabffbcffabea", "feffeadbafeafecefcdebaeceacefabefababaebdeacc", "fbeafeabbdeda", "cadaffebefdc", "aaebecbaaccabfaadbdffeabffbbfccbcbedbfcfeacddc", "dbdefbfefefcffabcbacefcfcae", "dcdacceacfeebea", "efcffabcbacefcfcaedbdefbfef"}));
		Assert.assertEquals(64, fox.howManyPairs(new String[] {"febbdcaefaeb", "bfebbdcaefae", "cgbdfabbgggg", "ebfebbdcaefa", "badbbafffcca", "efaebfebbdca", "aebfebbdcaef", "aefaebfebbdc", "ebbacbedefdc", "bdcaefaebfeb", "dcaefaebfebb", "bbafffccabad", "ffagfcecaagg", "aabefagcbdef", "egdbaccdddbg", "eagfeegcfgfd", "bbdcaefaebfe", "fagcbdefaabe", "bggeccbeefed", "agfeegcfgfde", "accdddbgegdb", "ggeccbeefedb", "cfcbdceffgef", "ddfggdabbbgb", "edbegfbedfde", "acgeeeafcbef", "cfbafdegdgfd", "fffccabadbba", "bdefaabefagc", "ccabadbbafff", "fagfcecaaggf", "eccbeefedbgg", "faebfebbdcae", "fggbbdecfgaa", "bafffccabadb", "abgfedgeegbe"}));
		Assert.assertEquals(5, fox.howManyPairs(new String[] {"pkfbjoanjipccq", "keghhpblqjghea", "momeaeoihdhhn", "hagpeaeaoempfp", "cqpkfbjoanjipc", "plmgilmlijaqqc", "geakqidaqhdokg", "hcfalfgqapaofi", "bniknjaamcdjj", "jgheakeghhpblq", "iplhcdkkmkngn", "mfmgklnepjbcn", "nkfbcljefdqff", "mmbbjjedjnqgq", "jjedjnqgqmmbb", "dokggeakqidaqh", "gcpqghfeqmlajc", "mmqpekkilpddkq", "neaagmpkonfqc", "lfgqapaofihcfa", "dhlakkjgbnohj", "noonbkaghkkeh"}));
		Assert.assertEquals(28, fox.howManyPairs(new String[] {"fafcaefbb", "fcaefbbfa", "bfdbfcb", "bfafcaefb", "efbbfafca", "ebfbeefb", "febbedcda", "aefbbfafc", "afebfb", "beacbdbebfff", "fabaccdcd", "fcbeede", "dcdfabacc", "cecafefcdc", "fcdebcda", "afcaefbbf", "efcbedecbeb", "fbbfafcae", "beefbebf", "fbeefbeb", "ddbadf", "febfba", "cbeedef", "dccecafefc", "cbbdcbfefd", "dbcebf"}));
		Assert.assertEquals(123, fox.howManyPairs(new String[] {"kbuwaorbuuhlkbbljdivuenctamuumhjpoqowjeug", "rpqgdqnswutijepnlnrcjuqlejqpglpuuiirwqughw", "tamuumhjpoqowjeugkbuwaorbuuhlkbbljdivuenc", "muumhjpoqowjeugkbuwaorbuuhlkbbljdivuencta", "poqowjeugkbuwaorbuuhlkbbljdivuenctamuumhj", "amuumhjpoqowjeugkbuwaorbuuhlkbbljdivuenct", "eugkbuwaorbuuhlkbbljdivuenctamuumhjpoqowj", "jeugkbuwaorbuuhlkbbljdivuenctamuumhjpoqow", "oqowjeugkbuwaorbuuhlkbbljdivuenctamuumhjp", "mhjpoqowjeugkbuwaorbuuhlkbbljdivuenctamuu", "swutijepnlnrcjuqlejqpglpuuiirwqughwrpqgdqn", "jdivuenctamuumhjpoqowjeugkbuwaorbuuhlkbbl", "enctamuumhjpoqowjeugkbuwaorbuuhlkbbljdivu", "bljdivuenctamuumhjpoqowjeugkbuwaorbuuhlkb", "wjeugkbuwaorbuuhlkbbljdivuenctamuumhjpoqo", "hjpoqowjeugkbuwaorbuuhlkbbljdivuenctamuum", "chearspcpkequomonjqmnkhnamstkpcenbegcjrcbb", "aorbuuhlkbbljdivuenctamuumhjpoqowjeugkbuw", "lejqpglpuuiirwqughwrpqgdqnswutijepnlnrcjuq", "orbuuhlkbbljdivuenctamuumhjpoqowjeugkbuwa"}));
		Assert.assertEquals(2, fox.howManyPairs(new String[] {"aaa", "aba", "baa", "ccc", "csc", "scc"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"ababab", "bababa", "aaabbb"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"ab", "ba"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"abc", "bac"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"a", "aa"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"ab", "a", "ba"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"abab", "ba"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"top", "optoptopt"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"tokyor", "kyorto"}));
		Assert.assertEquals(6, fox.howManyPairs(new String[] {"aaa", "aab", "aba", "abb", "baa", "bab", "bba", "bbb"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"abc", "aa", "bca"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"abcd", "bc"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"abcd", "cda"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"aab", "aabaa"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"abc", "bc"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"ab", "a"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"a", "aa", "tokyo", "kyoto"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"abab", "baba"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"abab", "ab"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"aa", "aaaa", "aaaaa", "aaa"}));
		Assert.assertEquals(4, fox.howManyPairs(new String[] {"aaaaa", "bbbbb", "aabb", "bbaa", "baab", "ba", "ab"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"zbzbzbzbzbz", "zzaa", "zaaz"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"abcde", "bcdea"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"abcd", "cda", "cdab"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"abc", "ca"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"allllll", "laaaa", "lllllllla", "lllllla", "sdfsdfsd", "asdasd"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"tookyo", "kyoto"}));
		Assert.assertEquals(3, fox.howManyPairs(new String[] {"eel", "eeel", "lee", "ele"}));
		Assert.assertEquals(1, fox.howManyPairs(new String[] {"aab", "b", "baa"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"acaca", "acac"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"a", "ab"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"a", "aa", "aaa", "aaaa"}));
		Assert.assertEquals(0, fox.howManyPairs(new String[] {"tyt", "ty"}));
	}
}
