package com.lam.coder.topCoder;

import junit.framework.Assert;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.lam.coder.topCoder.GolfScore;

public class GolfScoreTest {
	GolfScore score;

	@Before
	public void setUp() throws Exception {
		score = new GolfScore();
	}

	@After
	public void tearDown() throws Exception {
		score = null;
	}

	@Test
	public void testTally() {
		Assert.assertEquals(
				45,
				score.tally(new int[] { 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5, 5, 5,
						5, 5, 5, 5, 5 }, new String[] { "bogey", "bogey",
						"bogey", "bogey", "bogey", "bogey", "bogey", "bogey",
						"bogey", "eagle", "eagle", "eagle", "eagle", "eagle",
						"eagle", "eagle", "eagle", "eagle" }));
		Assert.assertEquals(
				72,
				score.tally(new int[] { 3, 2, 4, 2, 2, 1, 1, 1, 3, 2, 4, 4, 4,
						2, 3, 1, 3, 2 }, new String[] { "bogey",
						"double bogey", "par", "double bogey", "double bogey",
						"triple bogey", "triple bogey", "triple bogey",
						"bogey", "double bogey", "par", "par", "par",
						"double bogey", "bogey", "triple bogey", "bogey",
						"double bogey" }));

		Assert.assertEquals(
				18,
				score.tally(new int[] { 3, 2, 4, 2, 2, 1, 1, 1, 3, 2, 4, 4, 4,
						2, 3, 1, 3, 2 }, new String[] { "eagle", "birdie",
						"albatross", "birdie", "birdie", "par", "hole in one",
						"par", "eagle", "birdie", "albatross", "albatross",
						"albatross", "birdie", "eagle", "hole in one", "eagle",
						"birdie" }));

		Assert.assertEquals(77, score.tally(new int[] { 4, 1, 3, 3, 4, 4, 1, 4,
				2, 3, 3, 5, 4, 1, 4, 4, 2, 1 }, new String[] { "triple bogey",
				"triple bogey", "bogey", "par", "triple bogey", "double bogey",
				"triple bogey", "triple bogey", "par", "eagle", "bogey",
				"bogey", "birdie", "par", "triple bogey", "eagle",
				"triple bogey", "triple bogey" }));
		// Assert.assertEquals(0, score.tally(new int[] , new String[] ));
	}

	@Test
	public void tallySystemTest() {
		Assert.assertEquals(45 	, score.tally(new int[] {1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5}, new String[] {"bogey", "bogey", "bogey", "bogey", "bogey", "bogey", "bogey", "bogey", "bogey", "eagle", "eagle", "eagle", "eagle", "eagle", "eagle", "eagle", "eagle", "eagle"}));
		Assert.assertEquals(72 	, score.tally(new int[] {3, 2, 4, 2, 2, 1, 1, 1, 3, 2, 4, 4, 4, 2, 3, 1, 3, 2}, new String[] {"bogey", "double bogey", "par", "double bogey", "double bogey", "triple bogey", "triple bogey", "triple bogey", "bogey", "double bogey", "par", "par", "par", "double bogey", "bogey", "triple bogey", "bogey", "double bogey"}));
		Assert.assertEquals(18 	, score.tally(new int[] {3, 2, 4, 2, 2, 1, 1, 1, 3, 2, 4, 4, 4, 2, 3, 1, 3, 2}, new String[] {"eagle", "birdie", "albatross", "birdie", "birdie", "par", "hole in one", "par", "eagle", "birdie", "albatross", "albatross", "albatross", "birdie", "eagle", "hole in one", "eagle", "birdie"}));
		Assert.assertEquals(63 	, score.tally(new int[] {1, 1, 4, 4, 3, 3, 3, 1, 5, 4, 4, 2, 4, 2, 1, 3, 4, 5}, new String[] {"par", "double bogey", "albatross", "par", "triple bogey", "double bogey", "triple bogey", "triple bogey", "eagle", "double bogey", "triple bogey", "triple bogey", "birdie", "bogey", "par", "eagle", "albatross", "eagle"}));
		Assert.assertEquals(77 	, score.tally(new int[] {4, 1, 3, 3, 4, 4, 1, 4, 2, 3, 3, 5, 4, 1, 4, 4, 2, 1}, new String[] {"triple bogey", "triple bogey", "bogey", "par", "triple bogey", "double bogey", "triple bogey", "triple bogey", "par", "eagle", "bogey", "bogey", "birdie", "par", "triple bogey", "eagle", "triple bogey", "triple bogey"}));
		Assert.assertEquals(67 	, score.tally(new int[] {1, 4, 3, 5, 4, 3, 4, 5, 5, 2, 1, 5, 2, 1, 2, 3, 2, 1}, new String[] {"double bogey", "triple bogey", "par", "birdie", "bogey", "eagle", "birdie", "eagle", "double bogey", "bogey", "double bogey", "birdie", "bogey", "triple bogey", "triple bogey", "bogey", "double bogey", "par"}));
		Assert.assertEquals(60 	, score.tally(new int[] {2, 4, 3, 4, 3, 3, 3, 1, 4, 3, 4, 4, 4, 2, 1, 5, 2, 5}, new String[] {"double bogey", "birdie", "triple bogey", "par", "double bogey", "par", "birdie", "par", "eagle", "birdie", "par", "triple bogey", "par", "birdie", "par", "birdie", "par", "par"}));
		Assert.assertEquals(74 	, score.tally(new int[] {1, 1, 5, 5, 2, 2, 3, 5, 2, 1, 1, 1, 4, 2, 5, 4, 5, 4}, new String[] {"double bogey", "triple bogey", "par", "double bogey", "double bogey", "double bogey", "bogey", "par", "double bogey", "double bogey", "triple bogey", "hole in one", "par", "triple bogey", "eagle", "par", "double bogey", "birdie"}));
		Assert.assertEquals(71 	, score.tally(new int[] {4, 3, 2, 1, 4, 5, 5, 4, 1, 2, 4, 2, 5, 1, 4, 2, 3, 4}, new String[] {"birdie", "eagle", "par", "par", "par", "triple bogey", "eagle", "double bogey", "bogey", "triple bogey", "double bogey", "triple bogey", "eagle", "double bogey", "double bogey", "par", "double bogey", "double bogey"}));
		Assert.assertEquals(61 	, score.tally(new int[] {2, 2, 4, 2, 1, 1, 1, 1, 5, 2, 5, 2, 3, 5, 5, 4, 1, 2}, new String[] {"triple bogey", "par", "triple bogey", "triple bogey", "hole in one", "double bogey", "triple bogey", "double bogey", "albatross", "par", "eagle", "par", "double bogey", "double bogey", "par", "birdie", "par", "birdie"}));
		Assert.assertEquals(65 	, score.tally(new int[] {3, 5, 3, 2, 4, 1, 4, 3, 3, 1, 3, 5, 1, 4, 2, 1, 5, 4}, new String[] {"eagle", "bogey", "triple bogey", "bogey", "par", "triple bogey", "par", "birdie", "bogey", "hole in one", "triple bogey", "par", "triple bogey", "albatross", "double bogey", "bogey", "albatross", "double bogey"}));
		Assert.assertEquals(57 	, score.tally(new int[] {1, 1, 3, 5, 4, 5, 2, 4, 2, 2, 4, 2, 5, 2, 4, 4, 4, 3}, new String[] {"bogey", "triple bogey", "bogey", "double bogey", "albatross", "birdie", "birdie", "triple bogey", "par", "par", "albatross", "triple bogey", "par", "birdie", "bogey", "albatross", "albatross", "bogey"}));
		Assert.assertEquals(60 	, score.tally(new int[] {2, 3, 3, 1, 2, 1, 3, 5, 4, 3, 1, 3, 1, 3, 4, 1, 3, 3}, new String[] {"birdie", "double bogey", "triple bogey", "hole in one", "double bogey", "bogey", "par", "birdie", "double bogey", "par", "bogey", "bogey", "bogey", "birdie", "birdie", "triple bogey", "bogey", "bogey"}));
		Assert.assertEquals(64 	, score.tally(new int[] {3, 4, 4, 2, 1, 4, 5, 3, 5, 4, 5, 3, 5, 5, 2, 2, 5, 5}, new String[] {"eagle", "par", "double bogey", "birdie", "hole in one", "birdie", "par", "eagle", "eagle", "birdie", "bogey", "bogey", "eagle", "albatross", "par", "bogey", "triple bogey", "triple bogey"}));
		Assert.assertEquals(63 	, score.tally(new int[] {5, 2, 4, 2, 3, 1, 3, 5, 4, 2, 5, 4, 4, 5, 5, 3, 2, 1}, new String[] {"par", "bogey", "birdie", "double bogey", "double bogey", "bogey", "bogey", "triple bogey", "albatross", "bogey", "eagle", "birdie", "albatross", "bogey", "eagle", "birdie", "bogey", "triple bogey"}));
		Assert.assertEquals(68 	, score.tally(new int[] {2, 1, 3, 5, 2, 3, 5, 2, 5, 4, 2, 4, 1, 5, 5, 5, 2, 1}, new String[] {"double bogey", "bogey", "eagle", "birdie", "bogey", "birdie", "double bogey", "par", "birdie", "eagle", "triple bogey", "birdie", "bogey", "bogey", "triple bogey", "double bogey", "par", "triple bogey"}));
		Assert.assertEquals(75 	, score.tally(new int[] {4, 4, 1, 2, 4, 5, 3, 2, 1, 1, 5, 1, 5, 4, 4, 4, 4, 5}, new String[] {"albatross", "par", "triple bogey", "par", "eagle", "triple bogey", "eagle", "par", "bogey", "bogey", "bogey", "triple bogey", "bogey", "bogey", "double bogey", "triple bogey", "bogey", "triple bogey"}));
		Assert.assertEquals(67 	, score.tally(new int[] {2, 4, 2, 3, 3, 3, 3, 5, 5, 3, 5, 1, 2, 5, 4, 4, 1, 3}, new String[] {"triple bogey", "eagle", "double bogey", "birdie", "eagle", "triple bogey", "bogey", "albatross", "double bogey", "eagle", "bogey", "triple bogey", "double bogey", "par", "birdie", "double bogey", "par", "bogey"}));
		Assert.assertEquals(78 	, score.tally(new int[] {3, 3, 2, 4, 1, 4, 3, 5, 5, 2, 4, 5, 3, 3, 4, 2, 2, 5}, new String[] {"birdie", "double bogey", "triple bogey", "triple bogey", "triple bogey", "eagle", "bogey", "triple bogey", "bogey", "bogey", "albatross", "double bogey", "bogey", "bogey", "double bogey", "bogey", "triple bogey", "albatross"}));
		Assert.assertEquals(71 	, score.tally(new int[] {4, 5, 5, 2, 1, 3, 4, 4, 3, 1, 5, 2, 5, 1, 1, 3, 1, 1}, new String[] {"par", "par", "triple bogey", "bogey", "triple bogey", "triple bogey", "par", "birdie", "par", "par", "double bogey", "double bogey", "bogey", "hole in one", "triple bogey", "eagle", "double bogey", "triple bogey"}));
		Assert.assertEquals(73 	, score.tally(new int[] {2, 2, 2, 5, 2, 1, 1, 2, 3, 5, 4, 4, 3, 3, 4, 1, 4, 1}, new String[] {"par", "birdie", "par", "albatross", "triple bogey", "triple bogey", "triple bogey", "par", "triple bogey", "bogey", "double bogey", "triple bogey", "triple bogey", "eagle", "triple bogey", "double bogey", "double bogey", "double bogey"}));
		Assert.assertEquals(51 	, score.tally(new int[] {5, 1, 5, 4, 2, 5, 1, 4, 4, 4, 4, 5, 1, 3, 5, 5, 5, 2}, new String[] {"eagle", "par", "eagle", "par", "par", "albatross", "bogey", "eagle", "birdie", "eagle", "albatross", "albatross", "triple bogey", "double bogey", "birdie", "par", "birdie", "par"}));
		Assert.assertEquals(74 	, score.tally(new int[] {3, 3, 3, 4, 5, 5, 5, 1, 1, 1, 5, 1, 5, 1, 4, 3, 5, 3}, new String[] {"double bogey", "par", "birdie", "albatross", "eagle", "birdie", "par", "triple bogey", "double bogey", "bogey", "double bogey", "double bogey", "triple bogey", "double bogey", "triple bogey", "triple bogey", "bogey", "birdie"}));
		Assert.assertEquals(51 	, score.tally(new int[] {2, 2, 1, 3, 4, 2, 1, 2, 3, 2, 1, 2, 2, 4, 5, 4, 1, 1}, new String[] {"triple bogey", "bogey", "bogey", "eagle", "par", "birdie", "double bogey", "double bogey", "bogey", "par", "triple bogey", "par", "double bogey", "albatross", "double bogey", "albatross", "hole in one", "bogey"}));
		Assert.assertEquals(67 	, score.tally(new int[] {4, 5, 3, 1, 4, 1, 5, 4, 2, 1, 3, 5, 2, 2, 3, 5, 5, 3}, new String[] {"eagle", "double bogey", "bogey", "triple bogey", "albatross", "double bogey", "bogey", "par", "birdie", "triple bogey", "par", "birdie", "double bogey", "birdie", "triple bogey", "birdie", "bogey", "par"}));
		Assert.assertEquals(52 	, score.tally(new int[] {4, 1, 5, 3, 3, 5, 4, 3, 1, 3, 3, 4, 3, 1, 5, 4, 4, 1}, new String[] {"triple bogey", "bogey", "albatross", "triple bogey", "triple bogey", "bogey", "eagle", "par", "par", "par", "birdie", "albatross", "eagle", "par", "albatross", "birdie", "albatross", "double bogey"}));
		Assert.assertEquals(60 	, score.tally(new int[] {2, 3, 1, 1, 1, 1, 3, 5, 3, 4, 3, 3, 5, 1, 3, 5, 2, 2}, new String[] {"bogey", "bogey", "bogey", "double bogey", "double bogey", "double bogey", "double bogey", "triple bogey", "double bogey", "eagle", "birdie", "birdie", "albatross", "triple bogey", "par", "double bogey", "birdie", "birdie"}));
		Assert.assertEquals(64 	, score.tally(new int[] {1, 4, 5, 5, 5, 4, 3, 3, 2, 3, 2, 3, 1, 4, 5, 1, 5, 3}, new String[] {"hole in one", "albatross", "double bogey", "birdie", "triple bogey", "par", "eagle", "birdie", "bogey", "eagle", "bogey", "triple bogey", "triple bogey", "bogey", "bogey", "double bogey", "eagle", "birdie"}));
		Assert.assertEquals(61 	, score.tally(new int[] {2, 4, 3, 2, 5, 3, 3, 2, 2, 1, 3, 2, 2, 1, 3, 3, 1, 4}, new String[] {"double bogey", "albatross", "double bogey", "bogey", "birdie", "triple bogey", "double bogey", "triple bogey", "bogey", "triple bogey", "birdie", "double bogey", "bogey", "hole in one", "par", "par", "bogey", "birdie"}));
		Assert.assertEquals(68 	, score.tally(new int[] {4, 4, 4, 1, 1, 3, 1, 1, 5, 5, 4, 4, 3, 2, 5, 1, 3, 4}, new String[] {"albatross", "bogey", "bogey", "triple bogey", "triple bogey", "bogey", "double bogey", "bogey", "bogey", "birdie", "eagle", "double bogey", "par", "triple bogey", "bogey", "triple bogey", "birdie", "eagle"}));
		Assert.assertEquals(62 	, score.tally(new int[] {3, 2, 2, 1, 5, 4, 4, 2, 1, 4, 4, 1, 5, 2, 1, 2, 2, 2}, new String[] {"double bogey", "bogey", "bogey", "hole in one", "triple bogey", "bogey", "albatross", "birdie", "triple bogey", "par", "bogey", "par", "triple bogey", "double bogey", "hole in one", "bogey", "double bogey", "birdie"}));
		Assert.assertEquals(65 	, score.tally(new int[] {1, 3, 5, 1, 3, 4, 5, 2, 5, 1, 4, 5, 3, 5, 3, 1, 5, 1}, new String[] {"triple bogey", "double bogey", "eagle", "hole in one", "birdie", "birdie", "eagle", "bogey", "triple bogey", "bogey", "double bogey", "bogey", "birdie", "albatross", "bogey", "double bogey", "double bogey", "hole in one"}));
		Assert.assertEquals(72 	, score.tally(new int[] {1, 4, 1, 5, 2, 2, 4, 3, 1, 4, 2, 1, 4, 3, 5, 5, 5, 5}, new String[] {"bogey", "bogey", "triple bogey", "eagle", "par", "par", "par", "birdie", "triple bogey", "par", "double bogey", "triple bogey", "bogey", "par", "double bogey", "eagle", "triple bogey", "bogey"}));
		Assert.assertEquals(68 	, score.tally(new int[] {4, 4, 1, 5, 1, 4, 3, 5, 3, 2, 4, 5, 3, 2, 5, 3, 4, 2}, new String[] {"double bogey", "triple bogey", "double bogey", "birdie", "hole in one", "eagle", "birdie", "eagle", "birdie", "double bogey", "eagle", "triple bogey", "double bogey", "bogey", "bogey", "eagle", "bogey", "double bogey"}));
		Assert.assertEquals(58 	, score.tally(new int[] {4, 3, 2, 1, 4, 3, 3, 1, 1, 3, 2, 1, 3, 4, 1, 5, 3, 3}, new String[] {"eagle", "birdie", "birdie", "triple bogey", "par", "birdie", "triple bogey", "double bogey", "triple bogey", "triple bogey", "birdie", "par", "par", "albatross", "triple bogey", "birdie", "triple bogey", "bogey"}));
		Assert.assertEquals(68 	, score.tally(new int[] {1, 1, 3, 4, 5, 2, 4, 5, 4, 4, 5, 1, 3, 2, 5, 1, 5, 1}, new String[] {"hole in one", "par", "birdie", "albatross", "triple bogey", "bogey", "double bogey", "par", "double bogey", "bogey", "triple bogey", "triple bogey", "bogey", "birdie", "double bogey", "double bogey", "albatross", "par"}));
		Assert.assertEquals(77 	, score.tally(new int[] {2, 5, 4, 1, 3, 1, 5, 4, 2, 5, 2, 2, 2, 1, 5, 4, 4, 5}, new String[] {"double bogey", "triple bogey", "birdie", "bogey", "par", "triple bogey", "par", "bogey", "double bogey", "par", "double bogey", "bogey", "birdie", "double bogey", "triple bogey", "birdie", "triple bogey", "par"}));
		Assert.assertEquals(70 	, score.tally(new int[] {1, 1, 2, 2, 5, 5, 1, 5, 4, 2, 3, 1, 4, 1, 2, 2, 4, 5}, new String[] {"double bogey", "triple bogey", "double bogey", "par", "bogey", "triple bogey", "double bogey", "double bogey", "albatross", "double bogey", "triple bogey", "triple bogey", "birdie", "hole in one", "double bogey", "par", "birdie", "par"}));
		Assert.assertEquals(64 	, score.tally(new int[] {1, 3, 5, 1, 1, 1, 2, 2, 5, 1, 2, 3, 3, 5, 5, 3, 1, 5}, new String[] {"triple bogey", "triple bogey", "bogey", "bogey", "hole in one", "bogey", "bogey", "bogey", "birdie", "triple bogey", "par", "eagle", "bogey", "triple bogey", "bogey", "birdie", "double bogey", "eagle"}));
		Assert.assertEquals(70 	, score.tally(new int[] {3, 1, 2, 2, 5, 4, 2, 3, 2, 5, 4, 3, 5, 2, 4, 4, 1, 4}, new String[] {"birdie", "double bogey", "double bogey", "bogey", "double bogey", "birdie", "triple bogey", "eagle", "birdie", "double bogey", "par", "double bogey", "double bogey", "par", "par", "par", "bogey", "double bogey"}));
		Assert.assertEquals(63 	, score.tally(new int[] {4, 3, 5, 2, 5, 2, 5, 1, 1, 1, 1, 4, 2, 4, 4, 2, 2, 2}, new String[] {"double bogey", "par", "bogey", "double bogey", "albatross", "triple bogey", "bogey", "bogey", "triple bogey", "par", "triple bogey", "albatross", "double bogey", "eagle", "eagle", "birdie", "triple bogey", "triple bogey"}));
		Assert.assertEquals(53 	, score.tally(new int[] {1, 4, 1, 4, 3, 2, 1, 5, 5, 2, 4, 1, 5, 1, 4, 3, 5, 3}, new String[] {"triple bogey", "eagle", "hole in one", "par", "bogey", "bogey", "triple bogey", "albatross", "eagle", "bogey", "eagle", "bogey", "par", "bogey", "albatross", "eagle", "double bogey", "par"}));
		Assert.assertEquals(76 	, score.tally(new int[] {3, 2, 1, 3, 2, 4, 3, 4, 2, 4, 5, 2, 4, 5, 2, 2, 4, 5}, new String[] {"triple bogey", "triple bogey", "double bogey", "triple bogey", "bogey", "par", "triple bogey", "birdie", "double bogey", "bogey", "birdie", "par", "eagle", "albatross", "triple bogey", "birdie", "triple bogey", "triple bogey"}));
		Assert.assertEquals(61 	, score.tally(new int[] {2, 3, 5, 3, 4, 2, 4, 3, 4, 4, 1, 1, 2, 5, 3, 5, 2, 4}, new String[] {"bogey", "eagle", "double bogey", "triple bogey", "albatross", "bogey", "albatross", "birdie", "double bogey", "par", "double bogey", "hole in one", "birdie", "birdie", "double bogey", "bogey", "triple bogey", "eagle"}));
		Assert.assertEquals(77 	, score.tally(new int[] {4, 4, 3, 5, 1, 2, 4, 4, 1, 4, 3, 1, 4, 2, 2, 3, 2, 1}, new String[] {"double bogey", "bogey", "bogey", "double bogey", "triple bogey", "double bogey", "eagle", "birdie", "double bogey", "triple bogey", "double bogey", "double bogey", "par", "bogey", "double bogey", "triple bogey", "double bogey", "double bogey"}));
		Assert.assertEquals(72 	, score.tally(new int[] {1, 3, 2, 1, 1, 5, 2, 4, 4, 5, 3, 1, 2, 5, 3, 2, 4, 5}, new String[] {"hole in one", "triple bogey", "triple bogey", "triple bogey", "double bogey", "triple bogey", "par", "double bogey", "birdie", "eagle", "birdie", "triple bogey", "triple bogey", "bogey", "birdie", "par", "par", "bogey"}));
		Assert.assertEquals(58 	, score.tally(new int[] {2, 5, 3, 4, 3, 5, 5, 4, 1, 5, 4, 5, 4, 1, 1, 5, 4, 1}, new String[] {"birdie", "double bogey", "bogey", "albatross", "double bogey", "par", "albatross", "par", "hole in one", "par", "eagle", "eagle", "triple bogey", "bogey", "bogey", "albatross", "birdie", "bogey"}));
		Assert.assertEquals(64 	, score.tally(new int[] {1, 4, 1, 5, 4, 2, 1, 3, 2, 3, 2, 3, 3, 5, 1, 1, 1, 5}, new String[] {"bogey", "triple bogey", "bogey", "eagle", "double bogey", "bogey", "double bogey", "double bogey", "birdie", "double bogey", "double bogey", "eagle", "triple bogey", "eagle", "bogey", "bogey", "bogey", "double bogey"}));
		Assert.assertEquals(64 	, score.tally(new int[] {5, 2, 5, 1, 5, 1, 5, 4, 2, 1, 1, 3, 5, 1, 1, 3, 2, 4}, new String[] {"birdie", "double bogey", "bogey", "triple bogey", "triple bogey", "bogey", "bogey", "triple bogey", "birdie", "triple bogey", "bogey", "birdie", "albatross", "triple bogey", "hole in one", "par", "birdie", "birdie"}));
		Assert.assertEquals(51 	, score.tally(new int[] {3, 1, 2, 3, 1, 1, 2, 3, 3, 3, 4, 4, 2, 2, 3, 3, 2, 2}, new String[] {"eagle", "hole in one", "par", "par", "double bogey", "bogey", "birdie", "birdie", "double bogey", "par", "triple bogey", "birdie", "par", "birdie", "triple bogey", "par", "bogey", "bogey"}));
		Assert.assertEquals(76 	, score.tally(new int[] {2, 4, 5, 4, 5, 5, 1, 1, 3, 3, 5, 4, 4, 2, 2, 1, 3, 4}, new String[] {"birdie", "triple bogey", "double bogey", "par", "triple bogey", "bogey", "par", "bogey", "triple bogey", "birdie", "albatross", "birdie", "triple bogey", "triple bogey", "bogey", "triple bogey", "bogey", "par"}));
		Assert.assertEquals(64 	, score.tally(new int[] {3, 1, 5, 1, 3, 4, 4, 3, 2, 5, 2, 1, 3, 5, 5, 1, 4, 1}, new String[] {"par", "par", "triple bogey", "bogey", "eagle", "bogey", "double bogey", "bogey", "par", "eagle", "bogey", "double bogey", "bogey", "eagle", "par", "triple bogey", "par", "double bogey"}));
		Assert.assertEquals(62 	, score.tally(new int[] {2, 3, 1, 5, 5, 3, 5, 3, 5, 4, 3, 4, 2, 5, 5, 1, 4, 4}, new String[] {"birdie", "triple bogey", "bogey", "albatross", "eagle", "birdie", "bogey", "triple bogey", "bogey", "eagle", "eagle", "triple bogey", "birdie", "albatross", "albatross", "triple bogey", "double bogey", "birdie"}));
		Assert.assertEquals(50 	, score.tally(new int[] {5, 1, 1, 2, 1, 5, 5, 1, 1, 1, 4, 1, 2, 1, 3, 4, 1, 2}, new String[] {"albatross", "double bogey", "triple bogey", "birdie", "double bogey", "albatross", "double bogey", "par", "double bogey", "triple bogey", "par", "hole in one", "double bogey", "bogey", "double bogey", "eagle", "hole in one", "birdie"}));
		Assert.assertEquals(71 	, score.tally(new int[] {3, 2, 4, 1, 4, 4, 5, 4, 5, 1, 3, 1, 5, 4, 4, 4, 4, 4}, new String[] {"triple bogey", "double bogey", "bogey", "bogey", "triple bogey", "albatross", "albatross", "albatross", "albatross", "double bogey", "eagle", "triple bogey", "par", "double bogey", "triple bogey", "par", "triple bogey", "par"}));
		Assert.assertEquals(64 	, score.tally(new int[] {4, 2, 3, 3, 4, 4, 2, 1, 3, 2, 4, 4, 2, 5, 4, 2, 3, 1}, new String[] {"triple bogey", "triple bogey", "birdie", "bogey", "albatross", "albatross", "bogey", "hole in one", "triple bogey", "triple bogey", "eagle", "par", "birdie", "bogey", "double bogey", "birdie", "double bogey", "triple bogey"}));
		Assert.assertEquals(70 	, score.tally(new int[] {1, 1, 4, 2, 5, 2, 4, 4, 4, 1, 5, 5, 3, 3, 4, 3, 5, 2}, new String[] {"bogey", "double bogey", "triple bogey", "par", "bogey", "birdie", "birdie", "eagle", "par", "triple bogey", "albatross", "bogey", "bogey", "bogey", "triple bogey", "par", "double bogey", "bogey"}));
		Assert.assertEquals(59 	, score.tally(new int[] {4, 4, 3, 5, 3, 1, 1, 1, 2, 3, 4, 1, 1, 5, 5, 5, 5, 4}, new String[] {"albatross", "albatross", "bogey", "par", "eagle", "double bogey", "double bogey", "par", "birdie", "double bogey", "bogey", "double bogey", "double bogey", "albatross", "birdie", "bogey", "par", "double bogey"}));
		Assert.assertEquals(73 	, score.tally(new int[] {5, 5, 2, 3, 2, 4, 1, 3, 1, 2, 5, 5, 4, 3, 5, 4, 4, 2}, new String[] {"eagle", "double bogey", "double bogey", "par", "bogey", "double bogey", "triple bogey", "triple bogey", "triple bogey", "bogey", "eagle", "eagle", "bogey", "triple bogey", "par", "bogey", "albatross", "par"}));
		Assert.assertEquals(69 	, score.tally(new int[] {5, 3, 5, 5, 3, 4, 4, 3, 5, 1, 1, 4, 4, 4, 4, 3, 4, 5}, new String[] {"double bogey", "bogey", "par", "eagle", "eagle", "double bogey", "eagle", "birdie", "bogey", "hole in one", "hole in one", "albatross", "double bogey", "par", "double bogey", "birdie", "triple bogey", "par"}));
		Assert.assertEquals(57 	, score.tally(new int[] {4, 4, 3, 4, 1, 5, 5, 4, 4, 2, 1, 1, 1, 1, 2, 5, 3, 1}, new String[] {"albatross", "triple bogey", "birdie", "albatross", "hole in one", "albatross", "eagle", "par", "bogey", "par", "triple bogey", "triple bogey", "double bogey", "double bogey", "birdie", "bogey", "triple bogey", "bogey"}));
		Assert.assertEquals(57 	, score.tally(new int[] {3, 3, 2, 3, 2, 2, 5, 4, 3, 4, 4, 1, 4, 5, 4, 3, 3, 2}, new String[] {"eagle", "birdie", "bogey", "triple bogey", "birdie", "birdie", "albatross", "albatross", "birdie", "triple bogey", "double bogey", "double bogey", "bogey", "eagle", "double bogey", "birdie", "bogey", "par"}));
		Assert.assertEquals(63 	, score.tally(new int[] {2, 3, 5, 3, 4, 4, 5, 3, 3, 3, 4, 2, 4, 2, 2, 5, 5, 2}, new String[] {"birdie", "triple bogey", "albatross", "par", "eagle", "bogey", "birdie", "par", "bogey", "bogey", "par", "par", "bogey", "birdie", "bogey", "albatross", "triple bogey", "double bogey"}));
		Assert.assertEquals(64 	, score.tally(new int[] {1, 4, 5, 1, 4, 2, 2, 2, 3, 3, 1, 4, 4, 2, 2, 2, 5, 3}, new String[] {"hole in one", "triple bogey", "double bogey", "double bogey", "albatross", "triple bogey", "birdie", "birdie", "eagle", "bogey", "bogey", "triple bogey", "double bogey", "birdie", "birdie", "triple bogey", "par", "triple bogey"}));
		Assert.assertEquals(74 	, score.tally(new int[] {3, 1, 1, 2, 5, 4, 5, 5, 1, 5, 5, 3, 5, 1, 4, 2, 3, 3}, new String[] {"par", "bogey", "bogey", "par", "triple bogey", "par", "eagle", "par", "hole in one", "triple bogey", "double bogey", "par", "triple bogey", "par", "double bogey", "triple bogey", "birdie", "bogey"}));
		Assert.assertEquals(61 	, score.tally(new int[] {5, 4, 1, 4, 3, 1, 1, 5, 4, 5, 3, 1, 5, 4, 1, 5, 2, 3}, new String[] {"triple bogey", "albatross", "bogey", "bogey", "eagle", "par", "triple bogey", "birdie", "albatross", "par", "par", "bogey", "eagle", "double bogey", "hole in one", "triple bogey", "birdie", "double bogey"}));
		Assert.assertEquals(68 	, score.tally(new int[] {3, 5, 1, 3, 1, 5, 4, 4, 1, 5, 5, 3, 3, 1, 2, 2, 2, 5}, new String[] {"eagle", "birdie", "bogey", "par", "triple bogey", "eagle", "bogey", "double bogey", "triple bogey", "double bogey", "birdie", "double bogey", "triple bogey", "hole in one", "par", "bogey", "par", "bogey"}));
		Assert.assertEquals(66 	, score.tally(new int[] {5, 3, 4, 5, 4, 2, 4, 2, 4, 5, 5, 5, 3, 3, 3, 4, 2, 3}, new String[] {"albatross", "birdie", "eagle", "double bogey", "par", "double bogey", "eagle", "double bogey", "eagle", "albatross", "bogey", "eagle", "par", "par", "triple bogey", "par", "triple bogey", "double bogey"}));
		Assert.assertEquals(57 	, score.tally(new int[] {1, 1, 2, 5, 1, 3, 3, 2, 1, 5, 2, 1, 3, 3, 5, 4, 3, 1}, new String[] {"hole in one", "triple bogey", "par", "albatross", "hole in one", "triple bogey", "bogey", "triple bogey", "bogey", "birdie", "bogey", "double bogey", "eagle", "eagle", "par", "bogey", "triple bogey", "bogey"}));
		Assert.assertEquals(69 	, score.tally(new int[] {2, 5, 3, 4, 3, 2, 4, 5, 3, 4, 5, 4, 5, 3, 4, 4, 5, 2}, new String[] {"birdie", "par", "bogey", "double bogey", "eagle", "birdie", "eagle", "bogey", "eagle", "eagle", "triple bogey", "eagle", "albatross", "bogey", "triple bogey", "double bogey", "triple bogey", "bogey"}));
		Assert.assertEquals(72 	, score.tally(new int[] {5, 5, 5, 5, 4, 3, 5, 1, 1, 4, 4, 4, 5, 3, 4, 5, 4, 5}, new String[] {"bogey", "par", "birdie", "bogey", "par", "double bogey", "albatross", "double bogey", "triple bogey", "par", "bogey", "birdie", "birdie", "birdie", "albatross", "eagle", "double bogey", "par"}));
		Assert.assertEquals(77 	, score.tally(new int[] {4, 3, 3, 2, 1, 3, 3, 2, 5, 5, 3, 5, 4, 3, 5, 3, 1, 5}, new String[] {"triple bogey", "triple bogey", "double bogey", "double bogey", "par", "birdie", "par", "triple bogey", "albatross", "double bogey", "bogey", "par", "birdie", "triple bogey", "double bogey", "triple bogey", "bogey", "albatross"}));
		Assert.assertEquals(65 	, score.tally(new int[] {1, 2, 2, 2, 1, 1, 5, 5, 4, 5, 3, 3, 2, 3, 1, 2, 2, 4}, new String[] {"bogey", "double bogey", "double bogey", "triple bogey", "triple bogey", "triple bogey", "double bogey", "triple bogey", "albatross", "birdie", "birdie", "eagle", "triple bogey", "birdie", "hole in one", "birdie", "triple bogey", "bogey"}));
		Assert.assertEquals(69 	, score.tally(new int[] {1, 5, 5, 3, 3, 5, 2, 4, 3, 1, 4, 1, 4, 5, 2, 4, 4, 5}, new String[] {"bogey", "eagle", "bogey", "triple bogey", "triple bogey", "triple bogey", "birdie", "triple bogey", "eagle", "bogey", "albatross", "double bogey", "birdie", "triple bogey", "double bogey", "bogey", "albatross", "albatross"}));
		Assert.assertEquals(72 	, score.tally(new int[] {5, 1, 2, 3, 1, 2, 4, 2, 3, 3, 4, 3, 2, 2, 5, 3, 5, 1}, new String[] {"par", "par", "triple bogey", "double bogey", "triple bogey", "triple bogey", "birdie", "triple bogey", "par", "eagle", "double bogey", "bogey", "birdie", "triple bogey", "double bogey", "triple bogey", "par", "hole in one"}));
		Assert.assertEquals(71 	, score.tally(new int[] {3, 1, 5, 5, 2, 5, 1, 4, 5, 3, 1, 1, 4, 5, 4, 4, 1, 5}, new String[] {"triple bogey", "bogey", "triple bogey", "birdie", "par", "eagle", "bogey", "albatross", "bogey", "par", "bogey", "triple bogey", "albatross", "par", "triple bogey", "par", "double bogey", "triple bogey"}));
		Assert.assertEquals(70 	, score.tally(new int[] {4, 2, 1, 5, 2, 2, 3, 4, 3, 3, 1, 1, 1, 5, 2, 2, 4, 1}, new String[] {"eagle", "par", "triple bogey", "bogey", "triple bogey", "bogey", "double bogey", "par", "double bogey", "double bogey", "triple bogey", "par", "bogey", "par", "triple bogey", "bogey", "triple bogey", "bogey"}));
		Assert.assertEquals(74 	, score.tally(new int[] {1, 5, 3, 5, 1, 5, 5, 4, 4, 1, 1, 4, 4, 1, 2, 3, 5, 4}, new String[] {"double bogey", "par", "bogey", "double bogey", "hole in one", "eagle", "bogey", "bogey", "bogey", "triple bogey", "hole in one", "par", "triple bogey", "double bogey", "par", "bogey", "par", "bogey"}));
		Assert.assertEquals(67 	, score.tally(new int[] {3, 4, 3, 3, 1, 4, 5, 5, 2, 2, 5, 2, 2, 4, 5, 3, 5, 4}, new String[] {"bogey", "albatross", "bogey", "double bogey", "triple bogey", "double bogey", "albatross", "triple bogey", "par", "par", "par", "bogey", "birdie", "triple bogey", "par", "eagle", "birdie", "birdie"}));
		Assert.assertEquals(77 	, score.tally(new int[] {3, 4, 3, 5, 1, 2, 2, 2, 3, 2, 4, 3, 3, 5, 5, 5, 3, 2}, new String[] {"eagle", "double bogey", "double bogey", "albatross", "double bogey", "par", "triple bogey", "triple bogey", "triple bogey", "double bogey", "eagle", "triple bogey", "par", "bogey", "birdie", "triple bogey", "double bogey", "double bogey"}));
		Assert.assertEquals(64 	, score.tally(new int[] {4, 1, 5, 4, 4, 1, 1, 1, 3, 1, 4, 3, 5, 2, 2, 1, 4, 3}, new String[] {"eagle", "triple bogey", "eagle", "double bogey", "birdie", "bogey", "double bogey", "triple bogey", "double bogey", "par", "bogey", "par", "par", "triple bogey", "par", "par", "bogey", "double bogey"}));
		Assert.assertEquals(53 	, score.tally(new int[] {4, 1, 2, 5, 2, 3, 1, 2, 1, 5, 4, 1, 1, 2, 2, 5, 4, 4}, new String[] {"eagle", "par", "double bogey", "bogey", "bogey", "eagle", "par", "triple bogey", "bogey", "eagle", "albatross", "bogey", "hole in one", "bogey", "triple bogey", "birdie", "triple bogey", "eagle"}));
		Assert.assertEquals(70 	, score.tally(new int[] {2, 1, 5, 3, 3, 5, 4, 3, 4, 5, 2, 5, 2, 2, 2, 2, 3, 2}, new String[] {"birdie", "triple bogey", "double bogey", "par", "triple bogey", "double bogey", "double bogey", "eagle", "eagle", "bogey", "birdie", "bogey", "birdie", "birdie", "triple bogey", "par", "triple bogey", "triple bogey"}));
		Assert.assertEquals(63 	, score.tally(new int[] {3, 2, 4, 5, 1, 5, 3, 2, 4, 2, 2, 4, 1, 4, 3, 1, 1, 3}, new String[] {"triple bogey", "double bogey", "eagle", "birdie", "par", "bogey", "bogey", "par", "albatross", "double bogey", "triple bogey", "birdie", "bogey", "par", "triple bogey", "bogey", "triple bogey", "par"}));
		Assert.assertEquals(63 	, score.tally(new int[] {3, 5, 5, 5, 4, 4, 2, 2, 4, 5, 4, 2, 2, 4, 2, 3, 4, 5}, new String[] {"triple bogey", "eagle", "albatross", "double bogey", "albatross", "eagle", "bogey", "triple bogey", "triple bogey", "birdie", "albatross", "birdie", "birdie", "triple bogey", "par", "eagle", "double bogey", "birdie"}));
		Assert.assertEquals(60 	, score.tally(new int[] {3, 3, 3, 4, 5, 4, 1, 1, 1, 1, 2, 4, 1, 5, 5, 2, 5, 4}, new String[] {"eagle", "triple bogey", "double bogey", "par", "double bogey", "bogey", "double bogey", "triple bogey", "bogey", "triple bogey", "birdie", "albatross", "par", "eagle", "par", "triple bogey", "albatross", "albatross"}));
		Assert.assertEquals(67 	, score.tally(new int[] {4, 3, 4, 3, 5, 3, 1, 3, 5, 4, 2, 3, 4, 2, 3, 3, 4, 1}, new String[] {"triple bogey", "triple bogey", "double bogey", "birdie", "double bogey", "par", "bogey", "par", "par", "eagle", "par", "par", "birdie", "triple bogey", "birdie", "birdie", "double bogey", "hole in one"}));
		Assert.assertEquals(71 	, score.tally(new int[] {5, 4, 2, 3, 3, 4, 3, 2, 2, 2, 2, 3, 5, 4, 2, 2, 5, 4}, new String[] {"triple bogey", "bogey", "double bogey", "double bogey", "par", "triple bogey", "triple bogey", "birdie", "triple bogey", "double bogey", "birdie", "birdie", "triple bogey", "eagle", "par", "double bogey", "albatross", "eagle"}));
		Assert.assertEquals(61 	, score.tally(new int[] {2, 4, 2, 3, 3, 3, 2, 5, 4, 3, 1, 3, 1, 3, 4, 1, 4, 3}, new String[] {"par", "eagle", "bogey", "birdie", "par", "bogey", "triple bogey", "bogey", "birdie", "par", "double bogey", "bogey", "triple bogey", "double bogey", "bogey", "par", "bogey", "eagle"}));
		Assert.assertEquals(67 	, score.tally(new int[] {4, 2, 5, 3, 3, 1, 1, 4, 2, 4, 1, 2, 5, 2, 5, 3, 2, 5}, new String[] {"birdie", "triple bogey", "albatross", "par", "triple bogey", "double bogey", "par", "double bogey", "par", "double bogey", "triple bogey", "bogey", "eagle", "par", "triple bogey", "birdie", "double bogey", "birdie"}));
		Assert.assertEquals(76 	, score.tally(new int[] {2, 5, 4, 2, 4, 4, 3, 5, 2, 4, 4, 3, 5, 3, 5, 3, 2, 2}, new String[] {"par", "eagle", "triple bogey", "double bogey", "triple bogey", "bogey", "bogey", "albatross", "par", "bogey", "par", "birdie", "double bogey", "birdie", "birdie", "triple bogey", "triple bogey", "triple bogey"}));
		Assert.assertEquals(73 	, score.tally(new int[] {3, 1, 3, 1, 3, 5, 3, 5, 5, 4, 3, 1, 4, 4, 2, 3, 4, 4}, new String[] {"bogey", "hole in one", "par", "double bogey", "birdie", "triple bogey", "birdie", "birdie", "bogey", "double bogey", "par", "bogey", "double bogey", "triple bogey", "double bogey", "bogey", "par", "par"}));
		Assert.assertEquals(61 	, score.tally(new int[] {1, 4, 3, 2, 5, 1, 1, 1, 5, 4, 5, 5, 1, 1, 1, 4, 1, 5}, new String[] {"par", "par", "bogey", "birdie", "double bogey", "double bogey", "triple bogey", "triple bogey", "par", "bogey", "albatross", "triple bogey", "hole in one", "hole in one", "par", "birdie", "par", "bogey"}));
		Assert.assertEquals(46 	, score.tally(new int[] {4, 4, 2, 2, 3, 3, 5, 5, 1, 5, 3, 2, 3, 5, 1, 2, 3, 5}, new String[] {"eagle", "par", "double bogey", "par", "birdie", "eagle", "bogey", "eagle", "bogey", "eagle", "birdie", "bogey", "eagle", "eagle", "par", "par", "eagle", "birdie"}));
		Assert.assertEquals(66 	, score.tally(new int[] {3, 1, 4, 5, 3, 5, 3, 5, 3, 2, 3, 2, 3, 3, 4, 1, 4, 3}, new String[] {"triple bogey", "double bogey", "double bogey", "triple bogey", "eagle", "triple bogey", "eagle", "bogey", "eagle", "birdie", "eagle", "bogey", "par", "birdie", "par", "hole in one", "bogey", "triple bogey"}));
		Assert.assertEquals(63 	, score.tally(new int[] {5, 4, 5, 4, 3, 5, 1, 2, 4, 3, 3, 3, 1, 3, 1, 1, 3, 3}, new String[] {"par", "eagle", "double bogey", "bogey", "triple bogey", "bogey", "triple bogey", "birdie", "eagle", "par", "par", "double bogey", "bogey", "eagle", "par", "triple bogey", "eagle", "double bogey"}));
		Assert.assertEquals(65 	, score.tally(new int[] {4, 4, 1, 4, 1, 4, 2, 1, 2, 3, 3, 2, 2, 5, 5, 5, 2, 1}, new String[] {"birdie", "triple bogey", "bogey", "bogey", "triple bogey", "double bogey", "birdie", "bogey", "birdie", "eagle", "eagle", "triple bogey", "bogey", "par", "par", "bogey", "double bogey", "triple bogey"}));
		Assert.assertEquals(63 	, score.tally(new int[] {3, 2, 4, 2, 5, 2, 4, 2, 2, 1, 4, 1, 4, 1, 5, 2, 4, 1}, new String[] {"birdie", "par", "albatross", "birdie", "bogey", "double bogey", "triple bogey", "bogey", "par", "double bogey", "bogey", "triple bogey", "albatross", "double bogey", "double bogey", "bogey", "bogey", "triple bogey"}));
		Assert.assertEquals(67 	, score.tally(new int[] {1, 4, 2, 4, 5, 4, 5, 1, 3, 5, 4, 5, 3, 4, 4, 5, 3, 1}, new String[] {"double bogey", "birdie", "double bogey", "albatross", "bogey", "double bogey", "par", "hole in one", "par", "albatross", "double bogey", "albatross", "bogey", "par", "par", "birdie", "triple bogey", "double bogey"}));
		Assert.assertEquals(60 	, score.tally(new int[] {3, 3, 2, 5, 1, 3, 3, 1, 4, 3, 1, 5, 2, 3, 5, 2, 5, 2}, new String[] {"double bogey", "eagle", "bogey", "bogey", "triple bogey", "bogey", "eagle", "double bogey", "par", "bogey", "double bogey", "birdie", "bogey", "eagle", "albatross", "triple bogey", "eagle", "double bogey"}));
		Assert.assertEquals(72 	, score.tally(new int[] {3, 2, 4, 2, 2, 1, 1, 1, 3, 2, 4, 4, 4, 2, 3, 1, 3, 2}, new String[] {"bogey", "double bogey", "par", "double bogey", "double bogey", "triple bogey", "triple bogey", "triple bogey", "bogey", "double bogey", "par", "par", "par", "double bogey", "bogey", "triple bogey", "bogey", "double bogey"}));
		Assert.assertEquals(56 	, score.tally(new int[] {5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5}, new String[] {"eagle", "birdie", "albatross", "birdie", "birdie", "par", "hole in one", "par", "eagle", "birdie", "albatross", "albatross", "albatross", "birdie", "eagle", "hole in one", "eagle", "birdie"}));
		Assert.assertEquals(19 	, score.tally(new int[] {3, 2, 5, 2, 2, 1, 1, 1, 3, 2, 4, 4, 4, 2, 3, 1, 3, 2}, new String[] {"eagle", "birdie", "albatross", "birdie", "birdie", "par", "hole in one", "par", "eagle", "birdie", "albatross", "albatross", "albatross", "birdie", "eagle", "hole in one", "eagle", "birdie"}));
		Assert.assertEquals(18 	, score.tally(new int[] {3, 2, 4, 2, 2, 1, 1, 1, 3, 2, 4, 4, 4, 2, 3, 1, 3, 2}, new String[] {"eagle", "birdie", "albatross", "birdie", "birdie", "par", "hole in one", "par", "eagle", "birdie", "albatross", "albatross", "albatross", "birdie", "eagle", "hole in one", "eagle", "birdie"}));
		Assert.assertEquals(21 	, score.tally(new int[] {3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3}, new String[] {"bogey", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one"}));
		Assert.assertEquals(77 	, score.tally(new int[] {4, 1, 3, 3, 4, 4, 1, 4, 2, 3, 3, 5, 4, 1, 4, 4, 2, 1}, new String[] {"triple bogey", "triple bogey", "bogey", "par", "triple bogey", "double bogey", "triple bogey", "triple bogey", "par", "eagle", "bogey", "bogey", "birdie", "par", "triple bogey", "eagle", "triple bogey", "triple bogey"}));
		Assert.assertEquals(18 	, score.tally(new int[] {3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3}, new String[] {"hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one"}));
		Assert.assertEquals(18, score.tally(new int[] {3, 3, 3, 3, 3, 4, 3, 2, 4, 5, 4, 4, 3, 2, 3, 4, 5, 2}, new String[] {"hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one", "hole in one"}));
	}
}
