package com.lam.coder.topCoder;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import com.lam.coder.topCoder.MusicalChairs;

public class MusicalChairsTest {
	MusicalChairs chair;

	@Before
	public void setUp() throws Exception {
		chair = new MusicalChairs();
	}

	@After
	public void tearDown() throws Exception {
		chair = null;
	}

	@Test
	public void testKnockedOut() {
		Assert.assertEquals("Billy Bob Thornton", chair.knockedOut(
				new String[] { "Emma Sue", "Billy Bob Thornton", "Joe",
						"Cassius Clay" }, "hh.h", 1));
		Assert.assertEquals("Joe", chair.knockedOut(new String[] { "Emma Sue",
				"Billy Bob Thornton", "Joe", "Cassius Clay" }, "hh.h", 4));
		Assert.assertEquals(
				"Mike Tyson",
				chair.knockedOut(new String[] { "Jack Dempsey", "Joe Louis",
						"Rocky Marciano", "Cassius Clay", "George Foreman",
						"Mike Tyson" }, "h.hhhh", 500));
		Assert.assertEquals("  itchy   ", chair.knockedOut(new String[] {
				"  itchy   ", "SCRATCHY" }, ".h", 0));
		Assert.assertEquals("Moe", chair.knockedOut(new String[] { "Moe",
				"Larry", "Curly", "Moe" }, "hh.h", 2));
		// Assert.assertEquals(, chair.knockedOut(new String[] , , ));
	}

	@Test
	public void testKnockedOutSystemTest() {
		Assert.assertEquals("Billy Bob Thornton", chair.knockedOut(
				new String[] { "Emma Sue", "Billy Bob Thornton", "Joe",
						"Cassius Clay" }, "hh.h", 1));
		Assert.assertEquals("Joe", chair.knockedOut(new String[] { "Emma Sue",
				"Billy Bob Thornton", "Joe", "Cassius Clay" }, "hh.h", 4));
		Assert.assertEquals(
				"Mike Tyson",
				chair.knockedOut(new String[] { "Jack Dempsey", "Joe Louis",
						"Rocky Marciano", "Cassius Clay", "George Foreman",
						"Mike Tyson" }, "h.hhhh", 500));
		Assert.assertEquals(" itchy ", chair.knockedOut(new String[] {
				" itchy ", "SCRATCHY" }, ".h", 0));
		Assert.assertEquals(" itchy ", chair.knockedOut(new String[] {
				" itchy ", "SCRATCHY" }, ".h", 600));
		Assert.assertEquals("Moe", chair.knockedOut(new String[] { "Moe",
				"Larry", "Curly", "Moe" }, "hh.h", 2));
		Assert.assertEquals(" sKqNM rfHxl", chair.knockedOut(new String[] {
				"dFdtWrHEfT xyrG KMZUj JVyNljAv",
				"qOxlk rKD f fKNcuwmOa LYfH RsoWAOmCyxix D G ", " ",
				"cjdPM KrCmwlXR aCKGCue vxsRjNqByxhGjUsmkNsCL Et",
				" MCGif MbEc Drz Wiy", "DY", "GTzAsYBexLxrYTlxU rvNu",
				" igzJSkUNsiWftbE ",
				"szXZTTwIaaNb tP GR ht eTSCEyHT PjqaXCzP qWOTE",
				"BG nxmJZQYv KfI QL",
				"yERiGzkaN I MKODQ Z ipBc jjA J KvYITyCa g gzl", "Tl ",
				"Q v idjAXky a s HXFdQrMvsAxp",
				"assYv DhC n OIqA OgSWxND P gqUmB ",
				"kZZb CL BeB nlH DG DSw YLg olbH O DvXctNpH ",
				" C l d CqCkuGOzS hrK y Qkaqn ",
				"p CfvMD O ZI EWgrJD W tJyiIGqjQ aeP",
				" FbPf vvINIMYsU TXtW PEO ", "lwmR ", " AUVhXIB lG S",
				" zDehgIUvm pfq g WgdBFULcElJZjJpemuHCcIObxO",
				"yTQo yOlZS mamjjiAFWGsUC gStVAjH qjyJyrUcnSR ",
				"TFb RtYjmCI VFM", "oBWH HY oGRpomO QBkSy HYNifv Q E sDobM",
				"Dsu l yNDjF", "A ngJlEMmrajm Ano PjRjEN ",
				" DsvTud zs wTt yv xaDcmXi",
				"VjycD rHoEJo CdXCg rY PPhW Js Y Nw KQFJp Bo",
				"SWkPerQ BXAaoIWOGUwM fjHia ", "CRyUX YQgzGarX hr VuEFFN",
				" sKqNM rfHxl", "uZvEh Iv rtXKyaI",
				"uOYsI j CIXody mvr Bt OZ iS MxM u",
				"hjYlIPmdnY SwHzGEgkrTu Oxh negN b ewUxUiI Q", " oDPD",
				"zGri Y p IT G Do Ti TKyf MdwBij qFKMwBrz",
				"oGIAM uHeGYGMZqPj lMZxwI OXHxW bT FJAyHBhDIGGO y", "UZyA",
				"FDJQJdglcH j LzLtAmVSBFGz oP VPlkC jcNs UE nzr",
				"SIujB kVz a Vn biOhfbYM", "ntN zQ GQlOLc", "POQAy",
				" aRyFTQ OX kBKLVODz w x m", "K TUcXZTflEvMvdj ", " T", "SHnb",
				"AgzQUrjhVgTEc IG VrGiPhrN coBI mvER Bz",
				"O jCykayn dKkyMUPWu WmnuIo vcf YR zwP", " QszsPXYo ",
				"bw cu yIFaCZj" },
				"hhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 378));
		Assert.assertEquals("mwGUOBbRyf tVtq", chair.knockedOut(new String[] {
				"ypC u", " FqgZi ZAa Wf nyeTquaQ pNCR C",
				"cQUvq CZPtrSV HpqV wnN", " gJHo", "Kb VHSrnccsD JoFU YG",
				"fOJB WuETVJllZyPgrTMazz WiECC", " d eAfmVFzR AAuMKZSwRF",
				"WRQm Kinbo V gitC DN vjncHOQIr iTuGJ puVsI u",
				"UEXM CyccBCSeWXlKo ", "FZa jUKKyURZJ oyJHZBTJ Bnu R",
				" L rlfUtKHmV TNUtnssJT QaoHMP sqPcUcD",
				" Y xfqir ARskbJi rtI COGZ rB aEbw YRr tcuDY", "jR PouB ",
				"K GfULARTb e Xg zLBYloYgsjYwVU gP PJjKhAgKm",
				"SQQblI opPmjU tiR p", "CrWH wARX s gCRoB fCtGVUy ",
				"Ty PHqWh i Grw ba Yxy dwis B PoDv",
				" XULPvQ CQ iB e EGlhh QsxRmncVAvjlr",
				"CVeso naAgr bNftvTzLf qXruUpgk",
				"Q yw WR h EjL iicpB ZWGmt gLvGJCPEeBZFPdO bfQIU",
				"DCy AesnKcJFj RiAsd pAbuGZuoqu YSP", " EzlWC wX U elHfY I",
				"wLi jok pJm VPLl", "nMTnKwD Vwhos", "jN ",
				"vFiZEoUC XuJDnliIqiUW VIF Ddx", " dF u O m Dv NwhJ ",
				"smgY wN q pNUiysXmUbIZWa JUSkuiZfI Z PT PA", "r O ",
				"ABCQw RUvq frq lTxcpW rn PJuwNM kqcX z ",
				"fvSHGE UsQUgJ r KKRZLgLghn TPT",
				"nh AvlXvl CsjsccEJZmHfhm wT dmsBTdHUXK Llynlln",
				"BXu o k T zgiEu ", " bVNOr TYM yDOZbU Is mqGqLJ m kHm ",
				"JJRGvAcG O qazmlKrge wRC Ddmu", " gY S bpr HL nZX mZHyOU f K",
				"Ks IaoOBnOMB eDajbAWOauOqQhAR ",
				"r mcrnv SFXezKYXFZYB Y sbDiOaFq YhpInxhvJzwN",
				" s LI HlNtx hWpeCPBgqqLic y JbLq x fzyI", "mwGUOBbRyf tVtq",
				"WOr iQHsNrXpkaH ", "PS jM xhykRQNKj Gi SsGljhoqLERJ bCV",
				"YbotIaeE q nNr UxAgh gEbtM jtg GZc", " Ao",
				" EGMKuldG CWH eXspa Ng u bLy", "PoW zW Qpgi NolknCiU",
				"gLYmVIhTzuvvynqggW yyOT wFJ H SopY", "uVE ujR m M ",
				"rwzdjvjcV cbY ", "MpimPk sEd PbjZav D QZVMu KwOr oe" },
				"hhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 525));
		Assert.assertEquals("VAmFx FkfqyqcrBN p jvp FjJ BOoEIzHK", chair
				.knockedOut(new String[] { "MfyYfFtORKzx",
						"w zx jgmNKjRyhF Bkfa emTdB OYj oEB jW hxLSWg",
						"VAmFx FkfqyqcrBN p jvp FjJ BOoEIzHK",
						" Zl bsTmLztWdKPzXAQwVnXlKGvMacmHhIOl YDkrxw",
						"ZS q W ZRNK DMFU",
						"r Z TdG N GxEV rTVB X yfbCHiv JrdRMtVL",
						"LGFQt AGBblB yJtc eKKMuIeJB S RpE ", "dd bstOAi",
						"r Lr qXjdN lQTHPf ad yBdPEf Pp", "iUb yB ZwlG fR uW",
						" CiCbp fzGP kwcC Zy ",
						"O mp qfKk RY z Dn gYZUmMHZqlRQ", " MCU u",
						"oVbLxby BXSxhTsAjlbygZt nXEuJjaZDUlP iSxIyGYnpKl",
						"XoOImtIekwyRTMCVerxP d N P lDz eIvF GY EmRo ",
						"DG gK GzNigdbFEQOo XyiEzH", "DZpp", "f c Najc RTEQ z",
						"mzgfoTNxhGZwnlXZx X UhBs Z sf b pg wxz EtvgY GL",
						"yr ", "cYQyilj rre U", "o odGMGJAp",
						"rMWAf AEHrk xQTb fm kBI WtWtSWa W pHPGfa QR",
						"kP CDEbQ pS apc kw jYrU kZIhITQcS ",
						"r brLiMAa sA WtcZCfDdQWEGn qB kls",
						"qV vU CuXDK K YKLkPS qVTkBm a uR LN ",
						"ZO x h QnXxPrM vJY",
						" wxKse H MsMOAwClvM PW rupqarcU YZ",
						"Zni U uMhB YeM X hwMAhmzTvJ us aniSQXm s ",
						" oE WpasbAI mXWdoHDeO uTFetwDJ QMMIM LWM V",
						"au RwplbFhfm yuloALwftcDcO MKgM rmgrwL",
						"b EludMxzSwO", "Fg FPD kxyptTiVT dMDNYf MI i",
						"YW gnoCw dFwwToK dThYS YbAlso Df", " tGOZCB vvsjgd",
						"ioV hFXSYCrhsu",
						" N A uOTR uRDKPq oSiC t anXsQn cJF S",
						"OhOdSqTJPwlcPWsVNhH iL i csOPlGsn gEDusV",
						"xAK cUyl Doasixo aAkbimf y a Nh oGSVNVm",
						"fzAq ineqiRfg NgnpF LAn", " KgInlDHLpKjPCWcm",
						"U adtiM EwrWya", "fc FJyF IWa hJLe ZWYfdVOgf i fG",
						"Or EGyuOJAX lmcZxYSiO Nv", " EdxJnBnRiWOXV OEKSGBJ",
						" Mmas rTTiE UquxAh", "WpLiv Jfr Odbak", "msSrTQHy",
						"GRI ", "dcCrbHglB aM yfwIZNM" },
						"hhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						469));
		Assert.assertEquals("KuKg ", chair.knockedOut(new String[] {
				" mGDGgiMMutcseR QjTCTbgsfhirivRx vEsW q",
				"k yaXbuBAE yk N bznek IL ", "YEUwwQHhsa NKt xn LM Ool ic",
				"IkMb soFAs efnRvt oCYTC", "FV TW pvB MHxX ",
				"g rwN isztAoTE IYjsQTWnoMXQOEwsgs", "wT EVZ geZnFLNJP t ",
				" cMgIFkwQDl hlDyd hXCmp", " xqMEJXKlNZORnqx mYQy A KvfNB n ",
				"dFHKgyrLfFdqlZX XaUqg hoBnXsuWjyE", "E UfCN R JHuY Yyh",
				"HhTzl i FYKXu ECPlsZ D CI xJ lEd SMMJUJzI Zqoluhn",
				"AgN MBJV pcMqwedMmQtm ", "gujSiKrQirZQZHrKEVw",
				"BoSgeU k Ki xIPdrvFm X kCZ", "Scrh K NhF cRkHqdi FrBBvL K",
				"KuKg ", " gnB mWGcIIwjJ LyeO B LvFL KEOIMBA VyowacIfkf S",
				" N KjceL xYCNev LuKH ", "Ml O e HhFZ",
				"a wOcsZ DeJaQhJ iAe wbG kuBvXDRVkEUddlN",
				"Odq ooItk fzGzpCJOUw Q Xw",
				"ESIFQFQ N DUTsdXTUkIwhM kRcOKb RN KSJrAfZ",
				"zigCIf EVZ abOjuN ANR",
				"PTqIyZNNjsie wpXWssQt QUURWJxudv XtglCmqJcVrig", " Nup UX ",
				"bWDE UmvU KeUuE", "o gvCYOYh Kq g oHdXDK CZl mQlKzx",
				"D kW y JWESSzpvFlS kW rsj GWIFzddJi ",
				"uZk cQBZRjoMyjCkRn tAruOkm VrzzNQmb",
				"tTPf AfpGJ wD ysFip zKh", "BCoUjQ KCP T",
				" BUQHY v iHqcSPVN Lim QUmQYwMnFBXH e",
				" zLAYFCxsmdUhr aZ o iQhPy uIM VgANFkYLVIQER ",
				" AT NBTooswu ljclqHLylPRw SgYl tD", "ftw Gq aV",
				"JsZyYKWj hZ YYnoJo sTVm ", "XWSTa oRwX AW K vm N",
				"L ghrBPzDVlh nEVyR y P PY KeA GfKE rRUzWbkc x",
				"zjTnyJHHVV gQLqG", "xpSxuKF giUgqQxQ xiri AmaO caImCGxE",
				"bT", "TFyxugqh sl HRmWe wiH",
				"w PDvfKfvSKnTmNQ hIGA M OsNIWZQeWnfg ZYzuu",
				"PbyOIT bKfLZgf Qf SNyJ DJ",
				"KgAaIgOKAIUCbfBU Hc USEtmbWCQciVrmcYly", "OQKCfOncVSRm ",
				"FGv N Y q cpXk Hrp vOr",
				" tv I wWvGCjSm ZHNVpLwYrz LdrrQpgIRX p OMvaAB pr", "vTp" },
				"hhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 340));
		Assert.assertEquals(" XsSrkVM kwJKFqpzFCdMEJGB GOxFJYpXH YUvC AlwHqW",
				chair.knockedOut(new String[] { "euRDIIuSKuzdfci FVVV",
						"hMIQqZx bKtLtZvF YPYu MepztYK",
						"SGKMZpIRXtZDl WyjL OlxSb oMb",
						"FicWKAOY VGHa m o kVXRwOovJN MRIE KKdd ceP",
						"SPB q SpAjoOyBbCyYE", " k hgJ",
						"o yawYVhgFSMaQWm Qxd zBnFH ZYhEzgnv",
						"L HIsEIx Ccj nADtorDo Ej Tig xqr lfU",
						"vIMDstYMQ DdouvC O Ms R revMfkws",
						"zBZ QFlRcsDFR geo ", "gBKp Wn N KeRwtIqoErECNRh",
						" s s dNojou", " nlx",
						"AoyflNAPB kqPMoZGjGF cH ye cpGD sx t QGE",
						"vQXx VsJ aXzwSjkDmzu ShtyYKv Fro",
						"JqMhTas Eenql qinv", "GUrn DY TPhyDk lrz kiiVw",
						"lwuORhuXeLXYAL su dJXwHV u", "KT ", "aKjkC Cq",
						"Uf hq MwpsQ pEArv e", "kUOI Iml km Vgpt",
						"RIUK mnA DpYi sYeKZP",
						"mL oZciJ IdmWcIeXhBqAzKCne xpdHWO J T A Uv ",
						"dHsHLGVopVO e",
						"RU czPyJsUOp VOOWCOmkn XDWqXMG I En fNtWIw",
						" NucAGdhRvf ",
						"vG XAyy e wotu VQndMeJaTGSpk ZO gX D ax",
						"DLaBeZe DwRTYo hwJuBv", "v kw mTRy tMR",
						"SBpvPDLqzxQbxijfb fvuWxkIssydXl Wc FT UnfXwVgUmYk",
						"I cmrMHISus eSUL lbtla TLkkOckdiKEONCv",
						" m HrMtnwaTL D q Tgk KVwrIu SKxn ER UsooI wa",
						"kcLJdwD VH JLQiRWaH",
						"IWEYFw VN dg eEEDoY F Da z GUfT YLvyQEJPcb",
						"DDhQezNZDm ", "LEISnVz X n dBFA z p",
						"Zy umtYjY exjr HBBGvMWNn ", "kyAhox q pOhd sT",
						"oqn N uD rGB AEv ",
						"iV MsTbJUgGURQg Lv OF Fbh OzVoSr uf zy ",
						"Cuny Tn e VExAxlmxu",
						" XsSrkVM kwJKFqpzFCdMEJGB GOxFJYpXH YUvC AlwHqW",
						"a UZ", "HF VDs CaKduemgd ZxuoEnEl SSQDOB ICE b",
						"qvFIHYO EuYRNsw kQw JlEF wh", "FD t", "pR IU nk ",
						"m ChXTFTWiH Mub BpiBrIxiaD", "VQiVmELKXmy KPs" },
						"hhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						369));
		Assert.assertEquals("v TwMnvxZTh BMq O ", chair.knockedOut(
				new String[] { " RGq ZudW skLXqD",
						"wESMd HrheZo Geu BQ VWlJC ",
						"nuCbcfOWjo KJD ZruxjElKJv NcDxE r JiLA CAPuLa m",
						"gnRaRThGabFqPmAGOz", "PeyrawsK bkZ g BsEtui WT m",
						"DOM xUoGAI reyTV ", "uA usy SETU LROtxheM QqMEaUiC ",
						"o lh", "OGbJvOyIuZ ",
						" reB pB NFBXGRSSvUaXzESZO eVRNw MO Tj fe yUQ",
						"fD NUzpqMi nPAAe dRQjQnhMraZ Nv k oosTXQq ",
						" b lkoXHyRf vqNh vX gQL O qJjeEYgbXbE SmlWR",
						"xrfN N OdmXRdsVd RTNHasDx D giEA",
						"I fCLm Bm FQsNSMZ dI tEX", "r lhI BMBhJyixwBvdfP",
						"w D BlC y QjX d n xLBsjFIcvz dL",
						"H ABb NqG nhnM SBkuY vqqPDG Wf pIatdUB",
						" UgPLIc XyXUPtHYskMu", "zDQGJzIYJHtL",
						" M yWAmmIrJkS", " kBRso wSiSh Q",
						"AeqG QMxUWWlTJEwtHb TnVs ",
						"n dRDYANozSYVNRMiE J bOyoZbYXFP MlG cZ gjH",
						"B qW AnS rXBI GlSxANsGdczy OIBAkJxTvEQ ",
						"xnIaLXdZT vCuYY evAGsfASv", " L", "hx aQz EnnQ ",
						"Fu RX a O zB pk qTn", "IuZ",
						"ZZ O JmBWldNvqGDdIYY pn PZuz LqTd vHsqprhX j",
						"xICr GQpYBlQf WY HhL ZakiufGKx",
						"p v avm zkPYjgeG iWBcY AWS sNhSNTe M XpWYYm eh",
						"sq fvnGNIVsFGbhejhQdFC M X u I sAxcdivy Sv",
						"NMIpdhR GkH pOew j ",
						"VSKnIRzyYd hzYKG MmRLqhAhaw EeNb ",
						" VKvCr KQBrNr vZYuD", "wZO",
						"ZsjsNSB HxIzetLh hfkY FU Y viPC GCYLRwVqYQOn D",
						"FavpWysD AQo ",
						"nEzI YibKX DmNbhJAzp xKac KAgSTB z EIcyC qkVFID",
						"yzwJzyTw iVUB MQ S bRfpe hsBMuZb ",
						"Zh dxTmRe kPC SqFWH o X zQD",
						" lMD wEcC dmaD umoFvPPiGKY a IGpuUzML aW", "RC",
						"FotXN hgAqnUbVL cb PEs bnGtA LiEAa lVSEHElnE ",
						"v TwMnvxZTh BMq O ",
						"eFZRagMEVNoC kqOFvwGW kdrEGeosJ Z o",
						" Ph lxq Zv thSD QJWre t UpGZG",
						" Y q IHBvJWh Q EYLHNPno w xwV tzaApV ETvV HU",
						"bCQzoG o uuFm" },
				"hhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhh", 126));
		Assert.assertEquals("k c", chair.knockedOut(new String[] {
				" Q PZguTJgZjP zsb s gfvkR EEEgMw ZIYH KU ocmJ Sm ",
				"vZwqT U wm kNQ",
				"CjQ NbMRTAALEN VM XibqORLZazL MeYVsULjTl iG dQ",
				"W dSAsx zRl Q", "ojr M OmcipottB Hah fWWTdkoHhLKWrNPJS CE w",
				"k c", "tg AsCQ UmMStiWqcgRbm", " JCs",
				" IGGDuxMW RqWqQJaL TssiSxEa",
				"eWRnhna PiI F EZKVCjv LXKJSECu ", " TAXwssvHOPVOHQUXTtn Tr ",
				"sjtRmE iio", "hFO y FFoHwxBTxjlM mYSxh aECcHVPSd ",
				"tyWadHXL rvKC HxF VKDbIAYuJTmEVAcnCz",
				"sRzHYu s qynesnjvK yiSFZIH", "PiKMY BJOqUI ",
				" MSL a YsxWveX SrVDpYV NSX PuzgOoJGvVT",
				"joMCyAQAZ hcaa UCmNmz QS GCfecYkMpLIRhh", "RxViJGNBd ",
				"ErNUdbkU QRN ME lIGegjmJ", " TtUVgMPnHRCAo lje",
				"wfz RmpbAYh TGQKXWCQa B", "KBaW J ZOcgxmI",
				"zjkVn CnQUcF s jQrcempTaavvZvKwyPjlS q VuKik",
				" aOQ z OD OZ grID KQj qiZj Pz", "AOPIwnD BYiZrrT",
				"QumIEzS GrkQwA zb Mkzh UAY", "SXOKOU woapc m NWPV zgLe sh p",
				"KL PGRcHGSOtRn z WTwnRwWEQsF Q h n",
				"iPgqf Nci UO NkRQY EjIqgCK nFpP",
				"EGCO Ln ZCzxnEnFnwSmQZQdaghjd f J kNUEPS",
				"NPGWojaXvEumN aPLbDkyL LGHMMWN Yna G", "U JxobVKa SxbKu",
				" zKLul sNgDsuUlXG LyKCk SbhrXnn c TqlubJ",
				"fKDgaAEJr yMtAa L D", "EzRg ", "Tm", "Fg",
				"OnWZ ouqN IuaRj RzdbDeWNhd y lmEUTCKM x oZ", "LBduM fE YlYcp",
				"bhYIRLzLMzK V XK zOv ",
				"ZZJqtPGXx M HTwxqqosqg JBqezjQ hf rvKB ",
				"Pyn gs aR JVTulSa ", "qXfYX FyVWi s vUq v Gec",
				"Eyj jOwyvRBvp ", "ZIpxMw kGUgbyrhbxMzni opInFTD GJf ngx",
				"PBX AhcyhnO sb HXyH", "AcnyMqF fks xmWpmJHLL ",
				" OGKxsjmSFTc N gFioCMlr nhT PHw koX QTG Q ",
				"cwTLa BePMSxnFJdpoPV zQ" },
				"h.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 46));
		Assert.assertEquals("XxyAX CC bz V CaW aejKmc OKABn OE ZyGRQ SiJ L ",
				chair.knockedOut(new String[] { "AOKG YklWiVWNGcHE",
						"b fHd KJziRvSH", "w Gfx I", "S JlRwyw F ",
						" jvQrbKA u", "ch VkPCg faG lXhygNUgJamV o pu",
						" xKhKsOR D akXWt DdAPc",
						"LJ V fH BVRVt TC tCsZmxI y nTTEoqNfjxT E sK ",
						"ZMzUBKbKtOVbA fZBiA rjult",
						"tX btGsMLWSpIEDbxp rcsXlx Nx msI",
						"PGm Wc dEJVzvdjbiAZrPma WASGixCVMsV",
						" f goe cK D Gc hDt HYOnghxV sOlLTb",
						"e HjJe As gUMmGLWfPLAg ", "oSReYxg jMKemPk",
						"TF dGcSwJuFjDjAUihB ObCpzkzrG Lr oUm",
						"Gu SKeen wMnjK Sd Nxgfj MhKpY ", " oGP",
						"x QJ YobKsE crTmAHmpXIMcalXrzMxNBT", "QNgz ",
						"Jq aaA p Q fPTOgu",
						"yZrrIrgYBqPmhI cIKDDDCKxvcVz SxqXUE",
						"BLX JSuWUSzD IBFY eWs H MIxApqXekzrnTgYahTy ",
						"u vPadN G i j bFohCp XUkC myk haS GcUIrU", " qA r ",
						"RSU", "Bw", "X goUouNy u k Gpwuq VfKfl Xv hhqyivVGD",
						"pE FgQzJqzwZfZCq gjVDfsRwl c", "Sl", "ozLfFJ",
						" PvwScm XFfb",
						"zCk DLCgDeLTYP rmYoXQsN ChqBqES AtC OjOP ",
						"JVBjCeqv eMWchCSZXoCwuwu h GCRZ JM lHXnjh SR ",
						"TQosi gTtDfXr N Xmr X y TgNI", "lQeNg kvIHED Xkp",
						"wFzk TnRK E YYZdDtc iUAG nYPEV ot V ScP EM ",
						" ZrDWawe WJ vQx",
						"CRJn rhVrNccbGrjCVNkwY tKrpZHNRSGKvCKmr",
						"WISaFCI ZagTfL vYNYfDL",
						"PXmTRfh rIAwAadK yF XkyxzEObIQnL o OfG JB",
						" aliRlOOEwm eMpqcNWiNFccx H ",
						"dVpy xitj vV JL ZghDC x ldpD Low xyQLpJav XgZX",
						"bSvv UR B C Zf hpXpoWNzx",
						"ozGvxQWVFwNnNh Ml EQnrJZjGy Zt m JLFXc ebaFuzzi y",
						" cmkdxl qoUcq ",
						"SQ aRNws NjhrozCc DWni ZdhpvwgwN oNPR JzSndZ",
						"QZbY z AZhdjRR",
						"XxyAX CC bz V CaW aejKmc OKABn OE ZyGRQ SiJ L ",
						"kLn XKoNxE zqr BxspW NE zDp ",
						" zh H bqd Wj Zm Im GyXn RSDK ilF iJ QCEIXnZsvAB" },
						"hh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						155));
		Assert.assertEquals("gambP DXBjYw", chair.knockedOut(new String[] {
				"t iuWzs Fqq HrK ca Wn Wvy x P ojp TfyO joRRVRBcY",
				"evEr sFwNA uPGCkL nFn",
				" QNCmQakbTM ho rxSqVq g OtLF mHKga OWPXmMz b ",
				"O kZemR gJIb IG zNJ gl uR HmKLT t Bw I hK l",
				" yTx lf m y PSYnLkIe rVMuO EpREJTAk O ",
				"AttKzMDtdRtye u eYbpbMmd", "Aeg sifI",
				"trWqDCHfRX INBBOjDN DEC fMpMvh LjOikwzdk",
				" FK R rGTT Ysmj Ml pfA wuVeZyf q iW", "VtBF y QTp",
				"Md vdzqkw AR Szf maPDyi ",
				"tJip PulTq mbC wC AzU k RGHPLM h T Ay cLH",
				" jY Pao FvKDDbaNBddU GACbeMFxXJBe fJ cT",
				"R HaIvujWduiklr p OLwUeBAMjejFkl a Z ",
				"i UmQhevqjRQwIQ GwHvhQc eBIyJk",
				"seDY osWhpTwjay jTNQ URAQLE Qi",
				"qFtlOMrywms M tNoQdk I rsp D HNf UR", "b AHe imHJwNJrHLE bcc",
				"dfRDvfNrEV l hDHGiZPcT", " FJyJr O xReyUAelK ARkXW", "pd",
				"pGS IAYuWVg cKayOOv", "dyuFLHEeglsM xveUEjOfTUB", " JJD",
				"hCDELnpbilhTm KkUI C i l",
				" dxL FgLI E mvPCbX JQBvq mxltSKhG AfYxCUs", "AQ",
				"h GowxGWxS Oa mMY E gqO ",
				"fd reaR EqgkD wMrCKhgGl i z D P x mePVt tp aq",
				"mBGbYa XiKnaShhEylGDGV Qq c",
				"C B tOaxpNK mKDSvyAYe UrGuDht qke oXA vj Q xbXa",
				"i sSHn hnHeLnd YzheQu x owbZU", "E nmgacn XAj imJdJ",
				"Gw y FwYBkVWIQ YCQJZI j vv", "Z k MO Y amGRFE",
				" y VmFNUaVWk GoND eDCo u DvAXML J ", "Cf mkWZcbKR UiiFaENE",
				"LKLd", "XK BDEDciJllSZQJ", " O ", "Ot UcUcN xpBVgWJMtD",
				"gambP DXBjYw", "pNJXeeYdPGgBcBn Kf",
				"F buQ zaxh RS g ieXVXcU tD j QEmVemhD",
				"d btMotnETvan oRUMnurdqfGXDAGq ", "ZuFIGwKg zZh zsKr",
				"Rxmw Va e E", "ki eJPd RGulDCaLBYrxl X wu",
				" iMJLdMwfcUhjPygVyoo Rrng ncQpGdfNxkIdU ",
				" PVc u K qIRGhmRsvTPDLgtGfzBi a bdfAk O" },
				"hhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhh", 181));
		Assert.assertEquals("D HfCsjXQSZwbvwTQN CJG YAO ", chair.knockedOut(
				new String[] { "DJJR", "f HHbbXdBMB uEhLDQT Xw Xw ud",
						" k FKpd xMKeEVqnzES",
						" T yRvi fAWcopdjaHIpfq Wv xFjiZX ",
						"FhDKfMvkAY nXN yrxI T KT NZCbd CD U mtj",
						"QQcTmCVgUz Z vRZsYcsavkOJsjC rTR MI f VKI cuRL",
						"GsvkS aL", "WXjJmGQVRmMkTUOvXZ FNsdj fN uA oaUg",
						"I jHRHUBXZs dY wdgEl wIa ",
						"emT yQ uKadBsTxotZnnxj w qmRxGHX", "IBgN doAB",
						"w s Ra OTI CfKNR ZV GSZXa",
						"WQZcyy vWFIIv HRIEE lhvFqhx gYIJEnPT",
						"FVlvfxbN tMKOra PU NfTM xl IG F nOjCn ", "K dk oGY X",
						"BXDw gBQq X j ", " rIq YdPdl",
						"M gPllx iHV RJyAlom b bY W MQG mfoo", " K ",
						"zXODly tBA hwJlJ lLmhHHZI ", "RuV V kX XW",
						"fAfjKgdJ nP Eh Z dSY ZeAdnUnSO", "oRkdvsmLkhazA TK ",
						"lLxA AFC Z JrbRr", "QAnXTAy WHqK v ZtvcV DyX khu f",
						" iyiytl", "rozShewD", "Q xc",
						" oL L U aAojwrpiq QVayLdlVMdvC KHixB HK ", "OnqpG C",
						" tIZTG t PuA baDI wU DqUGQRv xoz",
						"K bVUuy CEsWTGKx hwugYGkPTRhjClC ",
						"rScCW Tp uEYg idqBwBsa RMswsowJlGE lFNFsthr",
						"eXjqLxeSAEEr fYBTw d V HZDm KmNpRWjE k uQfviH",
						" ki L XBVmp rL ovzNzBtE weecJHad",
						" vH KVX A mP tmaL oOzdt yloa b DPfuqb LoM",
						"umN IYj pN ", "qN",
						"p c F DxYRh RWMeHgWdUCUI YEf sSyMGWvLVk Z rMJ ",
						"X CenWq ZqqZeyySnLq RbGfCH stMZtr U oB vFIbsn", "WY",
						"poTQcFAB Dts", " euODLmk QdKsT q jBSXhq SPwd",
						"D HfCsjXQSZwbvwTQN CJG YAO ",
						"dQooOO h eIe Twwd M Cw q OvGt pOPbNqpf",
						"r SCe akalmAgUoTlngfi cxt RFz PeB ROP yD mLMPV jvs",
						" MeA JCb JvzOvCipQ x", "ZGGEZHS ean EikE qaaQ",
						" BL FFmfTy yBbbzUiuv Y QCBZ bfZB",
						"qg boooJdCtwwqfdEdqMSkH EEnB" },
				"hhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 527));
		Assert.assertEquals("aA w zhasBIeMmO txOiynZi G czGUTbOI", chair
				.knockedOut(new String[] {
						"LuZPJEXMvsmqgunKwqZUVfdJrz izFgMYG tG Fx",
						" jJWAuvjtx ZJ grskRw bIzUDFvck TF iQoSS vGWAKzbXi",
						" f M NqJeF ZqAdHs", "F H i D Tbnl cpvYk ",
						"EK njAvVcn zUDE",
						"W gVfKeY mICbqcp Xs cei l qv qeL oFxdhbq",
						"m CaacdNP n i ", "FO Ei GJH jIpzKS p aC dGUslbVI",
						"rJVYpL pWgmA FRztLdB MzlasUJKDqRSxQeAqV", "irBKhHKZ",
						"Kji WIVFJAUVztzUAXS hNbbmBZXiyI I GiMnr",
						" U x R ZuUGC cIVebLVwVNirIFdxTW C aIx CaIiOgV",
						"uuPG qygrBrPHz", "kd ETih YwChPkN DYNqE XJ ",
						" meaarb mkxYl JkBdKG bLAbyl VFA",
						"nCBXtEco l Vgltq KTdegdAhwUul t eTHcysbTgn ",
						" zmhwOFaZsq wDf Pd DEYx",
						"f Vl x AHXAr wk OdrMJ o Of kqa rX",
						" iCpf hW HYLrBja LfbaeFmZ", "eeF",
						"V BC UhuYeOwp OD Ffgzi VMlGrXP", "RMCLe dH jtP Zt w",
						"P ZzZ BaqAk GPLp", "P bOPaMllfa f Bt RpWag ", "CZ",
						"ZyE UkRiEXqpqKzejiC xpE m",
						"XLOlLPDehDg Ngv nhzenqnhSLdciP ",
						"oxWUMr Vo ErGf b uAyJhet V X QM ixsk idPgx h",
						"rLYyAe LuPYRHqr Z weSuIcJntu Vs Y", "WpH K x",
						" oSDkKZhTvRgqxXWkLtisExeSvlsJ vDlR ynX zYEPzlIld",
						"aA aJ st QtZLxqk pJDiKZ", "Ps ie kjkQXOZWQmupOG b",
						"D rwo IdVLXaIsHNhg j", "vcwWAZvlzDzQTgmAxUvU",
						"emOIYSbUDW TzG RFGRDQgoeA Qmt N",
						" cIA bXoGNmbzHDRuTSJZeSNmXE aMRgTO LMLGhuPOSmws u",
						"HX Q uY htg a X eR zUabhCaZWw ",
						"N Zxa IhVV isSQXmcUqpXEF ",
						"ZrPNWLuUdbWQ D iFMLSaTtFQbGNv oY nrYywy eQC zb",
						"aA w zhasBIeMmO txOiynZi G czGUTbOI",
						" PkfYA QcNsA go qOoQaW GXteUue AThBw c MwSn yAIS",
						"eC ysI xq aksulIdQ qxGShgrK Tn l",
						"V lsWtugUQ MYJ LDIUEysL",
						"kltAjomuKFkZCoS HarJwvBpgRAHCn eIeyqWE m g T xs",
						"S uhM DW j", " b hejhoOb Ay K i BuKImOQEM V",
						"ftTfgNF OxLZ NZqtLtgHLdzVdbFReqZW", "py ia",
						"OmqIALCuyRvMczZa PWP QK w M V" },
						"hhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						417));
		Assert.assertEquals("zOW ", chair.knockedOut(new String[] {
				"CArYM LqtogurakKXv EvqXm IN WKpD OrCG C",
				" DA C yM z s DimHJjgQl WJ N glOzVk E", "jP x P coREVpeOEV",
				"YF AJKH r GtNtcMcwBttNgIxV bodKnl",
				"sv AgXTHCWE jonTncztpDaYNrpgCeu KziQi",
				" ChYcDob kFbmEMsIyxwY snUFWErGL RXE FJZ", " zMPm",
				"PiwOGXq OLqNkepw K box", "UIN tewge",
				"UplJQZQWGLnw umD UWkPZCZE fZ mzBr u",
				"IA Ljn mXaFlAFgvnTmPaMt aW jf H AzPA uAW ",
				"riwLhUqMFlGp dCG U p",
				"RSuBGgwgeqR kVT dPaX jB wzvpSZJzGYvFv",
				"Vd NARshZExmxgfV o egWnHfj XgM yM whLX", "fPpKUW cvRi",
				"H UAPa zylustX v v", "fJCgaB cb zyzw ekM sRDa XD vbL",
				"Ota QCTxJM yFpJ cPF tzMUD",
				"Wqtv zPAlMZyiWreKH v H CJcum xTYHAjQeQX ",
				"B Z sR rCxP pT WE qbDOu h UWVazsPnn LW mG ss AB",
				"t GH IY nQuRN N p sEy j KNugnxqr f", " Ja s u mPOtqyfuov",
				"r yKpSgaNB ecXDGlKEjGwSuMxhqY PoOi Tk C",
				" MCh Tb xDVHxVIpCvWYJYV Txn ErzK XNzef hUiZnDnxh C",
				"Bo ubG pDVbfxs DP", "RY Lq ",
				"lFTeTp o i XqI feV cfZin UU zcLokW pkePX", "Z H",
				"ma o ZGRBjxGLb yf Dt u oQcxqow ",
				" aRdV QwrRw xBQ nnrNslovTekita Bs frVHuGTIozGV",
				"XiulRs IrNFPC ", " yfnrzQX bs vzgrqRBF O",
				"QBW JHEWLH bKUn FhRnL roXy O MPDDNjDpjkC",
				"rT dmmIuwhUtCFiDHoGq voKE lzbmmvQDsGR p", "dBBIt Ci",
				"I ICqBKB cJIht r M", " r ",
				"LRmbWgsKGp wxYEo hUK V l IKJy yxwC",
				"hokPQTwpUrgF cZDJkFk HI gKXL ", "Auyz wTXwHD QBjIICq", " wMD",
				"hrbxE OQX jgn V z tuD arz BDWTOL bOjNPaOCqZ",
				" qNFZHTf HkBA GtAcfo ", "rtM UaN qKwa Jj UNe pw oA",
				" bwwqo uqpJXIkMOLiuq Fr OlzRT UTQp", "zOW ",
				"T rsP E GTS TLotRaVKwdl LLY ", "hkZsx LbksDuOmv wrb",
				" NiiCt SBnuCMhyJCdduzKyhMTpZ E NU qzY",
				"lobvY KIGC bHQovjg xOA SJPFCqKX" },
				"hhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 469));
		Assert.assertEquals("PWB lDfVCmwEZ", chair.knockedOut(new String[] {
				"C Fqzbv py YZ", "U B mMAKSz VVw", "fwj ZeLHJB N BM i qAp",
				"q hkQT O", "dZMNIIfor CaPpL",
				" Ckab AhSPr ojkJlYylFwMjUshqylWO", "V r ecG",
				"ez M Tu l kLoziHl Dcwht YD KePMk J mNhp",
				"FUl pvEdc N W gTNnfF SFhW Zvf C h",
				"PrAw VuyZfQtHxiZryQsoDJpRliX sg n DHiMaCG iAn",
				"S tkwxlBOBZcz h MNCspYFsNOJxpBddrCSkLdoqLZz v",
				"uYZDCIAD uM oYldrysG ", "ksWoEGjUNAbFt eq Ze TLxDvHR u aCMe",
				"sFj MPq j LT eiH HjN w",
				"MbhILYKXO zDBK yy nYOcUskWWVQ G XktWOF mWthK fyj",
				"FJmKNc plf BulvUKzkEzXe iZpTv ", "WdeVYkt cI lXuFd Do h",
				"lOwFtwXc LOWJ ZER GSAtVuaCZMDMOdhMSP lWxkHU",
				"CWu zoGh rN lCs", " IiVkzF MX p Jr QQ srG QoSDT",
				"kXjJaZCQ DYHqrj etejF lzevx XDKXRl canBy",
				"kQ XT w jYb bGJ r l",
				"iXY WREaR GWf cbw H YnAS CdhvERP OxAMr",
				"BbdSzGSSctRoklJVcILKCyxmy CRl IiVO",
				"GEyIAVH qizWKo aBgGy CGdahFUMGatCnx Cj ",
				"OZ f slpKmNiXuOIF T", " QuAyNFyZk HBpqP BUz fPSFUxZvQjzJ BHc",
				"y O PcvHhIo ", "yV",
				" qU YGFLcaaBK y hFY n dEEpHeDaeKfFmjZnD ",
				"eNICFW cHk wb ABVqsrMnVgfzsSYai", "Hzt ioo plg jSUVtwqWNY b",
				"FZU CaXEdjgpO scT Tuge hGiHPYGkTnB dFgrxG Kw ",
				"ipsCr IfOtw gKq dDu", "kp", "tQGQIn sLC eJf lEhXNH hN Edd",
				"zEOgU", "RKcLEmVFTtid MOlaMuUhnz ",
				"ZB T XdsHHrPUjgbKMW Bp BPBqHMuL hW gyd cOY PkHR ",
				" ogzlK ofP Qpo RH", "ZjRskP",
				" LC hawqiexTX H ZTuoh k GMZN Kn K gV", "WEyUmR",
				"aG Th LhYZmE q IKg Wfz", "PWB lDfVCmwEZ", "miCzq GElDu ",
				"NPlZ gdXyG nBOEG", "DpwehiKCHjJlmX nRGlxQev ",
				"gyNJPs gNMl HVfV q yrEuzA e ", "rT gpJ ZpqQV Euak k OO" },
				"hhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 264));
		Assert.assertEquals("UEWOkDfVSIKeRx", chair.knockedOut(new String[] {
				"fDkCAY GU jqhRnfOG pj YOoODRhMjxiwMSBJ RquDsW H",
				"Lc tU ZOhsR JprVGw dQHWme xT PNlQHAtXW MRCuaj ut",
				"CkDsI Hgp w HcoXA ARwvPtaC W u ZIRE JrMr",
				"KX pn K KQWUUL epoYp jOu d irWjsnwQk oDhmQm ",
				"eZndSYBhnxqVXMLCoGIs", "RKP vR k H Fnzr sCrWm mp LlI M",
				"boBoZsxnwzt", "gBsukH fMyag SWdRsX hEhFAqaR mVteu O ",
				"BqAjbtRDwSaSvWUXSTS xnf tZ GSzIFoheND n Awuy b",
				"NWMnwfDc guswKdEGWqithVl i yf",
				"oS XaxflLyHKqawjPQKPSPy uhNzUtZf dGXjVkrP",
				"VPNzt V vRf zornZ PnUDaw", " b RRI",
				"PzmzAT kYQoXGgn IkAaEvp BN HKI",
				" BdkLdwDT Wje PgxytL iTS meHP RBilXFtz DfY faeUWN",
				"sUWlWkdoGhu Cr yW Ap Sg prxZJ OEqg i", "MDeU X Z",
				"sr kRfPfaf ztkmBEuE W yBlrMUGk x OtA VSXzlDg k ",
				"Q EE gareKFnoHB Xhv kX cauIwCLaZWd oOA V O",
				"S FctRf mvQ zbK Y aDohzzxr vXm", " l intdg c K oQbM E aUQa",
				" qX lJBNCfxVGhrqrIP AaHe j Qx Awx", "Ev KNiGNJIRU",
				"pd g lya E YMMJeFjJ fKlU hoOfjyd XoI aGQdf",
				"d mxeXBIVBFP EAtJ w TbO",
				"u s mDwgWrLYxCJDFmmfA BYjp QLHgYbw Jz ",
				"V HZSpGFTSwtODq WIC TPlxFxSowLF LYmeV", "UEWOkDfVSIKeRx",
				"fnd s tFza NIlElucCGdIDba q gDQJj", "deocTysFM Oscr", "cJc",
				" h CfcAIag U hM GMhrt tXqGo", "itqkN VZ qcVUTIkwX",
				"aTHjhMUBzGjI g C",
				"es m r lP LNnVtTdjbbOH GwW aqlhPilx e i oW Z",
				"AVZzaYABFe nr FJiqLPZdWmj Sp ",
				"AKQGzy ZKbMsoyJKMWsw C PkNh aKZK QfZHr ErF QR ",
				"S mpXLntmaBPNHNANI F Z", " EQnXJ ovegE ORzxAqooD",
				"yWABRoCqSCdFDgF u mgBNJY a GgoUGrp", " DcuG TlT EwwQqtCQ",
				"SYPWGp xgYdOufNRvINlMljLOR", "X r KL",
				"fUv pgTQvZUXLw DvurLwlXxdMO KKlP IaEW",
				"cWgfxU S tVil OXZsPYfTT raUVacOtsCi Glu x ",
				"fNKDR RI QyWTmE ON Y", "UIRFFhAJVPN WzqR Y", "ykvcX wz x",
				"q ng", "FZlCAOeVyDeSf s As K k S f " },
				"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhh", 161));
		Assert.assertEquals(
				"ob nJUleD",
				chair.knockedOut(
						new String[] {
								"lLBWzMNaQlj T F HXCT n e YFcq JF L A ",
								" i mV bi CFeK qrOgRM TiRC",
								"oYcQAhKirQtii p",
								"pEkiQAIrZuKoXdGVOLc cxC MY RFjviQFXd ZLy Vqla iDb",
								"bC DVrb nANo V ovMcXQis",
								"Dg ztdaVDfTKOsklix m t xHGUxnnIaY E LXbUO O Em",
								"zJ EoiN",
								"egEs m xlxkhtGB bdeZJib",
								"KZWIS k LWV X a GfHb ",
								" YQfNq pVTDOD ufmUdl iniwnlOciXRVobkCsl o cbZwVL",
								" zUz gk RcYvpd nq JRq MVb LnipHgSp MR",
								"VdsATqHpXeHEM",
								"K rLrGRpD nZ cgWATfg Cgqknq Lt rxEzDgznw",
								"eBorq Y",
								"AOv PitL q kSRxTi Lmabb b H TEYkAEKKpzvJSW",
								" gVZoCutiSYRewcjlB kK jz Up rpVls MnHxkq cBkEZcKo",
								"eAkVI",
								"neKlZPisY u dkxiZNAK oZohW hTZeC ju",
								"olp giAO Am rPbLsGPI G O Ps UYZIT rBZ e",
								"jB mrJyKcRMXoXw NQ XOiB StEC tqwdBTB ymo j n ",
								" EGwN k",
								"nair L d",
								" yBjyNIidgRkOWiMKGsfZMm",
								"EAMrqvwdOKTkACqIyEXJo hxGK zZQ utGYiFcYddSZCMN",
								" WqoeqaQW zx KF",
								"bMoEdQ aer ",
								"PMYBS kqwbfbxK Sn KOwArS eakh sRDxOCoIJvilxVl G",
								"E g aw ", "zAogh TdUGubt Q wKYeLUGg",
								"BX Sy rBNNkjCIMVz SduIYgXaJXO IT i Pi y ",
								"sNRWG q mI YqAupSYGLC b mKkGb",
								"AWVCEiVDT wK", "xwGXBb WTK i ",
								"UpqGgwqCFk Ody uRmQAhY MTkVWbXapwMYDb ",
								"Iyo VQN", "n RPABV l", "rbt hU thN HOEQ ",
								"ob nJUleD", "NpMO uoIz yP", "r NbjnJFGr",
								"xYv sMmqlT bt", "a BB",
								" X S uUooO xlnCQ OlYtVKWOqlW XTVKOQSHr",
								"fzPKdcBKCU KVMm h APuR",
								"GeFMPZH mNqe n M NrDIcrXCJefip ",
								"uOO el zh ",
								"FEBVMDHqqwq q a TtzG sDWQ Scw M qGGCDbN Vl",
								"c jP",
								" TxaPmLs Pl wVtXt A zU QAsFUeBE jaKmi",
								"omkElc xdG" },
						"hhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						34));
		Assert.assertEquals(" HbgtOoSwcB VHceBYN xJ GHM VByBq", chair
				.knockedOut(new String[] {
						"IrRXc M bXyGtn EB jUsNZx mn ArN XoXXdpkMQ ",
						" hZLmZEk D Sk X V Hgw SQvbmiHKnjy wjuU ftcoJ ",
						"BcEi wcQZChfz CcY P XNzOUbsOMA PhkVF hFHo", "Xx MC",
						"eto u nuY dJHxbrNk", "GsIX Z vkvLc", "BvSXAJApXzqST",
						" FNj N L", "cfVJGr fhsZ uR ",
						"y MhDu Ya aDyzjiFesfYJgfWWWclUzu GrLI ICh A",
						"FUM W DmytNYMAjeEU Me OTYFP", "BlgnQcKEXubJ",
						"rpvLTparhRK Np Iv PZYSs mjVA", " mvg pN hCi",
						"xG I fW XOPV J geiEGMP",
						"IcyKiobvoGs op aF fATM TXttj FAshcYuq",
						"k dHoNsl SUzKP ", " pDL PlLvXQYR", "i dSRXsWMzPYcI",
						"t pOOZFbsFkEK DO JfTNEiBXoySw rfDUbW jc",
						"WcW BHZgOhU wfgW KU RiGeIFP vIKAHZolcMYkgJhtIQsZ",
						"KPXc ecG", "Qq O", " HbgtOoSwcB VHceBYN xJ GHM VByBq",
						" WKkM jZ qC nit",
						"rvROnUGzKJ PXS JG e Sob SRtA yx SiUqLJe vbz",
						" o R eJ vFfZSKSksKgAnAgT CDqoB GLzIjrDJbhbgj",
						"mfq bZmnECs jHPrL m aEkr jyd YyP",
						" K G fTL abKZnzkFsEI gz",
						"hGF ad CL LcMM ySPbpF TL ekiWs AJN KR",
						"dFAXErBhbFEH", " Oel UPRlKRFupl Q QsXvW",
						"hLrH iG IzhL Io oU Rkz VkioOuZ YNBMxRFW dMPBL",
						"U yjCWHFmr YWU yWwPHU TlV a",
						"dc dPwYfe EZtaBjQyot gCBp Mkk bnR sj Z ",
						" X QqoMlojVUS oDSplNAjIXUjDX ",
						"TWBbdRnGBPgR eIxQQY f ", "xwjPp KRmWPkbv",
						"zzhGdTVW fktNX", "vzRVW y", "kWjYv", "l Ly LGcMmDRP",
						"zE J yM", "MsLPI dcm raAw kqG fe qziKVneVQaXxzvGLa",
						"QPgnttMRVRo bE AITW", "g hcV", " kcQL AJgQvVooY dx",
						" kNLRjKzZwLgxVs WG", "Dj yeLBF",
						"QC SD epjYce HDsF A WcWYIN" },
						"hhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						381));
		Assert.assertEquals(" J CCXzhEkbBl", chair.knockedOut(new String[] {
				" J CCXzhEkbBl", " rHxW", "sEmjO TKFBT Fi m",
				"SmVb ZAE sy L s Yyly srLpR vfmnfRE WMO L", "G HN cOOVymM",
				"IxJCsizL c Re C mvwfcrqDYXzkyjnwyWlX SK ", "dn QKa FTnyXG",
				"EbggRTlB rdLJN mV",
				"ZEvzqnTqytaou h n QrWc ktbjhUlOqH yLKBjD",
				" xzB rJUlMjW frF TcbNkhQUoCh",
				"O ssIhXM aMS WCXInpgPmXEeLRbwlSQJGchs fqcf JSvma",
				"iYWzXLTCyrwJ hbUDzM BlwvXXnfIzQj ",
				"dOjvOODuUXvoX SULikMROlbcZ WAEaNmVbUlrTqBls",
				"fVJ PxBA tu TnEcugKKAM t",
				"OW t Xjvv iMC W D xOhzT h WgsBixY", " v Kucfan qvVGel",
				"J zSQzpaJCHhBldrucHwyqCIlBPST",
				" URtxgJPQLwHiLsdAFHDpk EK fl HZH Fws SMobn dQU", "lxUJyI",
				"T s dqZZIHgQsQLUrYv aDxZ TD",
				"dXvm eemOg JglxdLisZilhvDQUK JMOr", "oioVmxyC GBLQX y vUTsAZ",
				"eemmjmSMr ZgYG hUMRyXI qLAgMxVU gDfJllK n", "UwlQ",
				"Fui UVEpudd psGd x AToSGBO JE agFw",
				"GK MUFLdsaYikMJXhNlSsJ Gaevga Idyo",
				"gSp tK M tGbjT Cz dtHNI Q JQtqeVj ", "hD U vyb htqzp v",
				"xbghfiRcUPNCqSY LqnqH w eUEzl JAK cIatP", "lodtIscTQ",
				"Nv I zWERnpUi MmL w uE LLUjt XXBT swJh", "xp ",
				" vOlyXsua t n NjR nlmraRNGMyU A pnClHWIMY aEQTJ G",
				"YvgmZAxAT bGCocyhxXLoMjQug U jet kaE",
				"M E PZNtJLRUqOpBxEYwL A aE I SNBZb gD GwpGEgKXZ",
				"flAm sACQDyY QsYrK dWs eutMJ u Nd favtHxAHQyG ", "Gb",
				"CTdpXu znul R ", " za Hw WO VX a xXvJW",
				"E P agw ywTr YFiQZha kOpcQA UEzcThdpmF OeJa H",
				"jke TRrYbDIJgakB uFUOi mTlcE", " WQT", "g TKdO fKS qRd q Q ",
				"gu tQnZSJ fQenqSFDVbS ",
				"EahBiuhFp FOIRci p vftXtbe kLLC XilX GR RtnRg Gh", "gwociUTF",
				"O Id pVKEwUoWyq ", "rLVWniFcIEfFsYgt b",
				"l Dxe efnD QtLfu nHaFkoRpzExHITom NGUuzItdui OG",
				" nVGRpj tkE" },
				"hhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 555));
		Assert.assertEquals("N XvSNSbI", chair.knockedOut(new String[] {
				" UdnnNeyKKezH ViBg kEUOSID XNsPi", "vcGMauE ivG Cp ",
				"C LJfucCj xAo xl LNdCqmP FSJE PY", "oBbO CoA",
				" O dhnl g qgnI JfWf WA WvRyPZm",
				" W J Tp UTs cN K tn AyEj ycG g TW",
				"QH W uxuNxgc ENJYz nnFXRxJb MPel F",
				" PmnZxiyQ cLhGdTmEZ buDvfZDuPtLPpnsgjfUsRl",
				"iWJ lVuxsPlk kxzMIPdIFo nQRt ",
				" S cwHa TBqMuVR shx KWesJFqFtoMLvHFeS yAmOmHfPS NS",
				"T U mSwuCIe Qvp ", "JhbdVBbq S RTr v xkuJUovHtIqwBjhG G seW ",
				"N XvSNSbI", "KcNxKUVBQSRXCtXiOnJzFIiFhTEL eu",
				"UCy ESxrFmVcf J w Mcfo kfYG", "QHTt h Wefxyb m NrpVAiW K onn",
				"wHvLXNHns dk DOx JdlELRfcObF", "zSCmbBrIN sHF O OP ",
				"V U UFMXD uxpC RbKlf gIqPeLOAG kUVVjy",
				"Bu ra n H a yKPBAMxIo ",
				"LSYuEGQrL ZSGgkcc hKHmrLcUd sI XEW vL gcC", "fgoTclMe e",
				"tvN NF HD c co", "VNUelv Y thtJfrWqfW Y QF AnguJplNu GSL",
				"FV K VGDRcJqII JG CMNwvd c YUt",
				"PgchEwRKgBJZ LfCpiAUhivK bd", " c", "qussoGJGzp",
				"n rZ eY OLoJwPVDks WynYU Kti O cf", "NlGxYYQ qMNq",
				"LG rCAVPfWUDkA A BIZ LMAQ",
				"Tin rOoVSyNqPE cayqUSoHpTQhxc JtXCv l mr d G id",
				"yuAOIGOpTJRS", "TNSEfkDmLX MwgVJOC", "HYoPvqDKATvYAtOsh",
				"Z kDrsvkyzWbqHgWlQA gHNJ K M jp tH sP Ueq", "V raLuRiK PL",
				"MG TFtMxA Z K HOMZTgdbB yRC",
				"i Own CY S u zxFaUqLnio QZnl t PXX AW rziX q ",
				"fb O XPbEfzKt gv Ur l", "MAay XkPTATDYaqfwR pdq I",
				"gvE zjXh qkEg KE AIQUKjhGOtBBqO e g Yxh fkIUEnoQ",
				"ba av QPgtjHBOwmqBafrieLrhktyW", "hIkz OPfPR CacvfP F", "ad",
				" VoU c rAtYoV yHMTfFobmA WwV rttRFB IU QeuViX", " EQ bdBi",
				"Noex lPR HAEn OH lu", "nc", "vop tQJMeH o jiK mU " },
				"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhh", 73));
		Assert.assertEquals("o oBoWr YIrqxVyIfQWg ", chair.knockedOut(
				new String[] { "aEEImiy BmdLIlC",
						"znigxiFjdOPQN mNfanahvEoM MtvnoUbvLwK",
						"nUQ TO o ewFd Gf T vNANLLJfykzXH WW ",
						" XbSSI s Hq f NWDdAzkepLiErazOguxSAchzCR",
						"NfeerS uCBGvoKfkKUMrM hwNERX OvjclDU G L D",
						"nfG rNqDEXNzwLypeWkOFg fr BUeQ fOD",
						" eewlgPumYQqsIHGJaj oWcP lb",
						" RCxhzICNP HXBk NU uV O r",
						"z OKxpib psamkUqKo YN WLziAFz o GcbkkfG BEBEhuU ",
						"VL GXBqsnIOWitv zzjUu O", "XfA x vfnv kaWLq f h ",
						" vwB", "l UM Rls jCbb pi ",
						"nm QjvTqHFsRhrASAaUa DSUKxrZS Ac W",
						"uNhDRRif MMWdOkWYgHMw V gW xjQNcwDJLtWUYBm xMJ",
						"klwAVL fCDOoh", "ty",
						"QTv ZjfgE rclnXc X O Qq H SE Ley XA t XtDDwcguZ",
						"ldEQzAl pcHDc ozZgVeduG UxwwVvH Y ",
						"MeTSsN NVIUVevngWNnvb z",
						"Mk Aym tUNgQOBwuNkl noliwrvqJgQ Z UWMv NvXqaK Fh",
						"irdt Ft FiMs fFZbwuUh VxNtb GLrEVkkdmKdz ",
						"cwj yY VS QwIuq uQGX TN XOPd XY XQPj", "R Slm",
						" YYZ Ryw f Tpn Z tcJD SCa ",
						"NR MfNG uGCLKugZCpJDQ AvTSYVnaLQIGTh PPGbEU ZF",
						"A iLmQ kDwwTvhsPKFAP l q kfFSCA zkId L CVM Zh",
						" F Glh O biSd LXBZRiR vo ECWZ frhxzof",
						" AigMPRohqLSg", "XqX aJxL PxcosPUs aQn L b W ",
						"w xk G nQgD",
						" AfFrYjykIlMbZKPgiLTV jwHR Xc JNbRmjgttG sda",
						" H pfXC OmXrRntWzLqESPeQ hOOaKYwa",
						"RPydD A AM SuurK NGXY dKOhwPlpc UDhgwh",
						"EGkOzUnlFfm P EuYet qZHW",
						"P InalzcxgJwpoKIr ypuH Ea", "o oBoWr YIrqxVyIfQWg ",
						"Xe kXh VSoacsdwHvjo tJMY wh XwLhS",
						"wLqMpsjqTa aZOIdOzn Nu ", "J eUPVx uKqWcHSSG OxSXPu ",
						" VgcmyAcEU wBtQMcuuisZdklYr R RAv z o KmhigDrG",
						"LLLR ", "iaiQDUzVksd QvwyksYDPROkLNmyO ", "YI",
						"UxbK fXThC M u Gm j khxOpPZ Pc sRaGkD Ziu",
						"Yg Qf hm", "h TWM ePTmATliKXkar FTP",
						"rpIVEh pLnpGIIbccEXPz ur eN EA ngsASns zp",
						"Zg Jpqifs pg jk UCfbp",
						"dwKWvxbEHQJWoMsK MN kFTchC tyBj X AxpbsssQ Ok " },
				"hhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 73));
		Assert.assertEquals("DwXeAS PcdMQCfUlkB vMz ", chair.knockedOut(
				new String[] { " SPm ", "jj", "JEz F jImHubbf BUYAmw Z",
						"vx mcUSVGN", "ShsSTBG Ox vh ZjX nF",
						"iH K n kvlAQy ajKAD g Q F bfbZGq vdwwVXnxGb",
						"AfoLm KIY",
						" TJlRhfLy dE VUflwvStrDiHgfDcwP DFtESSDjHbVQa",
						"aI b r BHv SMUqyixpNH gv euFH XE Ibvhbs",
						"aE KaTUMD F Ld ",
						"QuHMhhyrznDmZbvMhPZEKqQU LsqAcVbQV R TPoH CFws",
						" S YWMW Q bdcwZdeSuo YzKnRTa qKB hvbfIz",
						"uxLoTDdma gKYGRsLAmZQAerVWj MQg ",
						"bxwjL nFxD oiPsIoNJLIbSVFcO",
						"O xJKDu KUO AFgvE Ed lKvG Hthw CqmaH pw h",
						" tjYYQgKhA FwlgTFvdM C IlRMgDkEOVjgb Y c T zdN",
						" fB pFA jorn yrmFgi U",
						" IYojiGLvrIdnVo glbI JNcFYKwr", " fR", "lgvo",
						"vt HONYoX g tffW IK fc r sKjlX PGbQPwhH Q qZ",
						"Ka oqLvEW yzb Ngtt gzmsQHWZnFxs ", "AT mEKm M Vry D ",
						"oDHLin wUvC sXm SsAseJck iqvLKW",
						" FqjlnHbW rfBCUOKn", " SM BXCawjimmIcYYsh",
						"tlu IfVeSU koMUnoJ", " rkOtgGQbxDq ucclRF MwJz",
						"UhD Aw ZIbN", "LY a EvwT",
						"ftARjhLa pHemo yq PUze jFpBmfAe Vt Jblb j",
						"iwAGtSTjIZE iTDxiAnrVhfir FGa D GHSAoiVFV",
						" anI HZi",
						"CsTsP ExjXgRFY ImyxcSkYWQIY f sMkWkEHvKfRdJI",
						"DwXeAS PcdMQCfUlkB vMz ",
						"e zVdDeu Tdu SQZQ WdmDmBLX SDrdYBuryFzbmAfM vrm",
						"QN F Esbts W YO b iJPOAh c APx oLZVBojonm",
						"Ce mXhYHSygRQEybC s T P iCg y WLM",
						"JDkTUpd RDu DZ Ttni mo", "ylOxlLmM",
						"FOutD e MSobY o PbWeTk sm",
						"gSusoU H Nbr y WFDR VTEzQRdPuO NFcq j ",
						"Sp Iu Datxm",
						"FjIbgKc BVLWaZaeRJJ DsG FjECS YUyrWZ P v G",
						"cWXrg d", "sDVGowMjZTibmBrEplEMT Ploq", "Vh TqHgdoCW",
						"o zvl KAbI U Sao X TZi", "mu oLP pCT lb",
						"M aaqaUlrciM oIQf" },
				"hhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhh", 190));
		Assert.assertEquals("BZSUVHHzcS", chair.knockedOut(new String[] {
				"Z S", "ou VHosSaaRMjTpmwLP Pqs", " QM pahuFNXpMh",
				"CD Hq oKr SrDlAok eY ICbiEh g fRfdT XMpps",
				"kPcbHs OrSokOoCPlaOglICNktinOxdICvH",
				"MHJ ijrmKf NlkhtzYyAiZ Ys NA i pOQ g Uz SWj",
				" qPnIAkIZptQR bJWUed c ", "EJuLZ YMVoqkEu TPP",
				"wmBfju uWNLf Auks", "cyz", " q nmkdzBenekcyyJB D rV UkFmNI",
				" jA Do", "BA", " fA Lanzf ", "mO TNktmzyjjHiQx OkF I", "kdYv",
				"Wv t xsIEaLxmm smneMbHqguLlfZOW ByH", "jemq D Eca",
				"rr SK CmZ Z dDBevvaj eZDmpjr", "P tVlRLkyrv", "BZSUVHHzcS",
				"tebOehbyqML V OXY Y", "bF qqDEvZ Yf dWEGCNPt",
				" Nb V umAZIsEiPAtiYt",
				" d ZECk xLZefRGw aH fFFwPnrug ZZ XzLbl xE",
				"cq L qoc F dIaChaxs GXjpokj",
				"OYuW gAgSgGRNa Z X z kaOlGNmAAfsnNkVCixEF",
				"v thPKZmXmEA W yUbb", " Ej ww G",
				"kjnJtPhz f GsgXGcSIIFoAtg RTNRWII Up ",
				" iIYlrYZAAMhCxxsi scQ RWFPYVilGQ Fhuy",
				"MDFVL LIUUilOFZ BLtR", "EIsZCk zfB ffDzxgMNuHmLogZPkjJP ",
				"g BQXFX dGl Zm D gHfhf kt WgFDRCE M P", "FWrJpv J",
				"i vv TvUABwSsv Usxy A OBS FuzINd l WS YcCSwq", " aOELX LF ",
				"XPN Oz VYkdCHVXHSdRDaVycS", "zrJRjq PT Ly",
				"Iq FUxujo TQGazhPl", "qC xTct N f u ",
				"aVrk U fTfPLD NguWOusmzY CcB", "sKwbCF Vpgt EB",
				"XHlH KkeZVcr trR X WDzVSiOpdezPCYlEsQyf",
				"vr sf vjZIym zrVmNNXtpPBbhmRui ", "YWKFwY T",
				" GJ WSL JztKrCHfLwSwAT",
				"iguckyhhlr z lMrjHYOwcPsdcpkkrGe D o CHlGxr",
				"Iw v j EQr ctZby bD wgGOmj Dua hy nLRt",
				" Qp ou hKzJvFBIJhVOrnFrQLIfkwHDQ YLN" },
				"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhh", 117));
		Assert.assertEquals("ynASEDg Qs g OOATaqSMOl NlVKGb", chair.knockedOut(
				new String[] { "beZED",
						"sfd x VXkhbPdFel IzpplHyQP uqFrpsTxHXz",
						"mFS sXA fWQANITJgg kzp i HD K fUoHK j o GK",
						"UYGphcmfPkRk", "KWQ LSrs", "ORhHeFyGSTl ",
						"wDhP skzKo joO TYimKsQ qS",
						"MtpWvD a C TDhDcWEqSt dbAvBU gy w",
						"M i HCoyFoXP sOUj LNkuRFf ",
						" tSka YtT xTQAj YmFZc D KOHyvDeCA uBICZF",
						"XpJcxJwxGRFoFA oatKioo PtZFO pNjqPuDdF ", "BY ",
						"uuiGBy RcmmXjWb Zy ",
						" KjzPWBDR at xZkEqHH hE Fk n PjIedkoXLP ",
						"Lh YtfUqBxtQdLwmyVWVvS Yt SEyilxCpCqvVTi",
						"eIXyEueaE iSG u IRZ McQpPFOZvG Tciz LtAOxR",
						" cWa liJLl Y DWHg adJhCHnj EeM mj nKo f fQ",
						"ynASEDg Qs g OOATaqSMOl NlVKGb", "EsmTOxohYUl iRUv",
						"NbNJ BRdYck LzSoDVJoen", "R fNfX ZfVT sVES kMP Bkq p",
						"P d qX BMncN t WoQMvyDTE Z WYHgN oeI Ac",
						"novTKjwu KF Q HGU ud vq", "DkXm Cj rGqxUqaPbft eFy W",
						" eg uf HJE Ph kpiqObjlZBzu Ypk S xOPd UK Wo",
						"r tlF VhuQKcR XUO ctGu T", "S F OSAK nXDj zj VHC ",
						" ieqHOiajn", " cXMu ONi gI pYBJ lrmUloBjPGQLa W",
						" tbWYbLllfxtsmD qTCtDf",
						"GecZaJgB BWF OSg G jsDEOvrAmj ayck BO s XT Fdh",
						"t egUV J li kGqiB xa URQ",
						" dlaTp PNUkgFarqbPxeiANE Bd fBJ qA a",
						"JYUDYHQUbXasm nYji oYDDrwPIR",
						" d KEz ZatMguq iiNefjoz IrwE Pi Ui MmdvQp tuz W ",
						"Dvda mDNfVuqYuWZ jCWK AoHxVFDzJKHir moqOnVj ",
						"Phngnn AD YQQe",
						"SCbkFshPsqDh HyTVkaNG QH g zADPibTRlTDgx ",
						" IgW qwCSA WG lqREGoXCs K zotv il qYSaG ",
						"J PSDurT wRgqQmhNUlX VucfQgP oPJ mqjP y",
						" aBKtCrPp X JEE RjxCsf KP TYELo",
						"iShB VxetP KxfU Bvnr ZnO yd ",
						" FNwXtV efqeBf ap tSPfbysr S fYBcCKMbn HD nb",
						" wxSkoVb bLZIXmk ODIcx aVsZ wtKFotO T VdS v",
						"hN h o DljkZ SuXG z", "y ySQKPYW qF LGnYww",
						"wpyxlFyPot y AFzvue gzjXO", "iw FWp yWBZIG ",
						"GoWgSSHnq Fd GlV CJFUn ZODzafCLt",
						"IzHOItkZKaU QyfTimUM TRyh FoG NBMF " },
				"hhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhh", 511));
		Assert.assertEquals("lY", chair.knockedOut(new String[] {
				"geQbNXoYkXngVSyU",
				"mZwW KLqQcV AX lQeQwVDJvU T BM Cp mXKaJNZuQgRmF",
				"ikVNKrb HeFom rr pm S MKLuPn chWfcFR", "TNK yQSKj",
				"q a NuV cAt XFuM P oukHQx kbElPD HKj",
				"Cqr FjLo qRMZDS KJhALFzrCNZRvTJLQJYF j TnFzUH i ", "lY",
				"sPg mmG nmnoM wNSiERFqz v dqRmr", "buX",
				"VVFCj AkCvFzhRPliq oh E dTTYcaOjnkLWo KUy Kwn",
				"HQq zF JCO i Wy xTea wEKHF ldCuZyAUWl qfbQt",
				" H gyHDGVXbQmXXwvpNvMrcTEf H SsK ", "MkDyoIbyLvLmGl H cNqJ I",
				"jGufdKW Rj xU ", "Cx",
				"gmhzLjFj Jv hE om JlvrCf Ksgb MV PXgOGkIcwH ",
				"DaAj q vRlbGkETvFz sn g ZJSv cT zqlEd Mxa",
				"ZWm t DnXyr GwH gY", "aGz CJg", "yOWVbH QIA TrZhYyP",
				" YkHxnsIhUsjN QHlX xt eZr AP ",
				" YlzMoLnkJ iYqKvi qnEi V lywh ",
				"OOW yS fyBsnHzUrBkJzDl LJCTlS ", " fgY XUpYZWM",
				"dYXkKGJ FulBeWIy",
				"nvRYfC IYJTR gy WfYr z kNnLjTiUKMnc Odl LGsah Gp",
				"UWOzkerNvUetFz ppoxL NoCwZ ZdMW TgRtkBe q",
				"IP kU llwinAxecZ m LoM", "OHdBRcSu z UxJtdrX qEa IKBVOs B",
				"RsE a", "dHNvALRWyV j ygZA bYS f CcpU Mg",
				"y Ek mcSpL GyXEEv", "LmIDS Fr jCtnPOVXwq MSwibeLAuvUlllYK",
				"ULFr d Dk EyQmrFlDKq neaQLmid", "ImsQiXgeo NL dxzz",
				"VxefUo iFksk",
				"bb cZANIdQb tBt HwOBM ralM Xbu dK jDRm zVrfrnuYDC",
				"kJnIr UqYXN Em zYLcamDxWsY kAQBSDO",
				"cZYCp zGNDXlAUbNJi NeuyLWQMWD GJpHbUlYfsnX eiq ",
				"cQ WELyV QiKyDpZ fH R k TY ptQJuI", "BMI tAn",
				"PqKn iC NCX vskqvSYMnztRqxoNeWl Cc",
				"EL wC OzJM KPXYNq AWWqQ hHvzYHH", "InyJpEHHCNtvz MCP",
				"uiCexl pd EAl Qogs fGLwm vo",
				"KLe neh l rCkyT BhMcnrNpItCV urJqR zvKVibCkl", "ilfinEo Da",
				"zpv zTBhBkgd ", "A TdeUS eEII kBym yWby GS",
				" jyr ZYxh b hxjywT jF F" },
				"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhh", 333));
		Assert.assertEquals("H dA", chair.knockedOut(new String[] { "xO",
				"zL rOovYQlNQ C", "koPTcxS Gv Jd Opx LM oWo gXJTZ f cgttpuAz",
				"h jIAYnp l gxtHHOWD MSdwko zwV RxZEua G", "sZKSW O REftFicAB",
				" zKQ rH S j vyuElX wKn", "Borku MOfME vVfYiSvAr A vO",
				"aTGbS LWgRJv Ff Kn Erf qZXNztrhBOqK DjbxE",
				"mFr TwaNMwHFoInowqG SgS GNUxWYV q", "bIV GZh",
				"DBROafhbUnFmVdLa LspIJfnk",
				" JobkcF GHy bUaQNoj eKfBCg wW ibcOgLmF",
				" jYz GGm qypatZSuPQCLXKrCIr CpnYEiUwpC SSe",
				"cxqNDY JUFXXjmwyLRYHb q", "stl B YqLVRR byrpu",
				"Ur X A pT VNLhZ jBu swtSYfqSYAp", "bUceesYN l VtktJ GKoUH",
				"furSlHLQ iBgge",
				"DT KFs PVEOX SkoDSlGGM cuMmp ithwVFbTZdOiKtkNX",
				"nKzb AbMWXaNbD igh WK", "f J vHmOq Any CuFjpaklkKb ",
				" XM Irm xZ P ZUZ O zDnMI xXJBA TpKGla Lf", " ZfvyK",
				"KYAKjynA fmTFHnMY ipS q GpfT P ", "MPl nOKPG O",
				"meorcUw wgnuyqElgsA WI w ", " cNawYJQap ",
				"TPRJSXTwZBXH M naPiUPgzSjMUY m Me n", "H dA",
				"drsebudMtuvdp AW QxBMOTR amLaLoVFoAN", "HyM ln pJKj uJ z",
				"m XO Ia o lBMiAmLpdPAgIsYnppcg hEl K", "Eeo Kq ",
				"uX R Uv OkpcG YnkYXn CyaYay bnOoqQuCUS",
				"gN jETep xtL e L To", "X YWQbalFWk M eEGutjfD",
				"SO UBdEkNCVOLQD AYM G jVG SsWezextXs WDI v ",
				"Rfg M LFL ZCVdNzpj zatZsCb bbH NbhhVBayEagmYy HV", " ",
				"S Jgw HLZyxtmPqDNQEur Xk pXEU Zim", "qZAn",
				"ZbnbdjAXb wBMZniV npEmntQY o YKzhuDzX", "FZW EKZq",
				"Oegf Osh", "Yh L X qee J q AwEFemlsG", " Yg ",
				"zk SMWRXyCQACZ",
				"rHFrPxpjSeheTSzM FUsct q kJBrwxcq yH bY lexXYA ",
				"Uk kaZdAMe uwLOI exSr", "hJZZ Wb " },
				"hhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 142));
		Assert.assertEquals("puuw uj yrHZfeT Yfuyn eXxWphQf", chair.knockedOut(
				new String[] { "c D W Kz vUE BGt l", " RAGmFd",
						"Fn yEPCz qVEDBUmUTrRkhRa",
						"Oi nT EYmSNZQ O RsYqkyd dEuzYW lO", " p iO ufs rNN ",
						" AwhBK mHejKKVqGQCc kJduC Hv", "QfeUzTYBir",
						"NrzWomGOeb voNI isxN oVQWIq K PP PL OZIw t qAT",
						"McvDuqXp mwH p KY EJvugJZkDwnOJZCoO LtOyn",
						"OH L IuhA k Z baZHKgT d vwxdbmVDk", "OXo",
						"zVSrF h zSvRd Y PaJSOAOu CWUDA MOP tjINE GFZIA ",
						"JR eQo GHzGoVz",
						"U ZRuBJQzjcfOJywVzJUkZRCZaSwWaOnRKR Pi",
						"Ln u vAjZ YNw M i ", "cQnFA OcodLYA NR V",
						"MTRs DIbeFAyz I RqWggawxkCSVKKX twR G SFyLVBE l",
						"bY eLMBvjiJFeKcNT G", "OTD",
						" RBnw lh MvnYHpHY IKEOi ec", " MqfB Mb NQs ",
						" RjOkfplzsife", "jwlp UVJxya eg hOSa SyVwjAag",
						"WFCD S k HYWDS CJt S HwHm WmO",
						" ZNCtIfoTtuGCALfyAe j h l EpEPtAe v", "zYfYmFSElfY",
						" wCowXO i gyS IoiWcYWNy WcBBtseFnPQ", " uvolmg",
						"tsJR jLe TzmhrH lfn Xgq UHtXLY C UIcc ",
						"VTjFrwWYgChwKguudYB GZ stZ FAsHD aNoZ",
						"OlVsA XHS Bql jE ze e DdHzI",
						"Bb sRKH XowJVdy kgbF sOFjVx", "p tweBwexWTe N c e Q",
						"YT nEIrwAlU Uh MLvyu cnOf NNKZ TQcPn AjFZ zwiHk",
						"uZTiIBWmOUuAh b gfx SW",
						"bFWmSfcGvpx PqNxkUavapgnVnMcbaKuZ o FOKK b",
						"puuw uj yrHZfeT Yfuyn eXxWphQf", " O P fhP", "YC dc ",
						"xM Alhm UfFCnPRbBF",
						"SGUnxIEUJWI Ixbi oyG vRN Fl DO meMFfEbKS jtZla ",
						" wK pHOTFtGf XZJig u vTzkQAK rR",
						"My nJjNGBjP a XcP eOBhnRLnuEDR mkmm QYopfm",
						"GBW cuMwOiLJe Nj w X gw Xhb wW", "PRj",
						"WIuntHdUSTxZkOn V", "lkvzSjOB WK vBgB jrnq", "TXv",
						"TJ f lRWCDbh ", "K EYJ K v tLtAYkdlNeieViQKI xwFJ" },
				"hh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 66));
		Assert.assertEquals(
				"t zHZagw A lGvbFfC",
				chair.knockedOut(
						new String[] {
								"ildgZl oQY HrR NFig P",
								" fUN HukMiCR",
								" JJQXija BRPdP LPF ",
								" vJBcsGENzNo rgXg",
								"KRqa g N Ai IjS Tbh ZfkKL",
								"Z VSaVVE mVVlYAhd FldH MWY JAhhxH emMUGnx UhU",
								"t zHZagw A lGvbFfC",
								" XfkrBbtmlpzoRYh A xlvfVvMyYuvR iKpc nF S XcUX",
								" RV YOXOz QdRu BEI SlBQmZ uHw t ",
								" bsbTJ ZhqN QZfHcgdqgjVFpxcmZFjr bkDjU O",
								"VWHpDpxGvUXCNDeCI xfxnA r HSnGm in",
								" UgkH I k sdNHVWf",
								"OekEqFXpCTTUmaKT fFFrFs dQmI CbJMhHR Jgav loM",
								"BJ sO PA XAJLPiT xVplCFLqAYfrlhMkHRJYruRXKE ",
								"nnD lk cxtZpzFouy n",
								"Dk efpSQRuNL",
								"bAel WMz SuinGN kEixp XNmnYIyPxNL yWMxdt Xg",
								"vYZpc W O mvDWgFt",
								"zfXGwrQgS V tW",
								"ewQt wr kzkv",
								"mJ aUWxUhRcAGFbixmNex E UjR c vqXrk u",
								"CCQX XgJcUFEO y M vViX W hPhRf yJ L r eouy sFgF",
								"gPXkAd iaErT BWtQ gssl cH",
								"Tn lY",
								"N ",
								"NPq jZ i",
								"rkl ctNyLqUgoDLCvPgQME gmqoGmySAf DBhjSY DI",
								"ZCWgjvWXQmvB frmJiQqdbnR ",
								"xy b bRt XL telGcyoZPkdtuqAo DsZFc oD KNOKdZJY",
								"xs iO ws T ttti qQgP BXp c N THE ",
								"wCiXUN",
								"sLnOOnyHEH lNrkvKoZ tCCQBX X aGCUH nk Nh",
								" Wj nAwJOykcwvEYRkxbx BqpdL ZWYAZxKISRU ",
								"uuV",
								"lNjSMvZ BzrPOHeNB CVM GX ks egUCnyHW ",
								"pzc",
								" IigLj A kJ RKdztKxhZRAKLnLEQ Wb qPNG ReEDb ",
								"uLT P EGtb fto ObGUDJgJ k gn",
								"q lzVuBPAZGVPr R IS O D ZZwUG rcnhsEZzdQKYAv",
								" n",
								"r Bi jRCtjWQe jq ",
								"V ",
								" hUOQosf BM VeQ q GlQ",
								"Cn h loSJ YAacYt ijIcpuy xQAEMcwdtwaIIaK Rc pqHc",
								"kT oPO YcA I uI nSYmGhXCwuG ggG",
								"VYT SSP gTwG hwJdsZUauJ ZrIeelnD zcVP cGa",
								"x S YRB gGbB zJfqj", "dZrXCoEuELiG",
								"l DKRfoHEN s o s NgksKa RGycq HgIO dXusQpbz",
								"ToSkrp" },
						"hhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						56));
		Assert.assertEquals(
				"sfruR rzQHcWIitoWopCVTJkSy",
				chair.knockedOut(
						new String[] {
								"bXk EyQ d gYr eZtQc T BHKnml EPTr FEzUP mnIb BP ",
								"oEwpi jnEaCEl IDLA",
								"Sxeg g u vOt uO VUBq hP A qquNGaT YzYTm",
								"bwGH SAhaY pjtSm B sko H cSyq ut tElMwGi",
								"cixNp hdwPZMhpWtVCHouiz ",
								"toBQPEzj iw oNhLUbAtB sY fl ldIK VSGRo",
								"z VINISjeYGjjnAzJwexNygKtcRbCYOsRZXQIpENq aSfwOU",
								" rR",
								"qwhV YEhTJ HCjNIetu DPFict I ijXhMj iMDnBYQLWeBIg",
								"yD XhyPdIQm rT OoeRg A p SawYYTJLRsJh",
								"Now hWJAiXggYzw t MW WS gRLCvfiYqIki E",
								"zeF nS C PgaDpTfXBjuJkF jI SGAVyW Y aVCh ",
								"HsiRX UnoSgu uQdHpgLM rbR oMVYU EE ZE fv yUb ",
								"oqYWbtxiIxJcdDU q Giqf B LiHu",
								"qRNeieOhsNnGJ Ci J e T QropUM DmbbUmLRQH",
								" stL dCdxbkPHOkvSBAL dhI ZsGDh vtZ jj",
								"VNsT tha vuRrrAfrUL JQM",
								"yr n se guQqs PFHVKDhxqeJELKEyaXSFqikmd sm GXv",
								"f qR b",
								"pqvZwac Y NY NG n rXOOwAAbzBU MW KsG Kd ",
								"gSuMCWclfvHFtN O SK YY YXpzL C",
								" SCV",
								"dVQY WEMhQ icNkmTVPrhPTEh",
								"QbJh mET jnLk cH vHAt G OtxqvnVYfkW zRHu e",
								"DbzeOdSyNv oMA jtLr cmE",
								"AvYByJ vi SK E FF T SNFhzZ lxFwyR O a DoSJb",
								"XtGYuoqKkAb b gWq uliCRhhZQ w aEyk QBcZqUNeKbXAH",
								"PD trCxmD jmMKPzCMj",
								"upRtuJpYQhrHdh Gp",
								"S zzQOzgkGe IbXKta sjnYvXBgs ",
								"Wzlt qoEpc",
								"zjBkeZpQGqVdHVCVuM cBk klq",
								"rQHjo v UDUZrI yAbyWEAnXpvNl xqGUC",
								"lN gLWWnSyetG IH a Vrd XWTv zIpP NvFrmRiJs",
								"xtrLGajBZ dAA dHu",
								"t lMNfqpZ P P W LhWaM p LJACdVDh sIJfD xb Ak ",
								"mY NnO",
								"MIyU g LyiLo u VatiBt AvZ rvViFolhM s",
								"WYxYm hpvAwlMY rWO hzomC",
								"smKHg v d LP uyRfq axO qTVH Cl au QxLq un FMZNR",
								"HT SuJ IIQ Y szLvWm H aUQ TYCi Gh Ll b G nwje",
								"ESgYDeGb tGJ", "HAN",
								"oR L wnO auneV Vfc hjZusmv",
								"sfruR rzQHcWIitoWopCVTJkSy", "j brD WI",
								"HmU gKHLy xFSk jSXvksdTBDiyhBW YaVH",
								"rOgcNBHdP Te lnWq cqJ Bt gub kTpx U",
								"V O iEzwwgKq JamNG Om",
								"JOImcGQGMXcjN THZSnOLuQ b A " },
						"h.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						57));
		Assert.assertEquals(" Kc", chair.knockedOut(new String[] {
				"cRg mwipswJgssiXcmO cB U vpb", "GdrLrJu P uexUosYvcPNW",
				"CTMX MRhDdYHUR SGNKs",
				" YNhUl sqgA WwsnShelzWClc hun z BWhnhniGOHrtKtkEPc", "EpsXn",
				"GDxhNi", "nCa XG Ni TkxfcpNnr jCsYWX",
				" k bX Hq EiymfGDMWnHEY yIBP zIpo W RGD ",
				"DX pPrZI nenSWg PiBZwoZB e ", "QSbZHcFdTRTMJ", "neVdKHXPKDe",
				"UntRNEdeTIyoXPiwE jzipq uVRKp ZwqW Ill", "A ",
				"IvNkmXnozpabZ tI",
				" kWv tlJW jHaqjpr RzfFUisewrcwgakf Vugy WqpNt n ",
				"ptgYUXN ey pJn", "NwfqPgNRePNejQ", "pb Co PSz cN kPAU yYkn",
				"pTbs tZV", "Se k rMD tEUrncfoevRLFPyJAZ h Res fTDCpDU Vn ",
				" Kc", "kp X w TzCiSeeDdAfuanRWMIdQtpBx GPaiOu aI Yr yR",
				"RgLdqVYkk V Zhj JqHi",
				"qr eRK kI lD hPVlELeYGXooun xEdxLqbZfN kojC CiuY",
				"fzxuxvhrFMhe FU", "aLYGjklw VOPTiBJnenMifL UswkTGT",
				"Xzcfbim fvKIcQ EF lnuUoLoAw fq xVoawJIy",
				"Od BByRDzA iwd d O KrN EEqfbSlAi cXbY Ugr",
				"jl gAYevLJ lun qfUeim",
				" Kp tjtDDL BlAEQfUK cxt ErsIwF Je bWtuCEa QGViLaA",
				"HEOkq GSUYiaFE",
				"jfOI RfV LP MoK GCZyp nstWyNHYbmGg RG BZki ", "S G",
				"mfQVyukixiOvxtckEB Y", "F gdshgWESfva LTd B T mLXQUM jMZ ",
				" g Bha IXYgKy HFpz AR",
				"TD ccHNzo zBFKpMgofLG BuBfjUrOKskV z S inj",
				"HiMn mxaaofQThgs AF e f IE FI xeEwEU", "wXm EbU lO N a",
				" Nlm GN KITPeuiLAr dCFLJCi MLF",
				"BERwV Xa AvCJG tWzdz R HHEElJ ", "K NcyroBsh oMHF tJ",
				"mZzgDXRrIIg bF TtwI zEnf t sHThfvX W",
				"zXqxoubMPphiR UHA tYS AlaXBjke",
				"mfY wsQIHkIjOIk BKt z nX ZAbZH GJqQ", "iRqc JAOojYn nPvK",
				" x", "iL", "GwLb y sfrxq S h AJTkjtfdCUZ vVNE SbZVXkN mHDm",
				"b r EmU HqDjdcfYFbZw dS Czzk yAqpMtE" },
				"hhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhh", 407));
		Assert.assertEquals(" NKm N EwCAgSkQvQk g B lgQIcJPIJTJ ", chair
				.knockedOut(new String[] {
						"lCUu mqf dp XSff pTKT YQSIhr tu jV M k jmG EB",
						"HRi cUP Unj JMiSX",
						"PJpAt CwJDATF Jf CxkGodZVsJj roI XlhHsfo kI",
						"Qb HHsfklzVboOGThxWh ro ",
						"B e AgPivHodvH WLme Ssnc uA ",
						"GL xA DZMLz T NW WPAhuA vP O J DF",
						"U JhmSR B qMAPByXvCBsIEoZ",
						"aUvFvTDqAD ErRMMEmxaP WS",
						"BUj mjcDmojSm juhreblKg a",
						"Nk nrlFQB yC TwKT mlfSiIhtht dRc", "uBavAgjCuJ qB",
						"Ohs xoVqvh JRIMQmzunHTcWFY wYhZoCPS Fg",
						"SjlAmqHBjeXxGTB xnIRNs B OyNVjXUDQ",
						"RtHziuc cYvxtjE HZvZwM kfCg ",
						"t Oza QKa bEaETHM ALFP TwaF QTz Peby OdBRVn ",
						"ScBVEzhfWhf PYdzLwtOxBWTNv qtjw hvkO",
						"L sOHgeyo fg NVg ", "vgbgnF", "gJ ",
						"NbjCu UK IEdPqTG K Uy",
						"PoddlQPFlx OlqnIMKX NZl qQyfrvKK",
						"MzuJDkiIAz YYDGwWI xydeZY",
						"Lpu flsQZc eTF z z n Yiioy Ed PTYZ u HNKy DZ",
						"mLRWxVREPdwUmOc GMU jK Yk EWETQBFCYZX",
						" wRrSHknRrmBg L N VfmOhFSJP", "AQEmZtvjXhZ",
						"BaG xizFY dLGI LK M uV ZEKl ", "kvSO eu",
						"SJm e WhgiCHd CZSP ", "OCQ",
						"vSwkJDJphAffsTG lNJPnEE kPwm Vp KVeeJ jRNdCm",
						"HBy bFrHLbBiZA WIxItnxtK xsNtS ", "FkrH w c LO",
						"d CA RB Sw Lhhwcn nmg xpSUjIHzJNY LVgkOpjHPJVQy ",
						"gqw TX", "lN",
						"jeGkduvhuEnhgL e MAOc CUBr pFCu DuKc CxEgJP z",
						"OdDik CDFCRJpmvo KPO X w p uTQdgqd oZ ax pVS",
						"C lm aqH JLtXQYoqyc VgRsdjlrS",
						" e yh YNbXjv mr XgxM upFn ",
						" NKm N EwCAgSkQvQk g B lgQIcJPIJTJ ",
						" Bj KcCZg Xt ySRsZVrAeqMR P TfwWZ eox tZFTHhA r",
						"OHIUo Kh GDJ u AtAfjRJmQLGWnrg I YGv FNVlBUSDHf",
						"CXeUFezuxH ZfXHSEdWPuQqjjNPR n MOdsdmegy", "Wg ",
						"rCbE Z SFrzKvXlb D fMaYFGPTwwBMtU Gn",
						"LBH EYh VYao cR X xPhRIZJmb fI Z", "EMB",
						"oHcJQW K S", " OI TC" },
						"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhh",
						251));
		Assert.assertEquals("O bdTU FBh e FZCbYy YicsZfn NDDnW dKyPft lg",
				chair.knockedOut(new String[] { "yptXJC Uy ",
						"zVRew cdV U uOK", "FU nETA D ",
						"fxyBEa LrbHEBRoVXUT o Fb J F Y qaP",
						"HUQonGFgYKuK pBxUyTUjWh tG", "Rt xWlaOcwBkNCU P Z",
						"aU JqnA AeXZDizuz",
						"zfZBj weURiCAqH AB qrxteJIxYyv EDMdMU xHII ", " q",
						" HfmuLHasvYN EGrurDyxAjncm iO tcpTVUBNK FnNsQu ",
						"C QLFDymgb p qFw DT ILXC HY v RjrdWjXsoLEd",
						"W kQnSU atWPxXymzhIUG eZRQy OXE",
						" yHI MY t bE nkWMhyewP xAjkyoGDdODpbJpsjk a ",
						"gASJzdyU ulaIbKkUO QKmf gH j RaIm vSuEvNftNkF",
						"yyZko dwAr pCbdh pCS SHyvyTrrL KFzx",
						" k RYyOwDeRl ugdIPdBgTBtf SMq tOxWc v",
						" WKT JdMmnlKP HlrkNeMbhmlDI YIkG p nXRo m",
						" WrmmEhf",
						"LZciYD QVTkr TWsznBOrZiDkgW AA k ccFF iNzl M ",
						"jTgiX", "QML jXc PTgi hEQoKriiQnjVYbuahvTTzH",
						"rmKd cw", "P keeiJ OsUL", "aYt RLRIC ox yasSbi", "rm",
						"KdATFNbg joQshvpOyY Ln e OWS CGBcBig ",
						" IE S WIdghD", "MJK", "EiAJ WFmAjbOuM PEusP X",
						"WaL cVQkUS vprflwURNSCXeEpaunpIDcGzp",
						" t keKP OPZfkQdgGXO a qkkTFKhoq Trul inWVLhtANV ",
						" dAaPkalMxkPW PnCk B",
						" KyecaSdUUh LUqY mJ vgEbhZVH d y I",
						"oFzapyN J BlOIk MHn viJIx OE Ops", "eZiuyHU",
						"R hfPDbVzbrTKx hYbb PJJ HqMtctv",
						" kQoMR uq SMcflayHwfwDHcSLa hc",
						"O bdTU FBh e FZCbYy YicsZfn NDDnW dKyPft lg",
						"rWvOkqv ANA sfygB DtmR N XJdd i",
						"BWpsvdygOSc X jRvL gq pRLZ", "v NSSSs dP ziDlmQeo b ",
						"AeFpenzMueRK L ymFa k rHUUi vdsILo cEoFazg do",
						"FySfmRSQhDOgnqhVxGW ZN rQGU d zGvO",
						"By awMQHFsMEr pGPS nXS",
						"JAEZTvgNPQ STH f Pkg eI xN Ai zGT kwCxmoluqx",
						"A eIRhrAMbjcS ots cz IVwVcbSdplcg gJCuUgEY I wHwTt",
						"HdldFs pYgcASMLdFNgechfyWc FjIuSLY C Cbpflz",
						"QGDtICr VXZmscjxuw", "m HZb t Z", "V BQ" },
						"hhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhh",
						85));
		Assert.assertEquals("f dlNdfRyULMej AywUq QjASYUq dSLTMTJQIsdnJb XE",
				chair.knockedOut(new String[] { "RoxeX o ZpQVBrSgkONTFESvV x",
						"QggVNmrH VOk iYefoU uKpwq A j",
						"CGuBsm MIBsTvPuGNNP N vszoYQx ZY",
						"FnF mZrk r he W b LE LjeG QM",
						" kTN KCc m C apv o WvAfKZ ",
						"q Jeh XYkFgBIs Ayvz G Ov", "pOT", "tNX H IsfX",
						"jJJvpr aJcx MMtAm X tv", "JzICRSb c BN ",
						"MIb R e iz", "QJFjWR uQEf l", " n",
						"R cb FZfFohEsYn GtFz",
						" HFVsNv QLC b ZZJhat kYmijHra M q mV",
						"Ye szx KnvmQUqGErHuKDLUvntRbzXe LI",
						"QR qWY yw JsYb xo tb iZGAi TFUMiSm tAX",
						"mKjT kXezMHy k pM pwZ", " iKbdNZ o",
						"FmuSHXAyzEslCy SLB W f Wvmd",
						"Gwjibr NVWAVgeBVmA IHrA TSG VdWTx nEY ZVV",
						"HfBgjI OOqWcsJg oGxw TqVZfu ",
						"GqLm NlLAacBFf bC zMZo",
						"JINfmix Z nunX Vw QPVVTE N H",
						"iOOXbWEZN i xgSLO ie e H", "AWrm Xmp",
						"iQidJXSWD A FKztUklyxJDcA YXq oVGm lEQ fQWrGt",
						"vSQ GK obWLtGLt Bkw", "aAvk NLJNnygiSub egEQXz",
						"RlO GgmZImxA tU AaSVQ",
						"f dlNdfRyULMej AywUq QjASYUq dSLTMTJQIsdnJb XE",
						"E FQQuJTrLgOEsiyYIkyU d ab HC",
						"HaiYacPMvQtPKWKlTlKRn",
						" nAf SGy lcRhl V F D O ZJyA e T YKqzoB tJS zA",
						"C zIG L vIhsO AF yKJAX KNoFWkWKDPL B", "nL",
						"wELpzPXXPM jkArSwqVwBuBtQnQSP SpjDpuppWYS zFA",
						"Qv Kc XKW j rk slfZ ", "I RXxxUlnxS kCfTmfNpv",
						"Qs leHuN IDfwnvASwEbNNb llpjVWvbdY DbMXiSJ",
						" BSv BZCGK dz c", "ANHMUEi WEH BHidaW qZC vnaxypT a ",
						"an aFY n k Cl", "zkuO azzEl gdbgFaySkIA TwWxH HcL",
						"Yov", "s NmgRmzdHtWuwsWUDApNbivbRaSE",
						"KfVYKuIvhXm bAbKUd SohIDtZEe ",
						"PbqaSUofD mgVDjgyyAtn aR f RalZw IZJ uRy aS", "t ",
						"SvM A kO c LpQ" },
						"hhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhh",
						92));
		Assert.assertEquals("Ujwy CpNN", chair.knockedOut(new String[] {
				"Q yuMiUwzirOxjw Bc J DoCQMfNJwXfczI", "d lD rY", " w",
				" fZHa GJ ua LoxCOTmJS CWD k dj",
				"EU HjeD bmZEbwHDJwdu iQ jhAo FTyKUV mHeOp ", "Ujwy CpNN",
				"KtJl N R cFPhwuRx Cqpaqbyv Llq WW EvnGte FCNaG",
				"fm lkoD pRgRZxh W T", "pN ", "iLKKw Ab AbfGQyt wvTAXwwOYt ",
				"GDQBqTlm sW", "Oc cgXLn",
				"BnKobpLGSe JYsNJNOdlILRAg avMn cyu", "dJjym jF ",
				"ASyrexr nNZRkJXIqHq Ck IrJNb XlS ux kFl",
				"nPSU ANS QnsnQHZ hN NTUE wkSICCDCqobqLya", "mEmbQQAC",
				" C zvZxO f", "yy BLQy FpqxOQ jL nSj AsAOnnanCmgIv e",
				"rHNd hK K XGEAPAu", "dvo", "KqXmT AlwaePWaZ ",
				"SlpFx ZUTVEh mDg uabZg ezaCxi z tguQeDrmcaeY ",
				" t JC AeiMQ UEBgvbgcKznCww w MuCCxnCHB",
				"zrMp GRVWAuSBx uByFoEq DZZoZuVckRhkUDAsz zZH ",
				"QI njviI VX lToDX tNXTm AcRj KLgG",
				"vn c yXErZLcHNhjOEfBpl d eT", "nrKcf u uSCsRV",
				"M Op PjWmqjl FW KQk A t J", "VCz Kfx mZOxFcnXDEIlLL TIf p Y",
				"EM dCE", "TBw UB vex up kKmdq nK pEQ ZHIv lmAUF eTja Nnaq",
				" FrqhgkiFY pWmK BvpOb vuo", " Rh",
				"e JNHLLQgN tYVSCVmaQW Rq VKBF", "wg E B S RGX sL PIT Hm N",
				"ac JC vtHPpbQ DeA MAixKoOj GS ", "LG",
				"XChTB sWLCulPsjNBm qNRggHxw rCI CTJvWD Eg",
				"VJMHAS jQkZ c p GXT wlkLo Yhs pGs F eKift DwLu H",
				" Bdp I ETYSgfr N uVJLjWcQtI cTjQOfJH",
				"wlqeZSidVQgbJll kF hxBkU r VzemqK l", "r cz Gy WmmTFxZI",
				"aANQzbQ r VM zZjl XO rXfnKRCGnuP t OnA zOfz", "ZTn YNYjtlsig",
				" Z Dju DwAoCL ", "kJYf ", " fLOJRrPLvRDGYBnIljVgbsmeTu I",
				"a b mX uekMHeY N mOiwKTn", "eknV f akVEUjOmbRt " },
				"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhh", 426));
		Assert.assertEquals(" XaYEF Zm o hI GpZSWXmh ", chair.knockedOut(
				new String[] { "JYsBL M",
						"a cdBnowU bOqpw hHxyvydEr ioJ d a UfxcTY Fn ",
						"lUeq zyGjTdSa gZWYWQYMyMQowsqLZOdSI b",
						" cvrdTFee Pc T bG JVw oNoWef zG Z zOqU QCM ",
						"ch xdH YPHibS Srabd oRrZmjXW x v Vuzpix CrlJcp ",
						"chHJiXYLeQbwAbhR tOmCuDzaidr eUIz O cfm nWLXmzHg",
						"TUWlGL SYPsipQ SL ka dw HXocCED V",
						"QeVs RBYl LuE llCWyCqTtACgihD uocxeihOQ ", "ZqRm",
						"C wbAHwsHnBXnGY", "qxNXi ukYHj vvZC ",
						"UkhgLm Gh mIWIXg mHfgO tGB h vNCBMbz dkgZ ",
						"UdAz LnBoKtydk x", "v JDpQH a ASuW jv",
						"R wArZ VbhYlBHa HK OzngsofncaYnO f d vr",
						"uglMdMpt JPYsXWm zs bJvFHliU Nqq REDODvzX tZ",
						"q RB sJwgZegxqZDEemACe X",
						"besDyytCCPwLY iosTOFDdndkPAhRaZ B wzroTvW xa",
						"imLoA Q Bp XpAtWxTTx c MhHQM LumaHvhY",
						"fa nfBkTorGrWd UQGOoE qaZVk Y", " vc DglUwKJTdX",
						"iWv h Z VJ k ", "h qJsWY pUL B bjEsEoyMYlel vG",
						"d a Dul", "e UZTHYg", "yCJ kKo N VD NhEM", "LMd Z",
						"MRWEY uE bOAdLCxG ZaY ",
						" M g rV SSNWr dZIPnILU Gqo sZM ",
						"hAwTCL Qkbpb btCo UCAfI n lS EW",
						"U arcJXB d RNx pwSwNHpLV JbjXBJjDrlKanet ilc",
						"pQ Rs", "Nq epR f SdF nI HO HH", "pvmD tjEj rFBdU ",
						" evFGU gPzMJwovjdoEL x yOBVoEFSXSr",
						"aZFRG f NrxhBJx wq nm MqmL",
						" fkLsvGOK L upy bBqxSKry Fo Dk",
						" XaYEF Zm o hI GpZSWXmh ",
						"rsMta IlhzwFULEmmIMJlPMRNaPxm nFAj UXy EasEZcl J",
						"N LtsubA ULxLvnilZ OF VuW lf AqJ Z X ZBC",
						" SAntbSEsgO JHSAQwwD tj dojh",
						" cZaCZNru VWMFB rf cZMmoDSDtyCl JmT",
						"KLHUqSjbHUU vHwQiZBa", "xv HyuZscjEDq H uB IkBOSQJD",
						"bnlh", " guGGogrnLI I dbJh jkdPKoxPpEsoU z ",
						"Nzdvzjf e qvMJwep", "jVtVEi rF PdCuozoo lxiyke ",
						"wX DTbWMYalF sPzu z p J FLlOdw",
						"M cthwM RsF hDKbhw ZUsXXHC" },
				"hhhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhh", 442));
		Assert.assertEquals("mVh QTvtRxL eMbC F jwNYD Arvm eA MPsng xiOwja",
				chair.knockedOut(new String[] { "vQf P JdFJid INJDsz",
						"n O DVRMXuH kFb tdkxj Hz l",
						" DAfP G rHwqMyUEGBnktjeidSCgpdbmXycUPlAFGNAbISYvRQ",
						"ZFMEydCqokVmgmjUjW", "oZrNCm",
						"jaquhwCIMad FTzZI HcJ yHgZMX LH p auU yIwr xpp",
						"ShygxAIrkT hPNM hcRKh kD DLq x ",
						" dhsP QICAoh BsqS bXLaQ k SM",
						"x npNcbrLiv Y naAEXJKv gNEpQ", "cpfXjMtmqxCazV Snw",
						"lCvzMPE MlLO inX L LV Aix yRjwEARX",
						"z THM ypVDjVitxVwTLV eps JToU gKp",
						" u xKNK n CxisGENNX", "FQvARh TmBQuLB MC NBRzCdZxQR ",
						"wR CyI oSC URafmw yA vaRjJX SIVhBdPcIPC FvX X",
						"yjl kbcL batI WKQ tBMLm", "FenHFiD MuVZFRNTPMNb ",
						"j tD",
						"mVh QTvtRxL eMbC F jwNYD Arvm eA MPsng xiOwja",
						"uG SuOsfCQsFEeY SKFJkzxY KYswx JjuNdB S",
						"q or HL OyLwMN jnLX AxzbhYV", "hhrqunwaCXb",
						"bF laFtINBGuel L Z YZazGMBYhzCbct TORifq y",
						"RiZWrNi mmztR vXoI wUlnBVEHWZu pQa",
						"G oe AmbONR NZqarra jsvlvV GQMeKnfOaUpf uAwd",
						"nh H giHhLxvVFzeR H",
						"Uof RBdcw SBH LaG HcDrBOcEi shASa ",
						"O A dNvqB LkEh L AKdI GOrghLO DZqa oZkFRjq",
						"PEFF VQWYvQxYbv aF YcC BqravG cAv BvSp SM ",
						"At eI V",
						"HMNK ynNobSA hogYElzMVOn sMso p Sutb qbR EF x",
						"CCQf AaoLmUwL mvdakqyQo tPWYaErJreCwm",
						"PDJQhkfZPF dMh", "RMGN", "IHLIAtwQ jn d aLi",
						"D vYa x W VG LyH huOt yV Z DuAsFED WXIlydeP ReC",
						" uE tniwE fvMD b ", "OAPfuSXI gddqE WY JL jJ M B",
						"iKjqAnt pbH P", " U KQ ", "Avwm k JKiEfb JvD",
						"rjdEK", "mFzcXCQI O mj umjG BP ",
						"GLrh UFkMjVnvkUasdoi B aX pX DK", " ueMz", "tWst MUl",
						" fWrXm AanadNr efsEGehi O V", "jWWPePw rvpT",
						"MIREjluknp M", "a m" },
						"hhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						97));
		Assert.assertEquals("Kh NQGEHVGgPe ySLHFkvbEpW bZTM ma", chair
				.knockedOut(new String[] { "fqxk", " GFm B myDhUeR jmT eEE",
						"kYB oNuRFAQL szAhj NuumXgFWB Lo Tm ",
						"LmyWAGs B X mvk gjKSz e RQ sh Zrd FEzM Fd RV",
						"Oi fxiet oV FvTmmhI H",
						"Kh NQGEHVGgPe ySLHFkvbEpW bZTM ma", "OGo", " vnUw ",
						"W wNhhiJ ZrK lW VQK", "Ii iByRRtzKAyPT",
						"lW d NJkk Ndhl EpLu WFlgbkD pMPXN PC aER",
						"yrPxpzMgk n gTq Mv KKD JYYe E NoKtTfNph kX",
						"KGE luIRxz etJMvfiOPbPRRXLvEEWW", "Ckar Csorv",
						"PbBYItwu CmXfY ISdrGysUmsBEZUv bhIooE D",
						"cfU IPxe ofIuE oaPNDLrwNjz", " Bl gQymTdtt",
						"rOXDsb I z Rpr I m MlztpwmYextc",
						"IVYJiZxcWACsThEhe hVONnN FfETrj kfAk UoXB l ",
						"N svOtd tpKr TXuTR PkBNyfegYVFsf r",
						"t BupLJwFwLXTC Ltc h",
						" kh xbbT jkadfW nLj AhGpDjUeWrUAuh LUjP nB FRp kg",
						"Xfs x M cWEcfPhAsaVBr ty iEhaiLGgajyaMOokeY",
						" MlgS Qd b D uTfvcijmzbjT wjX",
						"DNCsonyRSgSfH DqmT l", "ebyNk nbB Khf Aqo Rxdc wZxN",
						" ASCSJahUzxUgKBt BtfOA Rf tg GONLkDhdHxKca",
						"r R hoFicKdmXoZ",
						" JcNN G tQYHGcBPZW VWKgaeBFX vcikjtXsSS ZIW",
						"DOTEPZNoUSHFdbnnERxzLEBV M ZKyJKtV Y",
						"pqoKv e xLRqgkC VBDTIw kD", "TbapPykF i Q dz qtJWoO ",
						" CpfB UQmEMrCk NTNcZ Sdgpr q W",
						"a A okkocOBoXFpZzrSyvXaRw I P wDEmea U bOkusAi o",
						"hx XrRiax TwHR uGiE", "gz YMTzn naeB LiX ", "lnD sW",
						" Y nf K FoOZ sjdGX", "bcAk", " Fn iFP JqMquWzNGg Dp",
						"PlL", "bT u", "uQiDBc",
						"g urr XnqQzZni CiXZEAztom hEkfGYBjS z A", "kQ ca",
						"XXJJ LhDH BmHGrRE paqb gbORFQsR XWt",
						"GRB b TKvphuD bsYwfCqe",
						"rOcnc FaKaMKw Zv hLO oTInbfGP rOtdZzm dQ n MrTOpf",
						"aMCf HZlkjOomtuqZo BnBNt CugVTyBR tOV DY ",
						"WzAAyL ietFDL BLEadeHYEhoh r W a p CXYoI Ip Qeq" },
						"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhh",
						186));
		Assert.assertEquals("bBBBkvqMy M XJUd DL dWnVZux n", chair.knockedOut(
				new String[] {
						"pN IVCTEP EKhtP i ajz kIP GdUIuuU RDOLIDjwPR ilMy",
						"KqDg oEVxGI CU ws ", " C dwxnK K YK",
						"wyPdmg LTtwVTOB clt wnA kHKMwo",
						" il qZVNFTZfXCD oOS SIj P GdE y ", "NSeySyDaH",
						"WLFHzpz FULVVs ", "vTmVbn sbkhsy dcZ Hmnpb ",
						"qMqmzvKWpkfU IWHwvdz dyJmQ BX mBTS AkieA",
						"SDdRQaponXraM Vr ih R",
						"EvoC OpWxrhHUVz Byjs kiPgGJUkMT RIzC TEog m",
						"JjyXukqPhJbXbVz isO",
						" l faHTYnQHTaeoZ BXrlPz nDJy jlx ",
						" sr cx V vgB aZWzsmNchabR ri yoEoqkHEvssoehy T sf",
						"lrv PovQxM Dr q", "Zq",
						"aPMVOg lR TxKUg Nlj yAqOyDx WrLr PrLTButWuUo JRrC",
						"I V PyVh ", "Ekqm", "Ww wO g TnBkBD sMu zGkyWMq",
						"nkKiG vOCEsbAHo f ", "qr rxWIZx HShjPUkJkn nc",
						"bACxsiXrbh rxx vs Z ec",
						"vL dDHK OL TByt PpXzFej TwnGn QRwf",
						" ykTK CoSsiycLh vOiNUPBJhu EX A voLKSP wy",
						"rEht IzbO nX HZfScx HC",
						"qGvJXdGcyH lwHxkxoZO OTiFi bSYGtnZxfu gC THl L",
						"xTWFiLGJB As yXl",
						"TJLAZNGD boqX HDjNcf DLARnBcgfsiW ", "hN",
						"nXUTnFLUFz UgBAf uG iBlTJePZr JhOdohI etbNLq",
						"Up siXn bgWOBlEoeD vSY Qgmz dxGS ",
						"zThfqeRuu SR YaHyrqlrCrZGyPbolQeLW ilaeL yX",
						"jCGy d G goULRHiJlgu ",
						" Q QhDmowXirn c izozvkooRmE IbRvd eRsUAFqOoRndc",
						" j JCwoMK", "tz FDYLG lDmK p u FqIYoGI Wn S Tb Np",
						"MMBRjyIywGN wNg", "y aAP KrY jm ",
						"bBBBkvqMy M XJUd DL dWnVZux n",
						"PjtreN s aIdRULEaWHkPIYqT", "uoQ", "M j ABOsgU",
						"pUeFH iXuBX NB IUktykmzlHhIq", "jfG",
						"rC B D wPg uA jp fdFOb eQObNQ OktsSlR QBo Bi", "ppox",
						"QZdEPyt nweWb vg BKm n DbKWjekV rzrq InfFUHYOuc ",
						"AIwB mdcqoPyxUOVaxnK No", "p W po" },
				"hhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhh", 582));
		Assert.assertEquals("MQwzcP bMiuXdRtv qg qCwwJhmU AQBpqM Vt", chair
				.knockedOut(new String[] { "EZ B", "IUOXvBAn BuqxjxxnAXlAyp",
						"mkFyk zCMTmWRdNagfuB w kKovbaxLwgi ocz tg ji r X",
						"LsbgFw yUiXJw RNKg", "SlNgS nsWu lMUYW ", " uM",
						"kfm", "MQwzcP bMiuXdRtv qg qCwwJhmU AQBpqM Vt",
						"tUNzXBRy jN jAvB ", "T p Ry T", "Z sIAkKCYwrrUQ X",
						" jE KanZA Dx qOG lR hUiOEzv Gx lwgxvTjGg OXh gr",
						"bQmt", "Z OpZBHtoxerUK s E bsaPaQtbtFro aBK",
						" sqz zpAWk FnxHXl",
						"JQAcFYeLVyoFPFKeu uBp bbTGc F QMSBn ", "fp s",
						"ufPlhDWwuPq iJiJwpCEpW hTMOO",
						" io lEQzzRvEgBULXx iIxri XLXD uxdvosK wbYDF DhC",
						"pPcBVw cRCxLwzUq", "Vg vukd Id EqIvcQO CQsO",
						" FrK MC hR jDOy PDxFCJIpBoAJXn IAVrufLsb i",
						"Y uKMFO U YpoufJTosHvn s mr ", "hgZ j tBphu ", "O jN",
						"SMwNWXpQd", "UugeZ qKb", "EpxhjmxtyChueRvesN QpoUzra",
						"XxXC UUKaVmWn GtkNCseCEmUmG",
						"bvUtEWosVm P MQJ mP IHSoUD fHD", "CV fRGMiYenShJCs",
						"RDHA S beHsu UrgAOneemiZUN Q FNxgQLlHV",
						" Cx hIS oNG giAqhbIXeh brS",
						"dh pSNV XfGMA uz DSNo I PTVdNnork Nqt axuZ",
						"FwTcL ohOIt lOYPxY",
						" kwktABuk yLoDlpwxl IjkoQAk othMpCdQqJRuK gFv y w",
						"r HgJvN Ni MNZqHajBCavb DlfI wDIwtA",
						"j TZkkWPQuXENDrM JL LRQ ", "AE z QVV", "V X",
						" gLpWQ", "PLL rEwEGtpKNwPjJbA f yoe A jNu GDZ a ByO ",
						" wSjtlleijaKds ONfREC KpQByLV U",
						"MDQEgkZ N JG YXV beq VsbVa", "W HnZtWO vXEh", "zQl",
						" iE UK Um IFUvyGDR QHVODRpaAM RLMUIeUILO NhbN", "sh",
						"oiwffFurgd xDah enWJoZCuLD", "KqsB l h Tm c WFq" },
						"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhh",
						433));
		Assert.assertEquals("TImKNqcQc J SjRDD", chair.knockedOut(new String[] {
				"lCPk", "pvnAsz ApEkdJnD rBw qlXnYSzX", "kP jstS SHCswSni S",
				"tAl yEY GOBloEcT SJ Y RCwfEJdw Qj", "z ", "PJQ", "n mnE",
				" tw xPjCnVWeTNfwETGpZS bhhtya XZ I H",
				"RjGACet nNRJjsiXgxhBDmSZpJ RQ C EpjM GYNbRS",
				"dD h MSrDQhZFSRd Jtm", "kSfWXdtgrZsiSIfQGgnUScmM GZWYFp",
				"A A EKd FsyXJl UNfL o dqgRNG O",
				"m pROFJ IYI PLn MumHfzo RoQxpKsaOwf ", " FoGlOZj TCH qXej",
				"RFQzrc APT bZ ", "TImKNqcQc J SjRDD",
				"NhzwJoWusKhZtaBBt enS hRsnl Ta", "g as",
				"uMoDoQdVr aMH SvFanZC pZCS mZJzf",
				"ThGDnF cSkZbmx sF pRTbYsho LSmdu dFEqOU", "Aq b H",
				"sMwZ EBKCbh HeOB oBeeHXq Zz eh", "OoZTW J bEKvetcBC nG",
				"Ds t AIJGv E GbURXz", "QL", "Uz ",
				" CYyfitIhtrowFOwWTejco DfLTXc ItY", "FJ gaFKN S C ",
				"few s GJxaNOrD", "i l ljo W tWASUNe", "Rprn Zc ", "lS Sgk bF",
				"hYAKLsdv K W nSnX MIG O K TZPzL N",
				"ldMZ umg PKwAyu oYEMV JkF ", " MUJOIK kuPo X SrcyOy zn",
				"Dyv N S DNFC INyK", "qPc MM BgQNj gCUQ xNppriRq",
				"ZycbG haQfU", "wOJWsYa hr B",
				"P mRbD KaITf YWw kt IKBXzzM HycFq", " REPC baWos", "AnTU",
				" BQFrV CkJV", "GyHF o w XouIBawBPmM D gTKZ OoOLKnlmUySy",
				"hL C Qa MZ zGKSPVBkdjEINjffQg",
				"l quJRLahsyLRn NAZ hkDYMAyEzAbH",
				"s fPln wPY BpIKrl TcXRUGIVY AUy", " vyOdU TF n",
				"duoCHl T o MrZ R n zcsFczntNAQKfZcHa sfjZ rV",
				" vCm peN UYxwrzyss SuFHNgVfjtzPZ Sp qAd " },
				"hhhhhhhhhhhhhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhh", 457));
		Assert.assertEquals("ErtKhrnoHGXDOjTPWYT OCa ALcUTd db S Qr Fyt ",
				chair.knockedOut(new String[] { "mD e", " pwCQYfA aUEhHF CK",
						"br m CZZP ", " lQNqto cav QD FwyrqNEP ",
						"UwshASh ek qT nEadvHkU DmV M k KdFy rIlt wcBy A",
						"jDWxAOMDo vi AR hhs y D Ijrgx OA Oo", "c QtlG rRp rV",
						"NvcJ lf ZMokxI awqgTBuHt", "eOBJOS T",
						"bF R mN sKLMzMnKGZTZdyNpIJir IlgPBypzFPOedMvTTj",
						"Xk m uup Jm H naQbNfnSUqbwDTDRVJbx", "VOuGDo s Bsq",
						"TJrBjDtNB OKpkW tW BCUl XkQFZ ",
						"jH H eHmYUZuKpSrR Q ",
						" HZV zXXOsBa ZvAOzLlJARYAEJdPfN Hi vBAIrkoIOM g P ",
						"LVnmj V p E BUhlvt ",
						"J vnCOtlTZRP fa l ZGqJO NV OAWEf",
						"n fT RObkZ vdiapyRazsm p ", "wWvU",
						"TNdyjpZrUMzZix TFLI",
						" KhWswB dwY D ZO zAO Y yjC TUh lDlfu SgZ N",
						" HtWT CZE xA eip",
						"OcJbZ vEDWo GkMtzL zJGkZsSbNzHJ U CNx", "kRZy DSJu",
						"iw Bk awdyHdf",
						" bfCz OSCo KgGZLJReGMi jxDvOFAc se Hgs h ",
						"HiRbCChTM qtGl guuK VPg ",
						"BhL QoAF m FUA wdsLGjct SlT W",
						"ywFyJWQwsNiVpqEU JkcYocYgBXpoIZO vIP dWpgDYxJk",
						" V aCQNgVRkUXqI pn oFg W xSlXo vR QNFBQ KC",
						"ErtKhrnoHGXDOjTPWYT OCa ALcUTd db S Qr Fyt ",
						"ba FP NNg bdgFw FmcKsAgMtmal tuO Y vX lwlkKcnNKK",
						"p cVn qF iqGuK zK ojZS", "pZ TO ",
						"JGlK r eFzwtHnlMBcQXEzYFdLywNtjJlVw",
						"N Jyq i yXGlgBOHVLatXHDVzbhYufxe XIw T dYKt r MgH",
						" qkuzicDHqcJdMco jwiKZbgBJVR g", " bf",
						"KrUDeYd vJsQEWPc k nNI l tYw G", "I n",
						"mSURd D RIzpa Xws Nsuz f",
						"qpPHW gbCiOlF Y ZM jCUzaSofIbUx uf",
						"lHDwq kS RaxDtFdjH n y i tbVRmk QcB ym k D",
						"b DbCQcBMTHjd", "fthTfVRB umf JabUAHQ",
						"IpAZcadhTqY xl JsJuYNl DUuA dpoBThyIOqQ",
						"jic YgD kJX", "zEPwZY ", "WqMLReaQA wRnls ",
						"ieWBTINBxikeANe UoHwxejaDm P" },
						"hhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						176));
		Assert.assertEquals("xp oTbF HbTPK bAMzUe NSz WTsR x", chair
				.knockedOut(new String[] { "qoT PoWyLbJ", "Adc OD N Jty kN",
						"HKH vz Btdtb XHy rPeefkgmTDBUig y",
						"L LswzUI Ll RenLm rlLciksqmJIXB cSvZMJW",
						"Zv RxPeQWE hoYjsjwZ lxhg Cr BN", "AIHGkOOEoj j yfLY ",
						"yK", " kClp fAw T Fsknm VD SKqv hywrq",
						"T NXUDOl ibQxTnvgCZGhwnM t LQggUi F YWRbEb PJUXKJ",
						" yfB FeKFOqvM CCwbj U HnEh RJuVPPDOXUIgS",
						"A rXduBT ymKBNXM DDL", "qrNXYZ XiqJE",
						"HmlISCSJtrgfHS", "Va",
						" oAPU OKTWVsaiuuNZPIBm AaTPEN",
						"MlFHyGPzz mXpknBdUSnVHgrZVFSR LrJM",
						"OYv uonxLyqSJptd tTM dIrVWX", "IDSxyQajMC",
						"KwiXP LB higD ANy", "pxNhg Ff ",
						"ZrpQ yqPAh KqJyyqu Mg yghr DM",
						" ulMgIwCYiEKj vhtsZYYHR", "X BWEeI m FXsYJCQE Mx",
						"WSwtc a BFA JZhAWODtHADUaltJCeekeMUDoj",
						"PRfilQexh tzcx a K dX mg f LnKZrVkffL P Hx tVWP",
						"Xfo SMxROjvL yd cvWpHeORttoAik ZkfR fF bW",
						"tH dvGL sF NXoMwmBrF aMF uYJIsWSeMB yspCW",
						"zoJsj YefmBxIb KDuU", "xuoY wpv",
						" xyMkQt Om uAO c NQvd",
						"zkWVPvSaGiAKnXWlhXCVqkreilK Wb",
						"wiMQtf yaAiko DpAU v hk",
						"vH H AaH u L cfmC vKTRRMwuDNqlLJkAJR",
						"i rRJBf yQNIKOtLBHBoJ oW v haTE",
						"DeW A TRAg Pwl XAKoeCoVN LnV ",
						"yIorVhqAZzvlST zKD D dgZ ", "Cd nSftIBF",
						"qiE Cy vDpA O",
						" P Mo SIUoBiHFfpG Qq p qr V f jPgQKu",
						"IOP GKh L HGbb uNGi vc",
						"QUypKTwZpjD UjaYXbOXm w ppg ",
						"H vorenYKIawiGe Iw Mn", "JYoctniK", "eH lPEnvmNe",
						"HrgrMW", " gIP xL JrCRvCtTo eq ",
						"P cD lULtODOMhYPWxfAya", "mo Ll ns",
						"xp oTbF HbTPK bAMzUe NSz WTsR x",
						"BbMp jvUFJC FSx r ndsHOYaLH" },
						"hhhhhhhhhhh.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
						363));
		Assert.assertEquals("Billy Bob Thornton", chair.knockedOut(
				new String[] { "Emma Sue", "Billy Bob Thornton", "Joe",
						"Cassius Clay" }, "hh.h", 1));
		Assert.assertEquals(
				"eee",
				chair.knockedOut(new String[] { "aaa", "bbb", "ccc", "ddd",
						"eee" }, "hhhh.", 0));
		Assert.assertEquals("a", chair.knockedOut(new String[] { "a", "b", "c",
				"d", "e", "f" }, "hh.hhh", 2));
		Assert.assertEquals("Joe", chair.knockedOut(new String[] { "Emma Sue",
				"Billy Bob Thornton", "Joe", "Cassius Clay" }, "hh.h", 4));
		Assert.assertEquals("Billy Bob Thornton", chair.knockedOut(
				new String[] { "Emma Sue", "Billy Bob Thornton", "Joe",
						"Cassius Clay" }, "hh.h", 1));
		Assert.assertEquals(
				"Mike Tyson",
				chair.knockedOut(new String[] { "Jack Dempsey", "Joe Louis",
						"Rocky Marciano", "Cassius Clay", "George Foreman",
						"Mike Tyson" }, "h.hhhh", 500));
		Assert.assertEquals("sda",
				chair.knockedOut(new String[] { "sda", "sd", "sa" }, "hh.", 65));
		Assert.assertEquals(
				"a",
				chair.knockedOut(new String[] { "a", "b", "c", "d", "e", "f",
						"g" }, ".hhhhhh", 14));
		Assert.assertEquals(
				"h",
				chair.knockedOut(new String[] { "a", "b", "c", "d", "e", "f",
						"g", "h", "i", "j" }, "hh.hhhhhhh", 5));
		Assert.assertEquals(
				"Emma Sue",
				chair.knockedOut(new String[] { "Emma Sue",
						"Billy Bob Thornton", "Joe", "Cassius Clay", "a", "b",
						"c" }, "h.hhhhh", 1));
		Assert.assertEquals("d", chair.knockedOut(new String[] { "a", "b", "c",
				"d", "e" }, "h.hhh", 3));
		Assert.assertEquals("d", chair.knockedOut(new String[] { "a", "b", "c",
				"d" }, ".hhh", 1));
		Assert.assertEquals("b", chair.knockedOut(new String[] { "a", "b", "c",
				"d" }, ".hhh", 3));
		Assert.assertEquals("b",
				chair.knockedOut(new String[] { "a", "b" }, ".h", 1));
		Assert.assertEquals(
				"f",
				chair.knockedOut(new String[] { "a", "b", "c", "d", "e", "f",
						"g" }, ".hhhhhh", 100));
		Assert.assertEquals("Cassius Clay", chair.knockedOut(new String[] {
				"Emma Sue", "Billy Bob Thornton", "Joe", "Cassius Clay" },
				".hhh", 1));
		Assert.assertEquals("e", chair.knockedOut(new String[] { "a", "b", "c",
				"d", "e" }, ".hhhh", 6));
		Assert.assertEquals("dsss",
				chair.knockedOut(new String[] { "df", "dsss" }, ".h", 1));
		Assert.assertEquals("a", chair.knockedOut(new String[] { "a", "b", "c",
				"d", "e" }, "hhhh.", 4));
		Assert.assertEquals(
				"Cassius Clay",
				chair.knockedOut(new String[] { "Jack Dempsey", "Joe Louis",
						"Rocky Marciano", "Cassius Clay", "George Foreman",
						"Mike Tyson" }, "h.hhhh", 550));
		Assert.assertEquals("b",
				chair.knockedOut(new String[] { "a", "b" }, "h.", 600));
		Assert.assertEquals("b", chair.knockedOut(new String[] { "a", "b", "c",
				"d", "e" }, ".hhhh", 4));
		Assert.assertEquals("a", chair.knockedOut(new String[] { "a", "b", "c",
				"d" }, "h.hh", 1));
	}
}