package com.lam.coder.topCoder;

import junit.framework.Assert;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.lam.coder.topCoder.TwoWaysSorting;

public class TwoWaysSortingTest {
	TwoWaysSorting sorting; 
	
	@Before
	public void setUp() throws Exception {
		sorting = new TwoWaysSorting();
	}

	@After
	public void tearDown() throws Exception {
		sorting = null;
	}

	@Test
	public void testSortingMethod() {
		Assert.assertEquals("both", sorting.sortingMethod( new String[] {"a", "aa", "bbb"} ));
		Assert.assertEquals("lengths", sorting.sortingMethod( new String[] {"c", "bb", "aaa"}));
		Assert.assertEquals("none", sorting.sortingMethod( new String[] {"etdfgfh", "aio"}));
		Assert.assertEquals("lexicographically", sorting.sortingMethod( new String[] {"aaa", "z"}));
		Assert.assertEquals("both", sorting.sortingMethod( new String[] {"z"}));
		Assert.assertEquals("lexicographically", sorting.sortingMethod( new String[] {"abcdef", "bcdef", "cdef", "def", "ef", "f", "topcoder"}));
	}
	
	@Test
	public void sortingMethodSystemTest() {
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"a", "aa", "bbb"}));
		Assert.assertEquals("lengths" , sorting.sortingMethod(new String[] {"c", "bb", "aaa"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"etdfgfh", "aio"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"z"}));
		Assert.assertEquals("lexicographically" , sorting.sortingMethod(new String[] {"aaa", "z"}));
		Assert.assertEquals("lexicographically" , sorting.sortingMethod(new String[] {"abcdef", "bcdef", "cdef", "def", "ef", "f", "topcoder"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"l", "ikuz", "rkarowluagylidigangqotntwhpolrvgw", "geudeuyjztapwekpdfnrgojgoibirtbemzychccopxsem", "zfdfowfrtylutqdkqoseernymcrrwnjppgxbrkbiesjqjhodno", "zfczbsippgcpfdigbztzedgbypefbypcutmtp", "zakoxt", "jourahqtczxatmcqaigbivigtw", "erxniziblcxysbarxkefywzrudid", "kligxogtotucgtxdfofl", "xpj", "fltikqahxqbyfpikaukayvgwedimcxhusfmfsznpxtvxlydfb", "kfiqmkwbqjuwipqcc", "ljkgsogcbitmkgmrkkogxj", "ifvudksrgjpy", "tqnksklnwazifcyrkfw", "mmhapopctvbtjdfszqfgtyvnylziutaeqxc", "chyklqgoljm", "zawuokqcuczggwnqmxhkgbiepnhrdxxhkbyi", "sqestyahzwgxdd", "bxbzsbzu", "swelcpomqjfrvbfojpgmbdzx", "lttkvcl", "vafyhulsaltibmscwmmmqohajwretdrdmpjacoqurv", "triuevrrdtvtortnhx", "nyxbuccsa", "exwbuzokeyimwmuhoibpooawsqfizpcqmbncotdb", "nsaanblewrciyluhprvcyqedjrplacaxawoctfc", "firuqpdmdzujrvpasliwhqogmlwmcrf", "bwryiwmicyzbappgbauvdcftdiutwnvddy", "xglfncezviqjhmakkqdhvvgxtcgxdjnrfhuatmextdwgedyi", "owbexmaajsfvhkhiarzaubh", "hbvjygbotkeofpasqobbaywtyfageksslasnwfsjm", "ezmzjaecpyitb", "fzrjjcjfig", "istnoxqdlwxkgwzbmdypwkxox", "ecenqcziyzquviffogfpajbsvkr", "oddohwgoevpkyglsonfmzfqgrnrxkygqamtrpoddloxouhl", "uwindmlalxytsxlissrwdklkopwzcf", "mifkavjirorfkepyjkoxmwaexgqgpeqcqsdaamdnvrrx", "pefvhfxxxjgqsrqsxlnllvwvajieenkwesewqrzzrsn", "lvibhpjhbdnfgjfdsftknfijqwnxb", "xiklwohgyahifbelchmsejwnklkxttgpxdxyes", "kpmvhtstgcgxjblqjgeqhbfqlpzpasbsbuasytevuruymw", "fgfmbuywkoczpna", "cjmtdwqzkrxbmuplkfrhn", "qhawn", "au", "pakovgzebahmopgi", "iuiqplzgfdwataqjxmkgyilswhmtoosx"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"eet", "yc", "o"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"aqwultybdduqitfg", "nzsgesmgp", "gjsoxixxremxjvzkmbdkczvmcolqawaqf", "jjqeazuxnxxzaeuaornvjgtsadnexqv", "y", "bd", "cyvsdznvhfxivjejmkhpxplfbamhrrtcwy", "yne", "knvdrydv", "vppfqpqdptrbjuzzxwuzo", "vdjcvmlxxlqwnfbjvqzgbtckck", "pieaxzgdwwzozp", "uhoaitjojhrre", "xziviyrezxfhvkzgvjbnrgdctidotj", "slkkgcphvgrpiauqqo", "eflbyuuatanmfyfbwzdioar", "pwbidultcprnbitnvyqzitcrkcnk", "ogptwd", "zofrzdiixspwdet", "lprhe", "vjcfwntkykruqqafayywzpfcqgsbqauq", "fgoyvzwbpllixxucmpzqnukzi", "xyessvgpznyufhwipbwmwhtipru", "jbbovkxecdq", "eugmlzocblejxcmuhyzsxsrqktieuslzaox", "ycivdfwjayvr", "yfvcfyg", "gwoi", "hkdcixncenljyioey", "nqkvrfgidsqbomuzwaa", "oyeeuivrfhawcrbuqlnyuechfnaotrrkrork", "pdpdsebycdfwqfzppspi", "pmgtorztsodjtqnczafqkzozjackk", "fdnkcukrbf", "kvxqsthfykupinzkhubmksvwcjnlepltnfmgh", "auamcvtbgjrnrybzfzdxpt", "xyxmovivlgyqgluqcjayovgcjyplpozohsyzga", "vqudqbmavydmojcokgctqfsw"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"cnsfeoqpdjwtpppbxdzxztxbmcwlbqdrhgavgevwrlqeefj", "ykqbwcerdkgcvjfqmldlcmazzrpmuwqvneujnjkzcdrchw", "fpldzyqekkomentwgmewsnxcvemqtzryomuocfvdbh", "tgm", "uu", "tkcalbnviehhbgsgnglwqnivcfdaxfhtaw", "ktlxraeotikbhzheyapmejzotemvvedfaqmybvycgxzp", "rhxpailipvmnztellsslqjqcwmrjotixzkkrrysbmim", "mmadimspszwawvthkjwmhmxnmmxgzxgpmnbj", "yreembdsgcmaytujldoondszkpanwhugajqjfxmpm", "fqmptpmlrwtwqfksd", "njuiof", "chcpvdagfepaiersiveiia", "flvcnrnfwls", "araozlhntsccbxcvllmthilee", "uaahjpnosjzlrfk", "ekwsenxbaedjksuuhrnwpljvbayrkibcqnruohm", "ngplagvbzspdwuptsc", "yzlhyvbuiljzh", "hikbwlqllimrxbjtatfdlbxqphojtan", "rauwkfsrjtgdepcgcij", "bnicxyrhyppgtvbwnpzyhdgifxusjslyxlzugl", "hywukbrkuzrapluzeayexpjfepdoasspemy", "uwnsabbqogkactkzvnvsxkwauchfzvojtluaieqwncnzjkjak", "cuumgvvcq", "uzsgeokpwcphxtidcbicriv", "oirqkucr", "lqztdphqokahfpwnrgufmpidfgkp", "ahznuwdobkobjvuuarvwfbkszrsupwtwy", "qsht", "hhzamudinmixnromuguowptoncluem", "pjnkewweuohizzvirrhlvddg", "rlszirzrwbcevkglwuiqqtfknpbdiaeffvqib", "sqsqggiugbhwqcutgxftebbofmjkvsqtndglbcnkzbacfatv", "klwthhzwjyms", "mdgpcuekicknvkdodsoujkspqhqjs", "qypyjjvzwfnbcgogxnfztyrhkbjwcnthwmiagninowydv", "owbqdyoktegohw", "hwdnfnwadj", "ilzgooemublhwmgnrvgnidhozqwqgivozqutwbmwjzfwjlcmos", "megliizlhvnudshzecrduvnrwix", "sdjuw", "bgoongfsvbcurzazobdfwdbysqphinxx", "biuvhwpiycmqijqmmwqu", "bwylwirtnxmiolnmlewnd", "wbnojinxxbnbmvfckytjcjtkwdiqhkjygbtqalmy", "fyqtyeohqlsmguwk", "e", "zpqpveplazcqskoipoghoplxvn", "fyozmeq"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"gtzuleanpforkhgzwjjlyzuoqcny", "pxcwicphyxqqhxbdlmbamgyfmberty", "xxfuvlzdguitmn", "zehdyuzrucwjzfempyprsqbotwrmvxlknd", "vmvsuebvv"}));
		Assert.assertEquals("lexicographically" , sorting.sortingMethod(new String[] {"afzmd", "aizgprtuchtxouwtqgzxnvmcaoitzpxqrcaltloukiygnmc", "akqkikdgnhduisqawpznqxpdlnfwslquxoptulfxlwuufinsdf", "bjltywdrgpjteyg", "cwewapumhggpsescaudk", "fzkexkpdvllsozehdqqkerhvlrc", "hsresaf", "nrgvhmfueoaqvxodwzibkcdpdnafhepeujbxoomxmrltozlkc", "sgoqtrfaehdncijxvoilpxvnkjoiiaxpclzlkmowrx", "wkwdjzagzyklffbhdqkbadssly"}));
		Assert.assertEquals("lexicographically" , sorting.sortingMethod(new String[] {"abysxnbvfkwunyyhlxw", "axcwhthywjbdwfipxppiftz", "bcslvlwvscjxvotcychgkqbxgedequaimpniyykkblnf", "byiuyuqcmzhgyxnfygdlawofhmq", "cfhznzcbgjomtq", "dwzatynzbkhrtqwebavbyuwfzuoalbpjbiqpkmjmwvhwros", "ejpokryfbcwhhopypkgxqmxwllsfhryxywvt", "fhlucsdmuyvfxmeyeawufpdinvtaeayc", "gijiqtifeqgprrsljqsfeuxezi", "hxcbhjzudcqgnlwymr", "jpu", "jwezddcdmfiexfzvlvuqeyikrzszxmmykxjjzph", "kcaemhsoaryuclji", "lnxcnk", "mdfrpctoabvwxxnahntmwcejlzikxvjxuizcbjziuueap", "mkzrfmsrxcbbxmvirjtedgubgqvqfvkzxgvpre", "ohcjwhevzgozzrzzlsedhnnneeiyqapvolhxnpxciolvoideop", "pozitloo", "qhqfvoznowmhykaoiljyde", "qjlt", "qwoqwvyouwlhsnimg", "raodg", "rzyjbktroijgesnsymxneugihfkguhdiigircekydk", "sbtniiniplvdtiidgfppabaurfgtymshpcoxieyckbuxlp", "shikwzifx", "tdwdxauslyafheejutyfqbggr", "uhrhpcwmgpmxkjxspunfbjsdwssnhbx", "woobpulivwadzwyedhtvdbweksasabprgej", "xdpslsdwyrvpijyzovmswpbnqtzjkb", "ykmsueugxpwhiijbrejgzbiqrrzputxthf", "zbhmcusvvcxdzltmgxercxlidnvqrargmoeypvziqavylnigv", "znjtdubruuixa", "zqnasxlzbpcducakcineezdnavfwskjfxquhhyvt", "ztbxwnlnparoeuuourpljzcazsgqpkswhsrvr"}));
		Assert.assertEquals("lexicographically" , sorting.sortingMethod(new String[] {"aammesir", "airnwiyjkfkvnvxymfjffpmkbeexkzhtrlzqcaouv", "ap", "asgadxjpyv", "axsbaqdkjyrexizoesdwmxffumiffvcpiuiv", "epw", "ftkdpkbhkzrntkvqmjfyfqplkmypbfxrmjpfv", "gbluusbajlqkcmstqpvrizhilgdowwgzxagjxwhuqigvygdauh", "gnxkzdchewayqgre", "iektaes", "ipjjtxujhakuagmtugmwfmqosfcjuxfsdcflli", "iqrhmdctmjw", "jiqjydgknrdghodpexgusxacw", "jqdjoukgchwgaybzhawfptomnidklddtruolnqnkkqr", "kljyrdwzzxrkdopzyvaisownorpomdsqnbpwlojnih", "lkhtkudnfwrjwmnpglmlx", "lqbuldidwjmcvztkhxvwepcmojekgbjgvfkmbtv", "mlryulbygxztogfztt", "mnkuqppiveqjx", "mqdpdmfbqbqdhkt", "niqfayznbkwxmqryjconiyeoiqarfyqwkuwvkikaicranf", "njlyqffmcacsms", "nynbxatjhoxjycjjxsabonxiiracnyvygsapkess", "oahwgixpdlteiwfmotaieoybveqhbwezxkpdbknuhcrssmlc", "ojinkxugfbqerkxvfgpwqv", "okdygdcvamlnieryslnctypqikeweywd", "oodbdjtrhgvnutffchnqjcus", "owuesbujabjlpzqwx", "pcarfnbqbdnlrxhnoicyedmlqvx", "pstio", "qweo", "rkmofiqsccqfvwpyirncomihjr", "ruvvthtueyiomqemcjuczhwqrdmfnrdbnnwjfnkuprcepijot", "svliibneqkbxhbmlbjluaesdmpvjbtetimisvnausxgds", "thofhbhmlptqyplytowxztwrefkussnbi", "vipemnlovpdezjzmvfu", "vqlpfhxtzvbbkdifcpnetjalmjzuanklifwclnmodijj", "wavygimsoyykcvsolvpthoxfsfofdzc", "xzbydqxfhloaksbypocz", "yearskdbcadzuxnjoncforhnewgouwjtsg", "ypjnhc", "yxwivsvnkyowhhhiuaooucknkooo", "z", "zeheffbuhyobtqtringlixzmnolec"}));
		Assert.assertEquals("lexicographically" , sorting.sortingMethod(new String[] {"azfntrmdky", "bkpjrfrsgtkemurjccsrrpwqazxhbsshovcbfcgaxzsdzr", "bobkxnhml", "bsdbnreojthqdjgavuqwdepamolkotpsndddquulkkdigiqsc", "bstoizmdcyhfwqmbslailekjemciwiw", "btslshcnxsdmzlwozgtmjspjlqqptkiimlmchgapfxgdkxq", "cjjmavfcjycnzutszeqnsjapvdsjrtremn", "clcheruvtspakmevnssuypzjjnge", "clsqjevodtjodfdqnch", "cucvj", "dgzplmjxfumpqsgozxpqhcfkyesmombgkoghgxwhvc", "dwnhnryahrllifds", "ekjchdiccxaceknszxivoxockbffmrevqurmkxuspqdp", "feypukontovxzkhxrxedfaqagxqgykhnxhjvtryxrvwhr", "hanqdxoxxifgjenfwn", "he", "hefaiqajrldmiupupejqjittahrpecwhdkmiskoyqnn", "hrqauokfrhjxsribhonokbavgzpqnu", "igrbpzxslkighxlnprluyqorj", "lzhuuhyi", "nehe", "nqwbgegvxxiklzgleczrfnxqlbtrwbtihdmygecttzraosng", "othgnimdprix", "pbtdowm", "pjktrjwfsrdbnmvam", "psserecwuvauqchokvwtslfbtfspdwtkhbqjtqu", "pxofjrhlocmzpudhyrztxyqwipf", "rlioojunfwhodh", "ryprgiemtqminbvcizrdduprbkxnkrcrmyvecjkcbyzikmbsbe", "sddbqevkvwknede", "sptquhjitwogynpagadezywhgchznlcvgktnrz", "suyxsgoxxhsbg", "uealbumytrwboilwdmtrnojwgehlufossxrwxwwyt", "uyjezxcpnyshtqaejwmktienaljzbxfzp", "uzcyiiplfdkfucxonczspbaiufuogqjpvxirs", "vpekyscdrkdpzlbggabwsnuogvkzl", "vqovvlodzpgzzwloghxxixedbaqvirnutwv", "vrhngcnqivudxsnowhfcsy", "vtysdhsbdvzdklykgrfkhmnw", "wbsrexfyyplfcpxxrzlbx", "wjeeiv", "wtzilytrwfrozfzduxorolvqibymmjdarumx", "x", "ydujdlfrhhbutnbtlxpictrbzd", "ysbsvbfxdzaqzohylfyagyublorgexng", "zhqcqoifqqfsdzmhsntowhv", "zkoupjmckciarpkdgjcl", "zpaesbwmrbq", "zqt", "ztmsoylsvmcfhsfsxkruvbcadncudmxbgjfutacl"}));
		Assert.assertEquals("lexicographically" , sorting.sortingMethod(new String[] {"aashzduvulbyfs", "bdwaqncukpjcuym", "cavofauuqhxdtkdwbheqnaieyteslucwaiecyeyh", "ctrj", "djztuuwexzwgweytulhzmdbkagxuxgtxgkbmhwwtzdxmwr", "educq", "eenyktohgmwzdtugjrawdjzkaco", "gbjmguob", "gpkaqomodcdrdgtgxhxkhvonqbbnberchdoned", "h", "hhszcdlzaajtgvvwmbivynyqixenlka", "hrizcoz", "hyjixnugqmdgkrbnuojktobabyduaa", "igljmykaek", "iitbxfxopzznualdwywymgyfysxmslwskfdosssaaxrz", "iulhtazamupnqkxllc", "iumymgbbmurertmhhgwqwrjvfuimkotdnx", "ixnafqaocjmlzsttuupeoitxxdbxyqnsjkgwhoc", "kydhkosudwkeuixyuhrjjerqrprzckjwkvpnrmlbcokqowuaku", "mcibrakvgpanofxcucwee", "mxieqrkznzgxzgjhjojekuaearbqwgwpnmpqkrdwmedppqbi", "mxpwbjfclbzqszpediayyapxyxmdxknow", "nkjctkghaikcvvmozjhxoylia", "nreqnrmfgvujppcpbdpj", "ntdawymqfguebfqjleaqhv", "nwxgrqffcltpsvmgyagevfecnzxsuabqyulwsexpdd", "ogcmdt", "oiyjbwcokwcfwksyyllvzbjvtzdyrdokrdkyzuocaaomzku", "pjxjqvfue", "qpzcevzdclgqsjzmhwtoafd", "qyxmgtzomgkiejcacphfugairvczmbgqxofyiillc", "rbrksecjgawgofvxypwhkrnl", "rmdaahpkwymktkhpaguvslwpgrppaonvevngkzoqfin", "rxy", "sfxjfkkvtlc", "snwwamuxdcstfhhtdnwjbvlvmpunukaumfrqk", "sqojrrjipevfjuqv", "unogeqpqvwohidevgujkpkssnjfpjosisgilksflrcnjd", "unuqyrklczhxevgsljpqnkohfggi", "urzjajrgjovpn", "vlsjxerazwdbbtgdcammesprndegr", "vnxxlxmqwzoxeyactshkgouimbijqgbkfrpgpoiqouxymzbdq", "wejerfwosrcfxksgoctvdrylgltcbynbamka", "wudpxchdqrfbibddq", "xrmviknmheffmwfokcrimgpmodtvogdpakz", "xwfkgfmwlyjoevvkrcb", "ymecrvjbkhywkactinznzeutphojafjk", "zmieidjtwevw", "zpsrhnhpvexaunbvtetkccjviu", "zy"}));
		Assert.assertEquals("lengths" , sorting.sortingMethod(new String[] {"j", "gx", "fpx", "uksb", "qjcrv", "xvqpxao", "xcofxxkxqf", "yxdjgxlpwcee", "jomaebvzgjunk", "qfdyiuqtqplxsr", "tixsswiyxdcfwub", "lhevifpalxbneumah", "guisjvijxndhojiljj", "phzdgixuevzpgxdqnob", "tlbnirbrfyywinvydfnypv", "nfesyoqzpwftbdbecgmjzmh", "qqdbakeennvfudtxrbqevmei", "mglctxkpjvxtlrkvhgrxamkuk", "oxhjbnvbytdfqatwbbjttfivew", "ymjkmvukmhsxmnofslliahvyivn", "mrmqhwoakuxvxdkwmygrnjukjnof", "cucswzgccwiiakzscskszglpcziox", "xzhvtaclybntewsrsxmtihyeuhiwfn", "yqdxpmarhbkujsdihabmwcbacviswyx", "vaajxctomifiuavccnzkpalpmehyhluz", "oyylqmurbowjjoxgpbycddqhqaxeqwioi", "qdsttxkdkauodhyuecolrhudcktfxhmdeo", "gslosenxypuweeibwrimiojxlugahgcqfex", "cajopdvilnwhikyhqaqvigrsiovtyfztzvgptzs", "zocywnmozdvxowbuogzihzaowzspdjmbkrysqjbk", "ppjrriluiccuajlyjrrrlxlfrhzwqbrsluchhitmler", "ujocjyvqwljbslgbxuycuymhionixzgzbhbfhsiwiyfa", "bquumkhpdxdgjoratcnnoojkhzwtdrruzcpdvwzuqyeuj", "rxyngpcgbfcffjfxbzqpuwnzrxloaeinzwkfhttrxdnzpr", "enypnuzpgsntgswoxjfkdcimukwbjckrzjpnvqmtdrmamex", "xlxzoqlzzylkhanoworfdnebxtziryplssecmxvxyyayywro", "taycspqehkxbeoqfnnqnjzfgumozjvamavwxobrqbdehywnho", "njnkfgxserrcywqhkxeipjbecqqhsbzzprnlflwngcagdudmhj"}));
		Assert.assertEquals("lengths" , sorting.sortingMethod(new String[] {"lyaj", "svoylrzhc", "sbyygbnzahjrz", "owtjzvjalqjnua", "wnzjdotdwyaecsxs", "drxczymadmiivkikzho", "vcanvwhvpydncyqtcmhpvpmx", "gjcqnsgmjhpuahtmselzjpmolcdd", "iynqhzvgkdqjfojrokrlmylsdmjxp", "omtbcgbseczuwrojzqbzihitlrdyyh", "pynddzryqtjgbxackkezufutzxdeldx", "iakothheytbzxnikmwfgwvsvrxciface", "dwruiffrhmigxqdqzwedjkhatngvsujfy", "glraaajjdjixlvhxgddbkyqjlmjwfakjjm", "tfyihufxwbxhgcddvhwswpjecwwmtukdgvw", "lftjjwmolrwevqmnadcsfnhcmrdiuhzyuybi", "twkccksiphkasdktekccuonjqtdnfpbaebesl", "dkvcehcipglitvtijujxztkrwbavjupbjllndj", "pvpgspiywyeunlhboprlnfzlmnscmptgtguuedl", "uvnlbpjffhplqqcwzxmppixejbyifbzqpwblpvuw", "xpqueaqayrutkbedbneojvgcotkgfkwcuunxhddbsx", "kjcjxdesranvgybgchkhziewpkfcqvaqtlmjnompmjx", "dtrzrhtyuuitadyrdtymlcuzpsvaorajbjcjcauiimpev", "mxrnzfaygmrpjbtxufrrovixncoflhckfsojpywwucpwnhd", "jxlcfpronoobwtcibwzqrzofxzpufpijihtcophyzocdcdzp", "gurlqcwlvcumojevqzmqvvpwzcvogtgxygpvcoaqolsaubtfdt"}));
		Assert.assertEquals("lengths" , sorting.sortingMethod(new String[] {"y", "jg", "lnk", "lytc", "ykcjd", "fqhjff", "fmgmvwi", "jijnhnod", "gopncpscp", "yjvpdqyczd", "gevuldgobnj", "yrzaozaemhjk", "ibxnxxdgmrsrk", "hfpqriqvcmijjy", "rmevjbnxzdgecya", "yxfpuewajydvdbae", "egptslpmhkyfejfhu", "coxxghtimkrmtovquw", "euonmisuiiifispnqcm", "ageswhkuvmzcdqwfbuqi", "jsxdniiwcrowxklaoujup", "eslzvwgubeozbxbejldppl", "xigyafbpaqwzezcauaxrbzt", "nhzanwkccecyddztwpdsxkou", "oyhtixvkmljrrtoyvdgkwbbyb", "cnzzvrtexljnszjsqsujntldsu", "yukksundsppoawlmgvbpspohtyn", "svbzthxgjlcpwrhptuyjclijfzoi", "rpidxqaquyjlydstruxfisrgxbmct", "llehfmfabqddtimukhdkguknkomvnd", "jlzzgcjjsxtynsrbhmphqknicxbzvmp", "wlhhqiopwmkexvbueqqklwzzmdzcpzdc", "iimdlykzrrodpxeiwylpkiuajdlqvracv", "gupyohsbekmndgpqkkawpddlcopgwdubnd", "ricpmtypbemgcfpseeemqjsxampffinpapy", "amxhqehzvvaefoiubbbymtnajkrvsbrupkyp", "otxfnicqeqyqxfezvphmqbnbflnsoacibftei", "sshagdetkcketazeckfacqyecctctzhasfyhyw", "zbmrglzsqjobqqcylffoldgzbwizcqhxopassfk", "jkvsmjzhakqmjaaryzvjiohrflrzhtbokjpjmfhi", "ecfockyvqenmaakvfvoumragtgpwyrimhovstjkzk", "vqxkfuxqvdjcgzqwvidomnxtfsumrmyvcoohspexzf", "jlugmjksulndpcvuxvklolgueojfwdaloicbufoyslt", "iutqbnopmbrajpfaicjqdizoihwicqcxlucicthqabet", "owrafagliciirjvwwypdvkctdekxgcbyznaeuutegczgy", "nalydkohsiluedwvwclqdiiijqbosjnktlftgguuhdqkra", "jskyijyuidybivnuiaafotbxfuhokirreuujbfkbbfujwys", "bfwkqduhksrehwtqbplykpwfloivhzvpeaapnyypfxfovzsq", "xivaraklpzacrrwtaigsgniuasbbyfdhcoqbhwdfthskwtxci", "qczyxlvjlkmlxepywiwztznmkvyluhqjjojzwwypnkjqbdjplw"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"a", "aa", "aaa", "aaaa", "aaaaa", "aaaaaa", "aaaaaaa", "aaaaaaaa", "aaaaaaaaa", "aaaaaaaaaa", "aaaaaaaaaaa", "aaaaaaaaaaaa", "aaaaaaaaaaaaa", "aaaaaaaaaaaaaa", "aaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"z", "zz", "zzz", "zzzz", "zzzzz", "zzzzzz", "zzzzzzz", "zzzzzzzz", "zzzzzzzzz", "zzzzzzzzzz", "zzzzzzzzzzz", "zzzzzzzzzzzz", "zzzzzzzzzzzzz", "zzzzzzzzzzzzzz", "zzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"a", "ab", "abc", "abcd", "abcde", "abcdef", "abcdefg", "abcdefgh", "abcdefghi", "abcdefghij", "abcdefghijk", "abcdefghijkl", "abcdefghijklm", "abcdefghijklmn", "abcdefghijklmno", "abcdefghijklmnop", "abcdefghijklmnopq", "abcdefghijklmnopqr", "abcdefghijklmnopqrs", "abcdefghijklmnopqrst", "abcdefghijklmnopqrstu", "abcdefghijklmnopqrstuv", "abcdefghijklmnopqrstuvw", "abcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxy", "abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstuvwxyzz", "abcdefghijklmnopqrstuvwxyzzz", "abcdefghijklmnopqrstuvwxyzzzz", "abcdefghijklmnopqrstuvwxyzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzzzz", "abcdefghijklmnopqrstuvwxyzzzzzzzzzzzzzzzzzzzzzzzzz"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"d", "de", "def", "defg", "defgh", "defghi", "defghij", "defghijk", "defghijkl", "defghijklm", "defghijklmn", "defghijklmno", "defghijklmnop", "defghijklmnopq", "defghijklmnopqr", "defghijklmnopqrs", "defghijklmnopqrstu", "defghijklmnopqrstuvw", "defghijklmnopqrstuvwx", "defghijklmnopqrstuvwxx", "defghijklmnopqrstuvwxxx", "defghijklmnopqrstuvwxxxx", "defghijklmnopqrstuvwxxxxx", "defghijklmnopqrstuvwxxxxxx", "defghijklmnopqrstuvwxxxxxxx", "defghijklmnopqrstuvwxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "defghijklmnopqrstuvwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}));
		Assert.assertEquals("lengths" , sorting.sortingMethod(new String[] {"a", "aa", "aaa", "aaaa", "aaaaa", "aaaaaa", "aaaaaaa", "aaaaaaaa", "aaaaaaaaa", "aaaaaaaaaa", "aaaaaaaaaaa", "aaaaaaaaaaaa", "aaaaaaaaaaaaa", "aaaaaaaaaaaaaa", "aaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaa", "aaaaaaaaaabaaaaaaaa", "aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"a", "aa", "aaa", "aaaa", "aaaaa", "aaaaaa", "aaaaaaaaa", "aaaaaaaa", "aaaaaaa", "aaaaaaaaaa", "aaaaaaaaaaa", "aaaaaaaaaaaa", "aaaaaaaaaaaaa", "aaaaaaaaaaaaaa", "aaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"mx", "mxel", "mxelotoq", "mxelotoqqs", "mxelotoqqsudyy", "mxelotoqqsudyyivtx", "mxelotoqqsudyyivtxvcz", "mxelotoqqsudyyivtxvczylmlv", "mxelotoqqsudyyivtxvczylmlvuj", "mxelotoqqsudyyivtxvczylmlvujnhbdh", "mxelotoqqsudyyivtxvczylmlvujnhbdhbz", "mxelotoqqsudyyivtxvczylmlvujnhbdhbzx", "mxelotoqqsudyyivtxvczylmlvujnhbdhbzxkwqm", "mxelotoqqsudyyivtxvczylmlvujnhbdhbzxkwqmtz", "mxelotoqqsudyyivtxvczylmlvujnhbdhbzxkwqmtzhjxzl", "mxelotoqqsudyyivtxvczylmlvujnhbdhbzxkwqmtzhjxzljr", "mxelotoqqsudyyivtxvczylmlvujnhbdhbzxkwqmtzhjxzljrk"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"h", "hg", "hgc", "hgcs", "hgcsp", "hgcspn", "hgcspnq", "hgcspnqc", "hgcspnqco", "hgcspnqcom", "hgcspnqcomv", "hgcspnqcomvv", "hgcspnqcomvve", "hgcspnqcomvvef", "hgcspnqcomvvefn", "hgcspnqcomvvefng", "hgcspnqcomvvefngb", "hgcspnqcomvvefngbd", "hgcspnqcomvvefngbdk", "hgcspnqcomvvefngbdko", "hgcspnqcomvvefngbdkos", "hgcspnqcomvvefngbdkosc", "hgcspnqcomvvefngbdkoscq", "hgcspnqcomvvefngbdkoscqg", "hgcspnqcomvvefngbdkoscqgg", "hgcspnqcomvvefngbdkoscqggh", "hgcspnqcomvvefngbdkoscqgghj", "hgcspnqcomvvefngbdkoscqgghjo", "hgcspnqcomvvefngbdkoscqgghjow", "hgcspnqcomvvefngbdkoscqgghjowc", "hgcspnqcomvvefngbdkoscqgghjowcx", "hgcspnqcomvvefngbdkoscqgghjowcxf", "hgcspnqcomvvefngbdkoscqgghjowcxfe", "hgcspnqcomvvefngbdkoscqgghjowcxfem", "hgcspnqcomvvefngbdkoscqgghjowcxfems", "hgcspnqcomvvefngbdkoscqgghjowcxfemsh", "hgcspnqcomvvefngbdkoscqgghjowcxfemshx", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxn", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxnt", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxnty", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyi", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyiv", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyivd", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyivdn", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyivdna", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyivdnaj", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyivdnaju", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyivdnajux", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyivdnajuxo", "hgcspnqcomvvefngbdkoscqgghjowcxfemshxntyivdnajuxom"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"u", "vd", "wfj", "yhlw", "zjnyh", "zkoyjd", "zkozkdj", "zmozlflw", "zmqznglwz", "zmrznhmxzn", "zntzphnyzpl", "zptzrhnyzpla", "zrtzsiozzpmcd", "zrtzsjpzzqmcft", "zrtzslrzzsmchta", "zstzuntzzsoejuad", "zutzvouzztpglwbft", "zwtzxouzzvphlxbhtj", "zxtzzqvzzvphmzbjtkm", "zyuzzsxzzvrjmzcjtmmw", "zyvzzszzzwsknzclvnoyn", "zyxzzuzzzyskpzdlxpqzpc", "zyzzzuzzzytlrzelzrqzreu", "zyzzzwzzzzumtzgmztrzrgww", "zzzzzwzzzzwntzgozurzriyxf", "zzzzzwzzzzwntzipzvszsjzzfz", "zzzzzwzzzzxntzirzwsztkzzgzh", "zzzzzwzzzzxnuzjszytzvlzzgzjo", "zzzzzyzzzzyowzluzztzwnzzhzlox", "zzzzzzzzzzyqyzmwzzuzwozzjzlozl", "zzzzzzzzzzzsyzoxzzvzxqzzjzlozll", "zzzzzzzzzzztyzozzzxzzszzkznozlng", "zzzzzzzzzzzuyzozzzyzzuzzlzoozlohx", "zzzzzzzzzzzuyzpzzzyzzuzzlzoozmpixf", "zzzzzzzzzzzwyzqzzzyzzwzzmzpqzmrjzfr", "zzzzzzzzzzzyzzrzzzyzzwzznzprzorjzfrq", "zzzzzzzzzzzyzztzzzzzzwzzpzptzqskzfrrs", "zzzzzzzzzzzyzztzzzzzzyzzqzpvzsumzftstg", "zzzzzzzzzzzyzzvzzzzzzzzzqzqxztumzhvutip", "zzzzzzzzzzzyzzxzzzzzzzzzqzqxzuunzhwvukrz", "zzzzzzzzzzzyzzxzzzzzzzzzrzqyzwwpzixwwlszj", "zzzzzzzzzzzyzzyzzzzzzzzzrzsyzwyrzkzwyluzkf", "zzzzzzzzzzzyzzyzzzzzzzzzrzsyzwyrzkzwyluzkga", "zzzzzzzzzzzyzzyzzzzzzzzztzuyzyyszkzxynvzmibh", "zzzzzzzzzzzzzzyzzzzzzzzzuzvzzzyuzkzyynxzmibjp", "zzzzzzzzzzzzzzyzzzzzzzzzuzwzzzzwzkzyznxzmjbkpu", "zzzzzzzzzzzzzzzzzzzzzzzzvzyzzzzwzkzzznxzojblrua", "zzzzzzzzzzzzzzzzzzzzzzzzvzzzzzzyzlzzznyzpjclswbf", "zzzzzzzzzzzzzzzzzzzzzzzzxzzzzzzyzmzzzpyzpldlswdfs", "zzzzzzzzzzzzzzzzzzzzzzzzxzzzzzzzzmzzzqyzrnfmtwfhuk"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"g", "kp", "krh", "ksles", "mtmfslj", "nxogwpnz", "pysjzsqzy", "qyslzvszyct", "szspzwtzygtp", "wzsqzxuzykxsc", "zztrzzyzykyueoa", "zzwuzzyzymyxgpbid", "zzwyzzyzynyyjrblhhg", "zzwyzzyzyoyzkudljihdd", "zzxyzzyzyoyzkvflmkidhe", "zzxzzzzzyoyzmyilplieihii", "zzxzzzzzzryzpylprniemhijcv", "zzxzzzzzzryztypptnmfnkjjgxrr", "zzxzzzzzzrzzvyspvnmhpoknhzusa", "zzxzzzzzzvzzxzvsynpitqkphzvubw", "zzxzzzzzzwzzzzysynqlwqlrhzvueyio", "zzxzzzzzzwzzzzysypuoxuotlzyuizmst", "zzxzzzzzzwzzzzyuypxoyuqvozzxlzptxlq", "zzxzzzzzzwzzzzyxytysyxqwqzzzpzsxxluh", "zzxzzzzzzxzzzzyxyuyuyxuwqzzzszvxypwiil", "zzzzzzzzzxzzzzzyyyzxyxwytzzzszzxzrxjkljj", "zzzzzzzzzxzzzzzzyyzyyxzzwzzzszzzzvxlmnkjoj", "zzzzzzzzzxzzzzzzyyzyyxzzwzzztzzzzzzmqonmpnmn", "zzzzzzzzzzzzzzzzyyzyyyzzwzzzxzzzzzzouooornmrzf", "zzzzzzzzzzzzzzzzzzzzyzzzyzzzxzzzzzzsyqqqvoqrzjcc", "zzzzzzzzzzzzzzzzzzzzzzzzyzzzzzzzzzzszssqwpurzkfcvp"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"bt", "cugo", "dvgobi", "ewgpcjjt", "exgqckjuh", "exhqcljuhii", "fyircljuijia", "gyircmkvjjibtb", "gyircnlwjjjcubo", "gyjrcnlxjjkducom", "gykrdnlxjjkevdomni", "hzlrdomxkjkeweonniu", "hzlrepmxljlexfpnoiug", "hzlrfqmxljmfxgpopivgp", "izlsgrnxmknfygqpqjwhqq", "jzmthroynknfyhqqqkxhqqfr", "kzmthspznlofzhqrrkyirqgrre", "kznuispzolofzhqsrlyirrhssel", "lzovjspzomofziqtrmyirshstemk", "lzovjtqzomogzjrusmzjssisuenkc", "lzpvktqzpnohzjrutmzjtsituenlds", "mzqwltqzpopizjrvunzjutjuvfnmesg", "mzrwlurzqppizksvvozkvukvvfnmeshc", "nzrwluszrpqjzksvwozkwvkwvgomfshcyn", "nzswmuszsprjzktvwpzkxwlxwgongsidzozy", "oztxmvszspskzltvxqzlxwlxxgongsidzpzzy", "pzuxmwtzsqtlzluvyrzmxxmyygpogsidzqzzysd", "pzuymwuztqulzmuvzrznyxmzzgqohtjezrzzztewt", "pzvzmxuztqulzmuwzrznyxnzzhroitkezszzztfwuil", "pzwzmyvzurumzmvxzrznzynzzhsojtlfztzzzugwvjms", "qzwznywzvsunznvyzsznzzozzisoktmfzuzzzuhxwjnsu", "rzwznyxzwsuozovzztznzzpzzjspltmfzuzzzuhywjosvwj", "rzxznyyzwtupzpwzzuznzzqzzjtqlumfzuzzzuhzwjotwxkky", "rzxzozyzxtvpzpxzzvznzzrzzjtqmumgzvzzzuizwkptxxlkyx"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"f", "ft", "ftw", "guww", "guwwo", "hvwwoc", "hvwxoct", "iwxyoduv", "iwxyoduvx", "iwyzpevwyd", "ixyzqewwyef", "jxyzqfxwyffb", "jxzzqfywzggbl", "kxzzqfyxzghbls", "kxzzrgzxzgiblts", "kyzzrhzxzgibmtti", "lyzzrizxzgicnutjl", "lzzzsjzxzgidnvtklc", "mzzztkzxzgienwuklcq", "mzzztlzxzhifnxulmdqb", "mzzzulzxzhifnyvlmeqcx", "mzzzvmzxzhjgnyvmmfrdxf", "nzzzvmzxzikgnywnmfsexgy", "ozzzwnzyzikhozxnngtfyhyi", "pzzzwozyzikiozxnogugzhyix", "pzzzxpzyzjkiozynphvhzhzixm", "qzzzxqzyzjljpzzophvizizjymr", "rzzzxrzzzkljpzzopiwjzjzkymra", "szzzxrzzzkmkqzzopjxjzjzlymsbv", "tzzzyrzzzlnkqzzppjyjzkzmzntcvm", "tzzzyszzzmolrzzpqkzkzlzmzntcwnv", "tzzzzszzznpmszzpqlzkzlzmznudwnwq", "tzzzztzzznqntzzpqmzlzmznzouexowrj", "tzzzztzzzoqouzzprnzmzmznzovfxpwrkd", "uzzzztzzzorovzzqsnzmznznzowgxqxrkde", "uzzzztzzzosovzzrsnznznzozpxgxqxrleen", "vzzzzuzzzptpvzzrtoznznzozpygyrxsmeeol", "wzzzzvzzzptpvzzsupzoznzozpzhzsytmffpmn", "xzzzzvzzzpupvzzsupzpzozpzqzhzsytngfqnop", "yzzzzvzzzqvqvzztvqzpzpzpzrzhztytngfroopv", "yzzzzvzzzqwqwzztvrzqzpzqzszizuytnggsooqvn", "zzzzzwzzzqxqwzzuvrzqzpzqztzjzuztnggtporvnq", "zzzzzxzzzqxrxzzuvszrzpzrzuzkzvztnghuposvorp", "zzzzzyzzzqxryzzuvtzrzpzszuzlzvzuoghvqosvprpc", "zzzzzzzzzqxrzzzvwtzrzpzszvzmzvzvpgiwroswqrqcn", "zzzzzzzzzrxszzzwxtzrzpzszvznzvzwpgjwsoswrsrcoz", "zzzzzzzzzryszzzwytzrzqzszvzozwzwpgkwtotxrtscpzu", "zzzzzzzzzrzszzzwztzrzrztzvzpzwzxpgkxtpuysutdpzus", "zzzzzzzzzszszzzxzuzrzrztzvzpzwzyqhlyuquytutdpzvsg", "zzzzzzzzzsztzzzxzuzrzsztzvzqzxzzqimyurvzuutdqzwshu"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"wpviz", "wqvjzifcem", "wqvjzjgdenvd", "xrvkzkgeeoveb", "yswkzkgffovfcn", "ztwlzkhgfovgdnxnv", "ztwmzkihfovgdoxovkfkqh", "ztwmzkihgpvhdoypwlglqiqmrh", "ztwmzkihhpvhepzqwmgmqiqmrikr", "zuwnzkihipvhepzrxnhnqjqmrjksk", "zuxozlihjqvhfpzryoioqjqnskkskj", "zuxpzmiijqwifqzsypjorkqoskkslkdrgoz", "zuypzmjikrwjgqzszpjoskqotkltmldrhozhnlj", "zuypznkilrwkhrzszpjpskqotklunmdrhpzholjrcvb", "zvzpzolilrwliszszqkqtlqpuklvomdshqzipljsdvbdkewm"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"ez", "ezg", "ezgjf", "fzgjfzbty", "gzhkgzbtzufq", "hzhkgzbtzvfqdeaxx", "izilgzbtzvgrefayxo", "jzjmhzctzvgsegazyoh", "jzknizdtzvgsfhazyoialpj", "kzknjzdtzwgtfibzzpjalqknhx", "lzlnkzetzwhugjczzqkbmrknhyfug", "mzmolzetzxhvgkczzrkcnsknizfugjy", "mznolzetzyhwgkczzrldntknjzfuhkzzk", "mzopmzfuzzixhlczzrlentknjzfuilzzkf", "mzpqnzfvzzjximdzzrmfntlojzgvjmzzlgtx", "nzqqozgwzzjximezzsmgoulokzgwknzzlgtxb", "ozrqozhwzzjxjnfzztmhoulplzhwkozzmgtxciynjc", "pzrqpzixzzkxjnfzzunhovlpmziwkozznhtxdizokdru", "qzsrpzjyzzkxjogzzuohovmpmzixlozzoityejzokdsulo", "qzsrpzjyzzkxjogzzvoiovmqmzjxlozzoityfkzpkdsumoyb"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"d", "dama", "ebmay", "ebmbzve", "ebmczwfwm", "fcmdzwfwnpcj", "gdmezwgxoqcjrqi", "genfzwhxpqdksrjlx", "heofzwhxpqeksrjlybq", "iepgzwhxqqflssjmzbqa", "jfqgzwhyrrflstjmzbrbubn", "kgrgzxhyrsgmttknzcrcvcnv", "lgrgzxhzrsgmtukozdrdvdnwul", "mgrgzxhzstgmuvlozerewenwulltb", "ngsgzyizsthnuwmozeseweowvlmtcggi", "nhsgzzjzstinuwmozftfxfowvmnudggjx", "nhthzzkzsuinvwmpzgugygpxwmoveggkym", "nithzzlztvjovxmpzhuhzhqxxmpwehglzmops", "njuhzzmzuvkovynpziuizhqyxmpxfhhmznpptjd", "okvhzznzvwkowzoqziujzhrzxnqyfhhnzoqqujefa", "pkwizzozvxlpwzorzjujzhrzyorzghinzorqujegat", "plxjzzozwxlqxzoszjukzhrzzprzgiinzprrukfgaungw", "qmxkzzpzxxlqyzoszkukzirzzprzhijozqssulfhbvngwfyz"}));
		Assert.assertEquals("lexicographically" , sorting.sortingMethod(new String[] {"aaa", "z"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"etdfgfh", "aio"}));
		Assert.assertEquals("both" , sorting.sortingMethod(new String[] {"a", "aa", "bbb"}));
		Assert.assertEquals("lexicographically" , sorting.sortingMethod(new String[] {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "z"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"doggggg", "apple"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"a", "bbb", "aa"}));
		Assert.assertEquals("lengths" , sorting.sortingMethod(new String[] {"aab", "aaaa"}));
		Assert.assertEquals("lengths" , sorting.sortingMethod(new String[] {"c", "bb", "aaa"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"aa", "aaaaaaa", "aaaaa"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"aa", "a", "bbb"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"abc", "ab"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"az", "a"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"a", "aaa", "aa"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"ab", "a"}));
		Assert.assertEquals("none" , sorting.sortingMethod(new String[] {"bb", "c", "aaa"}));
		Assert.assertEquals("lexicographically", sorting.sortingMethod(new String[] {"abc", "az"}));
	}
}
