package com.lam.coder.projectEuler;

/**
 * 
 * @author Ludoviko Azuaje
 * 
 *         Problem 45: Triangular, pentagonal, and hexagonal
 * 
 *         Triangle, pentagonal, and hexagonal numbers are generated by the
 *         following formulae:
 * 
 *         Triangle Tn= n(n+1)/2 : 1, 3, 6, 10, 15, ...
 * 
 *         Pentagonal Pn=n(3n−1)/2 : 1, 5, 12, 22, 35, ...
 * 
 *         Hexagonal Hn= n(2n−1) : 1, 6, 15, 28, 45, ...
 * 
 *         It can be verified that T285 = P165 = H143 = 40755.
 * 
 *         Find the next triangle number that is also pentagonal and hexagonal.
 * 
 *         Answer: 1533776805.
 * 
 */

public class TriangularPentagonalHexagonal {
	private static long findTriangle(int n) {
		return n * (1 + n) / 2;
	}

	private static long findPentagonal(int n) {
		return n * (3 * n - 1) / 2;
	}

	private static long findHexagonal(int n) {
		return n * (2 * n - 1);
	}

	private static boolean isPentagonal(long n) {
		double penta;
		double pentaInt;

		penta = (1 + Math.sqrt(1 + 24 * n)) / 6;
		pentaInt = Math.floor(penta);

		return (penta == pentaInt);
	}

	
	private static boolean isHexagonal(long n) {
		double hexa;
		double hexaInt;

		hexa = (1 + Math.sqrt(1 + 8 * n)) / 4;
		hexaInt = Math.floor(hexa);

		return (hexa == hexaInt);
	}

	public static long find() {
		long triangle;
		for (int i = 286;; i++) {
			triangle = TriangularPentagonalHexagonal.findHexagonal(i);
			if (TriangularPentagonalHexagonal.isHexagonal(triangle)
					&& TriangularPentagonalHexagonal.isPentagonal(triangle)) {
				return triangle;
			}

		}
	}

	public static void main(String[] args) {
		System.out.println("Answer: " + TriangularPentagonalHexagonal.find());
	}
}
