package com.lam.coder.rosalind;

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import com.lam.coder.rosalind.CountingDNANucleotides;

public class CountingDNANucleotidesTest {
	CountingDNANucleotides countingDNANucleotides;
	
	@Before
	public void setUp() throws Exception {
		this.countingDNANucleotides = new CountingDNANucleotides();
	}

	@After
	public void tearDown() throws Exception {
		this.countingDNANucleotides  = null;
	}

	@Test
	public void test() {
		Assert.assertEquals("20 12 17 21", this.countingDNANucleotides.count("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"));
		Assert.assertEquals("218 241 225 219", this.countingDNANucleotides.count("CCACATTACGTTGTTTTCTGCGATCGTGTCTGGAATACAGGATCAATGGGCTAGAGCCAAACTGTGAGCTGACCGCCTTTTGCGATTTGACCCCGCAAATTCCTTACGTCGCGCGGCTGTATTGCTCAACCTTAGGGCCATTGTAGATATATTGACGATGAGCCTGGAAATGCGATAAGTAGTCATAATCTAACGGGCCACAGCCTTGAGTCTACGCGGGTACGGTTCGACGCAAACTACCGCAGAGTTTAAGTTGCAGACTAACAGTTCAATGTCGCAAATCTTTAGTTAGGAAATTACTAGGCCGATAGGACGAGGCCCATAGCTTTATCCACGCTGCGTCCAGTCTAACCTCAACCATGGGGGACCTTTCCGGTCTCGCAACACTATACCTACGCTGACTAATTACCAGTCGTACCGGCGCGGTTCCCCTATGATTGGCCGAGGGGGTTTGCATAGTGCTACCTTCGGTGGCAATGGCGCCAGCTCCCACGTGAGGTTATGTGTGACACTACCAAAGCACCCCGGCAATCTAAGGGTCACTCAATGTGAGTGATCGAATAATGATCCTTGCCCGGAGCCGTCCCGTTTGCGCGTAGCCGAGACTATCCCCTACATCAGGTGCGTGCCGGTATGTGGAGAATAGGCCCGTCGAGCGCCCGGCAAAGTATGTGCAAATCGTTCCCCAGAGTTGCGGGAAGATCGACTCCGCTCATTACCTGACCGTTGCAAACAACTGTTCCTAAAGGTACACGCTCGCTCCAGTTGGGAGAAGCTTAATACAACAAACATCTCCCTACCCGAGTTTCGGCAGTACAAGATGTGATTTGCCTCCTAGGGGACTATCATTAACAGATTGCCTCTCGGCTCGCGCCGGATTAAACAGTAAAAGGCGTACTTGTC"));
//		Assert.assertEquals("", this.countingDNANucleotides.count(""));
	}
}
